.editorconfig
Fairly self explanatory, enforces consistency when multiple devs are working on the project.
=> Editorconfig file

src/CHANGELOG.js, src/Parser/MistweaverMonk/CombatLogParser.js, src/Parser/MistweaverMonk/Modules/Features/ChiJi.js, src/Parser/MistweaverMonk/Modules/Features/EssenceFontMastery.js, src/common/SPELLS_MONK.js
Updated MW module to include Chi-Ji healing.
Changelog.js reflects this information.
=> Chi-Ji Healing Updates

src/CHANGELOG.js, src/Parser/MistweaverMonk/CombatLogParser.js, src/Parser/MistweaverMonk/Modules/Features/ChiBurst.js, src/Parser/MistweaverMonk/Modules/Features/CooldownTracker.js, src/Parser/MistweaverMonk/README.md
- Chi Burst Tracker Implementation
- Chi Burst / RJW icon clean up in Cooldown Tracker
CHANGELOG.js Updated with new additions.
=> Chi Burst Tracker Implementation

src/Parser/MistweaverMonk/CombatLogParser.js, src/Parser/MistweaverMonk/Modules/Features/ChiBurst.js, src/Parser/MistweaverMonk/Modules/Features/ChiJi.js
Fix to stop Chi Ji Healing from continually increasing overall healing on tab / report loads.
=> (fixed) Fix for Issue #68

src/CHANGELOG.js, src/Parser/MistweaverMonk/CPM_ABILITIES.js, src/common/SPELLS_MONK.js
Added in Tier 75 defensive CDs to Cast Efficiency tab.
=> Utility Spell tracking in Cast Efficiency

src/Parser/MistweaverMonk/CombatLogParser.js
- Updated number formats to be consistent
- Updated wording to keep StatisticBox sizes consistent
Strictly format updates.  I didn't update CHANGELOG.js for this, but if you want an entry please let me know.
Thanks.
=> Formatting Updates

src/CHANGELOG.js, src/Parser/MistweaverMonk/CPM_ABILITIES.js, src/Parser/MistweaverMonk/CombatLogParser.js, src/Parser/MistweaverMonk/Modules/Items/Eithas.js, src/common/ITEMS.js
- Ei'thas Boots Stats Implemented
- Adjusted some suggestions to use percentage versus raw numbers
- Adjusted links to utilize SPELLLINK vs <a> tags
CHANGELOG.js updated to reflect changes.
=> [Mistweaver Monk] Additional Legendaries and Code Updates

src/Parser/MistweaverMonk/Modules/Features/ManaTea.js
Bug Fix.  Didn't update CHANGELOG.js but let me know if you want me to.
=> Adjusted Mana Tea formula

src/CHANGELOG.js, src/Parser/MistweaverMonk/CombatLogParser.js, src/Parser/MistweaverMonk/Modules/Features/AOEHealingTracker.js, src/Parser/MistweaverMonk/Modules/Features/ThunderFocusTea.js, src/Parser/MistweaverMonk/Modules/Items/T20_2pc.js, src/Parser/MistweaverMonk/Modules/Items/T20_4pc.js, src/Parser/MistweaverMonk/README.md, src/common/SPELLS_MONK.js
CHANGELOG.js updated along with README.md.
=> T20 Implementation, TFT Usage Update, and Focused Thunder Support

src/Parser/DisciplinePriest/CombatLogParser.js
Change the tooltip to the item for a temp fix.
=> Hotfix - March of the Legion

src/Parser/Core/CombatLogParser.js, src/Parser/MistweaverMonk/CombatLogParser.js
Should be 4pc Spell ID and not 2pc.
Very minor, no need to a CHANGELOG.js update.
=> Update incorrect Spell used.

src/CHANGELOG.js, src/Parser/MistweaverMonk/CombatLogParser.js, src/Parser/MistweaverMonk/Modules/Items/PetrichorLagniappe.js, src/common/ITEMS.js
=> Added Petrichor Lagniappe

src/Parser/MistweaverMonk/CombatLogParser.js, src/Parser/MistweaverMonk/Modules/Items/DoorwayToNowhere.js, src/Parser/MistweaverMonk/Modules/Items/PetrichorLagniappe.js
Also updated tooltip to be more clear.
=> Remove debug messages

src/CHANGELOG.js, src/Parser/HolyPriest/CombatLogParser.js, src/Parser/HolyPriest/Modules/Features/Divinity.js
- Added the Divinity talent for the holy priest.
=> Holy priest: added Divinity talent

src/Parser/DisciplinePriest/CombatLogParser.js, src/Parser/DisciplinePriest/Modules/Features/LeniencesReward.js, src/Parser/DisciplinePriest/Modules/Features/PowerWordBarrier.js, src/common/SPELLS_PRIEST.js
Introduces Power Word: Barrier and Lenience's Reward for Discipline. Power Word: Barrier has a non-perfect implementation whereby the mitigation from other barriers during the fight is included, this is unavoidable as the source for Power Word: Barrier's buff is the environment and not the player.
=> Power Word Barrier + LR Async Component

src/Main/App.css, src/Main/App.js, src/Main/FeedingTab.js, src/Main/FightSelecter.js, src/Main/Results.js, src/Main/SuggestionsTab.js
=> Filter kills only fight (fixes #92)

src/Main/CastEfficiency.js, src/Parser/RestorationShaman/CombatLogParser.js, src/Parser/RestorationShaman/Modules/Legendaries/T20_4Set.js, src/Parser/RestorationShaman/Modules/ShamanCore/ShamanAbilityTracker.js, src/common/SPELLS_SHAMAN.js
=> R Shaman T20 4 set module

src/Parser/DisciplinePriest/Modules/Items/Tier20_2set.js
There is an inconsistency with the Penance module and T20 2 set interactions, this is an attempt to fix that.
=> Priest T20 2 Set Priority

src/common/ITEMS.js
=> Shelter of Rin labeled incorrectly.

src/Parser/DisciplinePriest/Modules/Features/LeniencesReward.js
WCL expression was the inverse of what it should have been.
=> Correct WCL Expression

src/Parser/MistweaverMonk/Modules/Features/EssenceFontMastery.js
Bugfix from Discord discussion on 7/20.
=> Bugfix: Corrects issue if a pet if targeted and healed during a EF HoT.

src/Parser/SubtletyRogue/CONFIG.js, src/Parser/SubtletyRogue/CPM_ABILITIES.js, src/Parser/SubtletyRogue/CombatLogParser.js, src/Parser/SubtletyRogue/TALENT_DESCRIPTIONS.js, src/common/SPELLS.js, src/common/SPELLS_OTHERS.js, src/common/SPELLS_ROGUE.js
Create an initial draft for subtlety rogue.
=> SubtletyRogue initail draft

src/CHANGELOG.js, src/Parser/MistweaverMonk/Modules/Features/ThunderFocusTea.js
Added buffer time for TFT buff to fall off befor next cast.
=> Bug Fix for TFT Cast Tracking

src/Parser/DisciplinePriest/CombatLogParser.js, src/Parser/DisciplinePriest/Modules/Features/AtonementSource.js, src/Parser/DisciplinePriest/Modules/Items/Tier20_2set.js, src/Parser/DisciplinePriest/Modules/Spells/Castigation.js, src/Parser/DisciplinePriest/Modules/Spells/Penance.js
Implements a counter on Penance events, and also adds a Castigation module that piggybacks off those changes.
=> Castigation Module & Penance Bolt Count

src/Parser/AVAILABLE_CONFIGS.js, src/Parser/GuardianDruid/CONFIG.js, src/Parser/GuardianDruid/CPM_ABILITIES.js, src/Parser/GuardianDruid/CombatLogParser.js, src/Parser/GuardianDruid/Modules/Features/AlwaysBeCasting.js, src/Parser/GuardianDruid/Modules/Features/GalacticGuardian.js, src/Parser/GuardianDruid/Modules/Features/Gore.js, src/Parser/GuardianDruid/Modules/Features/GuardianOfElune.js, src/Parser/GuardianDruid/Modules/Features/IronFur.js, src/Parser/GuardianDruid/Modules/Items/DualDetermination.js, src/Parser/GuardianDruid/TALENT_DESCRIPTIONS.js, src/common/ITEMS.js, src/common/SPELLS_DRUID.js
Just a shell for the Guardian, its the first tank spec so work in progress.
=> Initial pass at Guardian

src/Parser/GuardianDruid/CombatLogParser.js
Uses the updated suggestions layout for guardian druids.
=> [Guardian Druid] Migrate suggestions to new layout

src/CHANGELOG.js, src/Parser/MistweaverMonk/CombatLogParser.js, src/Parser/MistweaverMonk/Modules/Items/OvydsWinterWrap.js, src/Parser/MistweaverMonk/Modules/Spells/EnvelopingMists.js
Added EvM Statistic
Updated CHANGELOG.js
=> Enveloping Mists Healing Contribution added

src/CHANGELOG.js, src/Parser/MistweaverMonk/CombatLogParser.js, src/Parser/MistweaverMonk/Modules/Spells/EnvelopingMists.js, src/Parser/MistweaverMonk/Modules/Spells/SoothingMist.js
Added Soothing Mist channeling suggestion
=> Soothing Mist Suggest

src/Parser/HolyPaladin/Modules/Items/Tier19_4set.js
Quick bugfix for Paladin T19 4 Piece bonus.
=> Paladin T19 4pc bugfix

src/Parser/GuardianDruid/CombatLogParser.js, src/Parser/GuardianDruid/Modules/Items/Skysecs.js, src/common/ITEMS.js, src/common/SPELLS_DRUID.js, src/common/format.js
Skysec's Hold is not a good legendary.  This module explains why.
=> [Guardian] Add Skysec's Hold efficiency metric and suggestions

src/CHANGELOG.js, src/Parser/BrewmasterMonk/Modules/Core/DamageTaken.js, src/Parser/BrewmasterMonk/Modules/Features/AlwaysBeCasting.js, src/Parser/BrewmasterMonk/Modules/Features/CastEfficiency.js, src/Parser/BrewmasterMonk/Modules/Spells/IronSkinBrew.js, src/common/SPELLS_MONK.js
Fixed issues from previous PR
Added a tooltip to ISB.
=> Brewmaster updates

src/CHANGELOG.js, src/Parser/GuardianDruid/Modules/Spells/IronFur.js
Fix to text of suggestion
Changed to use actual in suggest also.
=> [Guardian] Ironfur suggestion

src/CHANGELOG_MISTWEAVER_MONK.js, src/Main/MonkSpreadsheet.js, src/Parser/MistweaverMonk/Modules/Features/CastEfficiency.js, src/Parser/MistweaverMonk/Modules/Spells/EssenceFont.js, src/Parser/MistweaverMonk/Modules/Talents/ChiBurst.js, src/Parser/MistweaverMonk/Modules/Talents/RefreshingJadeWind.js, src/Parser/MistweaverMonk/Modules/Traits/CelestialBreath.js, src/Parser/MistweaverMonk/Modules/Traits/MistsOfSheilun.js, src/Parser/MistweaverMonk/Modules/Traits/WhispersOfShaohao.js
Statistics trimming based on feedback.
Cast Efficiency change to REM based on feedback.
CHANGELOG.js updated.
=> BugFix for MonkSpreadsheet Absorbless DTPS

src/common/SPELLS_HUNTER.js, src/common/SPELLS_MAGE.js, src/common/SPELLS_OTHERS.js, src/common/SPELLS_SHAMAN.js
Added all the hero haste buffs to the relevant common spells files.
These ids are referenced in a few places. I have not gone back and updated them however.
=> Added haste buffs to common/spells

src/Parser/VengeanceDemonHunter/CHANGELOG.js, src/Parser/VengeanceDemonHunter/Modules/Features/AlwaysBeCasting.js, src/Parser/VengeanceDemonHunter/Modules/Features/SpiritBomb.js
- Spirit Bomb uptime bug fix
- Corrected ABC recommended time
=> [Vengeance Demon Hunter] Bugfix

src/Parser/Core/CombatLogParser.js
Deleting the eventType from the on_event event.
=> Fix to on_event

src/Parser/MistweaverMonk/CHANGELOG.js, src/Parser/MistweaverMonk/CONFIG.js, src/Parser/MistweaverMonk/CombatLogParser.js, src/Parser/MistweaverMonk/Modules/Traits/CoalescingMists.js, src/Parser/MistweaverMonk/Modules/Traits/EssenceOfTheMist.js, src/Parser/MistweaverMonk/Modules/Traits/InfusionOfLife.js, src/Parser/MistweaverMonk/Modules/Traits/ProtectionOfShaohao.js, src/Parser/MistweaverMonk/Modules/Traits/RelicTraits.js, src/Parser/MistweaverMonk/Modules/Traits/SoothingRemedies.js, src/Parser/MistweaverMonk/Modules/Traits/WayOfTheMistweaver.js, src/common/SPELLS_MONK.js
Based on suggestion from Zero - Initial relic traits added.
=> Relic Traits added to statistics view.

src/Parser/DisciplinePriest/Modules/Items/Tier20_2set.js
Newest build has the bonus applying to the second bolt.
=> T20 2 Set Fix

src/Parser/MistweaverMonk/CHANGELOG.js, src/Parser/MistweaverMonk/CombatLogParser.js, src/Parser/MistweaverMonk/Modules/Traits/ExtendedHealing.js, src/Parser/MistweaverMonk/Modules/Traits/RelicTraits.js
All MW Relics currently implemented.
=> Extended Healing Relic Implemented.

src/Parser/BrewmasterMonk/Modules/Core/Stagger.js, src/Parser/BrewmasterMonk/Modules/Items/T20_2pc.js, src/Parser/BrewmasterMonk/Modules/Items/T20_4pc.js, src/Parser/BrewmasterMonk/Modules/Spells/BlackoutCombo.js, src/Parser/BrewmasterMonk/Modules/Spells/IronSkinBrew.js, src/tests/Parser/Brewmaster/BlackoutCombo.test.js
Keeping in line with the standard...
=> moved from using this.owner to using dependencies

src/Parser/FeralDruid/CombatLogParser.js, src/Parser/FeralDruid/Modules/Bleeds/RakeUptime.js, src/Parser/FeralDruid/Modules/Bleeds/RipUptime.js, src/Parser/FeralDruid/Modules/Features/AlwaysBeCasting.js, src/Parser/FeralDruid/Modules/Features/CooldownTracker.js, src/Parser/FeralDruid/Modules/Talents/MoonfireUptime.js, src/Parser/FeralDruid/Modules/Talents/SavageRoarUptime.js, src/common/SPELLS_DRUID.js
Configured the cooldown tracker and added modules for bleed/dot uptimes.
=> [FERAL] Added Cooldown tracker and Bleed uptimes

src/Parser/EnhancementShaman/CHANGELOG.js, src/Parser/EnhancementShaman/Modules/Items/Tier20_2set.js, src/Parser/EnhancementShaman/Modules/Main/CastEfficiency.js, src/Parser/EnhancementShaman/Modules/ShamanCore/Flametongue.js, src/Parser/EnhancementShaman/Modules/ShamanCore/Frostbrand.js, src/Parser/EnhancementShaman/Modules/ShamanCore/FuryOfAir.js, src/Parser/EnhancementShaman/Modules/ShamanCore/Landslide.js, src/Parser/EnhancementShaman/Modules/ShamanCore/ShamanStats.js
Update the owner module usage to add dependency instead of this.owner.combatant
Update Cast Efficiency for Shaman to display stuff as needed
=> Owner module handling update

src/Parser/MarksmanshipHunter/CombatLogParser.js, src/Parser/MarksmanshipHunter/Modules/Features/AlwaysBeCasting.js
Fixed spell usage suggestion and other problem area wasn't being utilized at this point so I removed it.
=> [MM Hunter] fixed PR request

src/Parser/BloodDeathKnight/Modules/Features/CastEfficiency.js
Updated the spells that arent affected by haste.
=> Removed haste calculations

src/Parser/AfflictionWarlock/Modules/Features/DamageDone.js, src/Parser/AfflictionWarlock/Modules/Features/FatalEchoes.js, src/Parser/AfflictionWarlock/Modules/Features/Sniping.js, src/Parser/AfflictionWarlock/Modules/Features/UABuffTracker.js, src/Parser/AfflictionWarlock/Modules/Items/Legendaries/PowerCordOfLethtendris.js, src/Parser/AfflictionWarlock/Modules/Items/Legendaries/ReapAndSow.js, src/Parser/AfflictionWarlock/Modules/Items/Tier20_2set.js, src/Parser/AfflictionWarlock/Modules/Items/Tier20_4set.js, src/Parser/AfflictionWarlock/Modules/SoulShards/SoulShardTracker.js, src/Parser/AfflictionWarlock/Modules/Talents/SoulHarvest.js, src/Parser/DestructionWarlock/Modules/Features/DamageDone.js, src/Parser/DestructionWarlock/Modules/Features/ImmolateUptime.js, src/Parser/DestructionWarlock/Modules/SoulShards/SoulShardEvents.js, src/Parser/DestructionWarlock/Modules/Talents/SoulHarvest.js
Mostly just renaming variables, prefixing with _ to indicate private members. Hopefully won't be too much of a pain to review.
=> [Affli+Destro] Minor refactoring

src/Parser/RestoDruid/CombatLogParser.js, src/Parser/RestoDruid/Modules/Legendaries/Sephuz.js
Overridden the Core Sephuz's Secret module to show its specific data, should work now.
=> [HOTFIX] Hotfix Resto Druid Sephuz module

src/Parser/RestoDruid/CHANGELOG.js, src/Parser/RestoDruid/CombatLogParser.js, src/Parser/RestoDruid/Modules/Features/EssenceOfGhanir.js, src/Parser/RestoDruid/Modules/Legendaries/T21_2Set.js, src/Parser/RestoDruid/Modules/Legendaries/T21_4Set.js, src/common/SPELLS_DRUID.js
T21 support for Resto Druids, using PTR logs to check my work. I also fixed some messed up dates in the changelog -_-
=> [resto druid] Added support for T21.

src/common/format.js
A commonly used utility, and you kinda have to squint at some of the code to figure out exactly what the formatting will be. I added some documentation.
The actual code is unchanged.
=> Documented format.js

src/Parser/DestructionWarlock/CHANGELOG.js, src/Parser/DestructionWarlock/CombatLogParser.js, src/Parser/DestructionWarlock/Modules/Features/DimensionalRift.js, src/common/SPELLS_WARLOCK.js
Really happy how that turned out :3 Now I'll move on some traits or set bonuses/legendaries. Suggestions are welcomed as always.
=> [Destruction] Added Dimensional Rift breakdown

src/Parser/RestoDruid/Modules/Features/Mastery.js
Changed Maps to Objects, used more functional techniques.
=> [resto druid] Refactored Mastery module for ESLint

src/Parser/HavocDemonHunter/Modules/Features/CastEfficiency.js
Changed the cast efficiency of Eye Beam and Felblade spells in order to implement the suggestions from #271 .
=> [Havoc] Updated CastEfficiency on Eye Beam and Felblade

.env.local.example, src/Parser/AVAILABLE_CONFIGS.js, src/Parser/DestructionWarlock/CHANGELOG.js, src/Parser/DestructionWarlock/CombatLogParser.js, src/Parser/DestructionWarlock/Modules/Features/DimensionalRift.js, src/Parser/FeralDruid/CHANGELOG.js, src/Parser/FeralDruid/Modules/ComboPoints/ComboPointDetails.js, src/Parser/FeralDruid/Modules/ComboPoints/ComboPointTracker.js, src/Parser/HolyPriest/Constants.js, src/Parser/HolyPriest/Modules/PriestCore/MasteryBreakdown.js, src/Parser/RestoDruid/Modules/Features/Mastery.js, src/Parser/RetributionPaladin/CHANGELOG.js, src/Parser/RetributionPaladin/CONFIG.js, src/Parser/RetributionPaladin/CombatLogParser.js, src/Parser/RetributionPaladin/Modules/Features/AlwaysBeCasting.js, src/Parser/RetributionPaladin/Modules/Features/CastEfficiency.js, src/Parser/RetributionPaladin/Modules/Features/CooldownTracker.js, src/Parser/RetributionPaladin/Modules/PaladinCore/DamageDone.js, src/common/SPELLS_WARLOCK.js
Started working on the Ret Paladin parser. Knocking out the easy stuff first will move onto more in depth things when I have more time
=> added damage done stat and cast effciencies

src/Parser/HavocDemonHunter/Modules/Features/CastEfficiency.js, src/Parser/HavocDemonHunter/Modules/Statistics/Spells/Momentum.js, src/Parser/HavocDemonHunter/Modules/Statistics/Spells/Nemesis.js, src/Parser/VengeanceDemonHunter/CombatLogParser.js, src/Parser/VengeanceDemonHunter/Modules/Statistics/Spells/ImmolationAura.js, src/Parser/VengeanceDemonHunter/Modules/Statistics/SpiritBomb/SpiritBomb.js
Blade Dance recommended cast efficiency was a bit higher than the normal.
Also, I've made some code refactoring too: moved the SpiritBomb.js module to a specific folder, removed the if(!this.owner.error) from the on_initialized functions and refactored the immolation aura module (I forgot to do in the previous PRs).
=> [Vengeance + Havoc] Code refactoring and updated Fel Rush and Blade Dance cast recommendation

src/Parser/AfflictionWarlock/Modules/Features/DamageDone.js, src/Parser/AfflictionWarlock/Modules/Features/FatalEchoes.js, src/Parser/AfflictionWarlock/Modules/Features/Sniping.js, src/Parser/AfflictionWarlock/Modules/Features/UABuffTracker.js, src/Parser/AfflictionWarlock/Modules/Items/Legendaries/PowerCordOfLethtendris.js, src/Parser/AfflictionWarlock/Modules/Items/Tier20_2set.js, src/Parser/AfflictionWarlock/Modules/Talents/DeathsEmbrace.js, src/Parser/AfflictionWarlock/Modules/Talents/MaleficGrasp.js, src/Parser/AfflictionWarlock/Modules/Talents/SoulHarvest.js, src/Parser/DestructionWarlock/Modules/Features/DamageDone.js, src/Parser/DestructionWarlock/Modules/Items/Legendaries/AlythesssPyrogenics.js, src/Parser/DestructionWarlock/Modules/Items/Legendaries/LessonsOfSpaceTime.js, src/Parser/DestructionWarlock/Modules/Items/Legendaries/OdrShawlOfTheYmirjar.js, src/Parser/DestructionWarlock/Modules/Items/Legendaries/SindoreiSpite.js, src/Parser/DestructionWarlock/Modules/Talents/SoulHarvest.js
Array may perform faster but I think at this small sizes it's rather irrelevant.
=> [Affli + Destro] Refactor Array.indexOf to Set for better readability

src/Parser/BalanceDruid/Modules/Features/AstralPower.js, src/Parser/EnhancementShaman/Modules/ShamanCore/Rockbiter.js, src/Parser/RestoDruid/Modules/Features/Innervate.js
Observed issue in RestoDruid Innervate module, added to the other places just in case.
=> Fixed a bug where event.classResources wasn't checked for undefined

src/Main/Event.js, src/Parser/Core/Modules/HealingDone.js, src/Parser/DisciplinePriest/CHANGELOG.js, src/Parser/DisciplinePriest/CombatLogParser.js, src/Parser/DisciplinePriest/Modules/Features/AtonementHealingBreakdown.js, src/Parser/DisciplinePriest/Modules/Features/AtonementHealingDone.js, src/Parser/DisciplinePriest/Modules/Features/AtonementSource.js
=> Disc Priest: Fix issue where friendly fire damage was considered a valid Atonement damage source

src/Parser/DemonologyWarlock/CHANGELOG.js, src/Parser/DemonologyWarlock/CombatLogParser.js, src/Parser/DemonologyWarlock/Modules/Features/DoomUptime.js, src/Parser/DemonologyWarlock/Modules/Features/DoomguardInfernal.js, src/Parser/DemonologyWarlock/Modules/SoulShards/SoulShardTracker.js, src/common/SPELLS_WARLOCK.js
Didn't need to change anything apart from input/output spells.
=> [Demonology] Soul Shard Tracker fix

src/Parser/RetributionPaladin/CONFIG.js
Need to add more legendaries and Judgment at least. Cast efficiency needs an overhaul to get around negative percent downtime and casting more spells than should be possible due to crusade. Could add something to make sure you are using trinkets at the right times as well
=> Still a lot of work left to do

src/Parser/RetributionPaladin/CHANGELOG.js, src/Parser/RetributionPaladin/CONFIG.js, src/Parser/RetributionPaladin/CombatLogParser.js, src/Parser/RetributionPaladin/Modules/HolyPower/HolyPowerDetails.js, src/Parser/RetributionPaladin/Modules/Items/AshesToDust.js, src/Parser/RetributionPaladin/Modules/Items/ChainOfThrayn.js, src/common/SPELLS_PALADIN.js
Added a chain of Thrayn Module
=> Chain of Thrayn

src/Parser/RetributionPaladin/Modules/Items/AshesToDust.js, src/Parser/RetributionPaladin/Modules/Items/ChainOfThrayn.js, src/Parser/RetributionPaladin/Modules/Items/Tier20_2set.js, src/Parser/RetributionPaladin/Modules/Items/WhisperOfTheNathrezim.js, src/Parser/RetributionPaladin/Modules/PaladinCore/GetDamageBonus.js
Changed the bonus damage calculations. also made getting bonus damage is own method to get rid of some copy pasting
=> Minor math bug fix

src/Parser/DestructionWarlock/Modules/Talents/SoulHarvest.js
Don't really know how I missed it, should be fine now.
=> [HOTFIX] Fixed Destruction Soul Harvest module

src/Parser/AVAILABLE_CONFIGS.js, src/Parser/ProtectionWarrior/CombatLogParser.js, src/Parser/ProtectionWarrior/Modules/Features/AlwaysBeCasting.js, src/Parser/ProtectionWarrior/Modules/Features/CastEfficiency.js, src/Parser/ProtectionWarrior/Modules/Spells/ShieldBlock.js, src/common/SPELLS_WARRIOR.js
Updated older files to remove unused & unnecessary lines, added lines for Protection Warrior into the Available Configs file, created a module that shows information revolving around Shield Block usage (total hits mitigated, total hits unmitigated, etc).
=> Updated old files + added Shield Block module.

src/Parser/Core/Modules/AlwaysBeCastingHealing.js
Now shows non-casting time instead of non-healing time. Now shows bar for time spent casting non-heal spells. Updated tooltips.
=> Updated AlwaysBeCastingHealing's stats box

src/Parser/VengeanceDemonHunter/CombatLogParser.js, src/Parser/VengeanceDemonHunter/Modules/Tier/Tier20/Tier20-2P.js, src/Parser/VengeanceDemonHunter/Modules/Tier/Tier20/Tier20-4P.js, src/common/SPELLS_DEMON_HUNTER.js
Tier 20 2 piece and 4 piece bonus is now being tracked as suggestions and statistics boxes.
=> [Vengeance] Tier20 2 piece and 4 piece trackers

src/Parser/VengeanceDemonHunter/CONFIG.js
As I previously stated, I've now implemented the last open suggestion: the Tier 20 2 and 4 piece buff/debuff tracker.
So, the next steps is to wait for new suggestions and tier 21 become available to add it's tracker too.
=> [Vengeance] Changed the spec completeness from good to great

src/Parser/RestoDruid/CHANGELOG.js, src/Parser/RestoDruid/Modules/Features/SoulOfTheForest.js, src/Parser/RestoDruid/SuggestionThresholds.js
=> Resto Druid: Added suggestions on sotf

src/Main/ExpandableStatisticBox.js, src/Parser/RestoDruid/CHANGELOG.js, src/Parser/RestoDruid/Modules/Features/Flourish.js
[![Screenshot from Gyazo](https://gyazo.com/41713a2a4d8164bd51b6c7bce5e5fa74/raw)](https://gyazo.com/41713a2a4d8164bd51b6c7bce5e5fa74)
=> Resto druid flourish display changes

src/Parser/RestoDruid/Modules/Features/Clearcasting.js, src/Parser/RestoDruid/Modules/Features/HealingTouch.js
Took the `<` signs off a couple recommendations so they don't suggest you do `<0%` of something. Updated an awkwardly worded tooltip.
=> [Resto Druid] Suggestion tooltip fixes

src/Parser/GuardianDruid/Modules/Spells/IronFur.js, src/common/SPELLS_DRUID.js, src/tests/Parser/Guardian/IronFur.test.js
Adds support for tracking individual stacks of Ironfur, and updates the statistic and suggestion accordingly.
=> [Guardian] Improved Ironfur module

src/Main/MonkSpreadsheet.js, src/common/SPELLS_OTHERS.js
Quick additions to MW Monk Spreadsheet tab.
=> MW Monk Spreadsheet Tab Update

src/Parser/MarksmanshipHunter/Modules/FocusChart/Focus.css, src/Parser/MarksmanshipHunter/Modules/FocusChart/Focus.js, src/Parser/MarksmanshipHunter/Modules/FocusChart/FocusComponent.js, src/Parser/MarksmanshipHunter/Modules/FocusChart/FocusTracker.js, src/Parser/MarksmanshipHunter/Modules/FocusChart/main.css
The code has been beautified and should be consistent with most, if not everything, else now.
fixes are:
- indentations 
- from let maxX = 0; to let maxX; (unneeded defining) 
It can safely be automerged, as it is nothing but pedantry.
=> [Marksmanship] Fixing indentations in FocusChart

src/Parser/GuardianDruid/Modules/Spells/IronFur.js
Fixes a computation error in the Ironfur module, and removes some references to unused data.
=> [Guardian] Ironfur bugfix

src/Parser/HolyPaladin/Modules/Talents/DivinePurpose.js
Had to reorder HS Divine Purpose since it was bugged in logs and showing above the cast that triggered it.
=> Holy Paladin: Add Divine Purpose cooldown reset of HS / LoD

src/Parser/Core/Modules/SpellUsable.js, src/Parser/HolyPaladin/CombatLogParser.js, src/Parser/HolyPaladin/Modules/Features/AlwaysBeCasting.js, src/Parser/HolyPaladin/Modules/Talents/CrusadersMight.js, src/common/format.js
TODO: show percentage instead (e.g. if your Holy Shock was on CD for 200 sec (after reductions) and you had a 60 sec CDR, it would show a 23% effective CDR. This is easier to grasp the value of.
=> Holy Paladin: Add a Crusader's Might module that shows the actual CDR

src/Parser/HolyPaladin/CHANGELOG.js, src/Parser/HolyPaladin/Modules/Items/MaraadsDyingBreath.js, src/Parser/HolyPaladin/Modules/PaladinCore/FillerLightOfTheMartyrs.js, src/common/SPELLS_PALADIN.js
=> Holy Paladin: Added a suggestion against casting Light of the Martyr while Holy Shock is available

src/common/ITEMS.js
Added the crafted legendaries as requested #388
=> Added Crafted legendaries to ITEMS.js

src/Parser/RestoDruid/Modules/Legendaries/Ekowraith.js, src/Parser/RestoDruid/Modules/Legendaries/T21_4Set.js, src/common/SPELLS_DRUID.js
I just gave Sharrq a hard time for naming two versions of a spell "1" and "2", so I guess I'll put my money where my mouth is.
=> [resto druid] Made Ysera's spell entries more descriptive

src/Parser/Core/CombatLogParser.js, src/Parser/Core/Modules/Items/Legendaries.js
=> Major suggestion if non-max ilvl legendary is used

src/common/ITEMS.js
Pushing DH legendaries for issue #388
=> Add all DH legendaries

src/common/ITEMS.js
Pushing Druid legendaries for issue #388
=> Add Druid legendaries

src/Parser/WindwalkerMonk/CombatLogParser.js, src/Parser/WindwalkerMonk/Modules/Features/CastEfficiency.js, src/Parser/WindwalkerMonk/Modules/Spells/SEF.js, src/Parser/WindwalkerMonk/Modules/Spells/StormEarthAndFire.js
Currently only dependant on amount of Split Personality traits - CoF calculation is probably not going to be added as it is already rarely used and doesn't reliably give extra casts and
=> Added cooldown calculation of Serenity/SEF

src/CHANGELOG.js, src/Parser/RestoDruid/CHANGELOG.js
Forgot to update changelog in #500 , so here is the update.
=> Updated changelog for Sephuz changes

src/Parser/FrostMage/CombatLogParser.js, src/Parser/FrostMage/Modules/Items/ZannesuJourney.js, src/common/SPELLS_MAGE.js
Added a Damage Count for Zann'esu Journey.
=> [Frost Mage] Damage Count for Zann'esu Journey

src/Parser/RetributionPaladin/Modules/HolyPower/HolyPowerDetails.js
I just think it looks better as how much holy power you wasted vs a percentage of holy power wasted
=> [Retribution] Changed holy power stat box

src/Parser/Mage/Frost/CHANGELOG.js, src/Parser/Mage/Frost/CombatLogParser.js, src/Parser/Mage/Frost/Modules/Items/MagtheridonsBanishedBracers.js, src/Parser/Mage/Frost/Modules/Items/ShatteredFragmentsOfSindragosa.js, src/common/SPELLS_MAGE.js
Damage Counts for Magtheridon's Banished Bracers and Shattered Fragments of Sindragosa.
=> [Frost Mage] More Frost Legendary Damage Counts

src/Parser/DisciplinePriest/CHANGELOG.js, src/Parser/DisciplinePriest/CombatLogParser.js, src/Parser/DisciplinePriest/Modules/Items/Tier20_4set.js
Fixes the problem with the T20 4 set bonus for Discipline, also adds in a handy suggestion.
=> Discipline T20 4 Set Bonus Bugfix

src/Parser/Monk/Brewmaster/Modules/Features/CastEfficiency.js
Remove Spell if the talent is not taken.
Related to Issue #537
=> Issue 537 Fix

src/Main/MonkSpreadsheet.js
In my quick renaming of things I forgot this.
Merging as is.
=> Quick Fix from Renaming

src/Parser/Mage/Fire/CHANGELOG.js, src/Parser/Mage/Fire/CombatLogParser.js, src/Parser/Mage/Frost/CHANGELOG.js, src/Parser/Mage/Frost/CombatLogParser.js, src/Parser/Mage/Frost/Modules/Features/ArcticGale.js, src/Parser/Mage/Frost/Modules/Features/FrostBomb.js, src/Parser/Mage/Shared/Modules/Features/UnstableMagic.js, src/common/SPELLS_MAGE.js
Added modules for Unstable Magic and Arctic Gale. I intended to also add the last Frost Mage lvl90 talent, but I literally cannot find a single log of anyone using Frost Bomb, and I don't want to ship a module I can't test.
=> [mage] FrostBomb, UnstableMagic, and ArcticGale

src/common/SPELLS/PRIEST.js
=> Disc priest: Fixed plea mana cost

src/common/SPELLS/SHAMAN.js
=> Resto shaman: Added mana cost for various spells

src/Parser/Warrior/Arms/Modules/BuffDebuff/ColossusSmashUptime.js, src/Parser/Warrior/Arms/Modules/Features/CastEfficiency.js, src/common/SPELLS/WARRIOR.js
Was neccessary due talent issue's with uptime of colossus smash
=> Arms warrior - fervor of battle update, cast efficiency update and spells added

src/Parser/Hunter/Marksmanship/CHANGELOG.js, src/Parser/Hunter/Marksmanship/CombatLogParser.js, src/Parser/Hunter/Marksmanship/Modules/Features/VulnerableApplications.js
Stole code from CastBehavior in Holy Paladin module to create this chart to show which abilities are used to generate vulnerable.
=> [Marksmanship] Vulnerable Applications Chart

src/Parser/Core/Modules/AlwaysBeCasting.js, src/Parser/Paladin/Retribution/CHANGELOG.js, src/Parser/Paladin/Retribution/Modules/Features/AlwaysBeCasting.js
=> Ret paladin: Changed the active time icon to something more befitting

src/Parser/AVAILABLE_CONFIGS.js, src/Parser/DeathKnight/Unholy/CHANGELOG.js, src/Parser/DeathKnight/Unholy/CONFIG.js, src/Parser/DeathKnight/Unholy/CombatLogParser.js, src/Parser/DeathKnight/Unholy/Modules/Features/AlwaysBeCasting.js, src/Parser/DeathKnight/Unholy/Modules/Features/CastEfficiency.js, src/Parser/DeathKnight/Unholy/Modules/Features/CooldownTracker.js, src/common/SPELLS/DEATH_KNIGHT.js
Only basic support right now.  Added the necessary files, did ABC and some crude cooldown efficiency.  Rearranged the death knight spell file a little bit and moved shared spells into their own section.
=> [Unholy Death Knight] Added initial Unholy Death Knight support

src/Parser/Monk/Mistweaver/Modules/Spells/ThunderFocusTea.js
Just changing to more defined colors.
=> [Mistweaver Monk] Slight Color Updates to Thunder Focus Tea

src/Parser/DeathKnight/Unholy/CombatLogParser.js, src/Parser/DeathKnight/Unholy/Modules/Features/VirulentPlagueUptime.js, src/common/SPELLS/DEATH_KNIGHT.js
Added basic module for Unholy's DoT uptime.  Made sure to double check copied code for Warlock spells this time 😁
=> [Unholy Death Knight]Added module for virulent plague uptime

src/Parser/Core/CombatLogParser.js, src/Parser/Core/Modules/Items/HighfathersMachination.js, src/Parser/Core/Modules/Items/TarratusKeystone.js, src/common/ITEMS/OTHERS.js, src/common/SPELLS/OTHERS.js
T21 Healing trinkets:
- Tarratus Keystone
- Highfather's Machination
=> T21 Healing trinkets

src/Parser/DeathKnight/Unholy/Modules/Features/AlwaysBeCasting.js
Reworded downtime suggestion to be more appropriate to melee/Unholy.
=> Death Knight - Unholy - Update AlwaysBeCasting.js

src/Parser/DeathKnight/Unholy/Modules/Features/VirulentPlagueUptime.js
Minor tweaks to suggestions to uptime. Decreased values of uptime to better reflect values that are realistic to in game performance.
=> Death Knight - Unholy - Update VirulentPlagueUptime.js

src/Parser/DeathKnight/Unholy/Modules/Features/CastEfficiency.js
Clarification on suggestions to account for TicTac shoulders, efficiency changes on Dark Transformation to account for it's more frequent use.
=> Death Knight - Unholy - Update CastEfficiency.js

src/Parser/Core/calculateEffectiveDamage.js, src/Parser/Priest/Discipline/Modules/Items/Tier20_2set.js
Fix for the T20 2pc Nerf. This also includes the healing being calculated on the first bolt since Blizzard fixed it
=> [Discipline Priest] Fix for the T20 2pc Nerf

src/Parser/Core/Modules/StatTracker.js, src/common/ITEMS/OTHERS.js, src/common/SPELLS/OTHERS.js
Fixes #417 (for real this time)
Tested with https://www.warcraftlogs.com/reports/9VZNXjmBPfn6YrkR#fight=6&type=auras&source=2
=> [core] Added Erratic Metronome to StatTracker

src/Parser/DeathKnight/Unholy/CombatLogParser.js, src/Parser/DeathKnight/Unholy/Modules/Features/CastEfficiency.js, src/Parser/DeathKnight/Unholy/Modules/Features/FesteringStrike.js, src/Parser/DeathKnight/Unholy/Modules/Features/VirulentPlagueUptime.js, src/common/SPELLS/DEATH_KNIGHT.js
Added a new module to give players feedback on how to more efficiently use one of the rune spenders.  Also fixed some errors I found working on this.
=> [Unholy Death Knight] Added Festering Strike module

src/Parser/Hunter/Marksmanship/Modules/Items/TarnishedSentinelMedallion.js
Resolves #640 
Bug was created when ts.end was undefined. Since TS is set length of 15 seconds, when ts.end is undefined we know that it will be (for the scope that concerns this particular module) ending at most 15 seconds later, so we can set ts.end to 15 seconds later, which resolves the bug.
=> [Marksmanship] Medallion Bug Fix

src/Parser/Core/Modules/NetherlightCrucibleTraits/DarkSorrows.js
Updated description to show x.xx% damage
=> [Core] Update DarkSorrows.js

src/Parser/Mage/Shared/Modules/Features/MirrorImage.js
=> [mage] Hopefully temp fix to Mirror Image

src/common/SPELLS/DEATH_KNIGHT.js
=> Death Knight - Adding Unholy 2 set Spell ID

src/Parser/Monk/Windwalker/CONFIG.js, src/Parser/Monk/Windwalker/Modules/Features/CastEfficiency.js
They nerfed T19 2pc even more lol
=> [Windwalker] Updating castefficiency and spec maintainer

src/Parser/Mage/Frost/CHANGELOG.js, src/Parser/Mage/Frost/CONFIG.js, src/Parser/Mage/Frost/Modules/Features/BrainFreeze.js, src/Parser/Mage/Frost/Modules/Features/WintersChill.js
Winter's chill display could split strangely on wider windows, this fixes the issue.
Before:
After:
=> [frost mage] Winter's Chill render fix and Brain Freeze appearance update

src/Parser/Mage/Frost/Modules/Features/BrainFreeze.js
Gives the user a suggestion to not hard cast flurry, i.e. they should never cast it with no brain freeze proc.
=> [Frost Mage] Suggestion for Hard Casting Flurry

src/Parser/Priest/Discipline/CombatLogParser.js, src/Parser/Priest/Discipline/Modules/Items/Tier21_2set.js, src/common/SPELLS/PRIEST.js, src/tests/Parser/Priest/Discipline/Fixtures/TestingEvents.js, src/tests/Parser/Priest/Discipline/Fixtures/processEvents.js, src/tests/Parser/Priest/Discipline/Modules/Items/Tier21_2set.test.js, src/tests/Parser/Priest/Discipline/Normalizers/AtonementSuccessiveDamage.test.js
This calculates the gross time saved on the tier. I will be adding the "Net Saved time" in a future PR
=> [Discipline Priest] T21 2pc bonus

src/Parser/Core/Modules/Features/BaseHealerStatWeights.js
Made Leech stop counting for absorbs.
Fixed extraneous `1 *` in a calculation.
Fixed hasteHpct calculation.
=> [core] Fixed some issues in BaseHealerStatWeights

src/Parser/Shaman/Elemental/CHANGELOG.js, src/Parser/Shaman/Elemental/CombatLogParser.js, src/Parser/Shaman/Elemental/Modules/Features/Overload.js, src/Parser/Shaman/Elemental/Modules/ShamanCore/ElementalFocus.js, src/Parser/Shaman/Elemental/Modules/ShamanCore/FlameShock.js
Added Tooltip:
Added 2 Suggestions:
Extra: Added missing Overload Spell list keys.
=> [Ele-Shami] Update FlameShock Tooltip and added Suggestions

src/Parser/DeathKnight/Unholy/CombatLogParser.js, src/Parser/DeathKnight/Unholy/Modules/RunicPower/RunicPowerBreakdown.js, src/Parser/DeathKnight/Unholy/Modules/RunicPower/RunicPowerDetails.js, src/Parser/DeathKnight/Unholy/Modules/RunicPower/RunicPowerTracker.js, src/common/SPELLS/DEATH_KNIGHT.js
Pretty straightforward, copied class resource tracking and plugged in the unholy spells
=> [Unholy Death Knight] Added runic power tracking

.env.local.example, src/Parser/AVAILABLE_CONFIGS.js, src/Parser/DeathKnight/Frost/CHANGELOG.js, src/Parser/DeathKnight/Frost/CONFIG.js, src/Parser/DeathKnight/Frost/CombatLogParser.js, src/Parser/DeathKnight/Frost/Modules/Features/AlwaysBeCasting.js, src/Parser/DeathKnight/Frost/Modules/Features/CastEfficiency.js, src/Parser/DeathKnight/Frost/Modules/Features/CooldownTracker.js, src/Parser/DeathKnight/Frost/Modules/Features/FrostFeverUptime.js, src/Parser/DeathKnight/Frost/Modules/Features/HardHowlingBlastCasts.js, src/Parser/DeathKnight/Frost/Modules/Features/WastedRimeProcs.js, src/common/SPELLS/DEATH_KNIGHT.js
Added some initial frost dk metrics and analysis
=> [Frost Death Knight] Initial analysis

src/Parser/DeathKnight/Frost/CHANGELOG.js, src/Parser/DeathKnight/Frost/CombatLogParser.js, src/Parser/DeathKnight/Frost/Modules/Features/CastEfficiency.js, src/Parser/DeathKnight/Frost/Modules/Items/Legendaries/ColdHeart.js, src/Parser/DeathKnight/Shared/getDamageBonus.js, src/common/SPELLS/DEATH_KNIGHT.js
Added support for Cold Heart Legendary
=> Cold Heart support

src/Main/App.js, src/Main/ReportSelecter.js
Implemented auto selecting of fight and player if provided in the passed URL.
=> Auto Select Fight/Player if in WCL URL

CONTRIBUTING.SPEC.md
(Hello! I'm new at both git & Javascript. First pull request to a repo that isn't mine, so apologies in advance if I screw it up. I'm trying my hand at documentation until I get more confident in doing Javascript outside of a textbook.)
As a note, when I was double-checking through reading all the specs, Enhancement Shaman is the only class-spec to have CastEfficiency.js in Modules/Main instead of in Modules/Features. I'm not sure if that should be changed for consistency's sake or if it's OK since everything runs anyway.
=> Documentation: Add Cast Efficiency

.idea/inspectionProfiles/Project_Default.xml, CONTRIBUTING.REVIEW.md, package-lock.json, package.json, src/CHANGELOG.js, src/Main/App.css, src/Main/EventsTab.css, src/Main/EventsTable.js, src/Main/SpellTimeline.css, src/Main/SpellTimeline.js, src/Main/Suggestion.js, src/Main/SuggestionsTab.js, src/Parser/Core/CombatLogParser.js, src/Parser/Core/Modules/CastEfficiency.js, src/Parser/Core/Modules/SpellHistory.js, src/Parser/Core/Modules/SpellUsable.js, src/Parser/Core/Modules/SpellUsable.test.js, src/Parser/Core/ParseResults.js, src/common/Wrapper.js, src/common/format.js
=> Add spell timeline to cast efficiency suggestions

docs/README.md, docs/a-new-spec.md
- **Added** "Add Always be Casting" section of a-new-spec.md doc.
Also some minor bugs:
- **docs/README.md**: 
- Code review link no longer 404s.
- **docs/a-new-spec.md**: 
- Links to parental/other folder items no longer 404.
- Fixed links for files that changed names.
- Updated CombatParser.js-->CombatLogParser.js text references.
=> Documentation: Add Always Be Casting

src/Parser/Monk/Windwalker/CHANGELOG.js, src/Parser/Monk/Windwalker/Modules/Features/CastEfficiency.js, src/Parser/Monk/Windwalker/Modules/Features/CooldownThroughputTracker.js, src/Parser/Monk/Windwalker/Modules/WindwalkerCore/getDamageBonus.js
Some initial groundwork for future expansion on select feature (Xuen, EE).
@juko8 Suboptimal talent notifications not included in this branch pending raid release.
-Talby (PeakOfSerenity)
=> Cast tracking for Xuen and Energizing Elixir

src/Parser/Priest/Holy/CHANGELOG.js, src/Parser/Priest/Holy/CombatLogParser.js, src/Parser/Priest/Holy/Modules/Items/Tier21_2set.js, src/Parser/Priest/Holy/Modules/Items/Tier21_4set.js, src/common/SPELLS/PRIEST.js
Added T21 Bonuses to Holy Priest.
Test logs:
https://www.warcraftlogs.com/reports/thQVp9F4GM8qryAR
Any fight on character Charite or Ssiikkaallaa
=> [Holy Priest] T21

src/Parser/Core/Modules/SpellUsable.js, src/Parser/Priest/Shadow/CHANGELOG.js, src/Parser/Priest/Shadow/CombatLogParser.js, src/Parser/Priest/Shadow/Modules/Core/Haste.js, src/Parser/Priest/Shadow/Modules/Features/AlwaysBeCasting.js, src/Parser/Priest/Shadow/Modules/Features/CastEfficiency.js
Remade the pull request.
Old request can be found here: https://github.com/WoWAnalyzer/WoWAnalyzer/pull/739
Already reviewed and should be good to go.
=> Shadow priest fixes, mostly ABC module

src/Parser/Mage/Frost/CONFIG.js
Updated the Config to give links to mage resources for additional help and suggestions.
=> [Frost Mage] Updated Config

src/Parser/DeathKnight/Frost/CHANGELOG.js, src/Parser/DeathKnight/Frost/Modules/Features/CastEfficiency.js, src/Parser/DeathKnight/Frost/Modules/Features/HardHowlingBlastCasts.js, src/Parser/DeathKnight/Frost/Modules/Features/WastedRimeProcs.js, src/common/SPELLS/DEATH_KNIGHT.js
**Major stuff**
Added BoS
IA talent support
**Minor Stuff**
Extra info changes.
=> BoS Support

src/Parser/Hunter/Marksmanship/CombatLogParser.js, src/Parser/Hunter/Marksmanship/Modules/Traits/Bullseye.js, src/Parser/Hunter/Shared/FocusChart/Focus.css
This implements a bullseye tracker with a suggestion and a statisticsbox. It also lays the groundwork for a future PR I'll make (or Putro, whoever gets around to it) to give more advanced checks for proper murder of crows and trueshot usage.
(sorry for new screenshots, but I'm in a rush right now- I intend to upload them later if they're needed)
=> [Marksmanship] Implemented Bullseye tracker

src/Parser/Hunter/Shared/FocusChart/FocusTracker.js
Fixes a bug where time focus capped was at 0% and removed unused variable.
=> [Marksmanship] minor style and bug fixes

src/Parser/DeathKnight/Unholy/Modules/Features/CastEfficiency.js, src/Parser/DeathKnight/Unholy/Modules/Talents/UnholyFrenzy.js
Added all active talents and rotational spells
=> [Unholy Death Knight]updated castefficiency

src/Parser/Monk/Windwalker/Modules/Features/AlwaysBeCasting.js
I tried using the channelling implementation from Spriest, but it was causing negative downtime, so is commented out for the time being
=> [Windwalker] Updated ABC with static GCDs

src/CHANGELOG.js, src/Main/App.css, src/Main/Results.js
=> Added a larger call for help for specs that are marked "Not actively maintained"

src/Parser/Mage/Frost/Modules/Features/CastEfficiency.js, src/Parser/Mage/Frost/Modules/Features/WintersChill.js
Added a damage counter to show how much extra damage the player got from Double Ice Lance. Also modified the cast time on Ebonbolt to include the Cast Time of the spell. That way the Cast Efficiency can be a little more accurate when it is determining how many casts were possible.
These changes were per some feedback from the Mage Discord
=> [Frost Mage] Misc Additions/Fixes

src/CHANGELOG.js, src/Main/App.css, src/Main/Changelog.js
=> Changed the Changelog tab to mark *shared changes* as grey and provided a toggle to hide them

src/Parser/DeathKnight/Unholy/CHANGELOG.js, src/Parser/DeathKnight/Unholy/CombatLogParser.js, src/Parser/DeathKnight/Unholy/Modules/Items/Tier20_2p.js, src/common/SPELLS/DEATH_KNIGHT.js
Finished an old PR on behalf of Maxweii
=> [Unholy Death Knight] Added t20 2 piece

src/Parser/Hunter/Marksmanship/Modules/Talents/PatientSniper/PatientSniperTracker.js
Janky, but functioning fix for crash...
This fixes the crash in the following logs: 
https://wowanalyzer.com/report/XyLqCw1rAYf32bNK/7-Normal+Harjatan+-+Kill+(2:10)/Niioxce
https://wowanalyzer.com/report/WdtbYpr1Lkmc7hR4/1-Mythic+Harjatan+-+Kill+(4:38)/10
and therefore should fix these sentry reports: 
https://sentry.io/share/issue/6027102b669f44b0ac1b2f54856070ae/
https://sentry.io/share/issue/2401195bc2ea4720afefe9d3cb41aa5a/
=> [Marksmanship] Patient sniper bug hunt

docs/contributor-names.md, src/Parser/Rogue/Subtlety/CONFIG.js
Hi,
I'd like to contribute to Sub Rogue, maybe take Assa when Sub is done.
First real pull request coming too. 
I'm not familiar with open source fork/pull request workflow, so let me know if I've messed up =)
=> Sub Rogue new contributor

src/Parser/Rogue/Subtlety/CombatLogParser.js, src/Parser/Rogue/Subtlety/Modules/Features/ShadowBladesUptime.js, src/Parser/Rogue/Subtlety/Modules/Features/ShadowDance.js, src/Parser/Rogue/Subtlety/Modules/Features/SymbolsOfDeathUptime.js, src/Parser/Rogue/Subtlety/Modules/Talents/DarkShadow.js, src/Parser/Rogue/Subtlety/Modules/Talents/DarkShadowContribution.js, src/Parser/Rogue/Subtlety/Modules/Talents/DarkShadowEvis.js, src/Parser/Rogue/Subtlety/Modules/index.js
Refactoring of the current sub rogue metrics.
=> Sub rogue refactoring

src/Parser/Mage/Frost/Modules/Cooldowns/FrozenOrb.js, src/Parser/Mage/Frost/Modules/Cooldowns/IcyVeins.js, src/Parser/Mage/Frost/Modules/Features/Abilities.js
Updated to new Cast Efficiency & Removed Icy Veins/Frozen orb Suggestions
=> [Frost Mage] Update to new Cast Efficiency

src/Parser/Hunter/Marksmanship/Modules/Spells/Trueshot.js, src/Parser/Hunter/Shared/FocusChart/FocusTracker.js
If one were to precast trueshot and not cast it anymore in a fight, you'd end up with this result: 
This updates fixes it so that it'll end up looking like this:
=> [Marksmanship] Fix infinity error on trueshot

src/Parser/Rogue/Subtlety/Modules/Features/Abilities.js, src/common/SPELLS/ROGUE.js, src/common/SPELLS/TALENTS/ROGUE.js
Adding new ~~Cast Efficiency~~ Abilities
=> Adding new Sub Abilities.

src/Parser/Hunter/Marksmanship/Modules/Features/AimedInVulnerableTracker.js
Fixes the crash in this log: 
https://wowanalyzer.com/report/yjz6dxFr1NqYMhPc/1-+%D0%9A%D0%B0%D0%B7%D0%B5%D0%BC%D0%B0%D1%82%D1%8B+%D0%A1%D1%82%D1%80%D0%B0%D0%B6%D0%B5%D0%B9+-+Kill+(26:17)/%D0%AD%D1%88%D0%BB%D1%8F
=> [Marksmanship] fixes crash in AimedInVulnerableTracker

src/Parser/Hunter/Marksmanship/Modules/Features/Abilities.js
Putting my money where my mouth is in terms of not having very high cast efficiency requirements without some sort of suggestion tied to it. 
oh and also adds Arcane torrent
=> [Marksmanship] add new cast efficiency suggestions

src/Parser/Core/Modules/Abilities.js, src/Parser/Core/Modules/Items/KiljaedensBurningWish.js
Kiljaeden's Burning Wish needs special handling for cast efficiency because it doesn't actually produce cast events for whatever reason.
=> [core] Implemented KJBW cast efficiency, and updated its statistic

src/Parser/Hunter/Marksmanship/Modules/Talents/PatientSniper/PatientSniperTracker.js
Should fix this crash: https://sentry.io/share/issue/d1bab9a4f7bf405d97d8111321d45a31/
=> [Marksmanship] fixes patientsniper crash

src/Parser/Mage/Frost/Modules/Features/IceLance.js
=> [frost mage] Fixed a bug where the IceLance module would sometimes crash

src/Parser/Priest/Shadow/CONFIG.js
I would like to become the maintainer once again for this spec.
=> Shadow priest: Maintainer change

src/Parser/Mage/Fire/CHANGELOG.js, src/Parser/Mage/Fire/CombatLogParser.js, src/Parser/Mage/Fire/Modules/Cooldowns/Combustion.js, src/Parser/Mage/Fire/Modules/Features/Kindling.js
Cooldown Reduction for Combustion
=> [Fire Mage] Combustion Cooldown Reduction

src/Parser/Mage/Fire/CHANGELOG.js, src/Parser/Mage/Fire/CombatLogParser.js, src/Parser/Mage/Fire/Modules/Items/ContainedInfernalCore.js, src/Parser/Mage/Fire/Modules/Items/DarcklisDragonfireDiadem.js, src/Parser/Mage/Fire/Modules/Items/PyrotexIgnitionCloth.js, src/common/SPELLS/MAGE.js
Adds support for three of fire's legendary items. Ill be adding support for more of them at a later time.
=> [Fire Mage] Legendary Item Support

src/Parser/Monk/Windwalker/Modules/Items/T21_4set.js, src/Parser/Monk/Windwalker/Modules/Spells/ComboBreaker.js
After doing some testing with the tier bonus myself i can see that the pet damage is no longer bugged.
=> [Windwalker] Updating Tier21 stuff

src/Parser/DeathKnight/Unholy/Modules/Features/FesteringStrike.js, src/Parser/DeathKnight/Unholy/Modules/RunicPower/RunicPowerDetails.js
Updating values on Runic Power wasted percentages.
=> Unholy - Runic Power/Festering Strike Module

src/Parser/Rogue/Subtlety/Modules/Features/Abilities.js, src/Parser/Rogue/Subtlety/Modules/ResourceTracker/ResourceTracker.js, src/Parser/Rogue/Subtlety/Modules/RogueCore/ComboPointTracker.js, src/common/SPELLS/ROGUE.js
Just adding cooldown reductions.
=> Sub Rogue - Cooldown Reductions for Dance and T21_2P Symbols

src/Parser/Warlock/Affliction/Modules/Features/UABuffTracker.js, src/Parser/Warlock/Affliction/Modules/Talents/MaleficGrasp.js
Self-explanatory, should fix what Sentry didn't like
=> [Bugfix][Warlock] Bugfixes for UA tracker and MG

src/Main/CastEfficiency.js, src/Parser/Core/Modules/CastEfficiency.js
Fixed a bug where Ability with multiple spells wasn't being handled properly in some areas.
Fixed a bug where spells with zero casts weren't getting suggestions or 'can be improved' markers.
=> [core] Cast Efficiency fixes

src/Parser/Priest/Shadow/CHANGELOG.js, src/Parser/Priest/Shadow/Modules/Features/Abilities.js, src/Parser/Priest/Shadow/Modules/Items/HeartOfTheVoid.js
Updated modifiers and cooldowns for the Antorus release.
Please do not merge before Antorus.
=> Shadow priest changes (Antorus)

src/common/Icon.js
=> Icon Source Change

src/Parser/Core/CombatLogParser.js, src/Parser/Core/Modules/Items/AmalgamsSeventhSpine.js, src/Parser/Core/Modules/Items/ArchimondesHatredReborn.js, src/Parser/Core/Modules/Items/ArchiveOfFaith.js, src/Parser/Core/Modules/Items/BarbaricMindslaver.js, src/Parser/Core/Modules/Items/CharmOfTheRisingTide.js, src/Parser/Core/Modules/Items/Cinidaria.js, src/Parser/Core/Modules/Items/DarkmoonDeckPromises.js, src/Parser/Core/Modules/Items/DeceiversGrandDesign.js, src/Parser/Core/Modules/Items/DrapeOfShame.js
I'm making a style / appearance pass on the Core Items modules. This covers all items from A to D. I also added two useful formatting utilities to CombatLogParser.
ALL: Added item's tooltip to comments at top of class.
AmalgamsSeventhSpine: Updated to use utility functions.
ArchimondesHatredReborn: Removed somewhat tautological tooltip.
ArchiveOfFaith: Fixed incorrectly named var, updated to use utility functions.
Cinidaria: Updated to use utility functions.
DarkmoonDeckPromises: Updated to use utility functions.
DeceiversGrandDesign: Complete rework, including cast listing in the item panel and a suggestion that now triggers on average HoT duration. See screenshots below:
=> [core] Core items update (A through D) including DGD rework

src/Parser/Rogue/Subtlety/CombatLogParser.js, src/Parser/Rogue/Subtlety/Modules/Items/T21_2P.js, src/Parser/Rogue/Subtlety/Modules/Legendaries/DenialOfHalfGiants.js, src/Parser/Rogue/Subtlety/Modules/ResourceTracker/ResourceTracker.js, src/Parser/Rogue/Subtlety/Modules/RogueCore/ComboPointDetails.js, src/Parser/Rogue/Subtlety/Modules/RogueCore/ComboPointTracker.js, src/Parser/Rogue/Subtlety/Modules/RogueCore/DanceCooldownReduction.js, src/Parser/Rogue/Subtlety/Modules/RogueCore/EnergyTracker.js
Adding Denial of the Half Giants.
Also refactoring the on_spend() method to be a fabricated event as advised by Serf.
=> [Sub Rogue] Denial of the Half Giants

src/Parser/Mage/Fire/CHANGELOG.js, src/Parser/Mage/Fire/CONFIG.js, src/Parser/Mage/Fire/CombatLogParser.js, src/Parser/Mage/Fire/Modules/Features/HotStreak.js, src/Parser/Mage/Fire/Normalizers/Flamestrike.js, src/common/SPELLS/MAGE.js
Hot Streak Analysis.
Tracks Total Procs, Expired Procs, and direct damage crits while Hot Streak is active.
=> [Fire Mage] Hot Streak Module

src/CHANGELOG.js, src/Parser/Core/Modules/Features/SpellInfo.js
=> Stat weight improvements as described in #656

src/Parser/Rogue/Subtlety/Modules/Items/T21_2P.js, src/common/SPELLS/ROGUE.js
Small PR to fix issues with 2P T21 and add some suggestions aswel.
=> [Sub Rogue ] T21 2P fixes and suggestions

src/Parser/Core/Modules/Haste.js, src/Parser/Core/Modules/StatTracker.js, src/Parser/Priest/Shadow/CHANGELOG.js, src/Parser/Priest/Shadow/CombatLogParser.js, src/Parser/Priest/Shadow/Modules/Core/Haste.js, src/Parser/Priest/Shadow/Modules/Features/Abilities.js, src/Parser/Priest/Shadow/Modules/Features/AlwaysBeCasting.js, src/Parser/Priest/Shadow/Modules/Features/SkippableCasts.js, src/Parser/Priest/Shadow/Modules/Spells/ShadowWordPain.js, src/Parser/Priest/Shadow/Modules/Spells/TwistOfFate.js, src/Parser/Priest/Shadow/Modules/Spells/VampiricTouch.js, src/Parser/Priest/Shadow/Modules/Spells/Voidform.js
=> Shadow priest: little bit of everything

src/Parser/Hunter/Marksmanship/Modules/Items/TarnishedSentinelMedallion.js, src/Parser/Hunter/Marksmanship/Modules/Talents/AMurderOfCrows.js
Something introduced a crash I haven't had anywhere before - this fixes  it, noticed it in one of my own logs... 
https://wowanalyzer.com/report/BVGYDTWv2wfAbdQF/49-Heroic+Argus+the+Unmaker+-+Kill+(9:11)/Putro
=> [Marksmanship] fixes a owl trinket crash

src/Parser/Core/CombatLogParser.js, src/Parser/Core/Modules/Items/PrototypePersonnelDecimator.js, src/common/ITEMS/OTHERS.js, src/common/SPELLS/OTHERS.js
Will likely need to be manually merged when #953 goes through, ping Khazak on discord to get that done.
=> Added Prototype Personnel Decimator to items

src/Parser/Priest/Discipline/CHANGELOG.js, src/Parser/Priest/Discipline/Modules/Features/AtonementHealingBreakdown.js, src/Parser/Priest/Discipline/Modules/Features/AtonementHealingDone.js
=> [Discipline Priest] Atonement per Penance Bolt in Atonement Source Tab

src/Parser/Rogue/Subtlety/Modules/BaseRotation/NightbladeDuringSymbols.js, src/Parser/Rogue/Subtlety/Modules/RogueCore/ComboPointDetails.js, src/Parser/Rogue/Subtlety/Modules/RogueCore/EnergyDetails.js
Just some suggestion re balance based on feedback
=> [Sub Rogue] Suggestion re balance

src/Parser/Core/CombatLogParser.js, src/Parser/Core/Modules/Items/NorgannonsProwess.js, src/common/ITEMS/OTHERS.js, src/common/SPELLS/OTHERS.js
=> Norgannon's Prowess

src/Parser/Core/CombatLogParser.js, src/Parser/Core/Modules/Items/SheathOfAsara.js, src/common/ITEMS/OTHERS.js, src/common/SPELLS/OTHERS.js
With this PR all the DPS trinkets for T21 should be accounted for
=> Added Sheath of Asara

src/Parser/Shaman/Restoration/CONFIG.js
=> Moving to maintain resto shaman

src/Parser/Warlock/Destruction/Modules/Features/Havoc.js, src/Parser/Warlock/Destruction/Modules/Talents/Eradication.js
hiding havoc, adding erad uptime as statistic, adding erad uptime as suggestion. (i talked with chizu about this stuff)
=> minor destruction tweaks

src/Parser/Warlock/Destruction/CombatLogParser.js, src/Parser/Warlock/Destruction/Modules/Features/AlwaysBeCasting.js, src/Parser/Warlock/Destruction/Modules/Features/Havoc.js, src/Parser/Warlock/Destruction/Modules/Talents/Backdraft.js, src/Parser/Warlock/Destruction/Modules/Talents/ChannelDemonfire.js, src/Parser/Warlock/Destruction/Modules/Talents/EmpoweredLifeTap.js, src/Parser/Warlock/Destruction/Modules/Talents/Eradication.js, src/Parser/Warlock/Destruction/Modules/Talents/FireAndBrimstone.js, src/Parser/Warlock/Destruction/Modules/Talents/ReverseEntropy.js, src/Parser/Warlock/Destruction/Modules/Talents/RoaringBlaze.js, src/Parser/Warlock/Destruction/Modules/Talents/Shadowburn.js, src/Parser/Warlock/Destruction/Modules/Talents/SoulHarvestTalent.js, src/Parser/Warlock/Destruction/Modules/Talents/TalentHub.js
@sMteX: added talent hub to clean up the interface. added a couple wording/explanation fixes to ABC module.
that merge is me merging latest wowanalyzer into my fork.
removing combatants broke it so i put it back
=> destro talent overhaul / minor updates

src/Parser/Core/CombatLogParser.js, src/Parser/Core/Modules/Items/EnchantChecker.js
Aims to address issue #685.  It works just fine but I'm not sure about the style used here so feedback is extra welcome
=> EnchantChecker

src/Parser/Warlock/Destruction/Modules/Talents/EmpoweredLifeTap.js
https://i.imgur.com/a9k8t1R.png
=> edit spacing for consistency

src/Parser/Rogue/Subtlety/Modules/BaseRotation/CastsInShadowDance.js
Just a bugfix, suggestion was not working.
Also altering it to always show major correctly instead of average when its just 1.
=> [Sub Rogue] Bugfix fro backstab in dance

src/common/SPELLS/ROGUE.js
=> [Sub Rogue] fix CP crash witrh 4pT21

src/Parser/DeathKnight/Unholy/CombatLogParser.js, src/Parser/DeathKnight/Unholy/Modules/Items/Tier21_2p.js, src/Parser/DeathKnight/Unholy/Modules/Items/Tier21_4p.js, src/common/SPELLS/DEATH_KNIGHT.js
=> [Unholy Death Knight] T21

src/Parser/Druid/Restoration/Modules/Features/Efflorescence.js
I came in just to fix #968 , and instead rewrote the whole module because it needed it. My rewrite also makes it easy for a later PR to add "don't early refresh Efflo" suggestion.
=> [resto druid] Rewrote efflo module, fixing the no-cast bug and also opening up easy implementation of 'early refresh' suggestion

src/Parser/Druid/Restoration/Modules/Features/Efflorescence.js, src/Parser/Shaman/Restoration/Modules/Spells/GiftOfTheQueen.js, src/Parser/Warrior/Fury/CONFIG.js, src/Parser/Warrior/Fury/Modules/BuffDebuff/EnrageUptime.js, src/Parser/Warrior/Fury/Modules/BuffDebuff/FrothingBerserkerUptime.js, src/Parser/Warrior/Fury/Modules/BuffDebuff/Juggernaut.js, src/Parser/Warrior/Fury/Modules/Features/Abilities.js
Fixed all of the issues mentioned by @MartijnHols in #982 
- Changed class names to PascalCase
- Added getters for uptimes
- Added suggestion thresholds
- Replaced <span> with <Wrapper>
- Replaced some low recommendedEfficiencies withfixed minor importance.
- Fixed missing dots
- Fixed insufficient extraSuggestions
- Fixed Shockwave recommendedEffiency being unrealisticly high
=> Fury warrior

src/Parser/Core/Modules/Features/Checklist.js, src/Parser/Priest/Shadow/CombatLogParser.js, src/Parser/Priest/Shadow/Modules/Features/Abilities.js, src/Parser/Priest/Shadow/Modules/Features/AlwaysBeCasting.js, src/Parser/Priest/Shadow/Modules/Features/Checklist.js, src/Parser/Priest/Shadow/Modules/Spells/Mindbender.js, src/Parser/Priest/Shadow/Modules/Spells/ShadowWordPain.js, src/Parser/Priest/Shadow/Modules/Spells/VampiricTouch.js, src/Parser/Priest/Shadow/Modules/Spells/VoidTorrent.js, src/Parser/Priest/Shadow/Modules/Spells/Voidform.js, src/common/format.js
Initial checklist implementation.
=> Shadowpriest checklist

src/Parser/Shaman/Elemental/Modules/Talents/LightningRod.js
Not too sure about looks/layout.
Just shows the damage done by the talent.
=> Added Lightning Rod Damage Display

src/Parser/Monk/Mistweaver/Modules/Features/Abilities.js, src/Parser/Monk/Mistweaver/Modules/Features/Checklist.js, src/Parser/Monk/Mistweaver/Modules/Spells/SheilunsGift.js, src/Parser/Monk/Mistweaver/Modules/Talents/ManaTea.js, src/Parser/Monk/Mistweaver/Modules/Talents/SpiritOfTheCrane.js, src/Parser/Monk/Mistweaver/Modules/Traits/RelicTraits.js
Additional Rules and suggestion adjustment for Spirit of the Crane Talent.
=> [Mistweaver Monk] SotC Update and Add in Defensive CD Usage to Checklist

src/Main/Toggleable.js
makes more sense that way and is the intended functionality (missed that in my pull request somehow)
=> changed toggleable to be toggled off by default

src/Parser/Core/Modules/StatTracker.js, src/Parser/Shaman/Elemental/CombatLogParser.js, src/Parser/Shaman/Elemental/Modules/Items/Tier21_2set.js, src/Parser/Shaman/Elemental/Modules/Items/Tier21_4set.js, src/common/SPELLS/SHAMAN.js
=> Elemental Shaman Mastery and Tier 21

src/Parser/Hunter/BeastMastery/CHANGELOG.js, src/Parser/Hunter/BeastMastery/CombatLogParser.js, src/Parser/Hunter/BeastMastery/Modules/Features/Abilities.js, src/Parser/Hunter/BeastMastery/Modules/Features/Checklist.js, src/Parser/Hunter/BeastMastery/Modules/Features/TraitsAndTalents.js, src/Parser/Hunter/BeastMastery/Modules/Items/Tier21_4p.js, src/Parser/Hunter/BeastMastery/Modules/Spells/AspectOfTheWild.js, src/Parser/Hunter/BeastMastery/Modules/Spells/BestialWrath/BestialWrathAverageFocus.js, src/Parser/Hunter/BeastMastery/Modules/Spells/BestialWrath/BestialWrathUptime.js, src/Parser/Hunter/BeastMastery/Modules/Spells/BestialWrath/GainedBestialWraths.js, src/Parser/Hunter/BeastMastery/Modules/Spells/DireBeast/DireBeast.js, src/Parser/Hunter/BeastMastery/Modules/Talents/AMurderOfCrows.js, src/Parser/Hunter/BeastMastery/Modules/Talents/AspectOfTheBeast.js, src/Parser/Hunter/BeastMastery/Modules/Talents/DireFrenzy.js, src/Parser/Hunter/BeastMastery/Modules/Talents/KillerCobra.js, src/Parser/Hunter/BeastMastery/Modules/Traits/TitansThunder.js, src/common/SPELLS/HUNTER.js
Adds some functionality to the Dire Frenzy module (fixes #919 )
Adds a Aspect of the Wild module
Fixes a bug in t21 4p module
Does some reordering of the statistic modules
=> [Beast Mastery] Checklist update + Dire Frenzy and AotW modules

src/Parser/Core/Combatant.js, src/Parser/Core/Modules/StatTracker.js
Some more stuff suggested by reddit
=> Added Prot Paladin Mastery Values and Ele-Mastery to Combatants

src/CHANGELOG.js, src/Main/Timeline/Events.js, src/Main/Timeline/SpellTimeline.css, src/Main/Timeline/SpellTimeline.js, src/Parser/Core/CombatLogParser.js, src/Parser/Core/Modules/AlwaysBeCasting.js, src/Parser/Core/Modules/GlobalCooldown.js
Might have to tweak the colors a bit. I thought about what color I thought the GCD would be and figured brown seemed right, but in hindsight it doesn't look that well.
Fixes #1044
=> Fix #1044: Added a *casting time* bar to the spell timeline that shows you the amount of time spent channeling or waiting for the GCD

src/Parser/Shaman/Enhancement/CombatLogParser.js, src/Parser/Shaman/Enhancement/Modules/Items/Tier20_2set.js, src/Parser/Shaman/Enhancement/Modules/Items/Tier21_2set.js, src/Parser/Shaman/Enhancement/Modules/Items/Tier21_4set.js, src/common/SPELLS/SHAMAN.js
=> Fixed Enhancement T20 2set always showing up (thx reddit)

src/Parser/Mage/Fire/CHANGELOG.js, src/Parser/Mage/Frost/CHANGELOG.js
Converted the changelogs for Fire and Frost to match the new layout
=> [Mage] New Changelog Format

src/Parser/Warrior/Fury/Modules/Features/Abilities.js, src/Parser/Warrior/Fury/Modules/Features/RampageCancelled.js, src/Parser/Warrior/Fury/Modules/Features/RampageFrothingBerserker.js
* Added support for Timeless Shoulders
* Fixed so Rampage casts during Battle Cry are not counted towards premature casts
* Fixed text for Rampage Cancellations as Rampage cannot be cancelled unless moving away or facing away from the target
=> [Fury warrior] Bug fix + Legendary Shoulders equip effect

src/Parser/Core/Modules/StatTracker.js, src/Parser/Druid/Balance/CHANGELOG.js, src/Parser/Druid/Balance/CombatLogParser.js, src/Parser/Druid/Balance/Modules/Core/Haste.js, src/Parser/Druid/Balance/Modules/Features/Abilities.js, src/Parser/Druid/Balance/Modules/Features/AlwaysBeCasting.js, src/Parser/Druid/Balance/Modules/Features/CooldownThroughputTracker.js, src/Parser/Druid/Balance/Modules/Spells/MoonSpells.js, src/Parser/Druid/Balance/Modules/Spells/UnempoweredLs.js, src/common/SPELLS/DRUID.js
- fixed a few things in ABC
- CooldownThroughputTracker added for Incarnation & Celestial Alignment
- Added Warrior of Elune and Force of Nature to cast efficiency
- Mastery conversion added
- adjusted unempowered lunar strikes to accept instant casts
- support for merging moon spells in statistic boxes (will not be used until they can be merged in cast efficiency aswell)
=> Balance Druid updates

src/Parser/DeathKnight/Blood/CombatLogParser.js, src/Parser/DeathKnight/Blood/Modules/Features/Abilities.js, src/Parser/DeathKnight/Blood/Modules/Features/BloodPlagueUptime.js, src/Parser/DeathKnight/Blood/Modules/Features/BoneShieldUptime.js, src/Parser/DeathKnight/Blood/Modules/Features/Checklist.js, src/Parser/DeathKnight/Blood/Modules/Features/OssuaryUptime.js, src/Parser/DeathKnight/Blood/Modules/RunicPower/RunicPowerDetails.js, src/common/SPELLS/DEATH_KNIGHT.js
Created the check list and updated some of the uptime code.
=> Initial Check List

src/Parser/Mage/Frost/Modules/Items/Tier21_2set.js
Turns out the timestamp tracking stuff wasn't needed, see added code comment for explanation. Thanks Norrinir for the research leading to this refactor.
=> [frost mage] Refactored 2t21 module for added simplicity and better handling of edge cases

src/Parser/Mage/Frost/Modules/Items/MagtheridonsBanishedBracers.js
Fix for crash caused by Magtheridon's Banished Bracers.
=> [Frost Mage] Fix Crash for Magtheridon's Banished Bracers

src/Parser/Hunter/BeastMastery/CHANGELOG.js, src/Parser/Hunter/BeastMastery/CombatLogParser.js, src/Parser/Hunter/BeastMastery/Modules/Spells/AspectOfTheWild.js, src/Parser/Hunter/BeastMastery/Modules/Spells/BestialWrath/BestialWrathAverageFocus.js, src/Parser/Hunter/BeastMastery/Modules/Spells/BestialWrath/BestialWrathUptime.js, src/Parser/Hunter/BeastMastery/Modules/Spells/BestialWrath/GainedBestialWraths.js, src/Parser/Hunter/BeastMastery/Modules/Spells/DireBeast/DireBeast.js, src/Parser/Hunter/BeastMastery/Modules/Talents/AMurderOfCrows.js, src/Parser/Hunter/BeastMastery/Modules/Traits/TitansThunder.js, src/Parser/Hunter/Marksmanship/CHANGELOG.js, src/Parser/Hunter/Marksmanship/CombatLogParser.js, src/Parser/Hunter/Shared/Modules/Features/FocusChart/Focus.js, src/Parser/Hunter/Shared/Modules/Features/FocusChart/FocusComponent.js, src/Parser/Hunter/Shared/Modules/Features/FocusChart/FocusTracker.js
Pretty minor, just ensuring that focus gained from pet is handled properly by the module aswell
Fixes a bug that allowed the chart to show negative focus aswell
Fixes #918
=> [Hunter] Updated Focus Chart, added that and timeFocusCapped module to BM 

src/Parser/DeathKnight/Unholy/Modules/Features/RpPoolingDA.js
Came in to fix a crash with the RP pooling module, did some refactoring while I was at it
=> [Unholy Death Knight] Refactored RP Pooling and fixed crash

src/Parser/Core/Modules/AlwaysBeCasting.js, src/Parser/Core/Modules/GlobalCooldown.js, src/Parser/Monk/Brewmaster/CombatLogParser.js, src/Parser/Monk/Brewmaster/Modules/Core/Channeling.js, src/Parser/Monk/Brewmaster/Modules/Core/GlobalCooldown.js, src/Parser/Monk/Brewmaster/Modules/Features/AlwaysBeCasting.js, src/Parser/Monk/Brewmaster/Modules/Features/Checklist.js
It's still missing a lot of spells from the abilities config which will cause the timeline to not be complete, but I won't be fixing that.
=> Fix Brewmaster's GCDs and channeling

src/Parser/Druid/Balance/CONFIG.js, src/Parser/Druid/Balance/CombatLogParser.js, src/Parser/Druid/Balance/Modules/Core/GlobalCooldown.js, src/Parser/Druid/Balance/Modules/Features/AlwaysBeCasting.js, src/Parser/Druid/Balance/Modules/Features/LunarEmpowerment.js, src/Parser/Druid/Balance/Modules/Features/SolarEmpowerment.js
- Timeline and ABC should be more accurate now.
- Increased ABC threshold for balance (most top logs have 4+% downtime, so expecting <2% doesn't seem reasonable). Might be worth considering making it a core change though.
- Added myself as balance maintainer so I can enjoy DMs
=> [Balance] Added Starlord GCD reduction

src/Parser/Hunter/Shared/Modules/Features/FocusChart/FocusTracker.js
a missing id was making it not show abilities correctly
=> [Hunter] fix focuschart

src/Parser/Druid/Balance/CHANGELOG.js, src/Parser/Druid/Balance/CombatLogParser.js, src/Parser/Druid/Balance/Modules/Items/ImpeccableFelEssence.js, src/Parser/Druid/Balance/Modules/Items/LadyAndTheChild.js, src/Parser/Druid/Balance/Modules/Items/OnethsIntuition.js, src/Parser/Druid/Balance/Modules/Items/PromiseOfElune.js, src/Parser/Druid/Balance/Modules/Items/SoulOfTheArchdruid.js, src/Parser/Druid/Balance/Modules/ResourceTracker/AstralPowerTracker.js, src/common/ITEMS/DRUID.js, src/common/SPELLS/DRUID.js
- Added wasted cooldown reduction to IFE
- Added Soul of the Archdruid
- Added Lady and the Child
- Added Oneth's Intuition
- Added Promise of Elune
=> [Balance] Added most legendaries

src/Parser/Druid/Balance/CHANGELOG.js, src/Parser/Druid/Balance/CombatLogParser.js, src/Parser/Druid/Balance/Modules/Items/Tier21_2set.js, src/Parser/Druid/Balance/Modules/Items/Tier21_4set.js, src/common/SPELLS/DRUID.js
- 2p: damage contribution
- 4p: damage contribition and uptime
=> [Balance] Tier 21

src/Parser/Mage/Fire/Modules/Features/HeatingUp.js
Fixes the suggestions on the Heating Up Module so that the suggestion isnt using the missed % but recommending using the Util %
=> [Fire Mage] Fix Suggestions on Heating Up

src/Parser/Core/Modules/NetherlightCrucibleTraits/MasterOfShadows.js
Simple adjustment since tooltips out of game are glitchy
=> [Core] updated Master of Shadows value

debug.log, src/Main/Timeline/SpellTimeline.js, src/Parser/Core/Modules/CastEfficiency.js, src/Parser/Druid/Restoration/Modules/Features/Abilities.js
> Fixed an issue where the analyzer would crash if user clicked "show timeline" for a cast efficiency suggestion.
> Fixed an issue where single spell timelines also showed GCD and channel time
> Fixed an issue where static suggestion importance wasn't being handled.
> Fixed an issue where static importance for Swiftmend wasn't being set correctly.
=> [core] Fixed several bugs introduced by abilities refactor

src/Parser/Hunter/BeastMastery/Modules/Spells/AspectOfTheWild.js, src/Parser/Hunter/Marksmanship/CHANGELOG.js, src/Parser/Hunter/Marksmanship/CombatLogParser.js, src/Parser/Hunter/Marksmanship/Modules/Spells/Trueshot.js, src/Parser/Hunter/Marksmanship/Modules/Talents/Sentinel.js, src/common/SPELLS/HUNTER.js
Adds a module for the Sentinel talent, and also showcases its buggy nature
Fixes #1069
=> [Marksmanship] Sentinel module

src/Parser/Hunter/Marksmanship/Modules/Abilities.js, src/Parser/Hunter/Marksmanship/Modules/Features/Checklist.js, src/Parser/Hunter/Shared/Modules/Features/TimeFocusCapped.js, src/common/SPELLS/HUNTER.js
In my recent large rewrites I introduced a few dumb mistakes, this PR fixes these.
Fixes:
https://cdn.discordapp.com/attachments/233915164871622657/400451154175197185/9d7e67e163b284a852734bb7649684f0.png
From this log: https://wowanalyzer.com/report/4vyfmgpHLn6Bc9qT/13-Heroic+Varimathras+-+Kill+(3:23)/Veraquiel
Fixes:
https://cdn.discordapp.com/attachments/233915164871622657/400479614159552512/Screenshot_21.png
to show properly percentages.
=> fix 2 bugs

src/MAINTAINERS.js, src/Parser/DeathKnight/Unholy/CHANGELOG.js, src/Parser/DeathKnight/Unholy/CONFIG.js
Bicepspump authored 3 modules with another in progress, and is also much more active in the unholy discord channels so I'm adding him as a maintainer/feedback target
=> [Unholy Death Knight] Added Bicepspump to contributors and updated changelog

src/Parser/Mage/Fire/Modules/Features/HeatingUp.js
Just noticed the Phoenix Flames Suggestion had the Fire Blast Icon.
=> [Fire Mage] More Fixes for Heating Up

src/Parser/Core/Modules/Haste.js, src/Parser/Core/Modules/Items/Legion/AntorusTheBurningThrone/GarothiFeedbackConduit.js, src/Parser/Core/Modules/StatTracker.js, src/Parser/Paladin/Holy/CHANGELOG.js
Add Garothi Feedback Conduit Haste gain to the list so it is properly accounted for in the current Haste
=> Fix Garothi Feedback Conduit average Haste calculation

src/Parser/Mage/Fire/Modules/Features/HeatingUp.js
The Heating Up Module was not taking into account the guaranteed crits during Firestarter and Combustion ... Per #1171
=> [Fire Mage] Fixed Bug with Heating Up

src/CHANGELOG.js, src/Parser/Core/CombatLogParser.js, src/Parser/Core/Modules/Items/Legion/Legendaries/AmanthulsVision.js, src/Parser/Paladin/Retribution/Modules/Items/ChainOfThrayn.js, src/Parser/Paladin/Retribution/Modules/PaladinCore/Retribution.js, src/Parser/Paladin/Retribution/Modules/Traits/WrathOfTheAshbringer.js, src/common/ITEMS/OTHERS.js, src/common/SPELLS/OTHERS.js
Added in a module for Amanthuls. Also removed friendly fire in all Retribution modules that were accounting for it.
=> [General] Aman'Thul's Vision

src/Parser/Core/Modules/StatTracker.js, src/Parser/Paladin/Retribution/Modules/Abilities.js, src/Parser/Paladin/Retribution/Modules/Features/AlwaysBeCasting.js, src/Parser/Paladin/Retribution/Modules/Features/Checklist.js, src/common/SPELLS/OTHERS.js
Added in the flasks and the 'good' food into spells and the stat tracker. Also made a minor suggestion tweak to the Wake of Ashes suggestion and fixed a bug with it displaying twice.
fixes #659  -- edited by kfinch
=> [General] Update stat tracker

src/Parser/Hunter/Marksmanship/Modules/Spells/Trueshot.js
Fixes some calculations so it's actually showing what it's meant to
(For reference it was showing 100% overall crit when it was in fact much lower)
=> [Marksmanship] fixing trueshot calcs

src/Parser/Core/CombatLogParser.js, src/Parser/Core/Modules/Items/Legion/AntorusTheBurningThrone/AggramarsConviction.js, src/common/ITEMS/OTHERS.js, src/common/SPELLS/OTHERS.js
Added support for Aggramars Conviction Trinket
=>  Aggramars Conviction Trinket

src/Parser/Core/Modules/Haste.js, src/Parser/Core/Modules/StatTracker.js, src/Parser/DemonHunter/Havoc/CHANGELOG.js, src/Parser/DemonHunter/Havoc/CONFIG.js, src/Parser/DemonHunter/Havoc/CombatLogParser.js, src/Parser/DemonHunter/Havoc/Modules/Abilities.js, src/Parser/DemonHunter/Havoc/Modules/Features/AlwaysBeCasting.js, src/Parser/DemonHunter/Havoc/Modules/Features/CooldownThroughputTracker.js, src/common/SPELLS/DEMON_HUNTER.js
Changed the ABC to the suggestions thresholds. Added in a few haste buffs to get the downtime correct. Updated the cast efficiency a little to account for talents and tier and such.
=> [Havoc] Refactoring

src/Parser/DeathKnight/Blood/Modules/Abilities.js
SImple add. Wanted death strike to show for cast counting and on the timeline.
=> Added Death Strike

src/Parser/DeathKnight/Blood/Modules/Abilities.js, src/Parser/DeathKnight/Blood/Modules/Features/Checklist.js
Added cooldowns, charges, talent checks, cast efficiency, and changed the check list a little bit.
=> Abilities Updates

src/Parser/Warlock/Destruction/CHANGELOG.js, src/Parser/Warlock/Destruction/CombatLogParser.js, src/Parser/Warlock/Destruction/Modules/Items/T21_2set.js, src/Parser/Warlock/Destruction/Modules/Items/T21_4set.js, src/common/SPELLS/WARLOCK.js
After talking to Motoko, we've decided not to go into any guesses for the 2p, so just showing how many crits happened there, and let the player/person reviewing the log decide how many fragments did it contribute, in order to not spread any false information.
=> [Destruction] Implemented Tier 21 bonuses

src/MAINTAINERS.js, src/Parser/DeathKnight/Frost/CHANGELOG.js, src/Parser/DeathKnight/Unholy/CHANGELOG.js, src/Parser/DemonHunter/Vengeance/CHANGELOG.js, src/Parser/Druid/Feral/CHANGELOG.js, src/Parser/Druid/Guardian/CHANGELOG.js, src/Parser/Mage/Fire/CHANGELOG.js, src/Parser/Mage/Frost/CHANGELOG.js, src/Parser/Monk/Brewmaster/CHANGELOG.js, src/Parser/Monk/Mistweaver/CHANGELOG.js
Will do one PR per spec after this.
=> Changelogs v2

src/Parser/Shaman/Elemental/Modules/ShamanCore/EarthShock.js
Fixes crash in this log: https://wowanalyzer.com/report/Dz9GJmRkxnrTQLFh/23-Heroic+Argus+the+Unmaker+-+Wipe+6+(12:08)/Rufur
=> [Elemental] 2 crash fixes

src/MAINTAINERS.js, src/Parser/AVAILABLE_CONFIGS.js, src/Parser/Core/Combatant.js, src/Parser/Core/Modules/StatTracker.js, src/Parser/Mage/Arcane/CHANGELOG.js, src/Parser/Mage/Arcane/CONFIG.js, src/Parser/Mage/Arcane/CombatLogParser.js, src/Parser/Mage/Arcane/Modules/Features/Abilities.js, src/Parser/Mage/Arcane/Modules/Features/AlwaysBeCasting.js, src/Parser/Mage/Arcane/Modules/Features/Channeling.js, src/Parser/Mage/Arcane/Modules/Features/CooldownThroughputTracker.js, src/common/SPELLS/MAGE.js
Added initial basic support for Arcane.
=> [Arcane Mage] Add Spec

src/Parser/Core/Modules/Features/WarningDisplay.js, src/Parser/Mage/Fire/CONFIG.js, src/Parser/Mage/Fire/CombatLogParser.js, src/Parser/Mage/Frost/CHANGELOG.js, src/Parser/Mage/Frost/CONFIG.js
- Marked Frost Completeness as Great (it has been complete for a while, and i havent heard any complaints or issues regarding it.)
- Added a new warning for Fire to try and get additional feedback on it before i mark it Good (The hope is that people will see the warning, realize im considering it Good, and provide feedback if its not instead of everyone in Mage Discord just saying "Fire is WIP, ignore that")
- Removed Fyruna from the Fire Spec Maintainers. She did the initial upload with "new spec" stuff, and hasnt done anything on it since. I left her on there incase she decided to come back and contribute towards it, but she didnt. If she decides to contribute towards it again in the future, then we can always add her back, but until then i want to make sure feedback is coming to me …
=> [Mage] Config/Completeness Changes

src/Parser/Shaman/Elemental/Modules/Items/EchoesOfTheGreatSundering.js
Fixes crash on this log: https://wowanalyzer.com/report/JH26vd4zNybRGnpB/24-Normal+Varimathras+-+Kill+(4:24)/Missingducks
=> [Elemental] fix crash and preemptively fix possible second crash

src/Parser/DemonHunter/Havoc/CHANGELOG.js, src/Parser/DemonHunter/Havoc/CombatLogParser.js, src/Parser/DemonHunter/Havoc/Modules/Talents/DemonReborn.js, src/Parser/DemonHunter/Havoc/Modules/Traits/FeastOnTheSouls.js, src/Parser/DemonHunter/Havoc/Modules/Traits/UnleashedDemons.js, src/Parser/Paladin/Retribution/Modules/Talents/DivinePurpose.js, src/common/SPELLS/DEMON_HUNTER.js
Added in the talent and trait that account for all eye beam cooldown reduction.
=> [Havoc] Eye beam CDR

src/Parser/DemonHunter/Havoc/CHANGELOG.js, src/Parser/DemonHunter/Havoc/CombatLogParser.js, src/Parser/DemonHunter/Havoc/Modules/Items/Tier21_4set.js, src/Parser/Paladin/Retribution/Modules/Items/WhisperOfTheNathrezim.js
The ret suggestion is a thing I meant to change a while ago but forgot.
=> [Havoc] Tier 21 4PC

src/Parser/Warlock/Affliction/CHANGELOG.js, src/Parser/Warlock/Affliction/CONFIG.js
The help of Motoko was really appreciated and needed. The checklist contains pretty much everything we need so far, there is a lot of useful statistics as well. I'll stay in touch with him (he'll be helping me with Destro and Demo as well), so if anything new is required from an expert's point of view, he'll let me know. 
I'll file 2 more updates but they're merely cosmetic - reordering of stat boxes and imports.
=> [Affliction] Updated spec completeness to Great

src/Parser/Hunter/Survival/CHANGELOG.js, src/Parser/Hunter/Survival/CombatLogParser.js, src/Parser/Hunter/Survival/Modules/Talents/WayOfTheMokNathal.js
Report: https://www.warcraftlogs.com/reports/GNTgBZLD8rnhvcpk/#fight=5&source=28
I plan on expanding this at a later point to include damage contribution, but I need to figure out the attack power scaling formulas a bit more and which abilities are affected and how much - but for now this provides good information to the user.
=> [Survival] Way of the Mok'Nathal talent

src/Parser/DemonHunter/Havoc/Modules/Abilities.js, src/Parser/DemonHunter/Havoc/Modules/Features/AlwaysBeCasting.js, src/Parser/DemonHunter/Havoc/Modules/Items/DelusionsOfGrandeur.js
https://www.warcraftlogs.com/reports/yqKaGptwXPRYr8zm#fight=6&type=summary&source=19
Updated abilites.js to have the isOnGCD value. Added in a suggestion if you are wearing shoulders and didn't get an extra cast of Metamorphosis
=> [Havoc] Delusions of Grandeur Suggestion

src/Parser/Hunter/Survival/Modules/Abilities.js, src/common/SPELLS/HUNTER.js
i am bad at numbers apparently. reverting my fix that wasn't a fix on this.
=> [Survival] Caltrops cooldown update

src/Parser/Warlock/Destruction/CHANGELOG.js, src/Parser/Warlock/Destruction/Modules/Items/Legendaries/LessonsOfSpaceTime.js, src/Parser/Warlock/Destruction/Modules/Talents/Eradication.js, src/Parser/Warlock/Destruction/Modules/Talents/FireAndBrimstone.js, src/Parser/Warlock/Destruction/Modules/Talents/TalentHub.js
1) Added more details about Eradication (and removed it from the other statistic box, that will be soon gone altogether):
2) Added suggestion when picking Fire and Brimstone on single target 
3) Added uptime to legendary shoulder buff
=> [Destruction] Small talent changes

src/Parser/Shaman/Elemental/CombatLogParser.js, src/Parser/Shaman/Elemental/Modules/Features/Abilities.js, src/Parser/Shaman/Elemental/Modules/Features/FireElemental.js, src/Parser/Shaman/Shared/MaelstromChart/MaelstromTracker.js, src/common/SPELLS/SHAMAN.js
Also found a line of leftover debugging stuff in MS-Tracker
Also also added Earthshock to abilities
=> Mainly Fixed Fire Elemental Precast

src/Parser/Core/Modules/Items/EnchantChecker.js
Ring under minor importance: http://localhost:3000/report/WrxQYCR7wT1j2bBd/14-Heroic+Varimathras+-+Kill+(3:18)/Preheetxd/gear
=> Show enchants/gems (bonuses) in the enchant suggestions (fixes #1297)

src/Main/Gear.js, src/common/ITEM_QUALITIES.js, src/common/ItemLink.js, src/common/getItemQualityLabel.js
Also removed duplicate item links and added quality border
=> Show enchants/gems (bonuses) in the gear tab (fixes #1298)

src/Parser/Hunter/BeastMastery/CHANGELOG.js, src/Parser/Hunter/Marksmanship/CHANGELOG.js, src/Parser/Hunter/Shared/Modules/Items/CallOfTheWild.js, src/Parser/Hunter/Survival/CHANGELOG.js
This updates the shared legendary Call of the Wild to include information on the various Aspects it reduced the cooldown of and how many extra casts was gained through this.
Report: https://www.warcraftlogs.com/reports/92nNqC1gQaRhXmkx/#fight=13&source=10
Report: https://www.warcraftlogs.com/reports/YFcH8P27mtGnzLMA#fight=8&type=damage-done&source=5
=> [Hunter] Call of the Wild

src/Parser/Druid/Feral/Modules/Features/Abilities.js, src/common/SPELLS/DEMON_HUNTER.js, src/common/SPELLS/DRUID.js, src/common/SPELLS/HUNTER.js, src/common/SPELLS/RACIALS.js, src/common/SPELLS/ROGUE.js
Just adding all activated racials to the respective class and moving spells out of their classes folder into the racials folder
=> [Core] update racials and move spells around

package-lock.json, src/Parser/DemonHunter/Havoc/Modules/Spells/Nemesis.js, src/Parser/Paladin/Retribution/Modules/Items/AshesToDust.js, src/common/SPELLS/DEMON_HUNTER.js
Old
New
This fixes a bug where the uptime was not accounting for if the enemy died with the debuff on them.  Also adds in how much dps you gained from the talent.
Test log: https://www.warcraftlogs.com/reports/T68JHYX7faDPW3jv#fight=8&type=damage-done
=> [Havoc] Nemesis Update

src/Parser/Druid/Restoration/Modules/Talents/TreeOfLife.js
by royal decree of Princess Vrocas
=> [resto druid] Added proc count and proc rate for Chameleon Song

docs/contributor-names.md, src/Parser/Shaman/Elemental/CHANGELOG.js, src/Parser/Shaman/Elemental/CONFIG.js
I dm'ed fasib around a week ago if he was still working on the module and didn't get an answer so I took the freedem to replace him with me.
=> Added previous commits to changelog and added myself as a contributor

src/Parser/DeathKnight/Blood/CombatLogParser.js, src/Parser/DeathKnight/Blood/Modules/Abilities.js, src/Parser/DeathKnight/Blood/Modules/Core/Channeling.js, src/Parser/DeathKnight/Blood/Modules/Core/GlobalCooldown.js, src/Parser/DeathKnight/Shared/RuneBreakdown.js, src/Parser/DeathKnight/Shared/RuneTracker.js
=> [Blood Death Knight] Updated abilities and Added Blooddrinker channeling

src/Parser/Shaman/Elemental/Modules/ShamanCore/EarthShock.js
=> make it so the ES suggestion doesn't show when you didn't use ES

src/Main/App.css, src/Main/Results/Header.js, src/Main/Results/Results.css, src/Main/Results/index.js, src/Main/SpecListing.js, src/common/SPEC_ANALYSIS_COMPLETENESS.js
=> Show spec's maintainers and completeness rating in the header and reword and recolor completeness ratings

src/Parser/AVAILABLE_CONFIGS.js, src/Parser/Core/Modules/StatTracker.js, src/Parser/Rogue/Assassination/Modules/Features/AlwaysBeCasting.js, src/Parser/Rogue/Outlaw/CHANGELOG.js, src/Parser/Rogue/Outlaw/CONFIG.js, src/Parser/Rogue/Outlaw/CombatLogParser.js, src/Parser/Rogue/Outlaw/Modules/Features/Abilities.js, src/Parser/Rogue/Outlaw/Modules/Features/AlwaysBeCasting.js, src/Parser/Rogue/Outlaw/Modules/RogueCore/ComboPoints.js, src/Parser/Rogue/Outlaw/Modules/RogueCore/Energy.js, src/Parser/Rogue/Outlaw/Modules/RogueCore/RestlessBlades.js, src/Parser/Rogue/Outlaw/Modules/Spells/SliceAndDiceUptime.js, src/Parser/Rogue/Subtlety/Modules/Features/AlwaysBeCasting.js, src/common/SPELLS/ROGUE.js
Basic setup for outlaw rogue. 
Main purpose it to make it simpler to start contributing to outlaw.
=> [Owtlaw] Basics

package.json, src/MAINTAINERS.js, src/Parser/Rogue/Assassination/CHANGELOG.js, src/Parser/Rogue/Assassination/CONFIG.js, src/Parser/Rogue/Assassination/CombatLogParser.js, src/Parser/Rogue/Assassination/Modules/Features/Abilities.js, src/Parser/Rogue/Assassination/Modules/Legendaries/DuskwalkersFootpads.js, src/Parser/Rogue/Assassination/Modules/Traits/MasterAssassin.js, src/Parser/Rogue/Common/Resources/ComboPointDetails.js, src/Parser/Rogue/Common/Resources/EnergyDetails.js, src/common/SPELLS/ROGUE.js
Also added support for Master Assassin artifact trait.
=> Added support for Duskwalker's Footpads.

src/Parser/Hunter/Marksmanship/Modules/Abilities.js
also removes unused combatants import
=> [Marksmanship] fix abilities crash

src/Parser/Hunter/Survival/CHANGELOG.js, src/Parser/Hunter/Survival/CombatLogParser.js, src/Parser/Hunter/Survival/Modules/Features/MongooseFury/SixStackBites.js, src/Parser/Hunter/Survival/Modules/Features/TraitsAndTalents.js, src/Parser/Hunter/Survival/Modules/Talents/ButcheryCarve.js, src/Parser/Hunter/Survival/Modules/Traits/FuryOfTheEagle.js
Report: https://www.warcraftlogs.com/reports/2J7mdjfCDBz1aZNA#fight=42&type=damage-done&source=218
=> [Survival] Artifact ability module

src/Parser/Shaman/Elemental/CombatLogParser.js, src/Parser/Shaman/Elemental/Modules/Features/Abilities.js, src/Parser/Shaman/Elemental/Modules/Features/AlwaysBeCasting.js, src/Parser/Shaman/Elemental/Modules/ShamanCore/FrostShock.js
Added a Suggestion if Frost Shock is cast without the necessary buffs or resources
=> Frost shock

src/Parser/Core/Modules/Items/Legion/AntorusTheBurningThrone/EonarsCompassion.js
fixes #1394 
log: https://www.warcraftlogs.com/reports/qD6arnA8ZFmTykMJ#fight=last&source=3&type=auras
=> [Core] fixes eonar bug with not all regular procs accounted for

src/Parser/Monk/Windwalker/Modules/Spells/StormEarthAndFire.js
After getting some experience working with statisticslistboxes i've reworked this statistic box too
Old: 
New:
=> [Windwalker] Reworking the visual of SEF/Serenity statistics

src/Parser/Mage/Fire/Modules/Features/Checklist.js
typo'd Cinderstorm checklist item (SuggestionThresholds --> suggestionThreshold)
=> [Fire Mage] Fix typo on Cinderstorm Checklist item

src/Parser/DeathKnight/Frost/CHANGELOG.js, src/Parser/DeathKnight/Frost/CombatLogParser.js, src/Parser/DeathKnight/Frost/Modules/Features/Abilities.js, src/Parser/DeathKnight/Frost/Modules/Talents/Frostscythe.js, src/common/SPELLS/DEATH_KNIGHT.js
Adds a statistic box and suggestion related to Frostscythe usage
=> [Frost Death Knight] Add Frostscythe module

src/Parser/Monk/Windwalker/Modules/Features/Abilities.js, src/Parser/Monk/Windwalker/Modules/Spells/SpinningCraneKick.js, src/Parser/Monk/Windwalker/Modules/Spells/StormEarthAndFire.js
In response to comments by @MartijnHols on my previous PRs. I will make a separate PR later with the changelog update.
=>  [Windwalker] Cleanup for maintainability and tuning castefficiency 

src/Parser/Monk/Windwalker/CHANGELOG.js
I have taken the liberty to edit a bit in old entries for the sake of consistency.
=> [Windwalker] Updating changelog to new layout

package-lock.json, src/Parser/DemonHunter/Havoc/CHANGELOG.js, src/Parser/DemonHunter/Havoc/CombatLogParser.js, src/Parser/DemonHunter/Havoc/Modules/Items/AngerOfTheHalfGiants.js, src/Parser/Paladin/Retribution/Modules/Items/LiadrinsFuryUnleashed.js
added in a legendary stat box for [Anger of the Half Giants](http://www.wowhead.com/item=137038/anger-of-the-half-giants). Also since I changed the holy power tracker there was a bug with the Liadrin's Module that I also fixed.
and 
test logs:
https://www.warcraftlogs.com/reports/BHyhvwRqYjrMVfk8#fight=13&type=damage-done
https://www.warcraftlogs.com/reports/2QMTZNPmaWkwX1Az#fight=9&type=summary
=> [Havoc] Added in Anger of the Half Giants

src/Parser/DemonHunter/Havoc/CHANGELOG.js, src/Parser/DemonHunter/Havoc/CombatLogParser.js, src/Parser/DemonHunter/Havoc/Modules/Items/DelusionsOfGrandeur.js, src/Parser/DemonHunter/Shared/Modules/Items/SoulOfTheSlayer.js, src/Parser/DemonHunter/Vengeance/CombatLogParser.js
Added in [Soul of the Slayer](http://www.wowhead.com/item=151639/soul-of-the-slayer) for both DH specs.
[Havoc Log](https://www.warcraftlogs.com/reports/2gLFBpMJXtcRajwr#fight=37&type=damage-done&source=8)
[Veng Log](https://www.warcraftlogs.com/reports/an8z64pRtYQFNWJC#fight=2&type=damage-done)
=> [Demon Hunter] Soul of the Slayer

src/Parser/Paladin/Retribution/CHANGELOG.js, src/Parser/Paladin/Retribution/CombatLogParser.js, src/Parser/Paladin/Retribution/Modules/Abilities.js, src/Parser/Paladin/Retribution/Modules/Features/Checklist.js, src/Parser/Paladin/Retribution/Modules/PaladinCore/Crusade.js
you want to build up your stacks of crusade as quickly as possible. This module checks to make sure the first global inside of the buff is a spender (which is how you build stacks). 
[doing it badly test log](https://www.warcraftlogs.com/reports/CR9fJqjmgGc4L67M#fight=17&type=summary&source=100)
[doing it welll test log](https://www.warcraftlogs.com/reports/9Lydbghk2TxWNjm8#fight=28&type=summary&source=53)
also updated the Blade of Justice cast efficiency a little since I think it was slightly too stringent.
=> [Retribution] Crusade

src/Parser/Paladin/Retribution/Modules/Features/Checklist.js, src/Parser/Paladin/Retribution/Modules/Items/SoulOfTheHighlord.js
new:
old:
[Test log](https://www.warcraftlogs.com/reports/CxgM2KP8rbLqQ43R#fight=27&type=summary&source=125)
=> [Retribution] Checklist Refactor

src/Parser/Paladin/Retribution/Modules/Features/Checklist.js, src/Parser/Paladin/Retribution/Modules/HolyPower/HolyPowerDetails.js, src/Parser/Paladin/Retribution/Modules/Items/LiadrinsFuryUnleashed.js, src/Parser/Paladin/Retribution/Modules/PaladinCore/BoWProcTracker.js, src/Parser/Paladin/Retribution/Modules/PaladinCore/Crusade.js, src/Parser/Paladin/Retribution/Modules/PaladinCore/Judgment.js
based on a suggestion from @Gebuz I updated the checklist again. Now the bars for resources make more sense since as the percent fills up so does the bar.
new: 
old:
[test log](https://www.warcraftlogs.com/reports/CxgM2KP8rbLqQ43R#fight=12&type=summary&source=125)
also changed the tightness of the Blade of Wrath suggestion and did some general nitpicky clean up.
=> [Retribution] Checklist refactor v2

src/Parser/DeathKnight/Unholy/Modules/Items/ColdHeartEfficiency.js
Added tracking of concordance and khazgoroth shaping.
Updated a criteria for holding at 20 stacks for more than 4 seconds.
Changed the minimum stacks for an allowed cast to 14.
Most of these changes are marginal dps increases but some players track these buffs. Giving them failed casts would be wrong and I therefore implemented these new changes.
=> Updated ColdHeartEfficiency

src/Parser/Paladin/Protection/CHANGELOG.js, src/Parser/Paladin/Protection/CombatLogParser.js, src/Parser/Paladin/Protection/Modules/Items/PillarsOfInmostLight.js
Added support for [Pillars of Inmost Light](http://www.wowhead.com/item=151812/pillars-of-inmost-light)
[Test Log](https://www.warcraftlogs.com/reports/gWxmnqPMfCYZGvtF#fight=2&type=summary&source=9)
=> [Hewhosmites] Pillar of Inmost Light

src/Parser/DeathKnight/Unholy/CHANGELOG.js, src/Parser/DeathKnight/Unholy/CombatLogParser.js, src/Parser/DeathKnight/Unholy/Modules/Items/TaktheritrixsShoulderpads.js, src/common/SPELLS/DEATH_KNIGHT.js
Added [Taktheritrixs Shoulderpads](http://www.wowhead.com/item=137075/taktheritrixs-shoulderpads)
[Test Log](https://www.warcraftlogs.com/reports/kVn9Cv78NGyPMRmL#fight=2&type=damage-done&source=13)
=> [Unholy] Taktheritrixs Shoulderpads

src/Parser/DeathKnight/Blood/CHANGELOG.js, src/Parser/DeathKnight/Blood/CombatLogParser.js, src/Parser/DeathKnight/Blood/Modules/Items/T21_2pc.js, src/Parser/DeathKnight/Blood/Modules/Items/T21_4pc.js, src/common/SPELLS/DEATH_KNIGHT.js
=> [Blood Death Knight] Tier 21 bonuses

src/Parser/Monk/Windwalker/CHANGELOG.js, src/Parser/Monk/Windwalker/CombatLogParser.js, src/Parser/Monk/Windwalker/Modules/Items/TheWindBlows.js, src/Parser/Monk/Windwalker/Modules/Spells/SpinningCraneKick.js, src/Parser/Monk/Windwalker/Modules/Spells/StormEarthAndFire.js
[Test Log](https://www.warcraftlogs.com/reports/cxjyG3JwTKFPNH9z#fight=4&type=damage-done&source=3)
Added [The Wind Blows](http://www.wowhead.com/item=151811/the-wind-blows)
=> [Windwalker] The Wind Blows

src/Parser/Monk/Windwalker/Modules/Features/ComboStrikes.js, src/Parser/Monk/Windwalker/Modules/Items/TheEmperorsCapacitor.js, src/Parser/Monk/Windwalker/Modules/Items/TheWindBlows.js, src/Parser/Monk/Windwalker/Modules/Spells/FistsofFury.js
Added a check on "The Wind Blows" so it now only attributes a free Blackout Kick if Strike of the Windlord was used without the buff already active.
=> [Windwalker] Updating some suggestions and TWB item breakdown

src/Parser/Shaman/Elemental/CHANGELOG.js, src/Parser/Shaman/Elemental/CombatLogParser.js, src/Parser/Shaman/Enhancement/CHANGELOG.js, src/Parser/Shaman/Enhancement/CombatLogParser.js, src/Parser/Shaman/Shared/Items/EyeOfTheTwistingNether.js, src/common/SPELLS/SHAMAN.js
Added [Eye of the Twisting Nether](http://www.wowhead.com/item=137050/eye-of-the-twisting-nether)
[Enhancement](https://www.warcraftlogs.com/reports/yPqv481A7cYdzXBa#fight=25&type=damage-done&source=193)
[Elemental](https://www.warcraftlogs.com/reports/7Zp4GLmFW9NRrzck#fight=21&type=damage-done&source=12)
=> [Enhancement/Elemental] Eye of the Twisting Nether

src/Parser/Mage/Fire/CONFIG.js
Removed warning from Fire Mage Config.
=> [Fire Mage] Config Changes

src/Parser/Core/Modules/GlobalCooldown.js, src/Parser/Druid/Balance/CONFIG.js
Also changed balance version from 7.3 to 7.3.5.
=> [bug] Fixed _verifyAccuracy to use last event instead of current where needed

src/Parser/Monk/Windwalker/CHANGELOG.js, src/Parser/Monk/Windwalker/CombatLogParser.js, src/Parser/Monk/Windwalker/Modules/Features/AlwaysBeCasting.js, src/Parser/Monk/Windwalker/Modules/Features/Checklist.js, src/Parser/Monk/Windwalker/Modules/Spells/BlackoutKick.js, src/Parser/Monk/Windwalker/Modules/Spells/SpinningCraneKick.js
Checklist entry:
Statistic:
Suggestion: 
As for GCDs, i had tried implementing this before, but couldn't get it to work because of what i now realize was some errors on my end.
=> [Windwalker] Blackout Kick Module and some quick GCD fixes

src/Parser/DeathKnight/Blood/CHANGELOG.js, src/Parser/DeathKnight/Blood/CombatLogParser.js, src/Parser/DeathKnight/Blood/Modules/Traits/AllConsumingRot.js, src/Parser/DeathKnight/Blood/Modules/Traits/Bonebreaker.js, src/Parser/DeathKnight/Blood/Modules/Traits/Coagulopathy.js, src/Parser/DeathKnight/Blood/Modules/Traits/RelicTraits.js, src/Parser/DeathKnight/Blood/Modules/Traits/Veinrender.js, src/Parser/DeathKnight/Shared/getDamageBonusStacked.js, src/common/SPELLS/DEATH_KNIGHT.js
=> [BDK] added BDK DPS traits

package-lock.json, package.json, src/CHANGELOG.js, src/Main/App.css, src/Main/App.js, src/Main/Home.js, src/Main/PlayerSelecter.js, src/Main/ReportHistory.js, src/Main/ReportSelecter.js, src/Main/makeAnalyzerUrl.js, src/actions/report.js, src/actions/reportHistory.js, src/reducers/index.js, src/reducers/reportHistory.js, src/selectors/reportHistory.js
=> Show recently viewed reports on homepage

src/Parser/DemonHunter/Havoc/Modules/Traits/CriticalChaos.js, src/Parser/Hunter/Marksmanship/Modules/Items/Tier20_2p.js, src/Parser/Hunter/Marksmanship/Modules/Spells/Trueshot.js, src/Parser/Hunter/Survival/Modules/Items/Tier21_2p.js
I intentionally left out the Tiger Palm module as it uses the hits to guess whether Face Palm procced or not.
=> Update modules that check for crit hits to also check for crit blocks.

src/Parser/Paladin/Protection/Modules/Abilities.js
=> [Prot Paladin] Bug: Blessed Hammer appeared twice in cast efficiency.

src/Parser/Core/CombatLogParser.js, src/Parser/Core/Modules/Items/Legion/MementoOfAngerboda.js
=> [General] Added Memento of Angerboda item breakdown

src/Parser/Core/Modules/Items/EnchantChecker.js
Fixes bug where enchant module suggested missing and cheap enchant at the same time.  Fixes #1426
Log missing enchant
Log with cheap enchant
=> Enchant suggestion fix

src/Parser/DeathKnight/Frost/CHANGELOG.js, src/Parser/DeathKnight/Frost/CombatLogParser.js, src/Parser/DeathKnight/Frost/Modules/Features/RuneTracker.js, src/Parser/DeathKnight/Frost/Modules/RunicPower/RunicPowerDetails.js, src/Parser/DeathKnight/Frost/Modules/RunicPower/RunicPowerTracker.js, src/common/SPELLS/DEATH_KNIGHT.js
Adds resource tracking for runic power and tweaks thresholds for rune efficiency.
=> [Frost Death Knight] Finished resource tracking

src/Parser/DeathKnight/Blood/Modules/Features/BoneShield.js, src/Parser/DeathKnight/Blood/Modules/Features/Checklist.js, src/Parser/DeathKnight/Blood/Modules/Features/MarrowrendUsage.js, src/Parser/DeathKnight/Blood/Modules/Talents/Bonestorm.js, src/Parser/DeathKnight/Shared/RuneBreakdown.js
Update the checklist to include the new metrics that @joshinat0r added. Also moved Blood Drinker to short cds.
old:
new:
=> [Blood Death Knight] Update Checklist

src/Parser/DeathKnight/Blood/Modules/Abilities.js, src/Parser/Druid/Balance/Modules/Features/Abilities.js
Also reduced Barkskin's suggestion threshold for Balance.
=> [Blood Death Knight] Order the timeline

src/Parser/DeathKnight/Frost/CombatLogParser.js, src/Parser/DeathKnight/Frost/Modules/Features/Abilities.js, src/Parser/DeathKnight/Frost/Modules/Features/AlwaysBeCasting.js, src/Parser/DeathKnight/Frost/Modules/Features/SpellUsable.js, src/common/SPELLS/DEATH_KNIGHT.js
Adds SpellUsable to Frost to address issues with tracking CDs for Pillar of Frost and Sindragosa's Fury.
=> [Frost Death Knight] Properly tracks reduced cooldowns

src/Parser/Monk/Brewmaster/Modules/Features/Abilities.js, src/Parser/Monk/Brewmaster/Modules/Features/Checklist.js, src/Parser/Monk/Brewmaster/Modules/Spells/RushingJadeWind.js, src/Parser/Monk/Brewmaster/Modules/Spells/TigerPalm.js
This adds a checklist item for brewmaster dps. Right now its relatively simplistic (BrMs technically have a strict rotation, but there are breakpoints that change it and fight mechanics disrupt it) -- focused on cast efficiency and correctly using Blackout Combo (if selected). Also includes checklist items for RJW and Invoke Niuzao (if they are selected).
=> [BrM Monk] Damage Checklist

src/Parser/DeathKnight/Frost/CONFIG.js, src/Parser/DeathKnight/Unholy/CONFIG.js
=> Updated descriptions for Frost and Unholy DKs

src/Parser/Druid/Balance/Modules/Features/MoonfireUptime.js, src/Parser/Druid/Balance/Modules/Features/StellarFlareUptime.js, src/Parser/Druid/Balance/Modules/Features/SunfireUptime.js, src/Parser/Druid/Balance/Modules/ResourceTracker/AstralPowerDetails.js, src/Parser/Druid/Guardian/CHANGELOG.js, src/Parser/Druid/Guardian/Modules/Abilities.js
- Fixes Mangle/Thrash cast efficiency and max casts being calculated incorrectly when using Incarnation.
- Fixes Moonfire, Sunfire and Stellar Flare uptime suggestion texts.
- Fixes Astral Power wasted statbox showing NaN initially before loading.
=> [Druid] bug fixes

src/Parser/Mage/Arcane/CombatLogParser.js, src/Parser/Mage/Arcane/Modules/Features/Evocation.js
Checks to see if Evocation is available or has less than 20 seconds left on the cooldown when the user hits Arcane Power. This is because you pop Arcane Power and then go into a burn phase where you burn your mana until its empty. If Evocate isnt off cooldown when you bottom out your mana, then you are sitting there until it comes off cooldown.
=> [Arcane Mage] Evocation

src/common/SPELLS/WARRIOR.js
Added a few missing Arms Warrior abilities and made an attempt at sorting out the triggered effects.
=> [Arms Warrior] Add missing abilities and triggered effects

.env.local, .env.local.example, src/Parser/Rogue/Outlaw/Modules/RogueCore/ComboPoints.js
Changed message to mention unavoidable cp waste, added tracking for remaining cp generators
=> ComboPoints.js Update

src/Parser/Paladin/Protection/Modules/Features/Checklist.js, src/Parser/Paladin/Protection/Modules/Spells/Judgment.js, src/Parser/Paladin/Protection/Modules/Talents/Seraphim.js
a temporal fix for the Seraphim / SotR issue (tracking the charges not 100% accurately, might cause to wrong sera-times) by removing the additional infos from the tooltip
also fixes the checklist (was missing the abilities-dependency) which is resulting in errors for prot on production right now 😅
=> [Protection Paladin] Sera & Checklist-Fix

src/Parser/Warrior/Arms/CHANGELOG.js, src/Parser/Warrior/Arms/CombatLogParser.js, src/Parser/Warrior/Arms/Modules/Features/BattleCry.js
Created the Battle Cry analyzer which currently will make suggestions regarding the preparation of Shattered Defenses.
The BattleCry data class is in place for future features that require collating a bit of information.
=> [Arms Warrior] Create Battle Cry analyzer with Shattered Defense analysis

src/Parser/DeathKnight/Frost/Modules/Features/Abilities.js
Fixed Abilities.js for Frost DK to include isOnGCD.
=> Added isOnGCD To Frost DK Abilities

src/Parser/Warrior/Arms/CombatLogParser.js, src/Parser/Warrior/Arms/Modules/Features/ExecuteRange.js, src/Parser/Warrior/Arms/Modules/Talents/Rend.js
I've improved the execute range checking code and moved it into its own module. I'll likely move it to a shared folder once I begin working on the fury analyzer.
=> [Arms Warrior] Add Execute range tracker and refactor Rend module

src/Parser/Warrior/Arms/Modules/Features/BattleCry.js
=> [Arms Warrior] Add inefficient cast flagging for Battle Cry

src/Parser/DeathKnight/Blood/CHANGELOG.js, src/Parser/DeathKnight/Blood/CombatLogParser.js, src/Parser/DeathKnight/Blood/Modules/Abilities.js, src/Parser/DeathKnight/Blood/Modules/Features/Checklist.js, src/Parser/DeathKnight/Blood/Modules/Talents/MarkOfBloodUptime.js, src/common/SPELLS/DEATH_KNIGHT.js
The log that broke live: https://www.warcraftlogs.com/reports/twPcQ6vgnJRBxC2a/#fight=1&type=summary
Yea they never used the talent.
Screenshots of the new parts:
=> MOB fixes and uptime

src/Parser/DeathKnight/Blood/Modules/Talents/MarkOfBloodUptime.js
Forgot to add the initialize condition for the talent
=> Mob active fix

src/Parser/DeathKnight/Blood/CHANGELOG.js, src/Parser/DeathKnight/Blood/Modules/Traits/AllConsumingRot.js, src/Parser/DeathKnight/Blood/Modules/Traits/Bonebreaker.js, src/Parser/DeathKnight/Blood/Modules/Traits/Coagulopathy.js, src/Parser/DeathKnight/Blood/Modules/Traits/Veinrender.js
=> Relic stats update

src/Parser/DeathKnight/Blood/CHANGELOG.js, src/Parser/DeathKnight/Blood/CombatLogParser.js, src/Parser/DeathKnight/Blood/Modules/Features/BlooddrinkerTicks.js, src/Parser/DeathKnight/Blood/Modules/Talents/Bloodworms.js, src/common/SPELLS/DEATH_KNIGHT.js
Added dps/hps stuff to the tooltip and cleaned up the code by putting in early returns for the events.
=> Blooddrinker Updates

src/Main/Layout/NavigationBar.js, src/Parser/DeathKnight/Blood/CHANGELOG.js, src/Parser/DeathKnight/Blood/CombatLogParser.js, src/Parser/DeathKnight/Blood/Modules/Talents/Heartbreaker.js
=> [Blood DK] HS-Module

src/Parser/DeathKnight/Blood/CHANGELOG.js, src/Parser/DeathKnight/Blood/CombatLogParser.js, src/Parser/DeathKnight/Blood/Modules/Features/BoneShield.js, src/Parser/DeathKnight/Blood/Modules/Features/BoneShieldStacksBySeconds.js, src/Parser/DeathKnight/Blood/Modules/Features/BoneShieldTimesByStacks.js, src/Parser/DeathKnight/Blood/Modules/Talents/FoulBulwark.js
Does what #1635 does, but for live.
Probably should've done live first and wait for the periodically merge to BfA and update then. In case of merge conflicts just keep the BfA stuff.
=> [Blood DK] updated BS & FB-Modules

src/Parser/Warrior/Arms/CHANGELOG.js, src/Parser/Warrior/Arms/CombatLogParser.js, src/Parser/Warrior/Arms/Modules/Items/Tier21_2Set.js, src/common/SPELLS/WARRIOR.js
=> [Arms Warrior] Add Arms tier 21 2 piece damage statistic

src/Parser/DeathKnight/Blood/Modules/Features/BloodPlagueUptime.js, src/Parser/DeathKnight/Blood/Modules/Features/BlooddrinkerTicks.js, src/Parser/DeathKnight/Blood/Modules/Features/BoneShield.js, src/Parser/DeathKnight/Blood/Modules/Features/CrimsonScourge.js, src/Parser/DeathKnight/Blood/Modules/Features/MarrowrendUsage.js, src/Parser/DeathKnight/Blood/Modules/Features/Souldrinker.js, src/Parser/DeathKnight/Blood/Modules/Features/UnendingThirstTracker.js, src/Parser/DeathKnight/Blood/Modules/RunicPower/RunicPowerDetails.js, src/Parser/DeathKnight/Blood/Modules/Talents/FoulBulwark.js, src/Parser/DeathKnight/Blood/Modules/Talents/Ossuary.js, src/Parser/DeathKnight/Blood/Modules/Talents/RedThirst.js
Some text clean up and reordering of statcores. If i had some overlaping expand stat boxes it got wierd.
=> Smalls updates

src/Parser/DeathKnight/Blood/CHANGELOG.js, src/Parser/DeathKnight/Blood/CombatLogParser.js, src/Parser/DeathKnight/Blood/Modules/Features/Checklist.js, src/Parser/DeathKnight/Blood/Modules/Talents/Bloodworms.js, src/Parser/DeathKnight/Blood/Modules/Talents/MarkOfBlood.js, src/Parser/DeathKnight/Blood/Modules/Talents/Tombstone.js
=> Bfa Tombstone

src/Parser/DeathKnight/Blood/CombatLogParser.js, src/Parser/DeathKnight/Blood/Modules/Talents/WillOfTheNecropolis.js
=> Will of the Necropolis

src/Parser/DeathKnight/Blood/CombatLogParser.js, src/Parser/DeathKnight/Blood/Modules/Talents/WillOfTheNecropolis.js, src/Parser/DemonHunter/Vengeance/CombatLogParser.js, src/Parser/DemonHunter/Vengeance/Modules/Spells/Painbringer/Painbringer.js, src/Parser/DemonHunter/Vengeance/Modules/Spells/Painbringer/PainbringerTimesByStacks.js, src/common/SPELLS/DEMON_HUNTER.js
=> DH Painbringer uptime and stack stats

src/Parser/DeathKnight/Blood/Modules/Talents/WillOfTheNecropolis.js
Based on https://github.com/WoWAnalyzer/WoWAnalyzer/pull/1651
=> Text fixes to the WOTN code

src/Parser/DeathKnight/Blood/CombatLogParser.js, src/Parser/DeathKnight/Blood/Modules/Talents/RapidDecomposition.js
=> Bfa rapid decomp

src/Parser/DemonHunter/Vengeance/CombatLogParser.js, src/Parser/DemonHunter/Vengeance/Modules/Spells/SoulBarrier.js
=> DH Soul Barrier Talent

src/Parser/DemonHunter/Vengeance/CombatLogParser.js, src/Parser/DemonHunter/Vengeance/Modules/Abilities.js
Added some spells and updated gcd/cd times.
=> Updated DH abilities

src/Parser/Hunter/Survival/Modules/Spells/Lacerate.js
Fixes crash on this log: https://wowanalyzer.com/report/v9pVwRzbKGAcZP1f/1-Normal+Kin'garoth+-+Kill+(10:02)/9-Kenderguru
=> [Survival] fix crash on lacerate

src/Parser/Hunter/BeastMastery/Modules/Items/TheMantleOfCommand.js
=> [BeastMastery] fix suggestion

src/Main/Character/CharacterParses.js
Fixes priests & trinkets not rerendering after we got the icons from blizzard
=> [Core] Charparsingfixes

src/Parser/Priest/Discipline/CombatLogParser.js, src/Parser/Priest/Discipline/Modules/Features/PowerWordBarrier.js, src/Parser/Priest/Discipline/Modules/Spells/LuminousBarrier.js, src/Parser/Priest/Discipline/SuggestionThresholds.js, src/common/SPELLS/PRIEST.js
Used p3rX6Ggy1BJ8fTtZ log for testing.
Suggestion:
Statistic:
Statistic Tooltip:
=> [BFA] [Discipline Priest] Luminous Barrier Module

src/Parser/DeathKnight/Blood/CHANGELOG.js, src/Parser/DeathKnight/Blood/CombatLogParser.js, src/Parser/DeathKnight/Blood/Modules/Core/DeathsCaress.js, src/Parser/DeathKnight/Blood/Modules/Features/Checklist.js
Adds a suggestion for the special kind of people when using DC, there is only very little reason to cast it over HS, DnD or BD.
=> [Blood Death Knight] Deaths Caress Suggestion

src/Parser/Druid/Restoration/CombatLogParser.js, src/Parser/Druid/Restoration/Modules/Talents/Photosynthesis.js, src/common/SPELLS/TALENTS/DRUID.js
Implementation of the new resto druid talent Photosynthesis
=> [BFA Resto Druid] Photosynthesis

src/Parser/DemonHunter/Vengeance/CombatLogParser.js, src/Parser/DemonHunter/Vengeance/Modules/Abilities.js, src/common/DEFENSIVE_BUFFS.js, src/common/SPELLS/DEMON_HUNTER.js
=> Deathlog for DH

src/Main/DeathRecapTracker.js, src/Parser/Druid/Balance/CombatLogParser.js, src/Parser/Druid/Balance/Modules/Features/Abilities.js
(yeah I know we don't have many defensives <.<)
=> [Balance Druid] Deathlog and buffs/debuffs on timeline

src/Parser/DemonHunter/Vengeance/CHANGELOG.js, src/Parser/Druid/Guardian/CHANGELOG.js
Added change log for recent PRs
=> Changelog updates

src/Parser/Druid/Feral/Modules/Bleeds/RakeSnapshot.js, src/Parser/Druid/Feral/Modules/FeralCore/Snapshot.js
A couple of mistakes that slipped in.
=> [Feral] Small fixes to rake snapshot

src/Parser/Core/Modules/StatTracker.js, src/Parser/Monk/Windwalker/CHANGELOG.js, src/Parser/Monk/Windwalker/CombatLogParser.js, src/Parser/Monk/Windwalker/Modules/Spells/TouchOfDeath.js, src/common/SPELLS/MONK.js, src/common/SPELLS/OTHERS.js
There's some other small things added like changes to SPELLS.MONK and the vers food being added. This was just to make sure those things missing weren't causing wrong calculations by this module. There is some rounding error, but as long as decimals are avoided on the % it should be accurate almost all of the time.
=> [Windwalker] Touch of Death / Gale Burst module

src/Parser/Hunter/Shared/Modules/Features/FocusUsage.js
Fixes crash from this: 
https://wowanalyzer.com/report/jQcpZ29V8qxkCyf1/4-Normal+Portal+Keeper+Hasabel/Ag%C3%ADelita
=> [Marksmanship] fix crash

src/Parser/Mage/Frost/Modules/Features/WintersChill.js
basic fix in string formatting.
=> Mage text bug fix

src/Parser/Mage/Arcane/CONFIG.js, src/Parser/Mage/Arcane/CombatLogParser.js, src/Parser/Mage/Arcane/Modules/Features/Abilities.js, src/Parser/Mage/Arcane/Modules/Features/AlwaysBeCasting.js, src/common/SPELLS/MAGE.js
- Updated Abilities
- Added Spells
- Removed Herusx as a maintainer
=> [BFA] [Arcane Mage] Arcane Mage Prepatch Changes

src/Parser/Druid/Guardian/CONFIG.js, src/Parser/Druid/Guardian/Modules/Abilities.js, src/common/SPELLS/DRUID.js
pretty much just the spellbook and removing artifact ability.
=> [BFA][Guardian] Update Guardian for prepatch

src/Parser/Priest/Holy/CombatLogParser.js, src/Parser/Priest/Holy/Modules/Abilities.js, src/Parser/Priest/Holy/Modules/Features/SpellUsable.js, src/Parser/Priest/Holy/Modules/Spells/SpiritOfRedemption.js
2 smaller features
- Dispelling someone only triggers Purify cooldown if it actually dispelled 
- Fabricating a Spirit of Redemption cast event when the buff applies, so that i can add it to the Timeline
=> [BFA] Holy Priest - Purify & Spirit of Redemption

src/Parser/Druid/Balance/Modules/Abilities.js, src/Parser/Druid/Guardian/Modules/Abilities.js
and dash + tiger's dash for guardian.
=> [BFA][Guardian/Balance] Soothe & Hibernate

src/Parser/Mage/Fire/CombatLogParser.js, src/Parser/Mage/Fire/Modules/Features/HotStreak.js, src/Parser/Mage/Fire/Modules/Features/Pyroclasm.js, src/Parser/Mage/Fire/Modules/Features/SearingTouch.js, src/Parser/Mage/Fire/Normalizers/PyroclasmBuff.js, src/common/SPELLS/MAGE.js
- Added some spells
- Added Pyroclasm and Searing Touch (Essentially just copies of Koralon's and Marquee Bindings
- Added a Normalizer for the Pyroclasm Buff (for the same reason as the Kaelthas utlimate ability one)
- Adjusted Hot Streak to take Pyroclasm into account in addition to the Marquee Bindings
=> [BFA] [Fire Mage] More PrePatch Changes

src/CHANGELOG.js, src/Main/App.css, src/Main/Header.css, src/Main/ReportSelecter.js, src/common/REGION_CODES.js
=> [Core] Character links in report-selecter

src/Interface/Character/Parses.js
With the update from WLCs API we have a new structure of the `character/rankings` endpoint.
It's right now missing some stuff (namely talents & gear), but PRing it for now so we have at least the basic functions working again.
Another issue is right now that heroic (not sure if normal & LFR have the same issue, but I'd guess so) don't return any percentile (rank 0 out of 0). Will talk with Kihra about it.
=> [Core][Bug] Update to new parses structure

src/Interface/Character/Parses.js
- adds talents back in
- adds gear back in
- fixes the update to specName & className (was initially the class&specID and is now a readable string again)
=> [Core][Bug] Talents & gear for characterParses

src/Main/Report/Results/Results.css
Changes the `left` property animation to be a transform, which eliminates the lag!
=> Performance increase for player and boss fadein

src/Parser/Rogue/Assassination/CHANGELOG.js, src/Parser/Rogue/Assassination/CONFIG.js, src/Parser/Rogue/Assassination/CombatLogParser.js, src/Parser/Rogue/Assassination/Modules/Talents/Blindside.js, src/Parser/Rogue/Common/CastTracker/FilteredDamageTracker.js, src/Parser/Rogue/Common/EnemyHpTracker.js, src/common/SPELLS/ROGUE.js
Analysis to make sure players who selected Blindside talent use it =)
EnemyHpTracker.js - Potential to add to core, many classes use similar logic for execute mechanics, but handle it locally.
=> [Assa Rogue/BFA] Blindside analysis

src/Parser/Monk/Brewmaster/Modules/Spells/Guard.js
This is an internal change. WCL now has absorb information for Guard, so I don't need to fabricate it anymore.
=> [BFA][BrM] Guard update

src/Parser/DeathKnight/Frost/CONFIG.js, src/Parser/DeathKnight/Frost/Modules/Abilities.js, src/common/SPELLS/TALENTS/DEATH_KNIGHT.js
Updated Frost DK Talents and fixed a crash in Abilities.js
Also went through Abilities and updated the cooldown information.
=> [Frost DK] Fixed Crash

package-lock.json, src/Parser/Paladin/Protection/CombatLogParser.js, src/Parser/Paladin/Protection/Modules/Features/MitigationCheck.js, src/Raids/AntorusTheBurningThrone/Aggramar.js, src/Raids/AntorusTheBurningThrone/AntoranHighCommand.js, src/Raids/AntorusTheBurningThrone/ArgusTheUnmaker.js, src/Raids/AntorusTheBurningThrone/EonarLifebinder.js, src/Raids/AntorusTheBurningThrone/FelhoundsOfSargeras.js, src/Raids/AntorusTheBurningThrone/GarothiWorldbreaker.js, src/Raids/AntorusTheBurningThrone/ImonarTheSoulhunter.js, src/Raids/AntorusTheBurningThrone/Kingaroth.js, src/Raids/AntorusTheBurningThrone/PortalKeeperHasabel.js, src/Raids/AntorusTheBurningThrone/TheCovenOfShivarra.js, src/Raids/AntorusTheBurningThrone/Varimathras.js
-Add checking for "soft" mitigation checks to Antorus bosses (soft mitigation checks are hard-hitting tank abilities that differ from "true" mitigation checks) for protection paladins. This includes adding some ability data to Antorus bosses.
=> Mitigation check

src/Parser/Monk/Brewmaster/Modules/Features/Checklist.js, src/Parser/Monk/Brewmaster/Modules/Spells/BreathOfFire.js
=> [BrM] Updated BoF recommendation and checklist item for BFA

src/Parser/Hunter/BeastMastery/Modules/Items/Tier20_2p.js, src/Parser/Hunter/BeastMastery/Modules/Items/Tier20_4p.js, src/Parser/Hunter/Marksmanship/Modules/Features/Checklist.js, src/Parser/Hunter/Marksmanship/Modules/Items/WarBeltOfTheSentinelArmy.js
Thanks to @Sharrq for finding the bug/solution
Replaced the removed SPELLS.MULTISHOT with either SPELLS.MULTISHOT_MM or SPELLS.MULTISHOT_BM, since MM received significant changes to multishot.
=> [MMS/BM] Multishot bug fixes

src/Parser/Shaman/Restoration/Modules/Abilities.js, src/Parser/Shaman/Restoration/Modules/Talents/FlashFlood.js, src/common/SPELLS/TALENTS/SHAMAN.js
-Soul again gives Echo instead of Flash Flood
-Adjusted Unleash Life mana cost
=> [Restoration Shaman] Hotfix changes

src/Parser/DemonHunter/Vengeance/Modules/Statistics/SoulFragments.js
=> Vdh soul fragments

src/Parser/Mage/Arcane/CombatLogParser.js, src/Parser/Mage/Fire/CombatLogParser.js, src/Parser/Mage/Frost/CombatLogParser.js, src/Parser/Mage/Shared/Modules/Features/ArcaneIntellect.js
Uptime Tracking for Arcane Intellect
Towards #1961
=> [Mages] Arcane Intellect Uptime

src/Parser/Mage/Arcane/CombatLogParser.js, src/Parser/Mage/Arcane/Modules/Features/ArcaneFamiliar.js, src/common/SPELLS/MAGE.js
Measures the uptime on Arcane Familiar to ensure it is up for the entire fight.
Towards #1961
=> [Arcane Mage] Arcane Familiar Uptime

src/Parser/Paladin/Retribution/Modules/Abilities.js, src/Parser/Paladin/Retribution/Modules/PaladinCore/Haste.js, src/common/SPELLS/TALENTS/PALADIN.js
Yes, the spell icon name is supposed to have a typo.
=> [Ret] Minor updates in Abilities and retribution haste

package-lock.json, src/Parser/Priest/Discipline/CHANGELOG.js, src/Parser/Priest/Discipline/Modules/Abilities.js, src/Parser/Priest/Discipline/Modules/Features/Checklist/Component.js, src/Parser/Priest/Discipline/Modules/Spells/Penance.js, src/common/SPELLS/PRIEST.js
Just checked last night and the developers have given us a nice cast event for Penance that is homogenous across friendly and offensive penances. Thanks Blizzard :^)
=> [Discipline Priest] Penance Cast Event

src/Interface/common/TooltipProvider/Wowdb.js, src/Interface/common/TooltipProvider/Wowhead.js, src/Parser/Paladin/Holy/Modules/Talents/DevotionAuraDamageReduction.md, src/common/stats.test.js
https://github.com/WoWAnalyzer/WoWAnalyzer/issues/1976
Self explanatory, seems to be working fine on my local but I'm not certain where all the surfaces for this piece of code are.
=> Use Live Databases

src/Parser/Core/CASTS_THAT_ARENT_CASTS.js, src/Parser/Hunter/BeastMastery/Modules/Abilities.js, src/Parser/Hunter/Marksmanship/CombatLogParser.js, src/Parser/Hunter/Marksmanship/Modules/Abilities.js, src/Parser/Hunter/Shared/Modules/Features/TimeFocusCapped.js, src/Parser/Hunter/Survival/CHANGELOG.js, src/Parser/Hunter/Survival/CombatLogParser.js, src/Parser/Hunter/Survival/Modules/Abilities.js, src/Parser/Hunter/Survival/Modules/Features/TraitsAndTalents.js, src/Parser/Hunter/Survival/Modules/Spells/SerpentSting.js, src/Parser/Hunter/Survival/Modules/Talents/VipersVenom.js, src/common/SPELLS/OTHERS.js, src/common/SPELLS/RACIALS.js
Also fixes a crash caused by focus capping. 
Viper's Venom:
Serpent Sting: 
Traits/Talents box:
=> [Survival] Serpent Sting update and Viper's Venom Talent

src/Parser/Mage/Arcane/Modules/Features/ArcaneChargeTracker.js
I forgot to turn off debug on the module before i submitted it.
=> [Arcane Mage] Turn off debug on ArcaneChargeTracker

src/Parser/Mage/Arcane/CombatLogParser.js, src/Parser/Mage/Arcane/Modules/ManaChart/Mana.js, src/Parser/Mage/Arcane/Modules/ManaChart/ManaValues.js, src/Parser/Mage/Arcane/Modules/ManaChart/TabComponent/ManaLevelGraph.js, src/Parser/Mage/Arcane/Modules/ManaChart/TabComponent/index.js
This adds a mana chart for Arcane. I decided against using the Mana Usage Chart as i didnt feel like the DPS Throughput was all that helpful, so i went with the Mana Level Chart instead as part of playing Arcane well is ending the fight with as little mana as possible (since you should burn your mana at the end of the fight regardless of cooldown state.
Towards #1961
=> [Arcane Mage] Mana Chart

src/Parser/Mage/Fire/Modules/Features/Abilities.js
Phoenix Flames was showing a suggestion to cast it more even if you didnt choose that talent.
Towards #2006
=> [Fire Mage] Fixed Phoenix Flames Suggestion

src/Parser/DemonHunter/Vengeance/CHANGELOG.js, src/Parser/DemonHunter/Vengeance/CONFIG.js, src/Parser/DemonHunter/Vengeance/Modules/Abilities.js, src/common/SPELLS/DEMON_HUNTER.js, src/common/SPELLS/TALENTS/DEMON_HUNTER.js
=> [Vengeance DH] BfA Update

src/Parser/DemonHunter/Vengeance/CHANGELOG.js, src/Parser/DemonHunter/Vengeance/CombatLogParser.js, src/Parser/DemonHunter/Vengeance/Modules/Features/Checklist.js
=> [Vengeance DH] Vengeance Checklist implementation

src/Parser/Druid/Restoration/Modules/Features/StatWeights.js, src/Parser/Druid/Restoration/SpellInfo.js, src/Parser/Shaman/Restoration/Modules/Features/StatValues.js
- Removed Riptide initial from HPM, removed overhealing from rshaman HPM
- Added Regrowth to HPM & filtered out the initial
Renew and Tranquility need similar treatment if they ever get implemented
=> [Restoration] Small HPM fix

src/Parser/Rogue/Assassination/CHANGELOG.js, src/Parser/Rogue/Assassination/CombatLogParser.js, src/Parser/Rogue/Common/CastTracker/StealthDamageTracker.js, src/Parser/Rogue/Common/Resources/EnergyCapTracker.js, src/Parser/Rogue/Common/Resources/EnergyTracker.js, src/Parser/Rogue/Common/Stealth/IsStealth.js, src/Parser/Rogue/Outlaw/CHANGELOG.js, src/Parser/Rogue/Outlaw/CombatLogParser.js, src/Parser/Rogue/Subtlety/CHANGELOG.js, src/Parser/Rogue/Subtlety/CombatLogParser.js, src/Parser/Rogue/Subtlety/Modules/BaseRotation/CastsInStealthBase.js
Natural energy regen for all rogues, and some random fixes for Sub.
=> Rogues - natural energy regen.

src/Parser/DemonHunter/Havoc/CHANGELOG.js, src/Parser/DemonHunter/Shared/Modules/Items/SoulOfTheSlayer.js
- Added this.option1 and this.option2 talents for Soul of the Slayer other talent choices when equipping it.
=> [Havoc DH] Added option1 and option2 for soul of the slayer havoc item module

src/Parser/Mage/Frost/Modules/Features/GlacialSpike.js
Fixes crash in Glacial Spike
https://wowanalyzer.com/report/rzJgKWyRtPHLaYXD/10-+Black+Rook+Hold+-+Kill+(34:22)/6-Lazyblink
=> [Frost Mage] Fix Crash

src/Parser/DeathKnight/Frost/Modules/Abilities.js, src/Parser/DeathKnight/Frost/Modules/Features/CooldownThroughputTracker.js, src/Parser/DeathKnight/Frost/Modules/Features/SpellUsable.js
Not finished updating FDK for 8.0.  This PR contains a subset of the changes in an effort to keep the PRs manageable.
=> [Frost Death Knight] Bfa fdk abilities

src/Parser/Mage/Arcane/CHANGELOG.js, src/Parser/Mage/Arcane/CONFIG.js, src/Parser/Mage/Arcane/CombatLogParser.js, src/Parser/Mage/Arcane/Modules/Checklist/Component.js, src/Parser/Mage/Arcane/Modules/Checklist/Module.js, src/Parser/Mage/Arcane/Modules/Features/ArcaneFamiliar.js
- Added the Checklist
- Fixed a typo in Arcane Familiar
- Changelog Entry
- Removed the spec completion warning
I still have a couple more things to add and I am going to send this to some people in the mage discord to test. But the spec is largely complete so I figured it was a good time to remove the warning.
Towards #1961
=> [Arcane Mage] Checklist & Fixes

server/config/config.js, src/Parser/Core/CombatLogParser.js, src/Parser/Core/Modules/Features/Checklist2/PreparationRuleAnalyzer.js, src/Parser/Core/Modules/RegenResourceCapTracker.js, src/Parser/DemonHunter/Havoc/Modules/Features/Checklist/Module.js, src/Parser/DemonHunter/Vengeance/Modules/Features/Checklist/Module.js, src/Parser/Druid/Feral/Modules/Features/Checklist/Module.js, src/Parser/Mage/Arcane/Modules/Checklist/Module.js, src/Parser/Paladin/Holy/Modules/Features/Checklist/Module.js, src/Parser/Priest/Discipline/Modules/Features/Checklist/Module.js, src/Parser/Rogue/Subtlety/CHANGELOG.js, src/Parser/Rogue/Subtlety/CombatLogParser.js, src/Parser/Rogue/Subtlety/Modules/Abilities.js, src/Parser/Rogue/Subtlety/Modules/BaseRotation/CastsInStealthBase.js, src/Parser/Rogue/Subtlety/Modules/BaseRotation/NightbladeDuringSymbols.js, src/Parser/Rogue/Subtlety/Modules/BaseRotation/NightbladeUptime.js, src/Parser/Rogue/Subtlety/Modules/Features/Checklist/Component.js, src/Parser/Rogue/Subtlety/Modules/Features/Checklist/Module.js, src/Parser/Rogue/Subtlety/Modules/RogueCore/ComboPoints.js, src/Parser/Rogue/Subtlety/Modules/RogueCore/Energy.js, src/Parser/Rogue/Subtlety/Modules/Talents/DarkShadow/DarkShadowNightblade.js, src/Parser/Rogue/Subtlety/Modules/Talents/FindWeakness.js, src/Parser/Shaman/Restoration/Modules/Features/Checklist/Module.js
#2030
Added Subtlety checklist, most of the existing analysis has been integrated in to it.
Fixed Find Weakness analysis.
Fixed a copypasta prepot/secondpot error that was in every checklist v2, by removing the copypastas,
=> [Sub Rogue] Checklist

src/Interface/Others/MonkSpreadsheet.js, src/Parser/Monk/Mistweaver/CombatLogParser.js, src/Parser/Monk/Mistweaver/Modules/Spells/EssenceFont.js, src/Parser/Monk/Mistweaver/Modules/Spells/LifeCocoon.js, src/Parser/Monk/Mistweaver/Modules/Spells/SoothingMist.js, src/Parser/Monk/Mistweaver/Modules/Talents/ChiJi.js, src/Parser/Monk/Mistweaver/Modules/Talents/RisingMist.js
Updated view for the Mistweaver Monk spreadsheet tab.
View:
=> [MW] Spreadsheet Tab Updates

src/Interface/Character/Parses.js, src/Parser/Core/Modules/Features/Checklist/Rules/PreparationRule.js
Removes legendaries from checklist v1
Makes the refresh-button on the character-page usable again
=> [Core] [Bug] Checklist fix

src/Parser/Hunter/Survival/CHANGELOG.js, src/Parser/Hunter/Survival/Modules/Abilities.js, src/common/SPELLS/HUNTER.js
Updates SV to properly handle when players take the Wildfire Infusion talent. 
Extracted from #2121 as that one takes a bit longer
=> [Survival] Abilities update to handle Wildfire Infusion talent

src/Interface/Others/Report/Results/EncounterStats.js
Adds azerite traits to the encounter-statistics.
=> [Core] Azerite traits for statistics

src/Parser/Monk/Mistweaver/Modules/Features/Checklist/Component.js
Quick fix to disable requirements in the checklist when talents are not selected.
=> [MW] Bug Fix for RJW and CB

src/Interface/Layout/Footer/index.js
=> [Core]Footer Link Fix

src/Interface/Others/HolyPriestSpreadsheet.js, src/Parser/Priest/Holy/CombatLogParser.js, src/Parser/Priest/Holy/Modules/PriestCore/EchoOfLight.js, src/Parser/Priest/Holy/Modules/Talents/CosmicRipple.js, src/Parser/Priest/Holy/Modules/Talents/EnduringRenewal.js
There was a bug that made halo display NaN hits.
Added a counter for total Cosmic Ripple hits
=> [HPriest] Improvements to spreadsheet output

src/Parser/Druid/Guardian/Modules/Spells/Moonfire.js
Removed Artifact Reference from Suggestion
=> Removed Artifact Reference

src/Parser/Druid/Guardian/Modules/Abilities.js
Removed Ring Reduction which doesn't work at 120.
=> Removed Legion artifact calc

src/common/fetchWclApi.js
This replaces all non-printable ASCII-chars from a string ( according to [this](https://www.w3resource.com/javascript-exercises/javascript-string-exercise-32.php) )
Sure its going to test all characters and impact the speed somewhat, but we get quite a few reports just because of those broken control-characters in the german game client. But the performance hit wasn't really noticeable for me while testing it.
=> [Core] [Bug] german control-character hotfix

src/CHANGELOG.js, src/Parser/Core/CombatLogParser.js, src/Parser/Core/Combatant.js, src/Parser/Core/Modules/Items/BFA/Dungeons/Seabreeze.js, src/common/ITEMS/BFA/Dungeons/index.js, src/common/SPELLS/BFA/Dungeons/ITEMS.js
=> Added support for Seabreeze

src/Parser/DemonHunter/Havoc/Modules/Abilities.js, src/Parser/DemonHunter/Havoc/Modules/Features/Checklist/Component.js
Applying a fix for this issue raised:
https://github.com/WoWAnalyzer/WoWAnalyzer/issues/2188
=> DH Havoc Fel Rush Fix

src/Parser/Priest/Holy/CombatLogParser.js, src/Parser/Priest/Holy/Modules/Features/CooldownThroughputTracker.js, src/Parser/Priest/Holy/Modules/PriestCore/EchoOfLight_Mastery.js, src/Parser/Priest/Holy/Modules/PriestCore/Fortitude_RaidBuff.js, src/Parser/Priest/Holy/Modules/PriestCore/HolyWords/HolyWordsReductionBySpell.js, src/Parser/Priest/Holy/Modules/PriestCore/HolyWords/ReductionCalculators/HolyWordsReduction.js, src/Parser/Priest/Holy/Modules/PriestCore/HolyWords/ReductionCalculators/SanctifyReduction.js, src/Parser/Priest/Holy/Modules/PriestCore/HolyWords/ReductionCalculators/SerenityReduction.js, src/Parser/Priest/Holy/Modules/PriestCore/HolyWords/SerendipityWastedAmounts.js, src/Parser/Priest/Holy/Modules/PriestCore/Serendipity.js, src/Parser/Priest/Holy/Modules/Spells/HolyWordSanctify.js, src/Parser/Priest/Holy/Modules/Spells/HymnBuffBenefit.js, src/common/SPELLS/PRIEST.js
Just removed some old legion references and made some changes to the file structure and names in hopes of making things more clear. 
Talked with the other maintainer Khadaj and he was fine with the changes.
=> Priest holy cleanup

src/common/ITEMS/BFA/Crafted/index.js
Updated them as they don't break the page anymore, and showing legion icons isn't ideal.
=> Updated icons for crafted items

src/Parser/Shaman/Restoration/Modules/Talents/Ascendance.js, src/Parser/Shaman/Restoration/Modules/Talents/CloudburstTotem.js, src/Parser/Shaman/Restoration/Modules/Talents/Downpour.js, src/Parser/Shaman/Restoration/Modules/Talents/EarthShield.js, src/Parser/Shaman/Restoration/Modules/Talents/HighTide.js, src/Parser/Shaman/Restoration/Modules/Talents/NaturesGuardian.js, src/Parser/Shaman/Restoration/Modules/Talents/UnleashLife.js, src/Parser/Shaman/Restoration/Modules/Talents/Wellspring.js
Some modules were missing absorbed healing, resulting in some odd things for fights like Vectis where a lot of your healing is absorbed.
=> [Restoration Shaman] Added absorbed healing to modules

src/CHANGELOG.js, src/Parser/Core/CombatLogParser.js, src/Parser/Core/Modules/Items/BFA/Crafted/DarkmoonDeckFathoms.js, src/common/SPELLS/BFA/Crafted/ITEMS.js
Log: https://www.warcraftlogs.com/reports/Xr7Nxjd1KnMT9QBf/#fight=1&source=13&type=auras
Fixes #1721
=> [Core] Darkmoon Deck Fathoms

src/Parser/DemonHunter/Vengeance/Modules/Abilities.js, src/Parser/DemonHunter/Vengeance/Modules/Features/Checklist/Component.js
- Removed from the Immolation Aura suggestion the Kirel Narak text part.
- Removed from checklist the AHR trinket suggestion
=> [Vengeance] Legion legendaries suggestion removal

src/CHANGELOG.js, src/Parser/Core/CombatLogParser.js, src/Parser/Core/Modules/Items/BFA/Crafted/DarkmoonDeckFathoms.js, src/Parser/Core/Modules/Spells/BFA/AzeriteTraits/ElementalWhirl.js, src/Parser/Core/Modules/Spells/BFA/AzeriteTraits/MeticulousScheming.js, src/Parser/Core/Modules/StatTracker.js, src/common/SPELLS/BFA/AzeriteTraits/General.js
https://www.warcraftlogs.com/reports/Xr7Nxjd1KnMT9QBf/#fight=1&source=13&type=summary
=> [Core] add elemental whirl azerite trait

src/Parser/Monk/Windwalker/CHANGELOG.js, src/Parser/Paladin/Retribution/CombatLogParser.js, src/Parser/Paladin/Retribution/Modules/Abilities.js, src/Parser/Paladin/Retribution/Modules/Features/Checklist/Component.js, src/Parser/Paladin/Retribution/Modules/Features/Checklist/Module.js, src/Parser/Paladin/Retribution/Modules/PaladinCore/ShieldOfVengeance.js
Also fixed a few abilities missing a GCD prop and Wake of Ashes being listed twice in Abilities
=> [Ret] Shield of Vengeance module

src/Parser/Druid/Restoration/CHANGELOG.js, src/Parser/Druid/Restoration/Constants.js, src/Parser/Druid/Restoration/Modules/Core/HotTracking/HotTracker.js, src/Parser/Druid/Restoration/Modules/Talents/Flourish.js, src/Parser/Druid/Restoration/SpellInfo.js
=> Resto druid - Added tranq HoT in various modules

src/Parser/Core/CombatLogParser.js, src/Parser/Core/Modules/Spells/BFA/AzeriteTraits/ElementalWhirl.js
It's buggy and causing other modules to break. 
I don't have time to look right now, so this is fast solution.
=> [Core] remove EW for now

src/Parser/Core/CombatLogParser.js, src/Parser/Core/Modules/Spells/BFA/AzeriteTraits/ElementalWhirl.js, src/Parser/Core/Modules/StatTracker.js
This fixes it so that downtime isn't completely messed up by this azerite trait anymore.
=> [Core] fix elemental whirl

src/Parser/Hunter/Survival/CHANGELOG.js, src/Parser/Hunter/Survival/CombatLogParser.js, src/Parser/Hunter/Survival/Modules/Spells/AzeriteTraits/WildernessSurvival.js, src/common/SPELLS/BFA/AzeriteTraits/Hunter.js
https://www.warcraftlogs.com/reports/Xr7Nxjd1KnMT9QBf/#fight=1&source=13
Sorry for the shitty if statement when it comes to Wildfire Infusion, not sure how else to be tracking that properly right now 😦
=> [Survival] add Wilderness Survival Azerite trait

src/Parser/Mage/Frost/Modules/Features/AlwaysBeCasting.js
Some slight grammar changes to the wording. Also, added a bit about continuing to cast frostbolts during boss immunity phases in order to generate procs and build icicles.
=> [Frost Mage] ABC downtime suggestion: grammar fix and addition

src/Parser/Warlock/Destruction/Modules/Talents/Eradication.js
Error and log:
https://www.warcraftlogs.com/reports/DPjthb13cg7WdGfk/#fight=13&source=30
=> Warlock crashing. Removed obsolete code

src/Parser/Mage/Frost/Modules/Features/GlacialSpike.js
Fixes a bug in the Glacial Spike module where a Glacial Spike cast that is in the air when the target dies could skew the Utilization %
Example here: the 109% Utilization
https://wowanalyzer.com/report/TYRLnfCXBN8WkMay/8-Normal+Vectis+-+Kill+(4:41)/1-Melekus/changelog
=> [Frost Mage] Glacial Spike Bug Fix

src/Parser/Druid/Restoration/CHANGELOG.js, src/Parser/Druid/Restoration/CombatLogParser.js, src/Parser/Druid/Restoration/Modules/Items/AzeriteTraits/WakingDream.js, src/Parser/Druid/Restoration/Modules/Talents/Abundance.js, src/Parser/Druid/Restoration/Modules/Talents/Stonebark.js, src/common/SPELLS/DRUID.js
/report/q6wgn2AcByW9Cb4N/4-Mythic+Fetid+Devourer+-+Kill+(5:06)/73-Kmx
=> Resto druid - Added abundance module

src/Parser/DeathKnight/Unholy/Modules/Features/Checklist.js
Because I'm a moron and missed this the first time I updated the checklist
=> Removed reference to cold heart in UH checklist

src/Parser/Core/Modules/Items/PrePotion.js
Reopening to escape some nastyness happening in #2169 
Updated version of prepotion and context by @domainzero
=> [Core] Contextual prepotion

src/Parser/Druid/Restoration/Modules/Talents/Abundance.js
Fixes a bug for abundance when the player didn't cast Regrowth
=> [Restoration Druid] [Bug] Abundance fix

src/Parser/Druid/Feral/Modules/Features/EnergyTracker.js, src/Parser/Druid/Feral/Modules/Spells/TigersFuryEnergy.js
Example crash log:
report/dgx37MW8m9nTk6pB/8-Heroic+MOTHER+-+Kill+(6:40)/94-Nantaniel
=> [Feral] Fix crash if player never uses Tiger's Fury

src/Parser/Warlock/Demonology/Modules/WarlockCore/Pets.js
To be honest, the whole Demonology pet tracking is one big TODO to rework it, so I just fixed it so it doesn't crash. Log that caused trouble: https://wowanalyzer.com/report/wAWmhrZcq47LafMj/6-Normal+MOTHER/Tikz
=> [Demonology] Fixed Demo pets bug

src/CHANGELOG.js, src/CONTRIBUTORS.js, src/Parser/Core/CombatLogParser.js, src/Parser/Core/Modules/Features/SpellInfo.js, src/Parser/Core/Modules/Spells/BFA/AzeriteTraits/ConcentratedMending.js, src/Parser/Paladin/Holy/Constants.js, src/common/SPELLS/BFA/AzeriteTraits/General.js, src/common/SPELLS/BFA/AzeriteTraits/Paladin.js, src/common/SPELLS/BFA/AzeriteTraits/__UNUSED.js
Issue #2242 
Super basic trait module for Concentrated Mending, shows % of total healing and HPS contribution.
First ever pull request! This is a whole new world to me and this seemed like a good way to get my toes wet. Feel free to yell at me if i'm doing something dumb.
=> [General Azerite] Concentrated Mending trait module

src/Parser/Druid/Restoration/CHANGELOG.js, src/Parser/Druid/Restoration/Constants.js, src/Parser/Druid/Restoration/Modules/Core/HotTracking/HotTracker.js, src/Parser/Druid/Restoration/Modules/Talents/Flourish.js, src/Parser/Druid/Restoration/Modules/Talents/Photosynthesis.js
=> Resto druid- updated photosynthesis calculations

src/Parser/Core/CombatLogParser.js
Should resolve #2269 
Let me know if this is not what is meant in the issue
=> [Core] Recursively disable dependent modules when a parent errors out

src/interface/character/Parses.js, src/interface/report/Results/EncounterStats.js
Essentially what Zero did already for the azerite-pane, just for the other usages of blizzards API
=> [Core] [Bug] 404 fix for parses & encounter stats

src/common/SPELLS/bfa/enchants.js, src/parser/core/CombatLogParser.js, src/parser/core/modules/items/bfa/enchants/QuickNavigation.js
=> Add Quick Navigation weapon enchant

src/common/SPELLS/monk.js, src/interface/others/MonkSpreadsheet.js, src/parser/monk/mistweaver/CHANGELOG.js, src/parser/monk/mistweaver/CombatLogParser.js, src/parser/monk/mistweaver/modules/features/Abilities.js, src/parser/monk/mistweaver/modules/features/CooldownThroughputTracker.js, src/parser/monk/mistweaver/modules/talents/JadeSerpentStatue.js
Let's try this again. 3rd times a charm.
#2304 and #2297
=> [MW] JSS Implemented for Spreadsheet

src/parser/demonhunter/havoc/modules/Abilities.js
https://www.wowhead.com/spell=183752/disrupt
=> DH Havoc add disrupt to spellbook

src/parser/priest/holy/modules/core/HolyWordsReductionBySpell.js
It currently looks like this: https://i.imgur.com/KFQy0Dn.png
It will now look like this: https://i.imgur.com/1L0MyIh.png
=> [HPriest] Holy word reduction styling

src/parser/core/modules/items/bfa/enchants/QuickNavigation.js
Changes max stack count to 4 and adjusts the 0 stack uptime. 
Fixes #2351
=> [Core] Fix Quick Navigation

src/parser/priest/shadow/CONFIG.js
This spec is actually not that far off of where it should be. I'm going to start maintaining shadow, but there is no real need for this to be disabled at the moment.
=> [SPriest] Enabling spec

src/common/SPELLS/bfa/azeritetraits/general.js, src/common/TraitIdMap.js, src/parser/core/CombatLogParser.js, src/parser/core/modules/spells/bfa/azeritetraits/TidalSurge.js
Dunno where the numbers in TraitIdMap.js comes from, it did not work with 280402 so I had to change it to 280404
=> Added azerite trait tidal surge

src/parser/warlock/affliction/modules/features/Darkglare.js
It was caused by a prepull dot that somehow didn't show up in logs, which caused it not to be tracked by the module and be undefined when it shouldn't be. Also reworked the `_resetDotOnTarget()` method a little.
Log that caused the error: https://www.warcraftlogs.com/reports/fbF2BZ9mqk3pPnGJ/#fight=11&source=25
=> [BUG] [Affliction] Fixed Darkglare bug

src/parser/warlock/destruction/CHANGELOG.js, src/parser/warlock/destruction/modules/talents/Eradication.js
Fixed Eradication module to check for Eradication on target on *cast* instead of damage for Chaos Bolt and Incinerate.
=> [Destruction] Eradication fix

src/parser/hunter/marksmanship/modules/spells/Trueshot.js
=> fix trueshot crash

src/parser/core/modules/StatTracker.js, src/parser/paladin/retribution/CHANGELOG.js, src/parser/paladin/retribution/CombatLogParser.js, src/parser/paladin/retribution/modules/core/azeritetraits/DivineRight.js
=> [Ret] Divine Right Azerite module

src/parser/priest/holy/modules/spells/Renew.js, src/parser/priest/holy/modules/talents/100/HolyWordSalvation.js
This pr makes renew counting more accurate for ER/Benediction/Holy Word: Salvation.
=> [HPriest] Benediction fix

src/parser/hunter/beastmastery/modules/spells/BarbedShot.js, src/parser/hunter/survival/modules/talents/MongooseBite.js
Flatten is no longer usable so change these two to flat
=> [Hunter] fix flatten

src/parser/priest/holy/modules/core/Fortitude_RaidBuff.js
The current Power Word: Fort thresholds are a bit hard to hit:
https://puu.sh/BFEsd/bbf3bd6e47.png
This pr should fix that.
=> [HPriest] Fort buff threshold fix

src/common/SPELLS/bfa/enchants.js, src/parser/core/CombatLogParser.js, src/parser/core/modules/items/bfa/enchants/DeadlyNavigation.js, src/parser/core/modules/items/bfa/enchants/MasterfulNavigation.js, src/parser/core/modules/items/bfa/enchants/Navigation.js, src/parser/core/modules/items/bfa/enchants/QuickNavigation.js, src/parser/core/modules/items/bfa/enchants/StalwartNavigation.js, src/parser/core/modules/items/bfa/enchants/VersatileNavigation.js
http://wow-analyzer.docker/report/MNzkd2Kx9TCFwtgH/4-Heroic+Zul+-+Wipe+4+(5:49)
Kagaroch - Stalwart
Tezek - Mastery
Leysha - Quick
Leysha - Versatility
Бибамёт - Deadly
=> Adding all Navigation enchants

src/parser/core/modules/others/DistanceMoved.js, src/parser/druid/balance/CONFIG.js, src/parser/druid/balance/CombatLogParser.js, src/parser/druid/balance/modules/Abilities.js, src/parser/druid/balance/modules/features/Checklist/Component.js, src/parser/druid/balance/modules/features/Checklist/Module.js, src/parser/druid/balance/modules/features/EarlyDotRefreshes.js, src/parser/druid/balance/modules/features/EarlyDotRefreshesInstants.js, src/parser/druid/balance/modules/features/Empowerment.js, src/parser/druid/balance/modules/features/UnempoweredLunarStrike.js
- Updated checklist to new format and added short cooldowns.
- fixed a bug where overcapped empowerments were being counted as generated.
- updated Lunar Strike target threshold.
- fixed a bug in distanceMoved.
- reduced thresholds for early dot refreshes and all balance druid cooldowns without charges.
- updated link to dreamgrove.
=> [Balance Druid] Update Checklist & Bug fixes

src/parser/druid/balance/modules/features/Checklist/Component.js
=> [Balance Druid] stellar flare bug

src/parser/priest/holy/CONFIG.js
New Message:
https://puu.sh/BIgQ4/89d5ebffc8.png
=> [HPriest] Updating holy welcome message

src/common/SPELLS/warrior.js, src/parser/warrior/arms/CHANGELOG.js, src/parser/warrior/arms/CONFIG.js, src/parser/warrior/arms/modules/Abilities.js
- Fixed some spell IDs that were not correct (according to the console alerts about missing spells from the spellbook
- Updated Config/Contributors
- Fixed some Ability information
=> [Arms Warrior] A Little Bit of Cleanup

src/parser/shaman/elemental/CombatLogParser.js, src/parser/shaman/enhancement/CombatLogParser.js, src/parser/shaman/restoration/CombatLogParser.js, src/parser/shaman/shared/talents/SpiritWolf.js
Added damage reduction statistics, also need a shared class changelog as i'm too lazy to add it to 3 of them
Log used: http://localhost:3000/report/N7D3GK4ygHvcjqYf/22-Mythic+G'huun+-+Kill+(8:43)/54-Werdup
=> [Shaman] Spirit Wolf Talent

src/parser/monk/brewmaster/modules/features/checklist/Component.js
Checklist failed when a player wasn't using Rushing Jade Wind. This will disable the requirement check when the player wasn't using RJW
=> [Brewmaster Monk] [Bug] Checklist fix

src/interface/home/Page.js
Added the discord logo along with the bot link as it was shown in [the discord bot announce](https://github.com/WoWAnalyzer/WoWAnalyzer/blob/master/src/articles/2017-10-21-DiscordBot/index.js)
=> Added invite link for the discord bot on the home page. Fixes #2077

src/CHANGELOG.js, src/interface/others/Cooldown.js
=> Healers - Fixed mana usage for innervate on cooldowns tab

src/common/SPELLS/priest.js, src/common/SPELLS/talents/priest.js, src/parser/priest/shadow/CombatLogParser.js, src/parser/priest/shadow/modules/checklist/Component.js, src/parser/priest/shadow/modules/talents/ShadowCrash.js, src/parser/priest/shadow/modules/talents/TwistOfFate.js, src/parser/priest/shadow/modules/talents/VoidTorrent.js
I've updated the existing talents for shadow.
Twist of Fate: 
Void Torrent:
I've also added Shadow Crash:
=> [Spriest] Talent update & adding shadow crash

src/parser/monk/brewmaster/modules/features/checklist/Component.js
=> [BrM] fixed BoB checklist item description

src/interface/home/SpecListing/Spec.js, src/interface/report/Results/About.js
=> Statustext for unmaintained specs

src/CHANGELOG.js, src/common/SPELLS/bfa/azeritetraits/general.js, src/parser/core/CombatLogParser.js, src/parser/shared/modules/StatTracker.js, src/parser/shared/modules/spells/bfa/azeritetraits/BlightborneInfusion.js
Adds a module for this trait, along with a correct stattracker entry.
https://www.warcraftlogs.com/reports/yfRGJwQvD2jTBKLP#fight=35&type=summary&source=5
relevant issue: #2242
=> [Core] Blightborne Infusion

src/parser/mage/frost/modules/features/BoneChilling.js, src/parser/mage/frost/modules/features/GlacialSpike.js, src/parser/mage/frost/modules/features/SplittingIce.js, src/parser/mage/frost/modules/features/ThermalVoid.js, src/parser/mage/shared/modules/features/MirrorImage.js, src/parser/mage/shared/modules/features/RuneOfPower.js
- Fixed totalCasts counter in GlacialSpike
- Moved Talent Stat Boxes to the Talents section
=> [Frost Mage] Glacial Spike Fix & Talent Trait Boxes

src/CHANGELOG.js, src/common/SPELLS/bfa/enchants.js, src/parser/core/CombatLogParser.js, src/parser/shared/modules/items/bfa/enchants/CoastalSurge.js
https://www.wowhead.com/spell=267537/coastal-surge
https://www.warcraftlogs.com/reports/nkAD7ZM13X682GmC/#fight=14&source=8
=> [Enchant] Coastal Surge

src/common/SPELLS/hunter.js, src/parser/hunter/beastmastery/modules/Abilities.js, src/parser/hunter/beastmastery/modules/core/GlobalCooldown.js, src/parser/hunter/beastmastery/modules/features/Checklist.js, src/parser/hunter/beastmastery/modules/features/TraitsAndTalents.js, src/parser/hunter/beastmastery/modules/spells/BarbedShot.js, src/parser/hunter/marksmanship/modules/Abilities.js, src/parser/hunter/marksmanship/modules/core/GlobalCooldown.js, src/parser/hunter/marksmanship/modules/talents/SteadyFocus.js, src/parser/hunter/shared/modules/talents/AMurderOfCrows.js, src/parser/hunter/survival/modules/Abilities.js
Updates some cast efficiencies
Updates Aspect of the Wild and double dipping of GCD reduction -- They fixed double dipping of haste and introduced a new double dipping. yay.
Updates A Murder of Crows resetting.
=> [Hunter] Steady Shot GCD, Crows Reset and Aspect of the Wild double dipping

src/common/SPELLS/bfa/azeritetraits/general.js, src/parser/core/CombatLogParser.js, src/parser/shared/modules/spells/bfa/azeritetraits/Savior.js
=> [Azerite] Adding Savior azerite trait

src/CHANGELOG.js, src/common/ITEMS/bfa/dungeons/index.js, src/common/SPELLS/bfa/dungeons/items.js, src/parser/core/CombatLogParser.js, src/parser/shared/modules/StatTracker.js, src/parser/shared/modules/items/bfa/dungeons/LustrousGoldenPlumage.js, src/parser/shared/modules/items/bfa/pvp/DreadGladiatorsBadge.js
=> [Core] add Lustrous Golden Plumage

src/common/SPELLS/bfa/azeritetraits/general.js, src/parser/core/CombatLogParser.js, src/parser/shared/modules/spells/bfa/azeritetraits/WoundBinder.js
As far as I can tell, this is correct. There are no published numbers for this azerite trait, so I built this module based on the theory crafters info in the priest discord.
=> [Azerite] Adding Woundbinder

src/parser/core/CombatLogParser.js, src/parser/shared/modules/spells/bfa/azeritetraits/BracingChill.js
I built this on top of #2513 and it should not be merged until that PR is.
=> [Azerite] Adding Bracing Chill

src/common/SPELLS/monk.js, src/parser/monk/brewmaster/CHANGELOG.js, src/parser/monk/brewmaster/CombatLogParser.js, src/parser/monk/brewmaster/modules/spells/CelestialFortune.js
Tracks healing from [Celestial Fortune](https://www.wowhead.com/spell=216519/celestial-fortune).
=> [BrM] Added Celestial Fortune stat and table

src/parser/hunter/beastmastery/modules/spells/azeritetraits/FeedingFrenzy.js
As was requested as one of the traits via #2535, I have modified the Feeding Frenzy module to include the damage contribution of the azerite trait. It does this by calculating how much of the damage portion of a Barbed Shot tick was actually contributed via the Feeding Frenzy increased damage. I've verified the accuracy of this contribution using an estimated damage number, which ended up being accurate in nearly all cases I've checked, only being off by 0 or 1 damage in most cases.
Screenshot of how it looks like: https://i.imgur.com/7f4LRx5.png
It works similar to the Wild Fleshrending trait that Feral Druids have; https://github.com/WoWAnalyzer/WoWAnalyzer/blob/master/src/parser/druid/feral/modules/azeritetraits/WildFleshrending.js
It comes with a minor flaw that the attack power of …
=> [Beast Mastery] Modify the Feeding Frenzy module to additionally track the damage contribution of the trait

src/common/SPELLS/mage.js, src/parser/mage/arcane/modules/features/Abilities.js, src/parser/mage/fire/modules/features/Abilities.js, src/parser/mage/frost/modules/checklist/Component.js, src/parser/mage/frost/modules/features/Abilities.js
Fixes a small number of capitalization issues and adds some missing buffids so that they appear in the timeline
=> [Mage] Fix some capitalization and add missing ability buffids

src/parser/paladin/protection/modules/spells/Consecration.js
uptime => hits mitigated
fixes #2545
=> [Prot Paladin] fixed consecration suggestion text

src/interface/others/RestorationShamanSpreadsheet.js, src/parser/shaman/restoration/CombatLogParser.js, src/parser/shaman/restoration/modules/azerite/OverflowingShores.js, src/parser/shaman/restoration/modules/core/Spreadsheet.js
https://www.wowhead.com/spell=277658/overflowing-shores
Relevant Issue #2009 
Also moves the relevant spreadsheet export from the dedicated file to this module.
=> [Restoration Shaman] Overflowing Shores

src/interface/others/RestorationShamanSpreadsheet.js, src/parser/shaman/restoration/CombatLogParser.js, src/parser/shaman/restoration/modules/azerite/SpoutingSpirits.js, src/parser/shaman/restoration/modules/core/Spreadsheet.js
2nd last trait from the main rshaman azerite traits
https://www.wowhead.com/spell=278715/spouting-spirits
https://www.warcraftlogs.com/reports/Mg3q1ALd6wPxTzhm/#fight=5&source=2&type=summary
Relevant Issue #2009
Also moves the relevant spreadsheet export from the dedicated file to this module.
=> [Restoration Shaman] Spouting Spirits

src/CHANGELOG.js, src/common/SPELLS/bfa/azeritetraits/general.js, src/parser/core/CombatLogParser.js, src/parser/shared/modules/StatTracker.js, src/parser/shared/modules/spells/bfa/azeritetraits/SwirlingSands.js
http://wowhead.com/spell=280429
https://www.warcraftlogs.com/reports/nkAD7ZM13X682GmC/#fight=14&source=8
Relevant issue #2242
=> [Azerite] Swirling Sands

src/parser/shaman/restoration/CHANGELOG.js, src/parser/shaman/restoration/modules/talents/AncestralVigor.js
Adds more detail to the AV module, partially to see if some of those "lives saved" were shortly after another on the same player (where he'd already be dead). I might filter that in the future if it happens too often in logs.
https://www.warcraftlogs.com/reports/vfktbD3mCaNR7Q8M/#fight=69&source=28
Thanks to whoever made the lazy-load statistic box expandable
=> [Restoration Shaman] Ancestral Vigor breakdown

src/parser/warlock/affliction/CONFIG.js, src/parser/warlock/destruction/CHANGELOG.js, src/parser/warlock/destruction/CONFIG.js, src/parser/warlock/destruction/CombatLogParser.js, src/parser/warlock/destruction/modules/talents/Eradication.js, src/parser/warlock/destruction/modules/talents/FireAndBrimstone.js, src/parser/warlock/destruction/modules/talents/GrimoireOfSupremacy.js, src/parser/warlock/destruction/modules/talents/index.js
After the flurry of PRs, I wanted to make sure everything is ok, hence this PR:
- switched 2 changelog entries (same day, just wanted to order the added talents from lowest to highest tier)
- bumped compatibility to 8.0.1 for Affli and Destro
- minor text changes to few talents
- reordering of imports and their usage (nothing changed, just switched places, Split diff might make it easier to read)
=> [Destruction] Cleanup

src/parser/shared/modules/items/bfa/raids/uldir/ConstructOvercharger.js
It got buffed by 50%. 
https://github.com/simulationcraft/simc/commit/34cc942772b77072b0919fe192c05fefb0d4336a
=> [Core] update construct overcharger to comply with the hotfixes

src/common/SPELLS/bfa/azeritetraits/index.js, src/common/SPELLS/bfa/azeritetraits/rogue.js, src/parser/druid/balance/modules/resourcetracker/AstralPowerDetails.js, src/parser/rogue/assassination/CHANGELOG.js, src/parser/rogue/assassination/CONFIG.js, src/parser/rogue/assassination/CombatLogParser.js, src/parser/rogue/assassination/modules/features/Checklist/Component.js, src/parser/rogue/assassination/modules/features/Checklist/Module.js, src/parser/rogue/assassination/modules/spells/EnvenomUptime.js, src/parser/rogue/assassination/modules/spells/GarroteUptime.js, src/parser/rogue/assassination/modules/spells/RuptureUptime.js, src/parser/rogue/outlaw/CHANGELOG.js, src/parser/rogue/shared/resources/ComboPointDetails.js, src/parser/rogue/shared/resources/EnergyCapTracker.js, src/parser/rogue/shared/resources/EnergyDetails.js, src/parser/rogue/subtlety/CHANGELOG.js
=> [Assassination] Add Checklist and update ResourceTracker

src/common/SPELLS/bfa/azeritetraits/priest.js, src/parser/priest/shadow/CHANGELOG.js, src/parser/priest/shadow/CombatLogParser.js, src/parser/priest/shadow/modules/spells/azeritetraits/ChorusOfInsanity.js, src/parser/shared/modules/StatTracker.js
=> [Spriest] Chorus of Insanity azerite trait

src/CHANGELOG.js, src/common/ITEMS/bfa/raids/uldir/index.js, src/common/SPELLS/bfa/raids/uldir/items.js, src/parser/core/CombatLogParser.js, src/parser/shared/modules/items/bfa/raids/uldir/SyringeOfBloodborneInfirmity.js
Added a module for Syringe of Bloodborne Infirmity (https://www.wowhead.com/item=160655)
=> [Trinket] Syringe of Bloodborne Infirmity

src/parser/shared/modules/StatTracker.js
forgot this when updating for hotfix
=> [Core] update statTracker

src/parser/warrior/arms/modules/core/Execute/MortalStrike.js
=> [Arms] Correcting visual

src/parser/priest/shadow/CHANGELOG.js, src/parser/priest/shadow/CombatLogParser.js, src/parser/priest/shadow/modules/spells/ShadowWordPain.js, src/parser/priest/shadow/modules/talents/DarkVoid.js
Adding a talent card and suggestion for Dark Void. I also made some changes to the SW:P module for some upcoming work I am going to do.
=> [Spriest] Dark Void

src/CHANGELOG.js, src/common/ITEMS/bfa/dungeons/index.js, src/common/SPELLS/bfa/dungeons/items.js, src/parser/core/CombatLogParser.js, src/parser/shared/modules/items/bfa/dungeons/AzerokksResonatingHeart.js
Added a statistic box for Azerokk's Resonating Heart.
=> [Core] Add Azerokk's Resonating Heart module

package-lock.json, package.json, src/interface/App.css, src/parser/monk/brewmaster/modules/features/StaggerPoolGraph.css, src/parser/monk/brewmaster/modules/features/StaggerPoolGraph.js
See #2489 for motivation on trying a new charting library.
I'm not happy with the responsiveness/feel of victory. I rebuilt the stagger plot (again) in [react-vis](https://uber.github.io/react-vis/), and it seems to be much more performant even on my crappy laptop.
Wanting to merge this into test to try it out on a few more devices and solicit feedback from people in discord.
[Example](https://cdn.discordapp.com/attachments/316864385052049420/510937173738913795/react-vis-plot.webm)
=> [TEST] React-vis instead of Victory (instead of Chart.js)

src/common/SPELLS/bfa/azeritetraits/hunter.js, src/common/SPELLS/hunter.js, src/parser/hunter/beastmastery/CHANGELOG.js, src/parser/hunter/beastmastery/CombatLogParser.js, src/parser/hunter/beastmastery/constants.js, src/parser/hunter/beastmastery/modules/spells/azeritetraits/FeedingFrenzy.js, src/parser/hunter/beastmastery/modules/spells/azeritetraits/PackAlpha.js, src/parser/hunter/beastmastery/modules/talents/AnimalCompanion.js
Second to last round of Beast Mastery talents. 
Relies on the two previous ones as those are the most important talents, so spend your limited review time there. 
Number 1: #2615 
Number 2: #2645 
Towards #2529 & #2037 
Extremely simple Pack Alpha module for now: 
Work for future module can be seen here: https://github.com/Pewtro/WoWAnalyzer/blob/08872054615a54058fba06c590c9054aab1e9c00/src/parser/hunter/beastmastery/modules/spells/azeritetraits/PackAlpha.js
Animal Companion module that looks like this:
=> [Hunter] Animal Companion & Pack Alpha

src/parser/warrior/arms/CHANGELOG.js, src/parser/warrior/arms/CombatLogParser.js, src/parser/warrior/arms/modules/talents/FervorOfBattle.js, src/parser/warrior/arms/modules/talents/index.js
Added Fervor of Battle in the Talents module
=> [Arms][Talent] Fervor of Battle

src/parser/warrior/arms/CHANGELOG.js, src/parser/warrior/arms/CombatLogParser.js, src/parser/warrior/arms/modules/core/Slam.js
Added a suggestion on using Slam while Mortal Strike was available
=> [Arms] Slam suggestion

src/parser/shaman/elemental/CHANGELOG.js
=> Added more changelog entries

src/CHANGELOG.js, src/common/SPELLS/racials.js, src/parser/core/CombatLogParser.js, src/parser/mage/frost/CHANGELOG.js, src/parser/shared/modules/racials/draenei/GiftOfTheNaaru.js
I did not add a module statistics box. This should just resolve errors about it missing from the spellbook and add it to the timeline & death recap.
=> [Core] Added GiftOfTheNaaru racial to draenei spellbooks

src/parser/rogue/outlaw/CombatLogParser.js, src/parser/rogue/outlaw/modules/Abilities.js, src/parser/rogue/outlaw/modules/core/RestlessBlades.js, src/parser/rogue/outlaw/modules/talents/SliceAndDiceUptime.js
Just a little refactor and removing of some leftover legendary stuff.
=> [Outlaw] Refactoring

src/common/SPELLS/bfa/azeritetraits/__UNUSED.js, src/common/SPELLS/hunter.js, src/parser/hunter/beastmastery/CHANGELOG.js, src/parser/hunter/beastmastery/CombatLogParser.js, src/parser/hunter/marksmanship/CHANGELOG.js, src/parser/hunter/marksmanship/CombatLogParser.js, src/parser/hunter/shared/modules/talents/BindingShot.js, src/parser/hunter/shared/modules/talents/BornToBeWild.js, src/parser/hunter/shared/modules/talents/NaturalMending.js, src/parser/hunter/survival/CHANGELOG.js, src/parser/hunter/survival/CombatLogParser.js
Log: https://www.warcraftlogs.com/reports/Maqb6BkvAKpVg972#fight=86&type=damage-done
Log: https://www.warcraftlogs.com/reports/GPBH7V9R1dXrnNam#fight=1&type=damage-done
Fixes #2529  (after the other 2 PRs aswell)
=> [Hunter] Born to be wild & Binding Shot

src/parser/monk/mistweaver/CHANGELOG.js, src/parser/monk/mistweaver/CombatLogParser.js, src/parser/monk/mistweaver/modules/features/MasteryStats.js, src/parser/monk/mistweaver/modules/features/MistweaverHealingEfficiencyTracker.js, src/parser/monk/mistweaver/modules/spells/EnvelopingMists.js, src/parser/monk/mistweaver/modules/spells/RenewingMist.js, src/parser/monk/mistweaver/modules/spells/SoothingMist.js, src/parser/monk/mistweaver/modules/spells/ThunderFocusTea.js, src/parser/monk/mistweaver/modules/spells/Vivify.js
Added gusts of mists breakdown chart. 
Fixed bug with the ReM and Vivify mana efficiency.
=> [Mistweaver] Gusts of Mists Breakdown Chart

src/parser/warrior/arms/modules/core/Slam.js, src/parser/warrior/arms/modules/features/Checklist/Component.js, src/parser/warrior/arms/modules/features/Checklist/Module.js, src/parser/warrior/arms/modules/spells/azeritetraits/ExecutionersPrecision.js
Changed the suggestions and the Checklist for Executioner's Precision trait
=> [Arms] Reworked Executioner's Precision

src/common/SPELLS/demonhunter.js, src/parser/demonhunter/vengeance/CHANGELOG.js, src/parser/demonhunter/vengeance/modules/Abilities.js, src/parser/demonhunter/vengeance/modules/features/SoulFragmentsTracker.js, src/parser/demonhunter/vengeance/modules/statistics/SoulFragmentsConsume.js, src/parser/demonhunter/vengeance/modules/talents/AgonizingFlames.js, src/parser/demonhunter/vengeance/modules/talents/BurningAlive.js, src/parser/demonhunter/vengeance/modules/talents/FeastOfSouls.js, src/parser/demonhunter/vengeance/modules/talents/FeedTheDemon.js, src/parser/demonhunter/vengeance/modules/talents/Gluttony.js, src/parser/demonhunter/vengeance/modules/talents/RazorSpikes.js, src/parser/demonhunter/vengeance/modules/talents/SoulBarrier.js, src/parser/demonhunter/vengeance/modules/talents/SpiritBombFrailtyDebuff.js, src/parser/demonhunter/vengeance/modules/talents/SpiritBombSoulsConsume.js, src/parser/demonhunter/vengeance/modules/talents/VoidReaverDebuff.js
Simply updated them to the new talentstat box
=> {VDH} Talents Update

src/CHANGELOG.js, src/common/ITEMS/bfa/pvp/index.js, src/common/SPELLS/bfa/pvp/items.js, src/parser/core/CombatLogParser.js, src/parser/shared/modules/StatTracker.js, src/parser/shared/modules/items/bfa/pvp/DreadGladiatorsInsignia.js
Added Dread Gladiator's Insignia stat block.
=> [Core] Add Dread Gladiator's Insignia module

src/parser/priest/shadow/modules/spells/VampiricEmbrace.js
I missed this in the last pr by like 5 seconds.
=> [Spriest] Fixing undefined in the tooltip

src/parser/core/CombatLogParser.js, src/parser/core/CombatLogParser.test.js
=> [Core] Fix on finish fix on finish again again

src/common/SPELLS/bfa/azeritetraits/priest.js, src/parser/priest/shadow/CHANGELOG.js, src/parser/priest/shadow/CombatLogParser.js, src/parser/priest/shadow/modules/spells/azeritetraits/DeathThroes.js
=> [SPriest] Adding Death Throes

src/parser/hunter/survival/CHANGELOG.js, src/parser/hunter/survival/modules/features/CooldownThroughputTracker.js, src/parser/hunter/survival/modules/spells/SerpentSting.js, src/parser/shared/modules/items/bfa/dungeons/GalecallersBoon.js
Updates Serpent Sting uptime thresholds
Makes galecaller push to abilities.
=> [Survival] Serpent Sting adjustments

src/parser/monk/windwalker/modules/features/checklist/Module.js
=> [WW Monk] Fix typo in checklist causing crash

src/parser/shared/normalizers/PrePullCooldowns.js
Title. Fixes a crash when the cast applied a buff with a different id
=> [Core] Fix trying to get GCD of buff id instead of cast id

src/parser/warlock/destruction/modules/features/Backdraft.js, src/parser/warlock/destruction/modules/features/Havoc.js, src/parser/warlock/destruction/modules/features/RainOfFire.js, src/parser/warlock/destruction/modules/talents/Cataclysm.js, src/parser/warlock/destruction/modules/talents/ChannelDemonfire.js, src/parser/warlock/destruction/modules/talents/Eradication.js, src/parser/warlock/destruction/modules/talents/FireAndBrimstone.js, src/parser/warlock/destruction/modules/talents/Flashover.js, src/parser/warlock/destruction/modules/talents/InternalCombustion.js, src/parser/warlock/destruction/modules/talents/RoaringBlaze.js, src/parser/warlock/destruction/modules/talents/Shadowburn.js
Updated majority to new listeners. Some are still left in the old ways, but not combined in 1 module
=> [Destruction] Event listener update

src/common/SPELLS/bfa/azeritetraits/__UNUSED.js, src/common/SPELLS/bfa/azeritetraits/warlock.js, src/common/SPELLS/warlock.js, src/parser/shared/modules/StatTracker.js, src/parser/warlock/affliction/CombatLogParser.js, src/parser/warlock/affliction/modules/azerite/WrackingBrilliance.js
Will cause merge conflicts with #2738 (files in SPELLS and CombatLogParser). For absence of Changelog entry, look at #2738. Part of #2724.
=> [Affliction] Wracking Brilliance trait

src/parser/mage/frost/CHANGELOG.js, src/parser/mage/frost/CombatLogParser.js, src/parser/mage/frost/modules/talents/LonelyWinter.js
=> [Frost Mage] Add Lonely Winter module

src/common/SPELLS/bfa/azeritetraits/warlock.js, src/parser/shared/modules/StatTracker.js, src/parser/warlock/demonology/CombatLogParser.js, src/parser/warlock/demonology/modules/azerite/SupremeCommander.js
=> [Demonology] Supreme Commander trait

src/common/SPELLS/bfa/azeritetraits/warlock.js, src/parser/shared/modules/StatTracker.js, src/parser/warlock/demonology/CombatLogParser.js, src/parser/warlock/demonology/modules/azerite/ExplosivePotential.js
=> [Demonology] Explosive Potential trait

src/common/SPELLS/bfa/azeritetraits/warlock.js, src/parser/warlock/affliction/CombatLogParser.js, src/parser/warlock/affliction/modules/azerite/SuddenOnset.js
The damage is a little high because it was from Mythic Zul, so I assume heavy multi-dotting, usually it's a lot lower. Part of #2724
=> [Affliction] Sudden Onset trait

src/common/SPELLS/bfa/azeritetraits/__UNUSED.js, src/common/SPELLS/bfa/azeritetraits/warlock.js, src/common/SPELLS/warlock.js, src/parser/shared/modules/Entities.js, src/parser/warlock/affliction/CombatLogParser.js, src/parser/warlock/affliction/modules/azerite/InevitableDemise.js
I **intentionally** didn't add changelog entry as I plan to do more traits (probably today) and I'd rather have 1 entry like "added traits X, Y, Z" than 3 entries for same date (feels less spammy this way and easier to resolve merge conflicts). If you insist on having 3 entries though, I'll make it happen
=> [Affliction] Inevitable Demise trait

src/common/SPELLS/bfa/azeritetraits/warlock.js, src/parser/shared/modules/StatTracker.js, src/parser/warlock/destruction/CombatLogParser.js, src/parser/warlock/destruction/modules/azerite/Accelerant.js
=> [Destruction] Added Accelerant trait

src/common/SPELLS/bfa/azeritetraits/__UNUSED.js, src/common/SPELLS/bfa/azeritetraits/warlock.js, src/parser/shared/modules/StatTracker.js, src/parser/warlock/destruction/CombatLogParser.js, src/parser/warlock/destruction/modules/azerite/Flashpoint.js
=> [Destruction] Added Flashpoint trait

src/common/SPELLS/bfa/azeritetraits/warlock.js, src/parser/shared/modules/StatTracker.js, src/parser/warlock/destruction/CombatLogParser.js, src/parser/warlock/destruction/modules/azerite/RollingHavoc.js
Part of #2724. Suffers from same problems as #2760
=> [Destruction] Rolling Havoc trait

src/parser/shared/modules/items/CombatPotion.js
Fix for #2742
Updated the CombatPotion.js file to include Potion of Replenishment to show it on the timeline.
=> #2742 - Updated CombatPotion.js

src/parser/druid/restoration/modules/features/WildGrowth.js
=> Resto druid - fixed bug with pre casted WGs

src/interface/others/HolyPriestSpreadsheet.js, src/parser/priest/holy/modules/spells/azeritetraits/WordOfMending.js
Adding some fields that were skipped over in the initial implementation
=> [HPriest] Updating holy priest spreadsheet

src/common/SPELLS/bfa/azeritetraits/warrior.js, src/parser/warrior/arms/CHANGELOG.js, src/parser/warrior/arms/CombatLogParser.js, src/parser/warrior/arms/modules/spells/azeritetraits/CrushingAssault.js, src/parser/warrior/arms/modules/spells/azeritetraits/SeismicWave.js, src/parser/warrior/arms/normalizers/CrushingAssaultBuff.js
Added Crushing assault statistic module
=> [Arms] Crushing Assault

src/parser/shaman/elemental/modules/azerite/LavaShock.js
added return if trait isnt active
http://localhost:3000/report/ZrXnCF7HyqPYLtRG/7-Heroic+Fetid+Devourer+-+Kill+(2:50)/10-Lurkette
Error:
=> Ele Shaman Lava Shock Error Fix

src/parser/warlock/affliction/CHANGELOG.js, src/parser/warlock/affliction/modules/azerite/DreadfulCalling.js, src/parser/warlock/demonology/CHANGELOG.js, src/parser/warlock/demonology/modules/pets/DemoPets/DemonicTyrantHandler.js, src/parser/warlock/demonology/modules/pets/PetTimelineTab/TabComponent/PetTimeline.js, src/parser/warlock/demonology/modules/talents/DemonicConsumption.js, src/parser/warlock/demonology/modules/talents/SacrificedSouls.js
- Unstable Affliction coefficient nerfed
- Demonic Tyrant now extends all pets, including the random ones
- Nether Portal changed from 20 seconds to 15
- Demonic Consumption doubled (still not overly viable tho)
- Sacrificed Souls nerfed
Only thing that's left are the new traits but I'm busy with school things so that will have to wait.
=> [Warlock] Some 8.1 changes for Warlocks

src/parser/warrior/fury/CombatLogParser.js
noticed these definition redefines were breaking the linter check on my PR.
=> Fixing some issues that are breaking the linter on PRs

src/common/SPELLS/encounter.js, src/raids/battleofdazaralor/ConclaveOfTheChosen.js, src/raids/battleofdazaralor/FridaIronbellows.js, src/raids/battleofdazaralor/GrongTheJungleLord.js, src/raids/battleofdazaralor/GrongTheRevenant.js, src/raids/battleofdazaralor/HighTinkerMekkatorque.js, src/raids/battleofdazaralor/JadefireMastersAlliance.js, src/raids/battleofdazaralor/JadefireMastersHorde.js, src/raids/battleofdazaralor/JainaProudmoore.js, src/raids/battleofdazaralor/KingRastakhan.js, src/raids/battleofdazaralor/OpulenceTreasureGuardian.js, src/raids/battleofdazaralor/RawaniKanae.js, src/raids/battleofdazaralor/StormwallBlockade.js
-Adds spell information for Battle of Dazar'alor encounters.
-Updates boss information with soft mitigation checks for Battle of Dazar'alor encounters.
=> [Tank] Update soft mitigation checks for Battle of Dazar'alor

src/parser/rogue/assassination/CONFIG.js, src/parser/rogue/assassination/CombatLogParser.js, src/parser/rogue/assassination/modules/Abilities.js, src/parser/rogue/assassination/modules/core/Snapshot.js, src/parser/rogue/assassination/modules/features/Checklist/Component.js, src/parser/rogue/assassination/modules/features/Checklist/Module.js, src/parser/rogue/assassination/modules/talents/MasterAssassin.js, src/parser/rogue/assassination/modules/talents/Nightstalker.js, src/parser/rogue/assassination/modules/talents/StealthCasts.js, src/parser/rogue/assassination/modules/talents/Subterfuge.js, src/parser/rogue/assassination/normalizers/GarroteNormalizer.js, src/parser/rogue/assassination/normalizers/GarroteOpenerNormalizer.js
Also set Assassination to actively maintained.
Subterfuge:
Master Assassin:
Nightstalker:
=> [Assassination Rogue] Vanish utilization & snapshot fixes

src/common/SPELLS/hunter.js, src/interface/report/Results/EncounterStats.js, src/parser/hunter/beastmastery/modules/Abilities.js, src/parser/hunter/beastmastery/modules/checklist/Component.js, src/parser/hunter/beastmastery/modules/core/GlobalCooldown.js, src/parser/hunter/beastmastery/modules/features/Checklist.js, src/parser/hunter/beastmastery/modules/spells/CobraShot.js, src/parser/hunter/beastmastery/modules/talents/AnimalCompanion.js, src/parser/hunter/beastmastery/modules/talents/AspectOfTheBeast.js, src/parser/hunter/beastmastery/modules/talents/KillerCobra.js, src/parser/hunter/beastmastery/modules/talents/KillerInstinct.js, src/parser/hunter/beastmastery/modules/talents/Stampede.js, src/parser/hunter/beastmastery/modules/talents/ThrillOfTheHunt.js, src/parser/hunter/beastmastery/modules/talents/VenomousBite.js, src/parser/hunter/shared/modules/features/FocusUsage.js, src/parser/hunter/survival/CHANGELOG.js, src/parser/hunter/survival/CombatLogParser.js, src/parser/hunter/survival/constants.js, src/parser/hunter/survival/modules/Abilities.js, src/parser/hunter/survival/modules/spells/KillCommand.js, src/parser/hunter/survival/modules/spells/SerpentSting.js, src/parser/hunter/survival/modules/talents/MongooseBite.js, src/parser/hunter/survival/modules/talents/WildfireInfusion.js, src/parser/hunter/survival/modules/talents/WildfireInfusion/PheromoneBomb.js, src/parser/hunter/survival/modules/talents/WildfireInfusion/ShrapnelBomb.js, src/parser/hunter/survival/modules/talents/WildfireInfusion/VolatileBomb.js
OBS: A lot of files changed, but that is merely because KILL_COMMAND had the naming scheme changed which affected a lot of files, you can just skim through those - nothing noteworthy. 
https://www.warcraftlogs.com/reports/n8AHdKCL9k3rtRDb#fight=36&type=damage-done
fixes #2721 
towards #2538 
Fixes a minor bug in the EncounterStats with amount of logs it parses when comparing logs in regards to kill times.
=> [Survival] Adds a Wildfire Infusion Module

src/common/SPELLS/bfa/azeritetraits/monk.js, src/parser/monk/windwalker/CombatLogParser.js, src/parser/monk/windwalker/modules/spells/TouchOfDeath.js, src/parser/monk/windwalker/modules/spells/azeritetraits/GloryOfTheDawn.js
also a quick change to Touch of Death module since they nerfed the scaling with 8.1
=> [Windwalker] Glory of the Dawn Azerite trait

src/parser/priest/discipline/modules/azeritetraits/DepthOfTheShadows.js
Fixes a crash in the Depth of Shadows module.
=> [DIscipline Priest] Fix Crash in Depth of Shadows

src/common/SPELLS/bfa/azeritetraits/monk.js, src/parser/monk/windwalker/CHANGELOG.js, src/parser/monk/windwalker/CONFIG.js, src/parser/monk/windwalker/CombatLogParser.js, src/parser/monk/windwalker/modules/Abilities.js, src/parser/monk/windwalker/modules/core/GlobalCooldown.js, src/parser/monk/windwalker/modules/spells/TouchOfKarma.js, src/parser/monk/windwalker/modules/spells/azeritetraits/FuryOfXuen.js
- Added Fury of Xuen azerite module![billede](https://user-images.githubusercontent.com/30317641/50593307-1ca67680-0e98-11e9-924f-fd4b5d4e7b5e.png)
- Fixed GCD being activated twice on Fists of Fury casts
- minor updates in Abilities and Touch of Karma module
=> [Windwalker] Add Fury of Xuen azerite module

src/interface/actions/previousPatch.js, src/interface/reducers/index.js, src/interface/reducers/reportCodesIgnoredPreviousPatchWarning.js, src/interface/report/PatchChecker.js, src/interface/report/index.js, src/interface/selectors/skipPreviousPatchWarning.js
Wrapped the fight selector with a new check.
Due to the Prepatch and Legion sites being removed, I've just provided text warnings for the moment, but this can be changed to a redirect as needed.
Also, very happy if someone has some better ideas for the text.
=> [#1668] Message when parsing log from different patch

src/parser/priest/discipline/modules/Abilities.js
Evangelism is 90 seconds since 8.1
=> [Discipline Priest] Evangelism Fix

src/parser/paladin/protection/modules/spells/LightOfTheProtector.js
=> [Prot Pal] fixed issue with lotp/hotp cast before getting hit

src/interface/report/Results/Timeline/Timeline.scss
Was just an idea I had to make the scroll bar look a little more fancy. 
Current:
Idea:
=> [NEXT] Styling idea for the scrollbar on the timeline

src/interface/others/HolyPriestSpreadsheet.js
=> [HPriest] Fixing bug with holy priest spreadsheet

src/parser/shaman/enhancement/modules/features/Checklist/Component.js
=> Fix enhancement crash

src/parser/shared/modules/spells/bfa/azeritetraits/TreacherousCovenant.js
Not sure how this happened, but part of my changes got missed in a commit.
=> [General] bugfix, Treacherous Covenant

src/common/ITEMS/bfa/raids/bod/index.js, src/common/SPELLS/bfa/raids/battleofdazaralor/items.js, src/parser/core/CombatLogParser.js, src/parser/shared/modules/items/bfa/raids/bod/IncandescentSliver.js
Adds Incandescent Sliver trinket for #2929 .
Sample log using trinket: https://www.warcraftlogs.com/reports/NvtFd9ymgbDhaYcV#fight=7&type=summary&source=4
=> [General]Add Incandescent Sliver trinket.

src/parser/priest/holy/modules/spells/azeritetraits/PrayerfulLitany.js
=> [HPriest] Prayerful Litany improvements

src/parser/priest/holy/modules/talents/45/GuardianAngel.js
GA was giving Guardian Spirit credit for 60% of all healing instead of healing on the target.
=> [HPriest] Fixing bug with GA

src/parser/warrior/arms/CHANGELOG.js, src/parser/warrior/arms/CombatLogParser.js, src/parser/warrior/arms/modules/core/SweepingStrikes.js, src/parser/warrior/arms/modules/features/Checklist/Module.js
Added a suggestion for Sweeping Strikes to always be cast before Colossus Smash/Warbreaker.
=> Arms Warrior - Sweeping Strikes

src/common/SPELLS/demonhunter.js, src/parser/demonhunter/havoc/CHANGELOG.js, src/parser/demonhunter/havoc/CombatLogParser.js, src/parser/demonhunter/havoc/modules/talents/BlindFury.js, src/parser/demonhunter/havoc/modules/talents/DemonicAppetite.js, src/parser/demonhunter/havoc/modules/talents/Felblade.js
Added the 3 talents and suggestions for them.
=> [Havoc DH] level 99 talents

src/common/SPELLS/demonhunter.js, src/parser/demonhunter/havoc/CHANGELOG.js, src/parser/demonhunter/havoc/CombatLogParser.js, src/parser/demonhunter/havoc/modules/Abilities.js, src/parser/demonhunter/havoc/modules/features/AlwaysBeCasting.js, src/parser/demonhunter/havoc/modules/features/Checklist/Component.js, src/parser/demonhunter/havoc/modules/talents/FelBarrage.js, src/parser/demonhunter/havoc/modules/talents/FelMastery.js, src/parser/demonhunter/havoc/modules/talents/TrailofRuin.js
=> [Havoc DH]Level 102 talents

src/parser/demonhunter/havoc/CHANGELOG.js, src/parser/demonhunter/havoc/modules/Abilities.js
Did a passover of all abilities and verified the correct spell id info. Added missing abilities. Updated gcds, cooldowns, suggestion thresholds/comments.
=> [Havoc DH] Updated abilities file

src/parser/demonhunter/havoc/modules/Abilities.js
Properly tracking the cast efficiency of blade dance outside of meta and death sweap during meta.
=> [Havok DH] Abilties fix

src/parser/shaman/enhancement/modules/Abilities.js
=> Fixing some enhancer spells

src/interface/others/MonkSpreadsheet.js, src/parser/monk/mistweaver/CHANGELOG.js, src/parser/monk/mistweaver/modules/features/Checklist/Component.js, src/parser/monk/mistweaver/modules/features/Checklist/Module.js, src/parser/monk/mistweaver/modules/talents/JadeSerpentStatue.js
New checklist item added for keep REM up when casting Vivify.
Also, quick bug fix for some spreadsheet import items.
=> [MW] New Checklist Item + Spreadsheet Import Fixes

src/parser/priest/holy/CombatLogParser.js, src/parser/priest/holy/modules/spells/GuardianSpirit.js, src/parser/priest/holy/modules/talents/45/GuardianAngel.js
This PR adds a new lazy loading module for Guardian Spirit and modifies Guardian Angel.
Before:
After:
=> [HPriest] Guardian spirit module

src/common/SPELLS/bfa/azeritetraits/monk.js, src/interface/others/MonkSpreadsheet.js, src/parser/monk/mistweaver/CHANGELOG.js, src/parser/monk/mistweaver/CombatLogParser.js, src/parser/monk/mistweaver/modules/spells/azeritetraits/SecretInfusion.js
Average stat gain from the Secret Infusion Azerite trait buff.
=> [MW] Secret Infusion Stat Gain

src/parser/mage/frost/CHANGELOG.js, src/parser/mage/frost/__snapshots__/CombatLogParser.test.js.snap, src/parser/mage/frost/modules/checklist/Component.js
I updated the Frost checklist to separate and better explain some of the core aspects of the frost rotation (Shattering Spells, and using GS properly)
=> [Frost Mage] Updated Checklist

src/parser/shaman/shared/maelstromchart/Maelstrom.js, src/parser/shaman/shared/maelstromchart/MaelstromTab.js
https://user-images.githubusercontent.com/2129161/53606343-cebd9e80-3bba-11e9-9133-181b7b713241.png
=> Fix shaman charts

src/parser/paladin/retribution/CONFIG.js, src/parser/paladin/retribution/CombatLogParser.js, src/parser/paladin/retribution/modules/Abilities.js, src/parser/paladin/retribution/modules/Buffs.js, src/parser/paladin/retribution/modules/core/ArtOfWar.js, src/parser/paladin/retribution/modules/core/Judgment.js, src/parser/paladin/retribution/modules/core/Retribution.js, src/parser/paladin/retribution/modules/core/ShieldOfVengeance.js, src/parser/paladin/retribution/modules/core/azeritetraits/RelentlessInquisitor.js, src/parser/paladin/retribution/modules/features/AlwaysBeCasting.js, src/parser/paladin/retribution/modules/features/Checklist/Component.js, src/parser/paladin/retribution/modules/holypower/HolyPowerDetails.js, src/parser/paladin/retribution/modules/talents/Crusade.js, src/parser/paladin/retribution/modules/talents/DivinePurpose.js, src/parser/paladin/retribution/modules/talents/Inquisition.js, src/parser/paladin/retribution/modules/talents/RighteousVerdict.js
Added Buffs.js Module.
Added Empyrean Power to Timeline.
Added Divine Purpose to Timeline.
Marked as updated for Patch 8.1.
Updated About Retribution Paladin and added Guide links.
Updated Righteous Verdict recommendation.
Updated AlwaysBeCasting recommendation.
Updated Judgment recommendation.
Capitalized Statistic Boxes for consistency.
Minor grammatical housekeeping and punctuation.
=> [Retribution Paladin] Timeline and Patch 8.1 Updates

src/common/SPELLS/shaman.js, src/parser/shaman/elemental/modules/features/StormFireElemental.js, src/parser/shaman/enhancement/CombatLogParser.js, src/parser/shaman/enhancement/modules/Abilities.js, src/parser/shaman/enhancement/modules/core/Stormbringer.js
Dunno what to add here really.
Purely a spell logic change that adds the resets from Stormbringer.
=> Stormbringer

src/parser/paladin/retribution/modules/Abilities.js, src/parser/paladin/retribution/modules/Buffs.js
Added Greater Blessing of Kings and Wisdom
Added Bloodlust to Timeline
=> [Retribution Paladin] Greater Blessings + Bloodlust

src/parser/mage/arcane/CHANGELOG.js, src/parser/mage/arcane/CombatLogParser.js, src/parser/mage/arcane/__snapshots__/CombatLogParser.test.js.snap, src/parser/mage/arcane/modules/features/Buffs.js, src/parser/mage/fire/CHANGELOG.js, src/parser/mage/fire/CombatLogParser.js, src/parser/mage/fire/__snapshots__/CombatLogParser.test.js.snap, src/parser/mage/fire/modules/features/Buffs.js, src/parser/mage/frost/CHANGELOG.js, src/parser/mage/frost/CombatLogParser.js, src/parser/mage/frost/__snapshots__/CombatLogParser.test.js.snap, src/parser/mage/frost/modules/features/Buffs.js
Adds mage spec buffs to the timeline.
=> [Mage] Add Buffs to Timeline

src/common/SPELLS/rogue.js, src/parser/rogue/outlaw/CombatLogParser.js, src/parser/rogue/outlaw/modules/core/RollTheBonesBuffs.js
=> Roll the bones buffs

src/parser/paladin/retribution/CombatLogParser.js, src/parser/paladin/retribution/modules/core/BladeofJustice.js, src/parser/paladin/retribution/modules/core/CrusaderStrike.js, src/parser/paladin/retribution/modules/core/Judgment.js, src/parser/paladin/retribution/modules/talents/Consecration.js, src/parser/paladin/retribution/modules/talents/HammerofWrath.js, src/parser/paladin/retribution/modules/talents/WakeofAshes.js
Updated Wake of Ashes to new event handlers and improved inefficient casts
Updated Judgment module to new event handlers and added inefficient casts
NEW: Consecration Talent Module- Highlight inefficient casts
NEW: Hammer of Wrath Talent Module- Highlight inefficient casts
NEW: Crusader Strike Module- Highlight inefficient casts
NEW: Blade of Justice Module- Highlight inefficient casts
New modules are very basic for now.
=> [Retribtuion Paladin]Basic Ability Modules + Updates

src/parser/shared/modules/DeathTracker.js
Added a link to Death recap per Issue #2307 
First PR Whoo!
=> You died suggestion: add a link to the death recap

src/parser/shaman/restoration/modules/azerite/BaseHealerAzerite.js
They're currently a bit messed up
After
=> [Next][Resto Shaman] Fixed look of Azerite panels

src/common/SPELLS/paladin.js, src/parser/paladin/retribution/CHANGELOG.js, src/parser/paladin/retribution/modules/talents/Consecration.js, src/parser/paladin/retribution/modules/talents/Crusade.js
Added Crusade inefficient casts based on Holy Power
Added CONSECRATION_DAMAGE to spellbook as it was missing
Added Consecration average hits per cast
Update changelog because I keep forgetting to update it
=> [Retribution Paladin] Crusade + Consecration Module Updates

src/parser/monk/mistweaver/CHANGELOG.js, src/parser/monk/mistweaver/modules/spells/azeritetraits/FontOfLife.js, src/parser/monk/mistweaver/modules/spells/azeritetraits/SecretInfusion.js, src/parser/monk/mistweaver/modules/spells/azeritetraits/UpliftedSpirits.js
Visual update of statistic boxes for the 3 Mistweaver Monk azerite traits implemented.
=> [MW] Azerite Trait Visual Updates

src/parser/monk/mistweaver/CHANGELOG.js, src/parser/monk/mistweaver/CombatLogParser.js, src/parser/monk/mistweaver/modules/features/Buffs.js
Added in a Buffs module to leverage the new buff highlighting on the timeline.
=> [MW] Buffs module implementation

src/parser/monk/mistweaver/modules/features/Checklist/Component.js
Added fort brew to defensive list
This spell was added as a defensive during nighthold
=> Added Fort brew

src/common/SPELLS/bfa/azeritetraits/__UNUSED.js, src/common/SPELLS/bfa/azeritetraits/hunter.js, src/parser/hunter/marksmanship/CHANGELOG.js, src/parser/hunter/marksmanship/CombatLogParser.js, src/parser/hunter/marksmanship/modules/spells/azeritetraits/InTheRhythm.js
Log: https://www.warcraftlogs.com/reports/PXZkCQYtbBwcANFf#fight=9&type=auras&target=8&ability=272733&view=events
=> [Hunter] Implement In The Rhythm Azerite Trait for Marksmanship hunters

src/interface/statistics/components/BoringNonSpellValueText/index.js, src/interface/statistics/components/BoringValueText/index.js, src/parser/mage/arcane/__snapshots__/CombatLogParser.test.js.snap, src/parser/mage/fire/__snapshots__/CombatLogParser.test.js.snap, src/parser/mage/frost/CHANGELOG.js, src/parser/mage/frost/__snapshots__/CombatLogParser.test.js.snap, src/parser/mage/frost/modules/features/AlwaysBeCasting.js, src/parser/mage/frost/modules/features/BrainFreeze.js, src/parser/mage/frost/modules/features/GlacialSpike.js, src/parser/mage/frost/modules/features/IceLance.js, src/parser/mage/frost/modules/features/WaterElemental.js, src/parser/mage/frost/modules/features/WintersChill.js, src/parser/mage/frost/modules/talents/BoneChilling.js, src/parser/mage/frost/modules/talents/LonelyWinter.js, src/parser/shared/modules/CancelledCasts.js
Updated the Frost Mage stats to the new Stats UI
Also created a new ValueText entry for non spells that accepts a standard label instead of a spell name.
Before
After
=> [Frost Mage] Updated Statistics

src/parser/monk/mistweaver/CHANGELOG.js, src/parser/monk/mistweaver/modules/talents/ManaTea.js
I know the changelog is not perfect so hit me with the more logical statement.
=> [MW] Mana Tea with Innervate

src/common/aprilFools.js, src/parser/priest/holy/modules/spells/SpiritOfRedemption.js
Adding a message that will only show up on the 1st of April.
=> [Hpriest] Adding super important suggestion

src/game/ZONES.js, src/interface/character/Parses.js
Updated the zones with the new raid and made it the default in the character selector.
=> Update character selector to new raid

src/common/SPELLS/bfa/azeritetraits/demonhunter.js, src/parser/demonhunter/havoc/CombatLogParser.js, src/parser/demonhunter/havoc/modules/spells/azeritetraits/ChaoticTransformation.js, src/parser/demonhunter/havoc/modules/spells/azeritetraits/EyesofRage.js, src/parser/demonhunter/havoc/modules/talents/BlindFury.js, src/parser/demonhunter/havoc/modules/talents/Demonic.js
=> DH Havoc Azerite traits

src/parser/shaman/elemental/CHANGELOG.js, src/parser/shaman/elemental/CombatLogParser.js, src/parser/shaman/elemental/modules/Abilities.js, src/parser/shaman/elemental/modules/Buffs.js, src/parser/shaman/elemental/modules/core/LavaSurge.js
Updating cooldowns and buffs for timeline.
Also added Lava Surge.
Will give some issues with Lava Surge resets that I can't pinpoint, but they are relatively rare it seems. 
http://localhost:3000/report/nZTJqfy67CXrb2tM/51-Heroic+Uu'nat,+Harbinger+of+the+Void+-+Kill+(6:10)/Kaldaek/timeline
=> Some fixes for the timeline

src/common/SPELLS/shaman.js, src/parser/shaman/restoration/modules/core/HealingEfficiencyTracker.js
=> [Restoration Shaman] Track Lava Burst damage

src/common/SPELLS/bfa/azeritetraits/druid.js, src/parser/druid/balance/CHANGELOG.js, src/parser/druid/balance/CombatLogParser.js, src/parser/druid/balance/modules/features/Checklist/Module.js, src/parser/druid/balance/modules/talents/azeritetraits/DawningSun.js, src/parser/druid/balance/modules/talents/azeritetraits/HighNoon.js, src/parser/druid/balance/modules/talents/azeritetraits/PowerOfTheMoon.js
This isn't finished but since its gonna be a few things I thought I'd make it early so if anyone wants to look over it they can. 
#2027 is the ticket that this is for.
Still need to add streaking stars and arcanic pulsar
=> Balance Druid Azerite

src/parser/monk/mistweaver/modules/features/StatValues.js
=> [MW] Enable QE Live Link for MW

src/parser/monk/mistweaver/CHANGELOG.js, src/parser/monk/mistweaver/modules/features/Checklist/Component.js, src/parser/monk/mistweaver/modules/features/Checklist/Module.js, src/parser/monk/mistweaver/modules/spells/SoothingMist.js
Finally got around to adding a soothing mist checker to see if you are casting spells during it or going afk during it.
=> New Soothing Mist Update

src/parser/deathknight/shared/RuneDetails.js, src/parser/deathknight/shared/RuneTracker.js
Fixed a bug where runes would be flagged as "finished recharging" after the fight ended. Resulting in data-points after fightend which showed up as the weird rune that travels back in time.
Old
New
=> [Death Knight] [Bug] Fix for Runetracker & Graph

src/parser/core/CombatLogParser.js, src/parser/shared/modules/items/bfa/raids/crucibleofstorms/HarbingersInscrutableWill.js
Adds the caster trinket "Harbinger's Inscrutable Will" from crucible of storms
Includes a suggestion for oblivion spears
Example log: https://www.warcraftlogs.com/reports/KkB8jL1HpwxV7NtT#fight=4&source=136
=> Harbingers inscrutable will

src/parser/core/CombatLogParser.js, src/parser/shared/modules/items/bfa/raids/crucibleofstorms/FathomDredgers.js
adds the cloth hands "fathom dredgers" from crucible of storms
Example log: https://www.warcraftlogs.com/reports/vZQfwra1xVK76M4L/#fight=13&source=6
=> Fathom dredgers

src/parser/core/CombatLogParser.js, src/parser/shared/modules/items/bfa/raids/crucibleofstorms/AbyssalSpeakersGauntlets.js
Adds the plate gloves "Abyssal Speaker's Gauntlets" from crucible of storms
Example log: https://www.warcraftlogs.com/reports/7bfnQGY8cKpT94RA#fight=11&source=18&translate=true
=> added abyssal speakers gauntlets

src/common/ITEMS/bfa/raids/bod/index.js, src/common/SPELLS/bfa/raids/battleofdazaralor/items.js, src/parser/core/CombatLogParser.js, src/parser/shared/modules/items/bfa/raids/bod/DiamondLacedReflectingPrism.js
Adds the tank trinket "Diamond-Laced Refracting Prism" from bod
Example log: https://www.warcraftlogs.com/reports/JQPygMZdB6LDcaRj#fight=18&source=8
=> added diamond-laced reflecting prism

src/parser/rogue/assassination/modules/features/Checklist/Component.js, src/parser/rogue/assassination/modules/talents/MasterAssassin.js
Small update, allowing use of TB in Vanish in opener.
This is the new theory.
=> [Assa Rogue]Small opener update

src/CHANGELOG.js
noticed I forgot to add the changelog entry for search
=> added search changelog entry

src/CHANGELOG.js, src/interface/others/Cooldown.js
updated PR for #3184 (for issue #3169) as discussed in discord
=> fix more info on cooldowns

src/interface/others/RestorationShamanSpreadsheet.js
adds damage / healing done and a nice big button to make life easier
=> [Restoration Shaman] Spreadsheet export update

src/CHANGELOG.js, src/common/SPELLS/bfa/essences/essences.js, src/common/SPELLS/bfa/essences/index.js, src/common/SPELLS/bfa/index.js, src/parser/core/CombatLogParser.js, src/parser/core/Combatant.js, src/parser/shared/modules/Haste.js, src/parser/shared/modules/spells/bfa/essences/TheEverRisingTide.js
general support for essences
to check if someone has a specific essence you have to use the spellIds kihra is using in his talent pane
including the ever rising tide essence as an example
=> Essence parsing & The Ever Rising Tide

src/CHANGELOG.js, src/common/SPELLS/bfa/essences/essences.js, src/parser/core/CombatLogParser.js, src/parser/shared/modules/spells/bfa/essences/TheCrucibleofFlame.js
=> Added crucible of the flame essence

src/parser/shared/modules/spells/bfa/essences/TheEverRisingTide.js
Only add the major ability and buff if the major is actually equipped
=> TheEverRisingTide fix

src/parser/druid/restoration/modules/talents/SoulOfTheForest.js
Caused the percentages to show 0%.
=> fixed a typo in suggestions

src/CHANGELOG.js, src/parser/shared/modules/spells/bfa/essences/TheCrucibleofFlame.js
See title, crucible of flame wasn't counting damage that got absorbed (aka any damage done during P1 of Lady Ashvane)
=> Fixed Crucible of Flame not accounting for absorbed damage

src/parser/monk/brewmaster/CHANGELOG.js, src/parser/monk/brewmaster/CONFIG.js, src/parser/monk/brewmaster/__snapshots__/CombatLogParser.test.js.snap, src/parser/monk/brewmaster/modules/constants/AbilityBlacklist.js, src/parser/monk/brewmaster/modules/constants/Mitigation.js
So many fucking dots and raid AoEs this tier >.<
=> [BrM] Updated hit-tracking blacklist and mitigation constants for EP

src/parser/paladin/retribution/CHANGELOG.js, src/parser/paladin/retribution/CONFIG.js, src/parser/paladin/retribution/modules/core/Judgment.js
-Added Execution Sentence consumptions to Judgment module.
=> [Ret Paladin] Judgment Module Update

src/common/SPELLS/warrior.js, src/parser/warrior/protection/CHANGELOG.js, src/parser/warrior/protection/CONFIG.js, src/parser/warrior/protection/modules/Abilities.js, src/parser/warrior/protection/modules/talents/BoomingVoice.js
Potentially not a full spell update but a good chunk
Tldr a good few people are planning on working on this so there will be small updates coming through the pipeline
=> [Prot Warrior] Spell update

src/CHANGELOG.js, src/parser/shared/modules/items/HealthPotion.js
Filled the order so it will show Abyssal's icon
=> Flipped order

package-lock.json, src/CHANGELOG.js, src/CONTRIBUTORS.js, src/articles/2018-08-03-DevotionAura/index.js, src/interface/Header.scss, src/interface/home/Page.js, src/interface/layout/Panel.scss, src/interface/news/News.scss, src/interface/news/index.js
Previously the header for news and the twitter link was on the right (which looks good on desktop) on mobile (making it go off screen, and as such causing a horizontal scrollbar).
I have now updated this header and the twitter link to stay within the container, so that it doesn't cause scrolling to the right on smaller devices. Which should improve responsiveness on the news section when viewing in mobile.
=> updated news header to stay within the "container" on mobile

.env, src/parser/monk/mistweaver/CHANGELOG.js, src/parser/monk/mistweaver/CONFIG.js
Changes wow's current patch to 8.2 and mw's compatibility to it too
=> everything to 8.2

src/parser/mage/arcane/CHANGELOG.js, src/parser/mage/arcane/CONFIG.js, src/parser/mage/fire/CHANGELOG.js, src/parser/mage/fire/CONFIG.js, src/parser/mage/fire/CombatLogParser.js, src/parser/mage/fire/__snapshots__/CombatLogParser.test.js.snap, src/parser/mage/fire/modules/Checklist/Component.js, src/parser/mage/fire/modules/Checklist/Module.js, src/parser/mage/fire/modules/features/HotStreakPreCasts.js, src/parser/mage/fire/modules/features/Meteor.js, src/parser/mage/frost/CHANGELOG.js, src/parser/mage/frost/CONFIG.js
Made the following changes
- Updated all three specs to 8.2 compatibility (nothing changed in 8.2)
- Added analysis for Meteor
- Reworded the HotStreak pre casts suggestion as many people were not understanding it.
=> [Mage] Compatibility Update, Suggestion Reword, Meteor Analysis

src/common/SPELLS/bfa/azeritetraits/demonhunter.js, src/parser/demonhunter/havoc/CHANGELOG.js, src/parser/demonhunter/havoc/CombatLogParser.js, src/parser/demonhunter/havoc/modules/spells/azeritetraits/RevolvingBlades.js
- Added documentation to explain Revolving Blades
- Added dps contribution for Revolving Blades
- Added dps contribution for Revolving Blades to overall damage
/report/TYfHayb1nxkDtKVJ/9-Heroic+Queen+Azshara+-+Kill+(7:23)/Flourishing/statistics
=> Add damage component of Revolving Blades

src/parser/monk/mistweaver/CHANGELOG.js, src/parser/monk/mistweaver/modules/talents/ManaTea.js
Make it so we return a number vs NaN
Before
After
=> Mistweaver NaN check

src/common/ITEMS/bfa/dungeons/index.js, src/common/SPELLS/bfa/dungeons/items.js, src/parser/mage/fire/CHANGELOG.js, src/parser/mage/fire/CombatLogParser.js, src/parser/mage/fire/__snapshots__/CombatLogParser.test.js.snap, src/parser/mage/fire/modules/features/Abilities.js, src/parser/mage/fire/modules/features/Meteor.js, src/parser/mage/fire/modules/items/HyperthreadWristwraps.js
Adds support for Hyperthread Wristwraps. Also threw in a bug fix for Meteor to name the class correctly.
=> [Fire Mage] Hyperthread Wristwraps

src/CHANGELOG.js, src/parser/shared/modules/items/bfa/raids/crucibleofstorms/VoidStone.js, src/parser/shared/normalizers/PrePullCooldowns.js
fixes prepull voidstone casts crashing the voidstone module
=> Fix prepull voidstone

src/parser/mage/fire/CHANGELOG.js, src/parser/mage/fire/modules/features/CombustionFirestarter.js, src/parser/mage/fire/modules/features/HeatingUp.js, src/parser/mage/fire/modules/features/HotStreakPreCasts.js, src/parser/mage/fire/modules/features/SearingTouch.js
Fix for the single line if statements that zero hates.
=> [Fire Mage] Code style fix

src/common/SPELLS/bfa/azeritetraits/warrior.js, src/parser/warrior/protection/CHANGELOG.js, src/parser/warrior/protection/CONFIG.js, src/parser/warrior/protection/CombatLogParser.js, src/parser/warrior/protection/modules/azerite/BraceForImpact.js, src/parser/warrior/protection/modules/features/Checklist/Component.js, src/parser/warrior/protection/modules/features/Checklist/Module.js, src/parser/warrior/protection/modules/features/CooldownThroughputTracker.js, src/parser/warrior/protection/modules/spells/ShieldBlock.js, src/parser/warrior/protection/modules/spells/ShieldBlockMit.js, src/parser/warrior/protection/modules/spells/ShieldBlockMitigation.js, src/parser/warrior/protection/modules/talents/AngerCD.js, src/parser/warrior/protection/modules/talents/HeavyRepercussions.js
Massive update that has changed
-Thresh holds to humanly possible values
-New method of checking if shield block was good or wasted
-Updated cd times for visions
-Updated config
-Renamed ShieldBlock to ShieldBlockMit for my sanity
-Moved the dial for patch compatibility
-Added Brace For Impact azerite infographic
=> [Prot Warrior] Big update

src/parser/mage/fire/CHANGELOG.js, src/parser/mage/fire/modules/items/LucidDreams.js
Fixes a bug that caused the module to crash.
=> [Fire Mage] Bug Fix for Lucid Dreams

src/common/SPELLS/shaman.js, src/common/SPELLS/talents/shaman.js, src/parser/core/CASTS_THAT_ARENT_CASTS.js, src/parser/shaman/restoration/CHANGELOG.js, src/parser/shaman/restoration/CONFIG.js, src/parser/shaman/restoration/normalizers/CloudburstNormalizer.js
Some 8.2 changes and made the cloudburst normalizer slightly more robust
=> [Restoration Shaman] Minor adjustments

src/CHANGELOG.js, src/common/SPELLS/bfa/enchants.js, src/parser/core/CombatLogParser.js, src/parser/shared/modules/items/bfa/enchants/ForceMultiplier.js
Can give haste, was fucking with spell CD tracking.
=> Added Force Multiplier Enchant

src/parser/monk/windwalker/CHANGELOG.js, src/parser/monk/windwalker/modules/features/checklist/Component.js, src/parser/monk/windwalker/modules/features/checklist/Module.js, src/parser/monk/windwalker/modules/spells/SpinningCraneKick.js
Suggestions regarding bad casts were inaccurate and misleading, and have therefore been removed
=> [Windwalker] Update Spinning Crane Kick

src/parser/warrior/protection/CHANGELOG.js, src/parser/warrior/protection/CombatLogParser.js, src/parser/warrior/protection/modules/azerite/BraceForImpact.js, src/parser/warrior/protection/modules/features/BlockCheck.js, src/parser/warrior/protection/modules/features/Checklist/Module.js, src/parser/warrior/protection/modules/talents/AngerCD.js
Threshold changes as the old ones were outdated.
Moved file to a new location as it is more logical.
Brace for Impact infographic changed to m:ss from m:ss.sss
Brace for impact bug fixed
=> [Prot warrior] Last update till release maybe

src/CHANGELOG.js, src/CONTRIBUTORS.js, src/parser/mage/arcane/CHANGELOG.js, src/parser/mage/arcane/modules/ManaChart/TabComponent/ManaLevelGraph.js, src/parser/mage/arcane/modules/ManaChart/TabComponent/index.js
The offset time was not being passed through all the way.
=> Fix for issue #3313: Arcane mage mana level graph x-axis shows NaN for each label.

src/parser/shaman/restoration/CHANGELOG.js, src/parser/shaman/restoration/CONFIG.js, src/parser/shaman/restoration/modules/talents/Deluge.js
=> [Restoration Shaman] Add Deluge 8.2.5 change

.env, src/parser/monk/brewmaster/CHANGELOG.js, src/parser/monk/brewmaster/CONFIG.js, src/parser/monk/mistweaver/CHANGELOG.js, src/parser/monk/mistweaver/CONFIG.js, src/parser/warrior/protection/CHANGELOG.js, src/parser/warrior/protection/CONFIG.js
This just updates the env variable to 8.2.5 and moves 3 specs up to that, MW, Brewmaster, and prot warrior
=> Everything to 8.2.5

src/parser/warrior/protection/CHANGELOG.js, src/parser/warrior/protection/CONFIG.js, src/parser/warrior/protection/modules/features/Checklist/Component.js, src/parser/warrior/protection/modules/talents/AngerCD.js
We are finally ready to be supported
Last changes are a prepull checker for avatar as our fabricated events doesn't capture it as we don't see they have the buff before pull, and removing stormbolt from the checklist
=> [Prot Warrior] Supported finally

src/CHANGELOG.js, src/common/SPELLS/bfa/raids/azsharaseternalpalace/mechanics.js, src/raids/azsharaseternalpalace/Orgozoa.js, src/raids/azsharaseternalpalace/QueenAzshara.js, src/raids/azsharaseternalpalace/ZaqulHarbringerOfNyalotha.js
Updated phase transitions for Orgozoa, Za'qul, and Queen Azshara to be more accurate and to leverage the new phase filters that Zeboot added.
=> [Core] Updated Phase Transitions

src/parser/monk/windwalker/CHANGELOG.js, src/parser/monk/windwalker/CONFIG.js, src/parser/monk/windwalker/modules/features/checklist/Component.js, src/parser/monk/windwalker/modules/resources/ChiTracker.js, src/parser/monk/windwalker/modules/spells/BlackoutKick.js, src/parser/monk/windwalker/modules/spells/ReverseHarm.js, src/parser/monk/windwalker/modules/spells/SpinningCraneKick.js, src/parser/monk/windwalker/modules/spells/TouchOfDeath.js
Old code was really messy and not surprisingly, gave inaccurate results.
Squeezing a few small edits in there with it, and there will be more refactoring PRs coming after this one.
=> [Windwalker] Update Spinning Crane Kick module and refactoring

src/parser/mage/fire/CHANGELOG.js, src/parser/mage/fire/__snapshots__/CombatLogParser.test.js.snap, src/parser/mage/fire/modules/features/HeatingUp.js, src/parser/mage/fire/modules/features/HotStreak.js, src/parser/mage/fire/modules/features/Meteor.js, src/parser/mage/fire/modules/features/Pyroclasm.js, src/parser/mage/fire/modules/traits/BlasterMaster.js
Updated the Fire Statistic Boxes to the new format.
I skipped Hot Streak Pre Casts as im going to work on merging that into Hot Streak so they can share a stat box in a separate PR
=> [Fire Mage] Updated Statistic Boxes

src/parser/shared/modules/racials/bloodelf/ArcaneTorrent.js, src/parser/warrior/protection/CHANGELOG.js, src/parser/warrior/protection/CombatLogParser.js
Exactly what it says up top (for prot warriors only)
=> [Prot Warrior] Removed arcane torrent suggestion

src/parser/mage/fire/CHANGELOG.js, src/parser/mage/fire/modules/features/Meteor.js
There is a slight delay between Rune of Power being cast and the buff getting applied to you, so if you cast Rune of Power and Meteor at the same time (which is common), then the meteor cast will happen before the buff gets applied
=> [Fire Mage] Meteor Fix (again)

src/CHANGELOG.js, src/parser/deathknight/blood/__snapshots__/CombatLogParser.test.js.snap, src/parser/mage/arcane/__snapshots__/CombatLogParser.test.js.snap, src/parser/mage/fire/__snapshots__/CombatLogParser.test.js.snap, src/parser/mage/frost/__snapshots__/CombatLogParser.test.js.snap, src/parser/monk/brewmaster/__snapshots__/CombatLogParser.test.js.snap, src/parser/paladin/holy/__snapshots__/CombatLogParser.test.js.snap, src/parser/paladin/protection/__snapshots__/CombatLogParser.test.js.snap, src/parser/shared/modules/CastEfficiency.js
Reverts WoWAnalyzer/WoWAnalyzer#3340
=> Revert "[Core] Cast Efficiency Fix"

src/CONTRIBUTORS.js, src/parser/warrior/protection/CHANGELOG.js, src/parser/warrior/protection/CombatLogParser.js, src/parser/warrior/protection/modules/features/Checklist/Component.js, src/parser/warrior/protection/modules/features/Checklist/Module.js, src/parser/warrior/protection/modules/spells/SpellReflect.js
Changed Spell Reflect to not be cast efficiency but rather did you use during magic damage.
=> [PROT Warrior]Spell Reflect damage calc

src/parser/mage/arcane/__snapshots__/CombatLogParser.test.js.snap, src/parser/mage/fire/CHANGELOG.js, src/parser/mage/fire/__snapshots__/CombatLogParser.test.js.snap, src/parser/mage/fire/modules/features/HotStreak.js, src/parser/mage/fire/modules/features/HotStreakPreCasts.js, src/parser/mage/fire/modules/features/Kindling.js, src/parser/mage/fire/modules/features/SearingTouch.js, src/parser/mage/shared/modules/features/RuneOfPower.js
Combined the Hot Streak and Hot Streak Pre Casts Stat Boxes
Added Stat Boxes for Kindling and Searing Touch
Fixed the Rune of Power Stat Box so it actually displays, and updated it to the new Stat Box design.
=> [Fire Mage] Stat Box Tweaks

src/CHANGELOG.js, src/common/ITEMS/bfa/raids/azsharaseternalpalace/index.js, src/common/ITEMS/bfa/raids/index.js, src/common/SPELLS/bfa/raids/azsharaseternalpalace/items.js, src/parser/core/CombatLogParser.js, src/parser/shared/modules/items/bfa/raids/azsharaseternalpalace/DribblingInkpod.js
I know I'm a bit late in the tier on this (dont hit me @abelito75 ), been a crazy couple months. Anyways here's the dribbling inkpod.
=> Dribbling Inkpod

src/CHANGELOG.js, src/common/ITEMS/bfa/raids/azsharaseternalpalace/index.js, src/common/SPELLS/bfa/raids/azsharaseternalpalace/items.js, src/parser/core/CombatLogParser.js, src/parser/shared/modules/items/bfa/raids/azsharaseternalpalace/BloodthirstyUrchin.js
Example log: https://www.warcraftlogs.com/reports/9hL1MGxnC6TXPRKt#fight=19&source=1&type=healing
=> Bloodthirsty Urchin

src/parser/monk/mistweaver/CHANGELOG.js, src/parser/monk/mistweaver/modules/talents/Tier45Comparison.js
=> [MW] T45 Tool Spelling corrections

src/parser/monk/brewmaster/CHANGELOG.js, src/parser/monk/brewmaster/CombatLogParser.js, src/parser/monk/brewmaster/__snapshots__/CombatLogParser.test.js.snap
Brewmasters have more energy than they can spend right now, so this suggestion is not very helpful.
=> Removed Arcane Torrent from BrM suggestions

src/CHANGELOG.js
=> Fixed a typo in the changelog

src/parser/shaman/elemental/CHANGELOG.js, src/parser/shaman/elemental/modules/talents/SurgeOfPower.js
https://wowanalyzer.com/report/v8rFnBVacpR1KJfD/18-Mythic+Orgozoa+-+Kill+(6:50)/Tarzhaman
=> [Elemental SoP]Fix percentage formatting

src/common/ITEMS/bfa/raids/azsharaseternalpalace/index.js, src/common/SPELLS/bfa/azeritetraits/general.js, src/common/SPELLS/bfa/raids/azsharaseternalpalace/items.js, src/parser/monk/brewmaster/CHANGELOG.js, src/parser/monk/brewmaster/modules/spells/CelestialFortune.js, src/parser/monk/mistweaver/CHANGELOG.js, src/parser/monk/mistweaver/modules/talents/RisingMist.js
Shows item names and icons as well to having a link to the item on wowhead. #3372
Also snuck in adding UT in general so we could include that :)
before:
after:
=> [Brew] Items for Celestial Fortunes

src/parser/paladin/retribution/CHANGELOG.js, src/parser/paladin/retribution/CONFIG.js, src/parser/paladin/retribution/modules/Abilities.js
also updated patch compatibility and example report
=> [Retribution] Updated cooldown calculations for Avenging Wrath and Crusade when using Strive for Perfection.

src/parser/warrior/protection/CHANGELOG.js, src/parser/warrior/protection/modules/spells/ShieldBlock.js
If shield block was casted before the fight begin the modules would die. (warcraft doesn't have shield block as a prepullbuff)
=> Protwarrior Bug fix

src/parser/monk/mistweaver/CHANGELOG.js, src/parser/monk/mistweaver/CombatLogParser.js, src/parser/monk/mistweaver/modules/talents/Upwelling.js
Added a statistic for upwelling the talent. The upwelling talent provides a stacking buff that is invisible so basically a steal of the essence font modules had to be done.
=> [MW] Upwelling

src/common/SPELLS/mage.js, src/parser/mage/fire/CHANGELOG.js, src/parser/mage/fire/CombatLogParser.js, src/parser/mage/fire/__snapshots__/CombatLogParser.test.js.snap, src/parser/mage/fire/modules/Checklist/Component.js, src/parser/mage/fire/modules/Checklist/Module.js, src/parser/mage/fire/modules/features/Abilities.js, src/parser/mage/fire/modules/features/Meteor.js, src/parser/mage/fire/modules/features/MeteorCombustion.js, src/parser/mage/fire/modules/features/MeteorRune.js
- Disabled the Cast Efficiency Suggestion for Meteor
- Calculated an adjusted efficiency % for Meteor
- Added a check to see if Meteor was cast in every Combustion
- Separated all the Meteor checks into separate modules (Meteor, MeteorRune, and MeteorCombustion
=> [Fire Mage] Meteor Enhancements

src/parser/monk/mistweaver/CHANGELOG.js, src/parser/monk/mistweaver/modules/spells/ThunderFocusTea.js, src/parser/monk/mistweaver/modules/spells/Vivify.js
No change in function just how we listen
=> [MW] New listeners :)

src/parser/monk/mistweaver/CHANGELOG.js, src/parser/monk/mistweaver/modules/talents/RisingMist.js
Added uplift's cooldown reduction to rising mist. Its easier to include it in here rather than parse it out in uplift itself. (rising mist is a talent and uplift is azerite)
=> [MW] Rising Mist additions

src/parser/deathknight/frost/CHANGELOG.js, src/parser/deathknight/frost/modules/features/AlwaysBeCasting.js, src/parser/deathknight/frost/modules/features/FrostFeverUptime.js, src/parser/deathknight/frost/modules/features/HardHowlingBlastCasts.js, src/parser/deathknight/frost/modules/runicpower/RunicPowerDetails.js, src/parser/deathknight/frost/modules/talents/GatheringStorm.js, src/parser/deathknight/shared/RuneTracker.js
Feel like this one is self explanatory.  Just aiming to clear the deprecation warnings
=> [Frost Death Knight] Update statistic order to use new way

src/parser/shaman/elemental/CHANGELOG.js, src/parser/shaman/elemental/CombatLogParser.js, src/parser/shaman/elemental/modules/talents/CallTheThunder.js, src/parser/shaman/shared/maelstromchart/Maelstrom.js
The numbers here are pretty hand wavy but I wanted something here for the talent to call it supported.
=> Add the nearly useless call the thunder statistic that I wrote for ele months ago.

src/parser/monk/mistweaver/CHANGELOG.js, src/parser/monk/mistweaver/CombatLogParser.js, src/parser/monk/mistweaver/modules/features/EssenceFontHealingBreakdown.js
=> [MW] Cool new infographic

src/parser/shaman/restoration/CHANGELOG.js, src/parser/shaman/restoration/modules/talents/EarthenWallTotem.js
fixes <https://wowanalyzer.com/report/gazDXYPN9yRtAm1C/9-Mythic+Abyssal+Commander+Sivara+-+Kill+(5:31)/Erobasso/> issue
=> [Resto Shaman] EWT prepull bug fix

src/CHANGELOG.js, src/CONTRIBUTORS.js, src/parser/shaman/elemental/__snapshots__/CombatLogParser.test.js.snap, src/parser/shared/modules/earlydotrefreshes/EarlyDotRefreshes.js
The sign was flipped having the opposite
effect than was intended.
=> Fix early DoT refresh extension check

src/CHANGELOG.js, src/parser/shaman/elemental/CONFIG.js
Just in time for 8.3 :) Thankfully almost nothing is changing for ele.
The only other items I want to update are our storm elemental usage but those sims haven't been officially done so....that will have to wait.
=> Ele shaman 8.2.5 readiness + new sample report

src/parser/mage/arcane/CHANGELOG.js, src/parser/mage/arcane/CONFIG.js
No changes for Arcane Mage in 8.3. Updating spec compatibility to 8.3
=> [Arcane Mage] Updated Compatibility to 8.3

src/parser/deathknight/frost/CHANGELOG.js, src/parser/deathknight/frost/CONFIG.js
=> [Frost Death Knight] Update spec compatibility to 8.3

src/parser/hunter/beastmastery/CHANGELOG.js, src/parser/hunter/beastmastery/modules/Buffs.tsx, src/parser/hunter/beastmastery/modules/checklist/Module.js, src/parser/hunter/beastmastery/modules/features/AlwaysBeCasting.tsx, src/parser/hunter/beastmastery/modules/spells/BarbedShot.tsx, src/parser/hunter/beastmastery/modules/spells/BeastCleave.tsx, src/parser/hunter/beastmastery/modules/spells/CobraShot.tsx, src/parser/hunter/beastmastery/modules/spells/azeritetraits/DanceOfDeath.js, src/parser/hunter/beastmastery/modules/spells/azeritetraits/FeedingFrenzy.js, src/parser/hunter/beastmastery/modules/spells/azeritetraits/HazeOfRage.js, src/parser/hunter/beastmastery/modules/spells/azeritetraits/PrimalInstincts.js, src/parser/hunter/beastmastery/modules/talents/KillerCobra.tsx, src/parser/hunter/beastmastery/modules/talents/KillerInstinct.tsx, src/parser/hunter/beastmastery/modules/talents/OneWithThePack.tsx, src/parser/hunter/beastmastery/modules/talents/ScentOfBlood.tsx, src/parser/hunter/beastmastery/modules/talents/SpittingCobra.tsx, src/parser/hunter/beastmastery/modules/talents/Stampede.tsx, src/parser/hunter/beastmastery/modules/talents/Stomp.tsx, src/parser/hunter/beastmastery/modules/talents/ThrillOfTheHunt.tsx, src/parser/hunter/beastmastery/modules/talents/VenomousBite.tsx, src/parser/hunter/marksmanship/CHANGELOG.js, src/parser/hunter/shared/modules/talents/AMurderOfCrows.tsx, src/parser/hunter/shared/modules/talents/Barrage.tsx, src/parser/hunter/shared/modules/talents/BindingShot.tsx, src/parser/hunter/shared/modules/talents/BornToBeWild.tsx, src/parser/hunter/shared/modules/talents/NaturalMending.tsx, src/parser/hunter/shared/modules/talents/Trailblazer.tsx, src/parser/hunter/survival/CHANGELOG.js
Nothing major here. 
I noticed the changelog entries are weird - I've updated them to be proper dates in a future commit, so they'll be in a PR right after this merges 😓
=> [Hunter] Talents to TypeScript, reformatting and updating to 8.3

src/parser/shaman/restoration/CHANGELOG.js, src/parser/shaman/restoration/CONFIG.js, src/parser/shaman/restoration/CombatLogParser.js, src/parser/shaman/shared/azerite/NaturalHarmony.js
=> [Restoration Shaman] Add Natural Harmony Azerite to RShaman

src/CHANGELOG.js, src/common/SPELLS/bfa/corruption/corruption.js, src/parser/core/CombatLogParser.js, src/parser/shared/modules/spells/bfa/corruptions/Siphoner.js, src/parser/shared/modules/spells/bfa/corruptions/Siphoner.tsx
=> Siphoner Corruption

src/CHANGELOG.js, src/common/SPELLS/bfa/corruption/corruption.js, src/parser/core/CombatLogParser.js, src/parser/shared/modules/spells/bfa/corruptions/VoidRitual.tsx
=> Corruption: Void Ritual

.idea/vcs.xml, src/CHANGELOG.js, src/parser/hunter/beastmastery/CHANGELOG.js, src/parser/hunter/beastmastery/modules/core/Focus.js, src/parser/hunter/shared/modules/resources/FocusCapTracker.js, src/parser/hunter/shared/modules/resources/FocusDetails.js, src/parser/hunter/shared/modules/resources/FocusTracker.js, src/parser/shared/modules/resourcetracker/ResourceSuggest.js, src/raids/nyalothathewakingcity/TheProphetSkitra.js
=> Minor changes to Focus and warning on Skitra

scripts/require-changelog-entry.js
This should allow for .tsx changelog entries.
=> Allow TSX formats in Changelogs

src/CHANGELOG.js, src/common/ITEMS/bfa/raids/nyalothathewakingcity/index.js, src/common/SPELLS/bfa/raids/nyalothathewakingcity/items.js, src/parser/core/CASTS_THAT_ARENT_CASTS.js, src/parser/core/CombatLogParser.js, src/parser/shared/modules/items/bfa/raids/nyalothathewakingcity/ForbiddenObsidianClaw.tsx, src/parser/shared/modules/items/bfa/raids/nyalothathewakingcity/HummingBlackDragonscale.tsx
=> [Items] Humming Black Dragonscale & Forbidden Obsidian Claw

src/CHANGELOG.js, src/common/SPELLS/bfa/essences/essences.js, src/parser/core/CombatLogParser.js, src/parser/shared/modules/spells/bfa/essences/TheFormlessVoid.js
=> Formless Void minor essence

src/parser/hunter/marksmanship/CHANGELOG.js, src/parser/hunter/shared/modules/resources/FocusCapTracker.js, src/parser/hunter/shared/modules/resources/SpellFocusCost.js
Don't need the DT check here anymore.
=> Minor adjustment to focus again

src/parser/warrior/fury/CHANGELOG.js, src/parser/warrior/fury/CombatLogParser.js, src/parser/warrior/fury/modules/features/Buffs.js, src/parser/warrior/fury/modules/features/checklist/Component.js, src/parser/warrior/fury/modules/features/checklist/Module.js, src/parser/warrior/fury/modules/talents/Siegebreaker.js
Check if you cast siege breaker inside of recklessness, highlight it on the timeline, also why not lets add bad recklessness casts if you have siege breaker active
=> [Fury] Siegebreaker inside of recklessness

src/parser/warrior/fury/CHANGELOG.js, src/parser/warrior/fury/modules/talents/Siegebreaker.js
=> [fury] fixed a typo

src/common/SPELLS/warrior.js, src/parser/warrior/fury/CHANGELOG.js, src/parser/warrior/fury/CombatLogParser.js, src/parser/warrior/fury/modules/features/checklist/Component.js, src/parser/warrior/fury/modules/features/checklist/Module.js, src/parser/warrior/fury/modules/spells/Whirlwind.js
checks to see if whirlwind is the only ability up OR it hit 2 or more targets while you didn't have the buff... events are also dum so you get the buff BEFORE you have a cast event for it
=> [Fury] Whirlwind cast validator

src/CHANGELOG.js, src/common/ITEMS/bfa/crafted/index.js, src/common/SPELLS/others.js, src/parser/core/CombatLogParser.js, src/parser/shared/modules/items/bfa/Ashjrakamas.js
=> Ashjra'kamas, Shroud of Resolve

src/common/SPELLS/bfa/azeritetraits/shaman.js, src/parser/shaman/elemental/CHANGELOG.js, src/parser/shaman/elemental/CombatLogParser.js, src/parser/shaman/enhancement/CHANGELOG.js, src/parser/shaman/enhancement/CombatLogParser.js, src/parser/shaman/restoration/CHANGELOG.js, src/parser/shaman/restoration/CombatLogParser.js, src/parser/shaman/restoration/modules/Abilities.js, src/parser/shaman/shared/azerite/AncestralResonance.js
closes #2009 as the last trait in that list isn't really interesting
=> Ancestral resonance

src/parser/paladin/holy/modules/azeritetraits/VisionOfPerfection.js, src/parser/shaman/restoration/CHANGELOG.js, src/parser/shaman/restoration/modules/azerite/essences/VisionOfPerfection.js
=> [RShaman] VoP pet filter

src/parser/paladin/retribution/CHANGELOG.js, src/parser/paladin/retribution/modules/talents/Inquisition.js
Update the statistic to show holy power used and duration remaining. 
The do not merge yet is another person has created this as well but we are going to compare and take the best one.
#3054 
[updated](https://user-images.githubusercontent.com/25177817/76156788-44612200-60cd-11ea-91f8-b1e8fcaa30d7.png)
=> [RET] Inquisition Statistic updated DO NOT MERGE YET

src/parser/druid/restoration/CHANGELOG.js, src/parser/druid/restoration/modules/essences/VisionsOfPerfection.js
Small update... plus plz rebuild since it died last time
=> Resto druid VOP

src/parser/warrior/fury/CHANGELOG.js, src/parser/warrior/fury/CONFIG.js, src/parser/warrior/fury/modules/Abilities.js
Depending on how many of these traits you have changes the prio of blood thirst.
=> [Fury] Cold Steel Hot Blood

src/CHANGELOG.js, src/common/SPELLS/bfa/essences/essences.js, src/parser/core/CombatLogParser.js, src/parser/deathknight/frost/integrationTests/example.test.ts.snap, src/parser/mage/frost/integrationTests/example.test.ts.snap, src/parser/shaman/elemental/integrationTests/example.test.ts.snap, src/parser/shared/modules/spells/bfa/azeritetraits/OverwhelmingPower.js, src/parser/shared/modules/spells/bfa/essences/BloodOfTheEnemy.js, src/parser/shared/modules/spells/bfa/essences/EssenceOfTheFocusingIris.js
Blood of the Enemy goes FROM: 
TO:
=> Essence of the Focusing Iris + Blood of the Enemy

src/common/SPELLS/bfa/azeritetraits/monk.js, src/parser/monk/mistweaver/CHANGELOG.js, src/parser/monk/mistweaver/CombatLogParser.js, src/parser/monk/mistweaver/modules/spells/azeritetraits/MistyPeaks.js
Adds average haste gained statistic from Misty Peaks azerite trait.
=> [MW] Misty Peaks average haste statistic

src/parser/shaman/restoration/CHANGELOG.js, src/parser/shaman/restoration/modules/talents/HighTide.js
buffs that ran out with the cast but before the heals happened weren't being counted
=> [RShaman] High Tide bug fix

src/CHANGELOG.js
=> Fix putput stuff

src/parser/mage/frost/CHANGELOG.js, src/parser/mage/frost/modules/features/BrainFreezeNoIL.js
Resolved an issue in BrainFreezeNoIL that was causing the module to crash.
=> [Frost Mage] Fix Module Crash in BrainFreeze for NoIL

src/common/SPELLS/deathknight.js, src/parser/deathknight/frost/CHANGELOG.js, src/parser/deathknight/frost/integrationTests/example.test.ts.snap, src/parser/deathknight/frost/modules/Abilities.js, src/parser/deathknight/frost/modules/features/HardHowlingBlastCasts.js, src/parser/deathknight/frost/modules/features/KillingMachine.js, src/parser/deathknight/frost/modules/features/checklist/Component.js, src/parser/deathknight/shared/RuneTracker.js
Fixed some minor issues with the spec and added the talent granted by conflict and strife as its been seeing decent use lately
=> [Frost Death Knight] Minor fixes

src/parser/mage/arcane/CHANGELOG.js, src/parser/mage/arcane/modules/features/Buffs.js, src/parser/mage/fire/CHANGELOG.tsx, src/parser/mage/fire/modules/features/Buffs.tsx, src/parser/mage/frost/CHANGELOG.tsx, src/parser/mage/frost/integrationTests/example.test.ts.snap, src/parser/mage/frost/modules/features/Buffs.tsx
Fixes #3521 
Not sure when this broke...
=> [Mage] Fix pre-pull detection for cooldowns by adding triggeredBySpellId to Buffs

src/parser/hunter/beastmastery/modules/Buffs.tsx, src/parser/hunter/beastmastery/modules/core/SpellUsable.tsx, src/parser/hunter/beastmastery/modules/spells/AspectOfTheWild.tsx, src/parser/hunter/marksmanship/CombatLogParser.tsx, src/parser/hunter/marksmanship/modules/Buffs.tsx, src/parser/hunter/marksmanship/modules/core/SpellUsable.tsx, src/parser/hunter/shared/modules/talents/AMurderOfCrows.tsx, src/parser/hunter/survival/CHANGELOG.tsx, src/parser/hunter/survival/CombatLogParser.tsx, src/parser/hunter/survival/modules/Abilities.tsx, src/parser/hunter/survival/modules/Buffs.tsx, src/parser/hunter/survival/modules/spells/CoordinatedAssault.tsx, src/parser/hunter/survival/modules/spells/SerpentSting.tsx, src/parser/hunter/survival/modules/spells/WildfireBomb.tsx, src/parser/hunter/survival/modules/talents/Chakrams.tsx, src/parser/hunter/survival/modules/talents/MongooseBite.tsx, src/parser/hunter/survival/modules/talents/SteelTrap.tsx, src/parser/hunter/survival/modules/talents/VipersVenom.tsx
https://www.warcraftlogs.com/reports/6x8VpvqdJNcf9bQX/#fight=8&source=15
Old: 
New: 
No suggestions
Old:
New: 
Old without errors:
New without errors (now with errors):
Log: https://www.warcraftlogs.com/reports/6x8VpvqdJNcf9bQX/#fight=4&source=15
Old with errors:
New with errors:
=> [Survival] Update Vipers Venom and Serpent Sting logic

src/parser/hunter/beastmastery/CHANGELOG.tsx, src/parser/hunter/beastmastery/CombatLogParser.tsx, src/parser/hunter/beastmastery/modules/checklist/Component.tsx, src/parser/hunter/beastmastery/modules/checklist/Module.tsx, src/parser/hunter/beastmastery/modules/pets/basicAttacksTracker.tsx
=> [Hunter] Add a pet basic attack tracking module

src/parser/hunter/marksmanship/CHANGELOG.tsx, src/parser/mage/frost/modules/features/BrainFreezeNoIL.tsx, src/parser/shared/modules/Enemies.js, src/parser/shared/modules/EnemyInstances.js
=> Set debug to false in any file that has it true

src/parser/hunter/beastmastery/CHANGELOG.tsx, src/parser/hunter/beastmastery/modules/pets/basicAttacksTracker.tsx, src/parser/hunter/beastmastery/modules/spells/AspectOfTheWild.tsx, src/parser/hunter/beastmastery/modules/spells/BestialWrath.tsx, src/parser/hunter/beastmastery/modules/spells/CobraShot.tsx, src/parser/hunter/beastmastery/modules/spells/azeritetraits/FeedingFrenzy.tsx, src/parser/hunter/beastmastery/modules/spells/azeritetraits/PrimalInstincts.tsx, src/parser/hunter/beastmastery/modules/talents/AnimalCompanion.tsx, src/parser/hunter/beastmastery/modules/talents/AspectOfTheBeast.tsx, src/parser/hunter/beastmastery/modules/talents/ChimaeraShot.tsx, src/parser/hunter/beastmastery/modules/talents/DireBeast.tsx, src/parser/hunter/beastmastery/modules/talents/KillerCobra.tsx, src/parser/hunter/beastmastery/modules/talents/KillerInstinct.tsx, src/parser/hunter/beastmastery/modules/talents/OneWithThePack.tsx, src/parser/hunter/beastmastery/modules/talents/ScentOfBlood.tsx, src/parser/hunter/beastmastery/modules/talents/SpittingCobra.tsx, src/parser/hunter/beastmastery/modules/talents/Stampede.tsx, src/parser/hunter/beastmastery/modules/talents/Stomp.tsx, src/parser/hunter/beastmastery/modules/talents/ThrillOfTheHunt.tsx, src/parser/hunter/beastmastery/modules/talents/VenomousBite.tsx
Issue #3616
Everything except talents done. Draft until then!
=> [BM] First pass at BM modules converted to event listeners

src/CHANGELOG.js, src/raids/nyalothathewakingcity/NzothTheCorruptor.js, src/raids/nyalothathewakingcity/TheProphetSkitra.js
Nzoth has some really weird stuff going on due to the realms: 
https://wowanalyzer.com/report/JYPdfwA9zrptQ8DB/2-Mythic+N%27Zoth+the+Corruptor+-+Kill+(12:02)/Bargo/standard/statistics
but if we look at the same log, but his own version of it, it's fine: 
https://wowanalyzer.com/report/LRcCJ9tBwVzHGXpj/39-Mythic+N%27Zoth+the+Corruptor+-+Kill+(12:02)/Bargo/standard/statistics
=> Add warnings to Nzoth the corruptor, and change the warning for Skitra

src/parser/mage/frost/CHANGELOG.tsx, src/parser/mage/frost/modules/cooldowns/ColdSnap.tsx, src/parser/mage/frost/modules/features/GlacialSpike.tsx, src/parser/mage/frost/modules/features/WintersChill.tsx, src/parser/mage/frost/modules/features/WintersChillNoIL.tsx
Some references to ability.guid instead of .id
=> [Frost] Fix constants

src/parser/mage/frost/CHANGELOG.tsx, src/parser/mage/frost/modules/features/GlacialSpikeNoIL.tsx
Fixed a bug that was not properly counting shatter buffs for the NoIL version of Glacial Spike
=> [Frost Mage] Fix for NoIL Glacial Spike

src/CHANGELOG.js, src/common/ITEMS/bfa/dungeons/index.js, src/common/SPELLS/bfa/dungeons/items.js, src/parser/core/CombatLogParser.js, src/parser/hunter/survival/integrationTests/survivalIntegrationTests.test.ts.snap, src/parser/shared/modules/items/bfa/dungeons/SubroutineRecalibration.tsx
=> Add support for Subroutine: Recalibration mechagon trinket card

src/parser/mage/fire/CHANGELOG.tsx, src/parser/mage/fire/modules/features/CooldownThroughputTracker.js
This is to show the spells that were cast in the 4 seconds before Combustion was cast in the Cooldowns page.
Before
After
=> [Fire Mage] Combustion CD Pre Spells

src/parser/mage/arcane/CHANGELOG.tsx, src/parser/mage/arcane/integrationTests/example.test.ts.snap, src/parser/mage/arcane/modules/features/ArcanePower.tsx
The module was unintentionally ignoring some cast events.
=> [Arcane Mage] Fix Arcane Power module 

src/CHANGELOG.js, src/game/RACES.js, src/parser/core/Combatant.ts
=> Missing races

src/CHANGELOG.js, src/CONTRIBUTORS.ts, src/common/changelog.ts, src/interface/ContributorDetails/ContributorDetails.tsx, src/parser/Config.ts
Also it turns out that the "desc" property of contributors has been improperly accessed as "about" for who knows how long. Fixed that.
Before:
After:
=> [Core] Add types for Contributor, and then convert ContributorDetails to TS

src/CHANGELOG.js, src/parser/hunter/shared/modules/features/CancelledCasts.tsx
Fixes the warning in dev env for the list not having a key prop
=> Hunter cancelledcasts key

src/CHANGELOG.js, src/interface/report/Results/index.js
Introduced this myself by changing the method signature and forgetting to change the call.
=> Fix bug where fightDuration was being adjusted for downtime (which has not been implemented)

src/CHANGELOG.js, src/parser/hunter/beastmastery/modules/talents/KillerInstinct.tsx, src/parser/hunter/beastmastery/modules/talents/SpittingCobra.tsx, src/parser/hunter/marksmanship/CombatLogParser.tsx, src/parser/hunter/marksmanship/constants.tsx, src/parser/hunter/marksmanship/modules/talents/CarefulAim.tsx, src/parser/hunter/shared/modules/spells/KillShot.tsx, src/parser/shared/ExecuteHelper.ts, src/parser/shared/modules/resources/ResourceUsage.tsx
Add a generic Execute Helper module that should help in making execute modules more standardized.
=> [Core] Execute Helper

src/common/SPELLS/mage.js, src/parser/mage/arcane/CHANGELOG.tsx, src/parser/mage/arcane/integrationTests/example.test.ts.snap, src/parser/mage/fire/CHANGELOG.tsx, src/parser/mage/fire/integrationTests/example.test.ts.snap, src/parser/mage/frost/CHANGELOG.tsx, src/parser/mage/shared/modules/features/CancelledCasts.tsx, src/parser/shared/modules/Haste.js, src/parser/shared/modules/StatTracker.js
- Removed some old Legion Spells
- Updated the Arcane Integration Test from the most recent changes
=> [Shadowlands][Prepatch] Mage Cleanup

src/parser/mage/arcane/integrationTests/example.test.ts.snap, src/parser/mage/arcane/modules/Checklist/Component.tsx, src/parser/mage/frost/CHANGELOG.tsx, src/parser/mage/frost/integrationTests/example.test.ts.snap, src/parser/mage/frost/modules/features/Abilities.tsx
- Added Fire Blast and Arcane Explosion to Spellbook
Towards #3657
=> [Shadowlands][Prepatch][Frost Mage] Base spec changes

src/common/SPELLS/monk.js, src/common/SPELLS/talents/monk.js, src/parser/core/Analyzer.ts, src/parser/core/Events.ts, src/parser/core/modules/EventEmitter.ts, src/parser/monk/brewmaster/CHANGELOG.js, src/parser/monk/brewmaster/CombatLogParser.ts, src/parser/monk/brewmaster/integrationTests/example.test.ts.snap, src/parser/monk/brewmaster/modules/Abilities.js, src/parser/monk/brewmaster/modules/core/BrewCDR.tsx, src/parser/monk/brewmaster/modules/core/SharedBrews.ts, src/parser/monk/brewmaster/modules/core/Stagger.tsx, src/parser/monk/brewmaster/modules/core/StaggerFabricator.ts, src/parser/monk/brewmaster/modules/spells/CelestialBrew.tsx, src/parser/monk/brewmaster/modules/spells/PurifyingBrew.tsx, src/parser/monk/brewmaster/test-fixtures/SimpleFight.js
Does not include covenant abilities yet.
Also includes a basic Celestial Brew module
=> Updated BrM Abiltiies for Shadowlands

src/CHANGELOG.js, src/interface/report/Results/index.js
Updated the shadowlands warning to include a link to the github shadowlands issues for feedback
=> [Core] Update Shadowlands Warning

src/common/SPELLS/mage.js, src/parser/mage/frost/CHANGELOG.tsx, src/parser/mage/frost/CombatLogParser.ts, src/parser/mage/frost/constants.tsx, src/parser/mage/frost/integrationTests/example.test.ts.snap, src/parser/mage/frost/modules/cooldowns/FrozenOrb.tsx, src/parser/mage/frost/modules/features/WintersChill.tsx, src/parser/mage/frost/modules/items/ColdFront.tsx, src/parser/mage/frost/modules/items/FreezingWinds.tsx
- Frozen Orb CDR from Freezing Winds
- Statistics to show the CDR for Freezing Winds and the Bonus Orbs from Cold Front
- Tweaked a couple things in Winter's Chill that was throwing off some statistics in some logs
Towards #3657
=> [Shadowlands][Frost Mage] Freezing Winds & Cold Front

src/common/SPELLS/shadowlands/conduits/monk.js, src/common/SPELLS/shadowlands/covenants/monk.js, src/parser/monk/mistweaver/CHANGELOG.js, src/parser/monk/mistweaver/CombatLogParser.js, src/parser/monk/shared/modules/conduits/FortifyingIngredients.js, src/parser/monk/shared/modules/conduits/GroundingBreath.js, src/parser/monk/shared/modules/conduits/HarmDenial.js
=> [Monk] All endurance Conduits added

src/common/SPELLS/shadowlands/conduits/monk.js, src/parser/monk/mistweaver/CHANGELOG.js, src/parser/monk/mistweaver/CombatLogParser.js, src/parser/monk/mistweaver/modules/shadowlands/conduits/JadeBond.js, src/parser/monk/mistweaver/modules/shadowlands/conduits/NourishingChi.js, src/parser/monk/mistweaver/modules/shadowlands/conduits/RisingSunRevival.js
=> [MW] Potency Conduits

src/common/SPELLS/monk.js, src/parser/monk/mistweaver/CHANGELOG.js, src/parser/monk/mistweaver/modules/features/CooldownThroughputTracker.js
Added Two cooldowns to the cooldowns tab and updated a spell
=> [MW] Added Cooldowns

src/CHANGELOG.js, src/interface/CastEfficiency/CastEfficiency.tsx, src/parser/shared/modules/CastEfficiency.tsx
Added a default cast of 0% incase a spell wasn't castable all combat
=> [Abilities update]

src/common/SPELLS/druid.js, src/common/SPELLS/shadowlands/conduits/druid.js, src/parser/druid/restoration/CHANGELOG.js, src/parser/druid/restoration/CombatLogParser.js, src/parser/druid/restoration/modules/Abilities.js, src/parser/druid/restoration/modules/shadowlands/conduits/FlashOfClarity.js
=> 1 resto druid conduit

src/common/SPELLS/shadowlands/conduits/shaman.js, src/parser/shaman/restoration/CHANGELOG.js, src/parser/shaman/restoration/CombatLogParser.js, src/parser/shaman/restoration/modules/shadowlands/conduits/EmbraceOfEarth.js, src/parser/shaman/restoration/modules/shadowlands/conduits/HeavyRainfall.js, src/parser/shaman/restoration/modules/shadowlands/conduits/SwirlingCurrents.js
Embrace of Earth, Heavy Rainfall and Swirling Currents
=> [Resto Shaman] 3 out of 4 potency conduits

src/common/SPELLS/shadowlands/covenants/monk.js, src/parser/monk/mistweaver/CHANGELOG.js, src/parser/monk/mistweaver/CombatLogParser.js, src/parser/monk/mistweaver/modules/shadowlands/conduits/NourishingChi.js, src/parser/monk/shared/modules/conduits/ImbuedReflections.js
added the conduit Imbued Reflections
=> [Monk] Imbued Reflections

src/common/SPELLS/shadowlands/legendaries/monk.js, src/parser/monk/mistweaver/CHANGELOG.js, src/parser/monk/mistweaver/CombatLogParser.js, src/parser/monk/mistweaver/modules/shadowlands/legendaries/AncientTeachingsoftheMonastery.js, src/parser/monk/mistweaver/modules/shadowlands/legendaries/TearofMorning.js
=> MW Legendaries

src/CHANGELOG.js, src/parser/shared/modules/CooldownThroughputTracker.tsx
=> Cooldown Throughput track now has pets!

src/parser/monk/mistweaver/CHANGELOG.js, src/parser/monk/mistweaver/integrationTests/example.test.ts.snap, src/parser/monk/mistweaver/modules/spells/LifeCocoon.js
Life cocoon now correctly tracks all hots
=> [MW] Life cocoon fixes

src/common/SPELLS/shadowlands/covenants/priest.js, src/parser/priest/discipline/CHANGELOG.js, src/parser/priest/discipline/CombatLogParser.js, src/parser/priest/discipline/constants.js, src/parser/priest/discipline/modules/shadowlands/covenants/MindGames.js
=> [Shadowlands][Discipline Priest] Mind Games Implementation

src/common/SPELLS/shadowlands/legendaries/monk.js, src/parser/monk/mistweaver/CHANGELOG.js, src/parser/monk/mistweaver/CombatLogParser.js, src/parser/monk/mistweaver/modules/shadowlands/legendaries/CloudedFocus.js
=> [MW] Clouded Focus

src/CHANGELOG.tsx, src/parser/shared/modules/HotTracker.js
Quiet hot tracker quiet 
Clearned up some console.warns that putput was angry about
=> Log Clean up for hottracker

src/parser/monk/mistweaver/CHANGELOG.tsx, src/parser/monk/mistweaver/modules/spells/RenewingMist.js
Simple update to REM module to use event listeners.
=> [MW] Updated Renewing Mist to Use Event Listeners
