WoWAnalyzer/WoWAnalyzer

- src/Main/Cooldown.js
- src/Main/CooldownOverview.js
- src/Parser/Core/Modules/CooldownTracker.js
- src/Parser/HolyPaladin/CombatLogParser.js
- src/Parser/RestorationShaman/CombatLogParser.js
- src/common/SPELLS_PALADIN.js
- src/common/SPELLS_SHAMAN.js
Spells that are tracked in a CooldownTracker module need to have an additional property: cooldownType . This value can be either 'DAMAGE' or 'HEALING' depending on the statistic that you want to track during this cooldown. This way we can track any statistic for any spell.
I've changed some of the variable names to be Healing/Damage agnostic.
e.g. the showHealing boolean for the CooldownTracker is now: showOutputStatistics.
And an extra boolean has been added(showResourceStatistic) to show/hide the mana usage statistic during the cooldown duration.
I've taken the liberty of updating the two classes that used _showHealing_ on the cooldowns, which was RestoShaman and HolyPaladin, both work as before.
> Updated Cooldown Tab & components to be able to represent damage as well as healing

- src/CHANGELOG.js
- src/Main/App.css
- src/Main/CastEfficiency.js
- src/Main/Cooldown.js
- src/Parser/AVAILABLE_CONFIGS.js
- src/Parser/Core/Modules/AbilityTracker.js
- src/Parser/Core/Modules/CooldownTracker.js
- src/Parser/Core/Modules/Initialize.js
- src/Parser/ElementalShaman/CONFIG.js
- src/Parser/ElementalShaman/CPM_ABILITIES.js
- src/Parser/ElementalShaman/CombatLogParser.js
- src/Parser/ElementalShaman/Modules/Features/AlwaysBeCasting.js
- src/Parser/ElementalShaman/Modules/Features/CooldownTracker.js
- src/Parser/ElementalShaman/Modules/Features/ProcTracker.js
- src/Parser/ElementalShaman/Modules/Main/CastEfficiency.js
- src/Parser/ElementalShaman/Modules/Main/Maelstrom.css
- src/Parser/ElementalShaman/Modules/Main/Maelstrom.js
- src/Parser/ElementalShaman/Modules/Main/MaelstromTab.js
- src/Parser/ElementalShaman/Modules/Main/main.css
- src/Parser/ElementalShaman/Modules/ShamanCore/ElementalAbilityTracker.js
- src/common/SPELLS_SHAMAN.js
For #51 
I added besides the Basic Elemental support, some stat colors and the DamageTracker implementation.
All new components are saved inside the `ElementalShaman/Modules/Main` folder.
The `MaelstromTab` and `Maelstrom` components are based on the `Mana*` ones.
The custom `CastEfficiency` will be later renamed to `MaelstromEfficiency`.
Some Tooltips need some work and are not done yet.
WIP
Without Talent descriptions right now. (and Restro descriptions shown)
Only Ascendance (if specced) and Stormkeeper right now
WIP Maelstrom usage; the spend category needs still some work.
> Add basic Elemental Shaman support

- src/CHANGELOG.js
- src/Parser/RestorationShaman/Modules/Features/CooldownTracker.js
- src/common/SPELLS_SHAMAN.js
Fix crash when CBT, AG or Ascendance was cast before pull. Also readds healing statistics to cloudburst totem in the cooldown overview.
> Fix crash when CBT, AG or Ascendance was cast before pull.

- src/Parser/HolyPriest/CPM_ABILITIES.js
- src/Parser/HolyPriest/CombatLogParser.js
- src/common/SPELLS_PRIEST.js
Fixes two bugs with the analyzer:
* Say Your Prayers was returning negative benefit when the average PoM lasted less than 5 stacks.
* Light of T'uure was expecting one less cast than it should have (since it starts with 2 charges).
> Holy Priest: SYP and LoT bugfixes

- src/Parser/RestoDruid/CombatLogParser.js
- src/Parser/RestoDruid/Modules/Legendaries/Tearstone.js
- src/tests/Parser/RestoDruid/CombatLogParser.test.js
track people who received WG buff, only those could have been the target of a tearstone proc.  
and track rejuv casts to avoid counting casted rejuvs that occur at the same time as tearstone proc.
depends on the other PR to fix the order of cast/applybuff events that kinda is needed for tearstone tracking to work well: https://github.com/MartijnHols/WoWAnalyzer/pull/107
> better tearstone calculation

- src/Parser/RestoDruid/CombatLogParser.js
- src/tests/Parser/RestoDruid/CombatLogParser.test.js
When parsing resto druid logs in the past with my own tool (https://github.com/rubensayshi/wcl-rdruid-mastery) I've noticed that sometimes `applybuff` events occur before the `cast` even that applied the buff.  
For resto druid there's a couple of things that make it rather important that the events are in the right order, there's so many HoTs proccing from various things that if they are not it's impossible to attribute them to the right legendaries and talents.
As an example you can look at `/report/WP6brRpDChmGFT9H/6/Saik%C3%B3/cast-efficiency`.
If you put a `console.log` in `Tearstone.js` to log the WG `cast` and `applybuff` events you will see the following (timestamp has been normalized to start of fight and seconds, the number before the timestamp is `targetID`):
```
APPLYBUFF:WG …
```
> reorder WG and rejuv cast/applybuff events to fix issues we run into later on

- src/Parser/Core/CombatLogParser.js
- src/Parser/Core/Modules/Items/GnawedThumbRing.js
intended to address issue #123 
added a variable to track the increased damage amount & modified the logic on how to format the result depending on if the ring increased healing or damage more. I'm a bit torn if this hybrid should display both damage and healing increases. Let me know what you think.
> adding damage increase support for gnawed ring

- src/Parser/Core/CombatLogParser.js
This may prompt further discussion:
Example: Goroth
If you hit another player with your Burning Eruption targetisfriendly is set to true in the event. However damage done in warcraftlogs does not show this in your damage done.
Friendly damage is added to totalDamageDoneToFriendly rather than totalDamageDone
`this.totalDamageDoneToFriendly += event.amount + (event.absorbed || 0);`
In order to match the log value i think totalDamageDone should be the value in the logs and exclude friendly damage, but if that messes with some other calculation then leaving it included but with a seperate totalDamageDoneToFriendly value which you would have to subtract is an alternative. It would be less intuitive for authors of dps parsers.
> Change to the damage done calculation to better reflect value in logs

- src/Parser/Core/CombatLogParser.js
This is a separate PR from 138 though related it is a separate issue. This is the same file as the other PR...
The damage taken includes absorbs, while this may be correct in certain circumstances it does not match the value in the logs.
I have introduced a new value so that the absorb is not lost (in case its used elsewhere), but that could be removed if its not needed.
> Change to the CombatLogParser to match warcraftlogs.com

- src/Parser/Core/Entity.js
I have an issue with getBuffUptime where it appears to be a few 10ths of a second off, and it appears to be because its using this.owner.currentTimestamp as the end of the fight. However that's the time of the last event in the combat log.
I have changed getBuffUptime to account for the end of the fight if its over in a similar way to fightDuration in the core/CombatLogParser.
However this method is used in multiple locations, though it only affects combatant buff uptimes not enemies. Other Parsers need to be tested.
> Change to end time calculation to account for end of fight

- src/CHANGELOG.js
- src/Parser/GuardianDruid/CombatLogParser.js
Added damage type to the tooltip of DTPS, this object can also be used later for damage reduction calculations. Damage type is a bitwise property, and chaos damage is not always the same so put a default of chaos and populated all of the other types of damage i could find in the object.
> Guardian druid damage detail

- src/Parser/MistweaverMonk/CombatLogParser.js
Removed this during CombatLogParser cleanup. Opps!
> MW Monk: Re-add removed Healing Increases constants.

- src/CHANGELOG.js
- src/Parser/Core/Modules/DamageTaken.js
- src/Parser/GuardianDruid/CombatLogParser.js
- src/Parser/GuardianDruid/Modules/Core/DamageDone.js
- src/Parser/GuardianDruid/Modules/Core/DamageTaken.js
- src/Parser/GuardianDruid/Modules/Core/HealingDone.js
- src/Parser/GuardianDruid/Modules/Features/AlwaysBeCasting.js
- src/Parser/GuardianDruid/Modules/Features/FrenziedRegenGoEProcs.js
- src/Parser/GuardianDruid/Modules/Features/GalacticGuardian.js
- src/Parser/GuardianDruid/Modules/Features/Gore.js
- src/Parser/GuardianDruid/Modules/Features/GuardianOfElune.js
- src/Parser/GuardianDruid/Modules/Features/IronFurGoEProcs.js
- src/Parser/GuardianDruid/Modules/Spells/IronFur.js
- src/Parser/GuardianDruid/Modules/Spells/Moonfire.js
- src/Parser/GuardianDruid/Modules/Spells/Pulverize.js
- src/Parser/GuardianDruid/Modules/Spells/Thrash.js
- src/common/DamageTypes.js
Mostly moving all the guardian druid into modules, also added overkill to damage taken (when you die the logs include it).
No new functionality, but it fixes the sorting of the statistics.
> [Guardian] Moved all of the druid suggestions and statistics into modules

- src/Parser/Core/Modules/Items/PrePotion.js
- src/Parser/Core/Modules/ManaValues.js
- src/Parser/Core/Modules/SpellManaCost.js
- src/Parser/Core/RESOURCE_TYPES.js
- src/common/RESOURCE_TYPES.js
Keeping with the convention of having shared data and enums in `common/`, this PR adds `common/RESOURCE_TYPES` with the known type ids from [Wowpedia's PowerType listing](https://wow.gamepedia.com/PowerType).  
I also removed the old `Parser/Core/RESOURCE_TYPES` and migrated existing references to the new location.  There might be other places where resource types are hardcoded in class modules, but I'll leave that for the maintainers to update.
> Move resource types into common and add all known types

- src/Parser/GuardianDruid/Modules/Items/Skysecs.js
Fixes a bug that shows metrics for Skysecs even when it's not equipped
> [Guardian] Disable Skysecs if it's not equipped

- src/Parser/GuardianDruid/CombatLogParser.js
- src/Parser/GuardianDruid/Modules/Features/RageWasted.js
- src/common/ITEMS.js
- src/common/SPELLS_DRUID.js
- src/common/SPELLS_OTHERS.js
Displays wasted rage as a statistic and suggestion, including % of total rage gained that was wasted and a breakdown of waste by spell.
> [Guardian] Rage waste statistic

- src/Parser/Core/Modules/Items/PrePotion.js
Currently if a non-healer that has mana as a resource, especially something like a bear who has a minimal amount of mana. If they go below the value of a mana potion it is suggested that they use a mana pot.
This should probably be done differently in a module, but this fixes the issues
> Changed logic for second pot suggestion for non-healers

- src/CHANGELOG_GUARDIAN_DRUID.js
- src/Parser/GuardianDruid/Modules/Features/FrenziedRegenGoEProcs.js
- src/Parser/GuardianDruid/Modules/Features/IronFurGoEProcs.js
Changed two dependancies of the GOE module to use dependancies
Fixed an issue with Guardian of Elune buffed Frenzied regen, was using the wrong value.
> Changed to use dependancies

- src/Parser/GuardianDruid/Modules/Features/CastEfficiency.js
Fixes Cast Efficiency bug where it shows SR being cast more than the max potential casts
> [Guardian] Account for Guttural Roars talent when getting Stampeding Roar cd

- src/Parser/GuardianDruid/CHANGELOG.js
- src/Parser/GuardianDruid/CONFIG.js
As discussed the other day, I will be taking over maintenance of the Guardian module from WOPR so he can continue to focus on Brewmaster.  This patch updates the maintainer name in `CONFIG.js`.
Also adds most of my changes to the `CHANGELOG`, per @buimichael's request.
> [Guardian] Ownership change and changelog updates

- src/Parser/GuardianDruid/CombatLogParser.js
- src/Parser/GuardianDruid/Modules/Spells/FrenziedRegeneration.js
- src/common/SPELLS_DRUID.js
Adds a Frenzied Regeneration module that tracks FR use, and creates a suggestion when it is being used poorly.
> [Guardian] Frenzied Regeneration

- src/Parser/BrewmasterMonk/Modules/Core/HealingDone.js
- src/Parser/Core/Modules/HealingDone.js
- src/tests/Parser/Brewmaster/HealingDone.test.js
I didn't validate the move to modules correctly for healing on stagger.
The stagger absorb is neither healing or damage taken it is deferred to the stagger dot to either be taken later or purged (purifying brew/T20 4pc/End of fight/External Absorb).
Also added unit tests on the SimpleFight fixture following the same scenarios as the damage taken with values corrected for healing. Only true heals and non-stagger absorb (Dark Side of the Moon) should show.
> [BrM] Fix to healing following the move to the module

- src/Parser/HolyPriest/Modules/Core/SpellManaCost.js
- src/Parser/HolyPriest/Modules/Items/TrousersOfAnjuna.js
- src/Parser/HolyPriest/Modules/Items/XanshiCloak.js
- src/Parser/HolyPriest/Modules/PriestCore/Divinity.js
- src/Parser/HolyPriest/Modules/PriestCore/EnduringRenewal.js
- src/Parser/HolyPriest/Modules/PriestCore/LightOfTuure.js
- src/Parser/HolyPriest/Modules/PriestCore/RenewTheFaith.js
- src/Parser/HolyPriest/Modules/Spells/PrayerOfMending.js
As discussed on Discord, `this.owner.selectedCombatant` and `this.owner.modules` are deprecated, so I've made such adjustments for the holy priest end here.
> (HPriest) Removing various this.owner calls

- src/Main/ExpandableStatisticBox.js
- src/Parser/Core/Combatant.js
- src/Parser/HolyPriest/CHANGELOG.js
- src/Parser/HolyPriest/CombatLogParser.js
- src/Parser/HolyPriest/Constants.js
- src/Parser/HolyPriest/Modules/PriestCore/MasteryBreakdown.js
- src/common/SPELLS_PRIEST.js
Finally got to writing the module for the Echo of Light breakdown. As this isn't something that is available through WCL, it's been highly requested in respect to other things.
Also fixes a bug with the Expandable Statistic Box that was causing it to span across multiple columns unexpectedly.
edit: the columns above look the same but the 3rd column is now % of total and the 4th is % overheal instead.
> (Holy Priest) Echo of Light (aka Mastery) breakdown

- src/Parser/RestoDruid/CombatLogParser.js
- src/Parser/RestoDruid/Modules/Legendaries/T19_2Set.js
- src/common/SPELLS_DRUID.js
Added an item display for Resto Druid's T19 2pc bonus. Added module is basically just the display, all the backend work was already doing in the Mastery module.
> [Resto Druid] Added T19 2pc module

- src/Parser/GuardianDruid/Modules/Features/CastEfficiency.js
- src/Parser/GuardianDruid/Modules/Features/FrenziedRegenGoEProcs.js
- src/Parser/GuardianDruid/Modules/Features/GalacticGuardian.js
- src/Parser/GuardianDruid/Modules/Features/GuardianOfElune.js
- src/Parser/GuardianDruid/Modules/Features/IronFurGoEProcs.js
- src/Parser/GuardianDruid/Modules/Items/DualDetermination.js
- src/Parser/GuardianDruid/Modules/Items/FuryOfNature.js
- src/Parser/GuardianDruid/Modules/Items/LuffaWrappings.js
- src/Parser/GuardianDruid/Modules/Items/Skysecs.js
- src/Parser/GuardianDruid/Modules/Spells/FrenziedRegeneration.js
- src/Parser/GuardianDruid/Modules/Spells/IronFur.js
- src/Parser/GuardianDruid/Modules/Spells/Moonfire.js
- src/Parser/GuardianDruid/Modules/Spells/Pulverize.js
- src/Parser/GuardianDruid/Modules/Spells/Thrash.js
- src/Parser/GuardianDruid/Modules/Talents/Earthwarden.js
Replaces most instances of `this.owner.modules` and `this.owner.selectedCombatant` in the guardian modules with the dependency injection pattern.  The remaining references are to `this.owner.fightDuration`, which does not currently have a better solution.
This PR also contains a change to the CastEfficiency of Thrash.  Previously, if Incarnation was talented, the maximum Thrash Casts were calculated based on the actual number of casts of Incarnation in the encounter.  Now, the maximum number of potential Incarnation casts is used to compute potential Thrash count, so poor Incarn cast efficiency will also lead to poor Thrash cast efficiency.  
This change should help better identify low Thrash counts, but was also necessary in order to remove the dependency on …
> [Guardian] Clean up module dependencies

- src/Main/DevelopmentTab.js
- src/Parser/Core/Modules/AbilityTracker.js
- src/Parser/Core/Modules/Items/Cinidaria.js
- src/Parser/ElementalShaman/CombatLogParser.js
- src/Parser/GuardianDruid/CombatLogParser.js
- src/Parser/VengeanceDemonHunter/Modules/Statistics/Spells/ImmolationAura.js
- src/Parser/VengeanceDemonHunter/Modules/Statistics/Spells/SigilOfFlame.js
- src/common/SPELLS_OTHERS.js
Adds a common module for tracking Cinidaria dps and hps.
Also fixes a typo in AbilityTracker (`damange` -> `damage`), and all occurrences of the typo in other modules.
> Cinidaria the Symbiote

- src/Parser/BalanceDruid/Modules/Features/AlwaysBeCasting.js
- src/Parser/Core/Modules/AlwaysBeCasting.js
- src/common/SPELLS_DRUID.js
- src/common/talents/TALENTS_DRUID.js
It essentially works, Im not completely sure about the placement of some things, any suggestions will be appreciated :D
And maybe too many comments in there, idk.
But well, this should support any specs stackable haste buffs.
Added too a couple silly things:
- Not letting the GCD go under 0.75s, no matter how much haste there is (I think this is true for every spec, if there's any exception should be added here)
- Added the possibility of abilities which GCD is not affected by haste (such as shapeshifting, i dont know it any other class has anything like this)
ToDo:
Add support for trinkets somehow (because haste values change with ilvl)
> [Core] + [Balance Druid] Added functionality to CoreABC to support stackable haste buffs

- src/Parser/AfflictionWarlock/CHANGELOG.js
- src/Parser/AfflictionWarlock/CombatLogParser.js
- src/Parser/AfflictionWarlock/Modules/Talents/EmpoweredLifeTap.js
- src/Parser/DestructionWarlock/CHANGELOG.js
- src/Parser/DestructionWarlock/CombatLogParser.js
- src/Parser/DestructionWarlock/Modules/Items/Legendaries/SoulOfTheNetherlord.js
- src/Parser/DestructionWarlock/Modules/Talents/EmpoweredLifeTap.js
- src/Parser/DestructionWarlock/Modules/Talents/Eradication.js
- src/Parser/DestructionWarlock/Modules/Talents/EradicationTalent.js
- src/Parser/DestructionWarlock/Modules/Talents/ReverseEntropy.js
Added tier 30 row for Destro talents - Reverse Entropy, Eradication and Empowered Life Tap. Pretty straightforward stuff. Also added the ELT module to Affli since it exists there too (albeit never used I'd say).
> [Destruction] Second batch of talents

- src/Parser/HavocDemonHunter/CHANGELOG.js
- src/Parser/HavocDemonHunter/Modules/Features/CastEfficiency.js
- src/Parser/VengeanceDemonHunter/CHANGELOG.js
- src/Parser/VengeanceDemonHunter/Modules/Features/CastEfficiency.js
- src/common/SPELLS_DEMON_HUNTER.js
Cast Efficiency is now less nitpicky: Some almost unused abilities or no CD abilities 'can be improved' warning is now disabled.
Also, corrected some getCooldown timers that was wrong in Vengeance CastEfficiency.
> [Vengeance+Havoc] Cast Efficiency rework

- src/Parser/HolyPriest/Constants.js
- src/Parser/HolyPriest/Modules/PriestCore/MasteryBreakdown.js
Basically, if something triggered mastery (and was not known in `CONSTANTS.js`) and nothing else known was applied within the 3 seconds prior to a mastery healing tick, it would cause the existing logic to crash. 
Also added a filter to avoid the table from being too congested when it expands to other spell ids.
> (Holy Priest) Fix for mastery breakdown bug

- src/Parser/HavocDemonHunter/Modules/Features/CastEfficiency.js
Vengeful Retreat does not show 'can be improved' anymore, as it is a really unused movement spell.
Eye Beam does not show 'can be improved' anymore, as it is a very situational spell.
> [Havoc] Update Cast Efficiency

- src/Main/Event.js
- src/Parser/Core/Modules/HealingDone.js
- src/Parser/DisciplinePriest/CHANGELOG.js
- src/Parser/DisciplinePriest/CombatLogParser.js
- src/Parser/DisciplinePriest/Modules/Features/AtonementHealingBreakdown.js
- src/Parser/DisciplinePriest/Modules/Features/AtonementHealingDone.js
- src/Parser/DisciplinePriest/Modules/Features/AtonementSource.js
Added an *Atonement sources* tab;
I wanted to see if I could get the atonement source tracking as accurate as beacon heal source tracking by using the same method and I figured this would be easier to do with a way to see the result. This does that. This display will always be as accurate as the tracking by the AtonementSource module and the accuracy of the shown data isn't related to changes in this PR.
> Disc Priest: Added Atonement sources breakdown

- src/Parser/VengeanceDemonHunter/Modules/Features/CastEfficiency.js
- src/Parser/VengeanceDemonHunter/Modules/Statistics/SoulFragments/SoulFragments.js
- src/Parser/VengeanceDemonHunter/Modules/Statistics/SpiritBomb/SpiritBomb.js
- src/common/SPELLS_DEMON_HUNTER.js
- Spirit Bomb debuff now have a statistic box to show the uptime as well.
- Soul Fragments statistics is now more complete: it shows the total generated/spent/wasted/unused Soul Fragments of a fight.
- Soul Fragments suggestions for wasting it is now created too.
> [Vengeance] Spirit Bomb statistics and Soul Fragments tracker

- src/CHANGELOG.js
- src/Parser/Core/Modules/Items/ArchimondesHatredReborn.js
- src/Parser/VengeanceDemonHunter/CHANGELOG.js
- src/common/SPELLS_OTHERS.js
I inserted the DPS contribution to the Archimonde's Hatred Reborn legendary. It was a suggestion from a theorycrafter player in order to keep track of it maximum damage possible and DPS meters for it.
> [Core] Added Archimonde's Hatred Reborn DPS meters on tooltip

- src/Parser/VengeanceDemonHunter/Modules/Features/CastEfficiency.js
Sigil of Flame cast efficiency was calculated with haste, but as I have a module to track the debuff uptime, it is no longer necessary in the cast efficiency module, as it is wrongly calculated by haste CD.
> [Vengeance] Removed Sigil of Flame from CastEfficiency

- src/Parser/Core/Modules/DamageTaken.js
- src/Parser/Core/Modules/HealingDone.js
I tried to use byAbility in HealingDone and was immediately hit by the inconvenience of constant undefined checks. It seems to me that if I call byAbility on something that hasn't healed yet, I should get zeroes, not undefined.
A search of the code revealed that no one has used these util methods in DamageTaken either, so I gave them the same treatment.
By the way, how do you feel about using "if(!object)" to check for undefined? Searching the web for this question, I found a lot of answers for how you *could* check for undefined, but very few about how you *should* check for undefined.
> [core] byAbility and byMagicSchool no longer return undefined when no entry yet

- src/Parser/RetributionPaladin/CombatLogParser.js
- src/Parser/RetributionPaladin/Modules/Features/CastEfficiency.js
- src/Parser/RetributionPaladin/Modules/Features/Judgment.js
- src/Parser/RetributionPaladin/Modules/HolyPower/HolyPowerDetails.js
- src/Parser/RetributionPaladin/Modules/Items/LiadrinsFuryUnleashed.js
- src/common/SPELLS_PALADIN.js
Tracks Spenders used outside of judgment. Fixed a display bug in the holy power suggestions. Also a small bug with Crusader Strike cast efficiency
> Made a judgment Module.

- src/Parser/RestoDruid/CHANGELOG.js
- src/Parser/RestoDruid/Modules/Legendaries/T20_2Set.js
Put the 'just the facts' statistic front facing, relegated the idealized throughput number to tooltip.
> [Resto Druid] Changed display of T20 2pc

- src/Parser/GuardianDruid/CONFIG.js
The guardian module currently tracks: (along with standard stuff like Dead GCD time, DPS, HPS, DTPS)
- Cast Efficiency for all rotational spells (Thrash cooldown tracking needs some improvement)
- Unused procs (Gore, Galactic Guardian, and Guardian of Elune)
- Uptimes (Ironfur, Thrash, Moonfire, Pulverize)
- DPS/HPS contribution for most spec legendaries
- Rage waste
- Earthwarden efficiency
- Frenzied Regeneration efficiency
Modules that are in development or are planned:
- Anti-filler spam
- Damage mitigation assessment for all relevant spells, talents, and items
- Cooldowns tab
- Multitarget suggestion improvements
- Efficiency metrics for other talents
- DPS/HPS contributiosn for remaining legendaries
I'd consider the current status of the Guardian module `Good`. The core rotational …
> [Guardian] Upgrade completeness to 'good'

- src/Parser/VengeanceDemonHunter/CONFIG.js
I actually consider that the Vengeance Demon Hunter spec is quite complete:
- It has several improvement suggestions, which vary with the talents you're using:
- Spirit Bomb have a separate module to include more accurate statistics and debuff uptime percentage (USP).
- Core rotation spells have it's own statistic boxes to show the buff uptime and, in Immolation Aura box, it also shows the total damage done by it (calculated both with the buff damage and the first strike damage) (USP).
- It has a Pain Chart to show how much Pain you wasted in the fight and Pain usage breakdown, including the spenders, which are a USP (WCL does not include spenders in it's chart).
- It also have a Soul Fragment wasted tracker, which can't be found anywhere (USP).
- It already have all spells in the cast …
> [Vengeance] Changed Spec Completeness

- src/Parser/Core/Modules/CastEfficiency.js
It shows cast efficiency numbers, but this trinket hasn't a cast event on it, so it always show 0 casts per fight, also triggering suggestions and 'can be improved', even if the player has used it off CD.
> [Core] Kil'Jaedens Burning Wish cast efficiency removed

- src/Parser/BalanceDruid/CONFIG.js
The balance module currently tracks:
Standard modules: Damage done, Downtime
Cast Efficiency for all rotational spells (Moons and Incarnation with IFE need work)
Moons usage
Uptimes (Moonfire, Sunfire)
Astral Power overcapping
Lunar and Solar Empowerment Overcapping
Lunar Strike casts without Lunar Empowerment that hit less than 3 targets
Modules that are planned:
Dots casted outside of pandemic
Short casts (unemp SW, NM) over 200% haste
OI (Legendary bracers) Procs wasted
ED (Legendary helm) buff dropped
Couple  minor things to fix
It's also needed to add whispers and other haste trinkets to the haste module
I believe the current status should be Good.
Every core module is in, the only thing left is dot spamming (this is a fairly complex module since monkin dots spread, so even when …
> [Balance Druid] Completeness

- src/Parser/HolyPriest/CONFIG.js
*cracks knuckles*
As I'm sure many healers mains know, Holy Priest is a fairly simplistic spec. The realms for improvement are often as simple as "press this button on CD, press these big buttons for damage, press other buttons in the meantime", so the spec won't have nearly as extensive of a list as others.
**Statistics** (viewable on WCL)
* Divinity Uptime
**Statistics** (not available on WCL, at least not with ease)
* Average good HW:Sanctify hits per cast (not available because it filters >80% OH hits)
* Say Your Prayers (trait) estimated contribution
* Echo of Light breakdown
* Light of T'uure gain, including from the % increase
* Renew the Faith (trait) gain 
* Enduring Renewal benefit 
* Wasted Serendipity (with the merging of #383)
**Suggestions** (all unavailable to WCL)
* …
> (Holy Priest) Changing spec completion to 'Good'

- src/Parser/Core/Modules/CooldownTracker.js
- src/Parser/MarksmanshipHunter/Modules/Features/CooldownTracker.js
- src/Parser/MistweaverMonk/Modules/Features/CooldownTracker.js
- src/common/SPELLS_OTHERS.js
**Original issue**: #387 
Not sure if there is some general solution to boss abilities, because even in the mentioned example, the casts are of Astral Vulnerability and it's from a player to a friendly player, so there's no way of knowing if that's a boss specific mechanic (just by looking at the event object). 
Instead I added a simple static array that contains spell IDs you wish to ignore. This can be furthermore extended by spec CooldownTrackers to add additional ignored spells (I suggested that in PR #405 and eventually rewrote that in this PR - works completely the same), for example see Marksmanship Hunter Cooldown Tracker.
Before: 
After:
> [Issue #387] Cooldown Tracker should not include boss abilities

- src/Parser/Core/Modules/Haste.js
- src/Parser/DemonologyWarlock/CHANGELOG.js
- src/Parser/DemonologyWarlock/CombatLogParser.js
- src/Parser/DemonologyWarlock/Modules/Items/T20_2set.js
- src/Parser/DemonologyWarlock/Modules/Items/T20_4set.js
- src/common/SPELLS_OTHERS.js
- src/common/SPELLS_WARLOCK.js
Keeping it small. I wanted to add the ability to somewhat count the correct number of possible Call Dreadstalkers since the T20 2pc resets the cooldown, but that proved to be difficult to say the least. I tried doing `fightDuration / baseCD + numberOfResets` but that's kinda fundamentally wrong, since each time you reset the CD, it alters the timestamps at which the cooldowns would be "normally" ready.
In conclusion - no clue how to deal with ability resets, I left it uncorrected with base cooldown of 15 seconds. Also, if you haven't heard on Discord, Dead time for Demo is still severely broken and I've got precisely 0 clue why. Any help appreciated O:)
> [Demonology] Added T20 set bonuses

- src/Parser/EnhancementShaman/CHANGELOG.js
- src/Parser/EnhancementShaman/CombatLogParser.js
- src/Parser/EnhancementShaman/Modules/ShamanCore/AlphaWolf.js
- src/common/SPELLS_SHAMAN.js
Add detection for proper usage of Crash Lightning as priority spell directly after Feral Spirits used
> [Enhancement] Alpha Wolf usage check

- src/Parser/RestoDruid/CONFIG.js
Added simple spec info for Resto Druids. Included link to Discord, reminded them to press ctrl-P for pins  😛 
There isn't yet support for adding 2 maintainer avatars to same spec, so no avatar yet.
> [resto druid] Added spec info to CONFIG.js

- src/Parser/AfflictionWarlock/Modules/Features/FatalEchoes.js
- src/Parser/AfflictionWarlock/Modules/Features/UABuffTracker.js
- src/Parser/AfflictionWarlock/Modules/Items/Legendaries/PowerCordOfLethtendris.js
- src/Parser/AfflictionWarlock/Modules/Items/Legendaries/SacrolashsDarkStrike.js
- src/Parser/AfflictionWarlock/Modules/Items/Legendaries/StretensSleeplessShackles.js
- src/Parser/AfflictionWarlock/Modules/Items/Legendaries/TheMasterHarvester.js
- src/Parser/AfflictionWarlock/Modules/Items/Tier20_2set.js
- src/Parser/AfflictionWarlock/Modules/Items/Tier20_4set.js
- src/Parser/AfflictionWarlock/Modules/SoulShards/SoulShardDetails.js
- src/Parser/AfflictionWarlock/Modules/Talents/EmpoweredLifeTap.js
- src/Parser/AfflictionWarlock/Modules/Talents/SoulHarvest.js
- src/Parser/DemonologyWarlock/Modules/Features/DoomUptime.js
- src/Parser/DemonologyWarlock/Modules/Items/Legendaries/TheMasterHarvester.js
- src/Parser/DemonologyWarlock/Modules/SoulShards/SoulShardDetails.js
- src/Parser/DemonologyWarlock/Modules/Talents/Demonbolt.js
- src/Parser/DemonologyWarlock/Modules/Talents/SoulHarvest.js
- src/Parser/DestructionWarlock/Modules/Features/ImmolateUptime.js
- src/Parser/DestructionWarlock/Modules/Items/Legendaries/AlythesssPyrogenics.js
- src/Parser/DestructionWarlock/Modules/Items/Legendaries/FeretoryOfSouls.js
- src/Parser/DestructionWarlock/Modules/Items/Legendaries/LessonsOfSpaceTime.js
- src/Parser/DestructionWarlock/Modules/Items/Legendaries/MagistrikeRestraints.js
- src/Parser/DestructionWarlock/Modules/Items/Legendaries/OdrShawlOfTheYmirjar.js
- src/Parser/DestructionWarlock/Modules/Items/Legendaries/TheMasterHarvester.js
- src/Parser/DestructionWarlock/Modules/Items/T20_2set.js
- src/Parser/DestructionWarlock/Modules/SoulShards/SoulShardDetails.js
- src/Parser/DestructionWarlock/Modules/Talents/EmpoweredLifeTap.js
- src/Parser/DestructionWarlock/Modules/Talents/FireAndBrimstone.js
- src/Parser/DestructionWarlock/Modules/Talents/ReverseEntropy.js
- src/Parser/DestructionWarlock/Modules/Talents/SoulHarvest.js
Mostly minor refactors:
- extraction of constants before class definition (FatalEchoes, SoulShardDetails in all specs etc.)
- trying to eliminate computations in `on_finished()` where unnecessary (Empowered Life Tap modules, Immolate uptime etc.)
- safety checks for division by zero (UABuffTracker)
- unified the text for item damage (SacrolashsDarkStrike, StretensSleeplessShackles etc., it's possible I missed something)
- minor text cleanup (PowerCordOfLethtendris, FeretoryOfSouls)
- refactor of SoulHarvest modules - private variables/methods renames and using `on_byPlayerPet_damage`
- empty lines here and there for better readability of the code (or to logically separate some parts)
Last but not least, I gave a second thought to Fire and Brimstone and realized it's way too unnecessarily …
> [Warlock] Refactors

- src/Parser/Core/CombatLogParser.js
- src/Parser/Core/EnemyInstance.js
- src/Parser/Core/Modules/Enemies.js
- src/Parser/Core/Modules/EnemyInstances.js
Adds a new Entity type `EnemyInstance`, and its corresponding module `EnemyInstances`.
I discovered when working on another feature that there is no support in the existing `Enemies` module for tracking individual adds throughout an encounter, since adds share a `targetId` and are only separated by `targetInstance`.   This PR adds that support by accounting for `targetInstance` when handling Enemy data.
The existing `Enemies` module has not been touched, to preserve compatibility with existing code.
> [Core] EnemyInstance and EnemyInstances

- src/Parser/MarksmanshipHunter/CHANGELOG.js
- src/Parser/MarksmanshipHunter/CombatLogParser.js
- src/Parser/MarksmanshipHunter/Modules/Features/CastEfficiency.js
- src/Parser/MarksmanshipHunter/Modules/Spells/Trueshot.js
- src/Parser/MarksmanshipHunter/Modules/Traits/QuickShot.js
- src/common/SPELLS_HUNTER.js
This adds a trueshot module for future usage for the advanced cooldown tracking, for now it simply has rank 0-7 of Quick Shot which reduces the CD of Trueshot with diminished values pr rank after initial 3. 
From my testing of various logs, it's accurate now when Convergence, Legendary boots and/or T192p aren't involved. They are on a future to-do list, but this solves the first hurdle when it comes to the CD of Trueshot. 
Example of before: 
Example of after:
> [Marksmanship] Trueshot CD reduction from artifact traits

- src/Parser/RestoDruid/CHANGELOG.js
- src/Parser/RestoDruid/CombatLogParser.js
- src/Parser/RestoDruid/Modules/Features/Ironbark.js
- src/common/SPELLS_DRUID.js
Added Ironbark module using a LazyLoaded stats box because an extra query is required. The stats generated here could be used to generate the NYI ArmorOfTheAncients trait, but I don't want to implement lazy loading in the Relic Trait box at the moment.
> [resto druid] Added ironbark module

- src/Parser/ElementalShaman/Modules/Features/CastEfficiency.js
- src/common/SPELLS_SHAMAN.js
Just two very simple fixes of bugs with existing implementation for shamans using Storm Elemental (SE) talent
1. Maelstorm overview now works by registering maelstorm generating spell of the SE in SPELLS (doesn't work at all, when SE is selected on live)
2. Cast efficiency analysis switches between SE and Fire Elemental, based on talents selected (on live you are blamed for not casting FE if you have SE talented).
> [Elemental Shaman] Storm Elemental bugfix

- src/Main/App.js
- src/Parser/RetributionPaladin/CHANGELOG.js
- src/Parser/RetributionPaladin/Modules/Items/AshesToDust.js
- src/Parser/RetributionPaladin/Modules/Items/ChainOfThrayn.js
- src/Parser/RetributionPaladin/Modules/Items/Tier20_2set.js
- src/Parser/RetributionPaladin/Modules/Items/WhisperOfTheNathrezim.js
- src/Parser/RetributionPaladin/Modules/PaladinCore/GetDamageBonus.js
- src/Parser/RetributionPaladin/Modules/PaladinCore/Retribution.js
- src/Parser/RetributionPaladin/Modules/PaladinCore/getDamageBonusStacked.js
- src/Parser/RetributionPaladin/Modules/Traits/DeliverTheJustice.js
- src/Parser/RetributionPaladin/Modules/Traits/HighlordsJudgment.js
- src/Parser/RetributionPaladin/Modules/Traits/MightOfTheTemplar.js
- src/Parser/RetributionPaladin/Modules/Traits/RighteousVerdict.js
The Wrath of the Ashbringer trait is a like hacky but I couldn't think of a better way to do it. It gets the average DPS of wings over the course of the fight then calculates how much damage 2 extra seconds of wings would be. I also couldn't figure out how to implement http://www.wowhead.com/spell=184759/sharpened-edge and am looking for suggestions on that. Otherwise should be good. Please let me know if there is anything you think I should change!
> [Retribution] Added in a relic traits stat box

- src/Parser/WindwalkerMonk/Modules/Features/CastEfficiency.js
- src/common/SPELLS_MONK.js
Power strikes looks like it has some different spell ID's for the talent itself, the buff it grants and the consumption of the buff. I've changed it to the buff consumption that grants chi so it can be used for resource tracking, but unsure if that's the correct approach.
> Expanded Windwalker CastEfficiency and change to a spell ID

- src/Main/App.css
Noticed this while opening the page, triggered my OCD so here is a quick fix.
Tested on Google Chrome on Windows 10
> Fixed main page button alignment

- src/Parser/RetributionPaladin/Modules/HolyPower/HolyPowerTracker.js
- src/common/SPELLS_PALADIN.js
For some reason there is a weird spell ID for divine hammers generating 2 and 3 holy power that I wasn't tracking my module. I fixed and updated it however.
> [Retribution] Fixed a bug where divine hammers didn't appear on my holy power graph

- src/Parser/MarksmanshipHunter/CombatLogParser.js
- src/Parser/MarksmanshipHunter/Modules/Features/AimedInVulnerableTracker.js
- src/Parser/MarksmanshipHunter/Modules/Features/CooldownTracker.js
I added a minor grammar fix to a module and added our execute into our cooldown window until I figure out a better way of dealing with it (some sort of graph/tab + tracking of buffstacks) - but for now, the information is accessible and good to see if you let your execute buff drop over the encounter. 
Example:
> [Marksmanship] Adding our execute into Cooldowntracker for now

- src/Parser/FrostMage/Modules/Features/AlwaysBeCasting.js
- src/Parser/FrostMage/Modules/Features/CastEfficiency.js
- src/Parser/FrostMage/Modules/Features/WintersChill.js
- src/common/SPELLS_MAGE.js
The Ice Lance ID that Winter's Chill was using was different than the ID that was being used in Cast Efficiency and Always Be Casting. As a result, Cast Efficiency said there were 0 casts of Ice Lance and Always Be Casting said that the Dead Time was high.
> [Mage] Fix for Ice Lance/Winters Chill

- src/Parser/FrostMage/Modules/Items/ShardOfTheExodar.js
- src/Parser/FrostMage/Modules/Items/Tier20_2set.js
In Tier20_2set fixed incorrectly defined id, standardized result format.
In ShardOfTheExodar made 'possible lusts' calculation correct for fights longer than 10 minutes.
> [frost mage] Fixes to Tier20_2set and ShardOfTheExodar

- src/Parser/GuardianDruid/Modules/Features/FrenziedRegenGoEProcs.js
- src/Parser/GuardianDruid/Modules/Spells/IronFur.js
- Unbuffed Frenzied Regeneration statistic hides itself if there are 0 FR casts
- Ironfur stack count returns 0 instead of undefined if there are no hits registered at 0 stacks
- `1 stacks` -> `1 stack` in Ironfur statistic
> [Guardian] Fix display bugs in Ironfur and Frenzied Regen modules

- src/Parser/MarksmanshipHunter/CHANGELOG.js
- src/Parser/MarksmanshipHunter/CombatLogParser.js
- src/Parser/MarksmanshipHunter/Modules/Features/TimeFocusCapped.js
- src/Parser/MarksmanshipHunter/Modules/FocusChart/FocusTracker.js
Added a statisticbox for the focus tracking module. Right now it doesn't have a suggestion yet, but Putro has confirmed that he'll take care of that (and he has the best numbers for it, too). 
Screenshots:
> [MMS HUNTER] Added Focus Capped Statisticbox

- src/Parser/Core/Modules/Items/PrePotion.js
- src/Parser/FrostMage/Modules/Features/ThermalVoid.js
- src/Parser/FrostMage/Modules/Features/WintersChill.js
Updated PrePotion to use the new prepull buff handling. Should make the code less fragile with respect to potion durations.
Added check for prepull cast to ThermalVoid
Fixed a bug in WintersChill where it wasn't differentiating between multiple enemies with the same name. This should eliminate instances where missed winter's chill was a negative number. Fixed a bug where the suggestion wasn't correctly displaying number of missed winter's chill (was referencing `this.missed` when it needed to be using `missed`)
> [core / frost mage] Misc fixes

- src/Parser/WindwalkerMonk/CombatLogParser.js
- src/Parser/WindwalkerMonk/Modules/Items/KatsuosEclipse.js
I tried using the `on_toPlayer_removebuff(event)` as seen in the Shadow Priest Module, but was not getting correct results from it.
Also, since Windwalker is an energy class with a fixed 1 second GCD, should all spells be listed as `STATIC_GCD_ABILITIES` instead of `ABILITIES_ON_GCD`?
> [Windwalker] Updated AlwaysBeCasting

- src/Parser/Core/CombatLogParser.js
The numbers from the DistanceMoved module couldn't possibly be correct. I'm consistently seeing reports that the player moved many miles over the course of a few minute fight. This is happening across all logs I see.
This PR simply disables the module until we figure out what's wrong.
> [core] Disabled DistanceMoved module

- src/Parser/Mage/Fire/Modules/Features/CastEfficiency.js
Removed suggestion/canBeImproved from Living Bomb, as it's only supposed to be used in AoE and shouldn't be cast on CD.
Changed classification of Cinderstorm from ROTATIONAL_AOE to ROTATIONAL. When talented, Cinderstorm should be used even on single target.
> [fire mage] Fixed minor CastEfficieny issues

- src/Parser/RetributionPaladin/Modules/Items/WhisperOfTheNathrezim.js
Looking over some more top logs I think that the percents I was using to show suggestions was a little too strict. Zero is going to try and get feedback from mods in the paladin discord but until then I still have to use kinda feely numbers.
> [Retribution] Changed Whispers of the Nathrezim suggestion values

- src/Parser/UnsupportedSpec/CHANGELOG.js
- src/Parser/UnsupportedSpec/CONFIG.js
Implemented a fix for this issue #558. 
This is just a quick fix. I left the current statistics box with the Unsupported Spec information along, as I feel that needs to be front and center.
This just ensures if a user clicks `More Information` the app does not crash.
> Fix: Issue #558: Clicking "more information" on an UnsupportedSpec report crashes the app

- src/Parser/RetributionPaladin/CONFIG.js
There are 5 main things you can do to improve your ret play:
1. Avoid capping your holy power
2. Using's Avenging Wrath/Crusade as much as possible
3. Making sure you're using holy power spenders inside of judgment
4. Using all of your blade of wrath procs
5. Using your artifact ability as much as possible.
I have implemented modules for all of these as well as all the top tier legendaries and some fluffy extra stats. I think using this implementation of the ret spec is a good starting spot but is no way complete yet. For this reason I think the spec completeness can be bumped up to good.
> [Retribution] Spec completeness upgraded to good

- src/Parser/Warrior/Arms/CHANGELOG.js
- src/Parser/Warrior/Arms/CONFIG.js
- src/Parser/Warrior/Arms/CombatLogParser.js
- src/Parser/Warrior/Arms/Modules/BuffDebuff/ColossusSmashUptime.js
- src/Parser/Warrior/Arms/Modules/BuffDebuff/TacticianProc.js
- src/common/SPELLS/WARRIOR.js
- tactician proc resets the cd on mortal strike and colossus smash
- Including the Notes from https://github.com/WoWAnalyzer/WoWAnalyzer/issues/571
> Arms Warrior - Tactician procs value

- src/Parser/Monk/Brewmaster/Modules/Features/AlwaysBeCasting.js
Brewmaster Base GCD is 1500 which is in the module correctly defined for every class. Brewmaster are reducing the GCD to max  1000 with haste. Just a fix because WOPR set it to 1sec always, which isn't true.
it's required because otherwise the downtime would be doubled in the summary.
> Brewmaster downtime fix

- src/Parser/RetributionPaladin/Modules/Features/CastEfficiency.js
- src/Parser/RetributionPaladin/Modules/Features/Judgment.js
- src/Parser/RetributionPaladin/Modules/Items/Tier20_2set.js
- src/Parser/RetributionPaladin/Modules/Items/WhisperOfTheNathrezim.js
> [Retribution] Tooltip updates

- src/Parser/Core/Modules/Items/GnawedThumbRing.js
Fixes #585 
Gnawed thumb ring only increases magic damage these days, so this excludes physical damage done while the buff is up.
Live: 
Post-fix:
> Fixing Gnawed Thumb Ring

- src/Parser/Mage/Frost/Modules/Features/ThermalVoid.js
- src/Parser/Mage/Frost/Modules/Features/WintersChill.js
Adjusted Thermal Void to exclude the uptime and cast for Icy Veins if it does not complete before the fight ends as it skews the average in a negative way.
Also adjusted Winters Chill to account for "Double Ice Lance" Hits within the Winter's Chill Window (which was causing this number to go negative or potentially hide a missed window).... This also counts the number of times the player managed to get 2 Ice Lance's in the window, but i havent decided how i want to use that data yet ... so for now it counts it and doesnt do anything further with it. Ill do something with that data at some point.
> [Frost Mage] Thermal Void and Winters Chill Fixes

- src/Parser/Monk/Mistweaver/CHANGELOG.js
- src/Parser/Monk/Mistweaver/Modules/Spells/RenewingMist.js
- src/Parser/Monk/Mistweaver/Modules/Spells/ThunderFocusTea.js
- src/Parser/Monk/Mistweaver/Modules/Spells/UpliftingTrance.js
Changed the format on 3 statistic boxes. No additional changes other than just the presentation of the current statistics.
Relevant SS's below:
Thunder Focus Tea Changes:
Uplifting Trance Changes:
Dancing Mist Changes:
> [Mistweaver Monk] Statistic Box Format Updates

- src/Parser/Hunter/Marksmanship/Modules/Talents/TrueAim.js
Minor update adding damage contribution to this talent. 
I'm also posting this for feedback on wording of the last line ``Aimed shot did x% and Arcane shot did y%``. I want this to showcase which abilities gained what % of the total damage contribution from the talent, but the wording right now irks me - any ideas are welcome! 
Tooltip now reads like this:
> [Marksmanship] True aim update

- src/Main/App.css
This gets fixed:
The header's z-index of 10 got caped to 1 before this commit.
> Fixes the z-index of the header overlay

- src/Parser/Shaman/Elemental/CHANGELOG.js
- src/Parser/Shaman/Elemental/Modules/Talents/TotemMastery.js
So that Totem Mastery can show its uptime (and not 0.00%...)
> (fix-ele) Remove Storm Totem which is a Summon Event and not a Buff.

- src/Parser/Mage/Frost/Modules/Cooldowns/FrozenOrb.js
Frost Mage Tier20 4set used to cause Brain Freeze to reduce remaining CD on Frozen Orb by 5 seconds. In 7.3.2, this was reduced to 4 seconds.
> [frost mage] Fix for t20 4set nerf

- src/Parser/Mage/Shared/Modules/Features/UnstableMagic.js
- src/common/SPELLS/MAGE.js
It appears Unstable Magic has a different damage ID depending on spec. I've fixed the module to handle the IDs for each spec.
> [mage] Fixed a bug in UnstableMagic where the wrong ID was being used for Fire

- src/Parser/Mage/Fire/Modules/Items/Tier20_4set.js
The implementation of Fire Mage Tier20 4set wasn't working at all in practice.
Unfortunately, the solution had to be somewhat complex in practice because of how the bonus was applied in logs, and due to fire mage cast time / spell travel time issues.
I also updated the display of the bonus.
> [fire mage] Fixed bugs in 4pc t20 calculation

- src/Parser/Mage/Frost/Modules/Features/WintersChill.js
- src/common/SPELLS/MAGE.js
We now also track frostbolt hits into Winter's Chill, and added a suggestion for it as well. Suggestion now triggers on missed PPM rather than total missed. Updated display of statistic to show % utilization, and added a stat for double icelance hits.
> [frost mage] Updated Winter's Chill display

- src/Parser/Hunter/Marksmanship/Modules/Talents/PatientSniper/PatientSniperTracker.js
Not proud of how I solved it but works as of now. 2 issues this solves:
1. If for some reason, Aimed Shot was cast but never landed and did damage (picture firing AS at Sisters of the Moon right before the boss despawns and another one spawns), it broke all Patient Sniper bonus damage from that point forward
=> solved by filtering out cast events that are too old - AS has a fast travel time, around <700ms so I added 1s max travel time
2. If Vulnerable debuff windows were slightly larger than 7000ms due to lag (removedebuff() was called let's say 70ms later than it *should've been*), then the difference between shot cast and start of the debuff window was > 7000ms which resulted in timeIntoVulnerable = 7 
=> solved by adding 100ms lag tolerance
> [Marksmanship] Bugfixes for Patient Sniper

- src/Parser/Mage/Frost/Modules/Features/WintersChill.js
- src/common/SPELLS/MAGE.js
Further updated Winter's Chill to accept Glacial Spike as a preceding hardcast. Modified suggestions / statistics to mention Glacial Spike as a preceding hardcast only if player is specced for it.
Updated tooltip to be more descriptive.
> [frost mage] WintersChill includes Glacial Spike

- src/Main/StatisticBox.js
- src/Parser/Shaman/Elemental/CHANGELOG.js
- src/Parser/Shaman/Elemental/CombatLogParser.js
- src/Parser/Shaman/Elemental/Modules/Features/Overload.js
Added a option/property to align the StatisticBox icon and refactored the overload module (moved it outside the CombatLogParser)
> [ele shami] Refactored Overloads and added option to align the StatisticBox Icon

- src/Parser/Mage/Frost/CHANGELOG.js
- src/Parser/Mage/Frost/CombatLogParser.js
- src/Parser/Mage/Frost/Modules/Features/BrainFreeze.js
- src/Parser/Mage/Frost/Modules/Features/IcicleTracker.js
- src/Parser/Mage/Frost/Modules/Features/SplittingIce.js
- src/common/SPELLS/MAGE.js
Added a splitting ice module that calculates total damage boost and also breaks it down by primary target boost and secondary target cleave.
Also renamed ICICLES spell to ICICLE_DAMAGE, as the actual spell name is "Icicle" and I want to make it more easily differentiated from ICICLES_BUFF
> [frost mage] Added Splitting Ice module

- src/Parser/Druid/Restoration/Modules/Features/StatWeights.js
Removed all the temp stat tracking stuff from StatWeights and integrated StatTracker.
I know I'll soon be refactoring again to use the generalized StatWeights module, but I'm just doing this to make it easier to compare when I do that larger refactor, and so that I get this functionality live sooner.
> [resto druid] Integrated StatTracker into StatWeights module

- src/Parser/Druid/Restoration/Modules/Features/StatWeights.js
Accidentally introduced this when integrating StatTracker. When player has leech, this bug makes their weight VERY off.
> [resto druid] StatWeight bugfix

- src/Parser/DeathKnight/Unholy/Modules/Features/CooldownTracker.js
- src/common/SPELLS/DEATH_KNIGHT.js
Unholy only has one cooldown where we have a window where we care about what we cast so this is a pretty small feature.  Highly useful though as most of our damage comes from that CD.
> [Unholy Death Knight] Added cooldown tracker for unholy

- src/Parser/Priest/Discipline/Modules/Spells/TouchOfTheGrave.js
fixed a small issue where the touch of the grave module would appear regardless of race in disc priest analysis.
> Disc Touch of the Grave Load Only when Undead

- src/Parser/Mage/Frost/Modules/Features/IceLance.js
Ice Lance suggestion tip showed actual as 'missed' when it was actually the percentage hit. Uncapitalized 'recommended' to match style.
These changes are entirely to output text, and not to code.
> [frost mage] Fixed IceLance suggestion tip

- src/Parser/Shaman/Elemental/Modules/Features/Overload.js
> [Ele Shami] Changed the overload StatisticBox layout to match the new left text-alignment.

- src/Parser/Core/Modules/Features/BaseHealerStatWeights.js
- src/Parser/Druid/Restoration/Modules/Features/Mastery.js
- src/Parser/Druid/Restoration/Modules/Features/StatWeights.js
- src/Parser/Druid/Restoration/SpellInfo.js
Currently, I completely copy the standalone version's functionality, overriding core version where appropriate.
I also needed to add missing `_hasteHpm` function to BaseHealerStatWeights.
> [resto druid] Migrated StatWeights to use the new core version

- src/Parser/DemonHunter/Vengeance/Modules/PainChart/Pain.js
It was an error with the WCL api response: the response for the pain data chart was returning an empty array because the log from WCL was corrupted. So I now output an error message and prevents the analyzer to crash.
> [Vengeance] Pain chart error handling message

- src/Parser/Core/Modules/CancelledCasts.js
- src/Parser/Mage/Frost/CHANGELOG.js
- src/Parser/Mage/Frost/CONFIG.js
- src/Parser/Mage/Frost/CombatLogParser.js
- src/Parser/Mage/Frost/Modules/Features/CancelledCasts.js
- src/Parser/Mage/Shared/Modules/Features/CancelledCasts.js
Module for showing the % of casts that were cancelled. Tooltip also shows the breakdown of spells cast, completed, and cancelled. Also filters out spells with a cast time, but the cast time was made instant by some proc or other event (Like Blizzard - Instant if Frozen Orb is up) .... but if the dev includes a pure instant cast spell in the list, then it will likely screw with the results because Instant Cast Spells dont have a "begincast", but spells that are sometimes instant do.
> [Core/FrostMage] Cancelled Casts

- src/Parser/Mage/Frost/Modules/Features/ArcticGale.js
- src/Parser/Mage/Frost/Modules/Features/BrainFreeze.js
- src/Parser/Mage/Frost/Modules/Features/FrostBomb.js
- src/Parser/Mage/Frost/Modules/Features/IceLance.js
- src/Parser/Mage/Frost/Modules/Features/IcicleTracker.js
- src/Parser/Mage/Frost/Modules/Features/SplittingIce.js
- src/Parser/Mage/Frost/Modules/Features/ThermalVoid.js
- src/Parser/Mage/Frost/Modules/Features/WintersChill.js
- src/Parser/Mage/Shared/Modules/Features/MirrorImage.js
- src/Parser/Mage/Shared/Modules/Features/RuneOfPower.js
- src/Parser/Mage/Shared/Modules/Features/UnstableMagic.js
The Frost Mage statistic ordering so far is mostly "unexamined copy pasting of previous statistic orders", so I'm doing something that makes sense.
At the top we'll have Damage Done, Downtime, and the soon to be implemented Cancelled Casts. Below that will be the 3 core spec utilization stats, Ice Lances Shattered, Brain Freeze Util, and Winters Chill Util. Below that will be all the talent based stats, with preference given to the Glacial Spike or Thermal Void stat because they're the biggest gameplay choice in Frost Mage talents.
> [frost mage] Redo statistic ordering

- src/Parser/Mage/Frost/CONFIG.js
@Sharrq and I believe Frost Mage completeness should be upgraded to 'Good'.
We've implemented the many suggestions from Mage discord, and we now offer statistics and suggestions for every facet of the core Frost Mage rotation. Analysis is provided for all reasonably analyzable talents. All legendaries are supported, along with t20 2set and 4set (pending the PRs listed below).
While t19 2set is still commonly used, there is unfortunately no reasonable way to make a statistic out of it.
We have not implemented a Stat Value module or a Relic Traits Value module, and this is an intentional decision. Frost Mage SimC is actively maintained and is the go-to gearing tool for the Mage community. Due to the heavily proc based nature of Frost Mage gameplay we believe sims will be able to provide …
> [frost mage] Upgraded completeness to 'good'

- src/Parser/Monk/Mistweaver/Modules/Spells/RenewingMist.js
Update to fix errors with `SpellUsable` module and Renewing Mist.
> [Mistweaver Monk] SpellUsable Fixes for Renewing Mist

- src/Parser/Druid/Restoration/Modules/Features/NaturesEssence.js
- src/Parser/Druid/Restoration/SuggestionThresholds.js
The NaturesEssence module was intended to make sure you were hitting enough injured targets with WildGrowth, but its method of detection had a high rate of false positives and false negatives.
I've used a completely different method that is more complicated but more directly measures what it's supposed to measure.
> [resto druid] Reworked NaturesEssence

- src/Parser/Monk/Windwalker/CHANGELOG.js
- src/Parser/Monk/Windwalker/CombatLogParser.js
- src/Parser/Monk/Windwalker/Modules/Talents/EnergizingElixir.js
Calculates the amount of energy and chi gained from the Energizing Elixir talent for Windwalker parses, using the energize event.
NOTE: The chi is calculated and available in the `chiGained` field but the engine is currently always returning a static amount of chi wasted on cast (incorrectly) and therefore it is not shown yet.
Coryn - Peak of Serenity
> WW Energizing Elixir Resource gains (Chi calc'ed not shown)

- src/Parser/Hunter/BeastMastery/Modules/Items/Tier20_4p.js
- src/Parser/Hunter/BeastMastery/Modules/Traits/TitansThunder.js
I fucked up so it would crash here: https://wowanalyzer.com/report/4XcyFdNLQYWAJBzH/31-Mythic+Kil'jaeden+-+Kill+(9:24)/Wulfeh
This fixes it and removes some debug=true, aswell as fixing structure in if statements to ensure all Titan's Thunder casts are counted properly.
> [Beast Mastery] Fixes a crash, and some fine tuning

- src/CHANGELOG.js
- src/Parser/Core/Modules/ManaValues.js
[![Screenshot from Gyazo](https://gyazo.com/1848f79eff7d6154832cc1b2eabeca16/raw)](https://gyazo.com/1848f79eff7d6154832cc1b2eabeca16)
(Ignore the branch name, I got the issue numbers mixed up). This is not 100% accurate since it gets the endingMana from the last cast event from the player, so the endingMana variable can be potentially higher (if the player didn't cast anything in the last X seconds of the encounter). 
This can be solved by calculating the players MP5 (or mana gained per second) and checking the time differences between the last cast event and the on_finished timestamp, and calculating the players endingMana. However this is not an easy task as there's many edge cases to consider that may alter the MP5 (unless there's a property for that). (Such as items, traits, spells …
> Added suggestions on mana levels on encounter finished. Fixes #82

- src/Parser/Hunter/Marksmanship/CHANGELOG.js
- src/Parser/Hunter/Marksmanship/CombatLogParser.js
- src/Parser/Hunter/Shared/FocusChart/Focus.js
- src/Parser/Hunter/Shared/FocusChart/FocusTracker.js
I figure it's probably easier to tell me what's stylistically wrong with this when you can see the code yourself. The issue was with extrapolateFocus(), as it was called after every event- now it only iterates appropriate indexes each call, instead of the entire thing. Vastly decreased load times on my machine.
> Focustracker performance fix

- src/Parser/Core/Modules/Haste.js
- src/Parser/Core/Modules/StatTracker.js
Handling for rating changes had previously been moved to the StatTracker module, but this meant that the Haste module no longer was tracking haste rating changes at all.
I've modified StatTracker so it generates a fabricated event any time stats change, and I've modified Haste to listen for those events and apply the appropriate change (including firing its own changehaste event).
It's plausible that the Haste module as a whole is due for a refactor, but in this PR I make the 'lightest touch' change I can while still implementing the desired functionality in a non-hacky manner.
> [core] Added handling for Haste rating changes to Haste analyzer

- src/Parser/Core/CombatLogParser.js
- src/Parser/Core/Modules/Items/EonarsCompassion.js
- src/common/ITEMS/OTHERS.js
- src/common/SPELLS/OTHERS.js
Added the antorus pantheon healing trinket (eonar's compassion).
logs:
https://www.warcraftlogs.com/reports/thQVp9F4GM8qryAR
any fight on character charite
the pantheon buff is only used in Varimathras wipe 3 fight.
The trinket icon is currently not displaying.
http://blzmedia-a.akamaihd.net/wow/icons/56/inv_antorus_green.jpg returns a 404 error
hope this should be patched in 7.3.5
(btw https://render-us.worldofwarcraft.com/icons/56/inv_antorus_green.jpg works fine)
> [Healing Trinket] Eonar's compassion

- src/Parser/Core/Modules/DamageDone.js
- src/Parser/Core/Modules/HealingDone.js
Changed the 'totals' part of each tooltip to be more concisely worded. For the 'pets contribution' part of DamageDone, updated the display and also made it only show if the player had >0 pet damage.
> [core] Updated appearance of DamageDone and HealingDone tooltips

- src/Parser/Hunter/Marksmanship/Modules/Items/TarnishedSentinelMedallion.js
This fixes an issue where sometimes medallionCasts would be 4, when in fact only 3 were cast. (or other math errors)
> [Marksmanship] Tarnished Sentinel Medallion fix

- src/Parser/Priest/Discipline/CHANGELOG.js
- src/Parser/Priest/Discipline/Modules/Features/AtonementHealingDone.js
- src/Parser/Priest/Discipline/Modules/Items/MarchOfTheLegion.js
- src/Parser/Priest/Discipline/Modules/Items/NeroBandOfPromises.js
- src/Parser/Priest/Discipline/Modules/Items/TarnishedSentinelMedallion.js
- src/Parser/Priest/Discipline/Modules/Spells/TouchOfTheGrave.js
Fixes this bug: https://sentry.io/share/issue/33ce182b00b64e65843b0c403b2b69c5/
Ideally the atonement source would always be there. I haven't figured out exactly why it's not always there, but for now I've more gracefully handled the exceptions so that the healing just won't be added in, which is much better than crashing the page.
> Disc Crash Fix

- src/Parser/Priest/Discipline/Normalizers/EstelNormalizer.js
fixes the sentry.io error from this log: https://www.warcraftlogs.com/reports/PFv7HpMc4ntX9k3W/#fight=31&type=summary
https://sentry.io/share/issue/5b77dc87172c4e4d90f7b95cef359a48/
> EstelNormalizer Null event.ability handling

- src/Parser/Hunter/Marksmanship/Modules/Features/CooldownThroughputTracker.js
- src/common/SPELLS/HUNTER.js
Fixes that the tethers and stuns from Binding Shot show up as casts in the cooldown window, even they aren't something the player actually cast. 
going from
to
> [Marksmanship] remove bindingShot from CooldownThroughput

- src/Parser/Priest/Discipline/Modules/Spells/TouchOfTheGrave.js
In the Touch of the Grave Undead racial, the direct healing wasn't added in the count. The spell generates healing from atonement but also direct healing on self. This PR adds the healing to the value of the racial and gives a breakdown in the mouse over.
> [Discipline Priest] Fixed value for Undead Racial

- src/Parser/Mage/Frost/Modules/Items/Tier20_4set.js
To be clear, the actual bonus procs on apply or refresh, and until this change our code was only checking apply.
> [frost mage] Fixed a bug where 4t20 CDR wasn't being applied on Brain Freeze refresh

- src/Parser/Druid/Restoration/CombatLogParser.js
- src/Parser/Druid/Restoration/Modules/Items/SoulOfTheArchdruid.js
- src/Parser/Druid/Restoration/Modules/Talents/SoulOfTheForest.js
Previously if player had SotA, there would be no SotF display and instead a rough duplicate of it would be put in the Items bar.
Now, you get the SotF statistic if you talented for SotF or if you have SotA, and if you have SotA you get an item entry saying "This gave you Soul of the Forest".
> [resto druid] Changed Soul of the Archdruid display to be like for other classes

- src/Parser/Core/Entity.js
- src/Parser/Paladin/Holy/Modules/Talents/DevotionAura.js
- src/common/format.js
Seemed silly that Entity didn't have support for sourceID filtering, so I added it.
`getBuffs` was only called in one place and it was obviously intended for sourceID filtering, so I removed it and replaced it in the once place it was used.
> [core] Added some documentation to format and Entity, and added support for sourceID filtering to Entity

- src/Parser/Mage/Frost/Modules/Cooldowns/IcyVeins.js
Minor fix for the Icy Veins Cooldown Reduction file. Just noticed that the class name was never changed from FrozenOrb
> [Frost Mage] Fix Icy Veins

- src/Parser/Mage/Fire/CombatLogParser.js
- src/Parser/Mage/Fire/Modules/Features/AlwaysBeCasting.js
- src/Parser/Mage/Frost/Modules/Features/Abilities.js
- src/Parser/Mage/Frost/Modules/Features/AlwaysBeCasting.js
- src/Parser/Mage/Frost/Modules/Features/IceLance.js
- src/Parser/Mage/Frost/Modules/Features/SplittingIce.js
- src/Parser/Mage/Frost/Modules/Features/WintersChill.js
- src/Parser/Mage/Frost/Modules/Items/MagtheridonsBanishedBracers.js
- src/common/SPELLS/MAGE.js
Misc Fixes and Tweaks for Frost and Fire Mage.
- Removed the Non Standard Icon/StatisticBox in the Fire AlwaysBeCasting Module
- Upped Frost Abilities to 90% Recommended Efficiency
- Removed noSuggestion/noCanBeImproved from Icy Veins
- Added some seldom used abilities to Fire/Frost AlwaysBeCasting, for those edge case fights where they are needed
- Added CancelledCasts to Fire
- Added missing cooldown timer for Comet Storm
- Renamed the SPELLS entry for ICE_LANCE_CAST to match all the other spells (where the base ICE_LANCE is the cast ID and ICE_LANCE_DAMAGE is the damage ID)
> [Mage] Misc Fixes/Tweaks

- src/Main/Timeline/Events.js
- src/Parser/Core/Modules/SpellUsable.js
DON'T MERGE just yet
Fixes #793 - I chose option 1 for fixing this, because option 1 was obviously the correct choice.
The reason I say "don't merge this yet" is because the cooldown tooltip on charged spells is now a bit janky -- it shows the total amount of contiguous time the spell was recharging, which typically has nothing to do with the spell's actual cooldown. I put up this PR to solicit ideas as to how this should be handled. My current best idea is that some sort of marker should delineate each gained charge, and the tooltip on each segment should display the amount of time it took that charge to be gained.
> [core] Fixed an issue where spell timelines weren't rendered properly for spells with charges

- src/Parser/Core/Modules/CastEfficiency.js
Previously had accidentally created a situation where if player never cast a spell, it was treated same way as a spell without a cooldown, which is to say "no suggestion" and "no can be improved"
> [core] Fixed a bug in CastEfficiency where spells with zero casts wouldn't get suggestions / can be improved

- src/Parser/Core/Modules/StatTracker.js
Analyzer was crashing on StatTracker if stat buff was detected, but its associated item didn't exist. This could happen if the player switches to the trinket that makes the buff mid encounter, which can easily happen during M+.
There's no good way to fully handle this case because we still don't get the itemlevel of the trinket in question, but I can at least make this not crash by just ignoring the buff entirely.
>  [core] Fixed a bug where a crash could sometimes occur when player switches items during encounter

- src/Parser/Rogue/Subtlety/CombatLogParser.js
- src/Parser/Rogue/Subtlety/Modules/Talents/DFA/DeathFormAbove.js
- src/common/SPELLS/ROGUE.js
Small PR that tracks correct DfA usage. 
This is currently core for Subtlety and the only viable build.
Makes sure that the DfA eviscerate hit is buffed by both Dark Shadow and Symbols of Death.
> Sub rogue, Death from Above usage

- src/Parser/Core/Modules/Entities.js
The `...buff` used when triggering the `changebuffstack` contains the timestamp field from the internal buff object, which is the timestamp when the buff was *initially applied*, rather than the timestamp the stack changed.
This was causing some truly esoteric bugs in the Haste module.
> [core] Fixed a bug where changebuffstack events were often given the wrong timestamp

- src/Main/PlayerSelecter.js
Wrapping the loading spinner inside of a `container` div makes the text location more visible to the user and more consistent with the headers of the player and fight selection pages.
Notice the text sits off to the left of the screen and is not very visible to the user.
Now the text is aligned with the headers of both the Player Selection and Fight Selection pages.
> PlayerSelector Loading Spinner Styling Consistency

- src/Parser/Rogue/Subtlety/CombatLogParser.js
- src/Parser/Rogue/Subtlety/Modules/Talents/DarkShadow/DarkShadowSpecterOfBetrayal.js
Specter  remains the BIS trinket for Antorus on ST fights.
Checking that it is used together with Dance to benefit from 30% Dark Shadow buff.
> [Sub Rogue] Specter usage

- src/Parser/Warlock/Destruction/Modules/Features/UnusedLordOfFlames.js
Self-explanatory, probably due to the rework, getAbility().casts was returning undefined when it wasn't cast.
> [Bugfix] [Destruction] Fixed the Lord of Flames bug.

- src/Parser/Hunter/BeastMastery/Modules/Traits/TitansThunder.js
No clue how both made it in, there weren't two when I made the push I'm pretty sure.. (relooking there was - im just an idiot)
Fixes this: 
https://github.com/WoWAnalyzer/WoWAnalyzer/pull/915#issuecomment-348834643
> Fixes double init

- src/Parser/Core/Modules/NetherlightCrucibleTraits/MurderousIntent.js
- src/Parser/Core/Modules/NetherlightCrucibleTraits/Shocklight.js
- src/Parser/Druid/Restoration/CHANGELOG.js
- src/Parser/Druid/Restoration/CombatLogParser.js
- src/Parser/Druid/Restoration/Modules/NetherlightCrucibleTraits/LightSpeed.js
- src/Parser/Druid/Restoration/Modules/NetherlightCrucibleTraits/MasterOfShadows.js
- src/Parser/Druid/Restoration/Modules/NetherlightCrucibleTraits/MurderousIntent.js
- src/Parser/Druid/Restoration/Modules/NetherlightCrucibleTraits/NLCTraits.js
- src/Parser/Druid/Restoration/Modules/NetherlightCrucibleTraits/Shocklight.js
- src/common/SPELLS/OTHERS.js
* Core: Murderous Intent and Shocklight shows the average stat gained instead of uptime (this infromation is already shown on WCL). This also takes additional levels into account.
* Resto Druid: Murderous Intent, Shocklight, Master of Shadows (new), Light Speed (new) shows the throughput healing based on the statweights module.
> NLC improvements

- src/Parser/Core/Modules/Items/SeaStarOfTheDepthmother.js
- src/Parser/Core/Modules/Items/SeepingScourgewing.js
- src/Parser/Core/Modules/Items/SephuzsSecret.js
- src/Parser/Core/Modules/Items/SpecterOfBetrayal.js
- src/Parser/Core/Modules/Items/SpectralThurible.js
- src/Parser/Core/Modules/Items/TarnishedSentinelMedallion.js
- src/Parser/Core/Modules/Items/TarratusKeystone.js
- src/Parser/Core/Modules/Items/TerrorFromBelow.js
- src/Parser/Core/Modules/Items/TomeOfUnravelingSanity.js
- src/Parser/Core/Modules/Items/UmbralMoonglaives.js
- src/Parser/Core/Modules/Items/Velens.js
- src/Parser/Core/Modules/Items/VialOfCeaselessToxins.js
- src/Parser/Core/Modules/StatTracker.js
- src/common/SPELLS/OTHERS.js
ALL - Added item's tooltip to comment at top of file
Seeping Scourgewing - Fixed a bug where absorbed damage wasn't being counted, and added a tracker for how many times player got 'isolated' procs.
Scepter of Betrayal - Fixed a bug where absorbed damage wasn't being counted, and updated display.
Spectral Thurible - Added 'average targets hit per proc' to tooltip.
Tarnished Sentinel Medallion - Updated to use an Array instead of a Set, and updated display.
Terror from Below - Updated display.
Tome of Unraveling Sanity - Updated display to also include average crit gain from proc. Also added proc to StatTracker.
Umbral Moonglaives - Fixed a bug where absorbed damage wasn't being counted, fixed a bug where 'cast' display was actually showing the number of ticks. Added 'average targets hit …
> [core] Core items update (Q through Z) 

- src/Parser/Mage/Frost/Modules/Features/ThermalVoid.js
Lowered threshold for Thermal Void warnings partly because it wont be as possible to hit 45 seconds as T20 4pc fades away. Also because 45 seconds was a tad bit high considering its partly based on RNG
> [Frost Mage] Lower Thermal Void Avg Time

- src/Parser/Core/Modules/StatTracker.js
Frost Mage and Fire Mage have 5% base crit instead of 8%, and Fire has an additional 15% from a passive (Critical Mass).
I confirmed both of these values vs my character sheet and after these changes, the values match perfectly
> [Mage] Fixed Crit in Stat Tracker

- src/Parser/Core/Modules/Features/BaseHealerStatValues.js
- src/Parser/Druid/Restoration/CHANGELOG.js
- src/Parser/Paladin/Holy/CHANGELOG.js
This is useful for comparing static stat values. I.e. if you're comparing a log where you had a trinket with healing procc with a stat stick. Or just interested in how much healing each stat did.
> BaseHealerStatValues exposes the amount of healing one rating does

- src/Parser/Core/Modules/StatTracker.js
- src/common/SPELLS/DEATH_KNIGHT.js
Vampiric Aura not being tracked was causing inflated Leech stat weights when player was gaining it.
Fixes #959
> Added Vampiric Aura to StatTracker

- src/Parser/Shaman/Restoration/Modules/Spells/GiftOfTheQueen.js
Found and fixed this in the Checklist PR but since this is a live bug now I decided to push it as a separate PR
> Fixing bug where GotQ/Cloudburst percent is show incorrectly

- src/Parser/Core/Modules/Items/PrototypePersonnelDecimator.js
This isn't something easily trackable in Warcraft Logs, since it has no cast event, thought it'd be interesting information.
> [Core] update Personnel Prototype Decimator to include procs and hits

- src/Parser/DeathKnight/Unholy/Modules/Features/Abilities.js
Clawing Shadows is a third-tier talent that replaces
Scourge Strike.
> Add Clawing Shadows alias for Scourge Strike

- src/Parser/Core/CombatLogParser.js
- src/Parser/Core/Entity.js
- src/Parser/Core/Modules/Entities.js
- src/Parser/Core/Modules/Items/ErraticMetronome.js
Added better buff stack tracking to Entity / Entities, including a utility function that can be used to calculate 'average stacks' of a buff. Also added an ErraticMetronome module (a trinket from Nighthold), as a demonstration of how average stack calculation can be done.
This should help with the implementation of PR #963
> [core] Added better buff stack tracking to Entities.

- src/Parser/Core/Modules/SpellUsable.js
I noticed that the console log was frequently telling me that Phoenix's Flames was used while it was on cooldown, so i went to look at SpellUsable to figure out why.
The way Phoenix's Flames works is it has 3 charges, 45 second cooldown each. And ignite damage has a chance to erupt and reduce the cooldown of Phoenix's Flames by 10 seconds.
I believe the issue is that if multiple charges of Phoenix's Flames are on cooldown, and there is less than 10 seconds left on the cooldown of a charge, then SpellUsable ends the cooldown and grants a charge, and then stops.
But in game, if you have less than 10 seconds left on a Phoenix Flames charge, then it ends the cooldown on that charge, and the remainder of that 10 seconds reduces the next charge. So for example. If i have 3 charges on cooldown …
> [Core] Fix for SpellUsable Reduction of Charge Spells

- src/Parser/Druid/Restoration/Modules/Talents/Flourish.js
Resto Druid T21 adds another HoT for the spec, and Flourish is a spell that extends all active resto HoTs. This PR simply adds tracking of Dreamer to the Flourish module.
> [resto druid] Added Dreamer (T21) to Flourish tracking

- src/Parser/Mage/Fire/Modules/Features/HotStreak.js
I believe my analysis is wrong for the direct damage crits which is causing people to get higher numbers than they should have. Removing the suggestion until I can take a closer look at this.
> [Fire Mage] Remove Direct Damage Crits Suggestion

- src/CHANGELOG.js
- src/Parser/Core/CombatLogParser.js
- src/Parser/Core/Modules/Items/InsigniaOfTheGrandArmy.js
- src/Parser/Core/Modules/NetherlightCrucibleTraits/LightSpeed.js
- src/Parser/Core/Modules/NetherlightCrucibleTraits/MasterOfShadows.js
- src/Parser/Core/Modules/NetherlightCrucibleTraits/NLCTraits.js
- src/Parser/Core/Modules/NetherlightCrucibleTraits/Shocklight.js
- src/common/SPELLS/OTHERS.js
This PR adds the insignia of the grand army to the core parser.
It will show either HPS or DPS depending on which is highest, if both of them are 0, it will refer to the tooltip. 
The tooltip includes a overall view of contribution of the ring (both DPS and HPS) aswell as a breakdown for each individual trait.
> [Core] Insignia of the grand army

- src/Parser/Shaman/Elemental/CombatLogParser.js
- src/Parser/Shaman/Elemental/Modules/Items/TheDeceiversBloodPact.js
- src/common/SPELLS/SHAMAN.js
Not too sure about the equip and the class Resource access.
The whole Maelstrom stuff only uses index 0 so i guess that it will always have that index.
Deciding if it's active could also be done via item check, but that seems a little harder than just checking the buff
> Implemented Legendary Boots for Elemental Shaman

- src/MAINTAINERS.js
- src/Parser/Monk/Brewmaster/CHANGELOG.js
- src/Parser/Monk/Brewmaster/Modules/Features/Checklist.js
- src/Parser/Monk/Brewmaster/Modules/Spells/IronSkinBrew.js
- src/common/SPELLS/MONK.js
This PR introduces two checklist items that track the use of Ironskin Brew for Brewmaster Monks. These checklist items give an at-a-glance view of:
1. The percentage of hits mitigated via Ironskin Brew (100% is the goal, in practice 99%+ is obtainable). Discounting fights with a large number of negligible hits while not actively tanking (which don't exist in the current relevant tiers as far as I know), this takes into account time not actively tanking better than a simple uptime check. The high requirements on uptime are set because having ISB inactive (ever) while actively tanking can easily result in a dead tank.
2. The amount of duration wasted by over-capping the ISB buff. Most (all?) tank AM buffs have a cap of 3x the duration of a single application of a buff (taking into account …
> Added ISB-tracking checklist items for Brewmasters

- src/CHANGELOG.js
- src/Parser/Core/Modules/Items/EnchantChecker.js
Some specs use the Warlords cloak enchants these days, due to the massive power disparity between secondary and primary stats.
See my character:
https://worldofwarcraft.com/en-gb/character/ragnaros/putro
My assumption is that people who use warlords enchants know that it's the best for them specifically (I hope)
> [Core] adds the 5 wod cloak enchants to the max enchant checker

- src/Parser/Mage/Frost/Modules/Items/MagtheridonsBanishedBracers.js
Magtheridon's Banished Bracers' buff stacks after the spell is cast, not when it hits.
> [Frost Mage] Fix for Magtheridon's Banished Bracers

- .gitignore
- src/Main/Results.js
- src/Parser/Core/CombatLogParser.js
- src/Parser/Core/Modules/AlwaysBeCasting.js
- src/Parser/Core/Modules/Features/WarningDisplay.js
- src/Parser/Mage/Fire/Modules/Features/AlwaysBeCasting.js
- src/Parser/Mage/Frost/Modules/Features/AlwaysBeCasting.js
- src/Raids/AntorusTheBurningThrone/EonarLifebinder.js
This uses the new boss fight settings to disable the Downtime StatisticBox/Suggestion for Eonar since the stat is pretty useless on that fight.
This is just the first of some other boss specific settings that I think will help. Part of Issue #391
> [Core] Remove Downtime Suggestion for Eonar

- src/Parser/Monk/Brewmaster/CHANGELOG.js
- src/Parser/Monk/Brewmaster/CombatLogParser.js
- src/Parser/Monk/Brewmaster/Modules/Core/StaggerFabricator.js
- src/Parser/Monk/Brewmaster/Modules/Features/Abilities.js
- src/Parser/Monk/Brewmaster/Modules/Normalizers/IronskinBrew.js
- src/Parser/Monk/Brewmaster/Modules/Spells/BlackoutCombo.js
- src/Parser/Monk/Brewmaster/Modules/Spells/IronSkinBrew.js
- src/Parser/Monk/Brewmaster/Modules/Spells/RushingJadeWind.js
- src/Parser/Monk/Brewmaster/Modules/Spells/RushingJadeWind.test.js
Rushing Jade Wind has a fixed duration, but variable uptime. It is possible (and recommended) to leave RJW off cooldown quite a bit and still maintain high uptime. (See for example, [this fight](https://wowanalyzer.com/report/g6kqfdVyBYbLKrTh/7-Heroic+Felhounds+of+Sargeras+-+Kill+(3:59)/Eisenpelz/cast-efficiency) where I have <60% cast efficiency but > 85% uptime) This PR replaces the Abilities-based suggestion with an uptime-based suggestion.
I didn't see a way to do uptime-based stuff mostly automatically, so this is done as a new module.
(Also fixed final reviews from previous PR)
> [BrM Monk] Replaced CD-based RJW suggestion with uptime-based suggestion

- src/Parser/Warlock/Affliction/Modules/Features/Checklist.js
That kind of a "way-too-late-at-night" bug. Master Harvester doesn't give the talent, just the effect sometimes procs. `ITEMS` was unnecessary then.
> [Affliction] HOTFIX - The Master Harvester

- src/Parser/Monk/Windwalker/Modules/Features/ComboStrikes.js
Also removing unnecessary reversing of the spell order
> [Windwalker] Fixing crash in Combo Strikes module

- src/Parser/Mage/Frost/CHANGELOG.js
- src/Parser/Mage/Frost/Modules/Features/BrainFreeze.js
- src/Parser/Mage/Frost/Modules/Features/Checklist.js
- src/Parser/Mage/Frost/Modules/Features/GlacialSpike.js
- src/Parser/Mage/Frost/Modules/Features/IceLance.js
- src/Parser/Mage/Frost/Modules/Features/ThermalVoid.js
- src/Parser/Mage/Frost/Modules/Features/WintersChill.js
New checklist entry "Fish for Procs" checks that you're spamming Frostbolt when you have no procs (rather than casting Ice Lance or Flurry without procs, which is almost always wrong)
Updated some suggestion texts / numbers too.
> [frost mage] Updated suggestions to new format, added new Checklist entry

- src/Parser/Core/Modules/Channeling.js
- src/Parser/Core/Modules/Features/WarningDisplay.js
- src/Parser/Mage/Fire/CHANGELOG.js
- src/Parser/Mage/Fire/CombatLogParser.js
Added a warning message to show anyone using the fire analyzer to inform them that the spec is under development/incomplete and may have missing or inaccurate information
> [Fire Mage] Add Warning for Spec Completeness

- src/Parser/Hunter/BeastMastery/CHANGELOG.js
- src/Parser/Hunter/BeastMastery/Modules/Talents/KillerCobra.js
This is a working preliminary fix until a proper update to SpellUsable can be made and PR'd to count GCDs as time spent on cooldown when using ``endCooldown`` from spellUsable
The effect this has on cast efficiency is large enough that I think this warrants a quick update.
> [Hunter] updating killer cobra reset

- src/Parser/Hunter/BeastMastery/Modules/Items/QaplaEredunWarOrder.js
Firstly looking for feedback on this solution and how to word things in this module and if it's makes sense to you guys.. 
The scenario is this: 
You're wearing a legendary that upon using Dire Beast (or Dire Frenzy) reduces the cooldown of Kill Command by 3 seconds. 
Now if your current CD is less than 3s+GCD, then the cast efficiency module assumes you could cast more Kill Commands than you actually could (seeing as it spent that GCD off cooldown). 
What this aims to fix is provide a more realistic maxPossibleCast metric for Kill Command, aswell as a more realistic number for how much Kill Command was effectively reduced through this legendary.
Taken from a high-end parse: 
After this change:
> [BeastMastery] qapla updates

- src/Parser/Monk/Brewmaster/CHANGELOG.js
- src/Parser/Monk/Brewmaster/Modules/Spells/PurifyingBrew.js
- src/common/SPELLS/MONK.js
Shows the amount, mean, min, and max amount of damage purified with Purifying Brew. Also tracks the number of times you purified w/o being in heavy (red) stagger. 
Generally speaking not purifying when below heavy stagger is a good rule of thumb, but I'm not sure where to put the suggestion threshold yet (so there isn't an associated suggestion).
> [BrM Monk] Basic Purifying Brew Stat

- src/Parser/Core/Combatant.js
- src/Parser/Core/Modules/StatTracker.js
- src/Parser/Priest/Holy/CHANGELOG.js
- src/Parser/Priest/Holy/CombatLogParser.js
- src/Parser/Priest/Holy/Modules/PriestCore/HymnBuffBenefit.js
Adds a module that allows users to see the (approximate, see comments) effective healing contributed by the Divine Hymn healing increase buff. Suggested by Roras on the H2P discord.
Also fixes the existing issue of Mastery appearing 5% lower than it should on the analyzer.
> (Holy Priest) Divine Hymn buff contribution

- src/Parser/Mage/Fire/CHANGELOG.js
- src/Parser/Mage/Fire/CombatLogParser.js
- src/Parser/Mage/Fire/Modules/Features/HotStreak.js
- src/Parser/Mage/Fire/Normalizers/Scorch.js
Hot Streak has been expanded to once again check for direct damage crits while Hot Streak is active (but now also disregards crits that happen when Pyromaniac procs and immediately re-activated Hot Streak).
Also added checks to make sure each use of hot streak has a hard cast ability like Fireball, Scorch, or Pyroblast (only if you have a bracer proc) immediately before it to increase the chance of getting a Heating Up or Hot Streak ... unless Combustion is active.
> [Fire Mage] Enhancements and Additions for Hot Streak

- src/Parser/Druid/Restoration/Modules/Core/HotTracking/RejuvenationAttributor.js
- src/Parser/Druid/Restoration/Modules/Items/Tearstone.js
In RejuvenationAttributor, fixed an issue where procs that happen at around the timestamp as a PotA consumption could be spuriously attributed to PotA.
In Tearstone, fixed an issue where it was assumed that the maximum number of HoTs were applied per cast, which could sometimes deflate the reported proc rate.
> [resto druid] Fixed some minor issues in RejuvenationAttributor and Tearstone

- src/Parser/Mage/Frost/Modules/Cooldowns/FrozenOrb.js
- src/Parser/Mage/Frost/Modules/Cooldowns/IcyVeins.js
- src/Parser/Mage/Frost/Modules/Features/AlwaysBeCasting.js
- src/Parser/Mage/Frost/Modules/Features/ArcticGale.js
- src/Parser/Mage/Frost/Modules/Features/BrainFreeze.js
- src/Parser/Mage/Frost/Modules/Features/FrostBomb.js
- src/Parser/Mage/Frost/Modules/Features/GlacialSpike.js
- src/Parser/Mage/Frost/Modules/Features/IceLance.js
- src/Parser/Mage/Frost/Modules/Features/SplittingIce.js
- src/Parser/Mage/Frost/Modules/Features/ThermalVoid.js
- src/Parser/Mage/Frost/Modules/Features/WintersChill.js
- src/Parser/Mage/Frost/Modules/Items/IceTime.js
- src/Parser/Mage/Frost/Modules/Items/LadyVashjsGrasp.js
- src/Parser/Mage/Frost/Modules/Items/MagtheridonsBanishedBracers.js
- src/Parser/Mage/Frost/Modules/Items/ShatteredFragmentsOfSindragosa.js
- src/Parser/Mage/Frost/Modules/Items/SoulOfTheArchmage.js
- src/Parser/Mage/Frost/Modules/Items/Tier20_2set.js
- src/Parser/Mage/Frost/Modules/Items/Tier20_4set.js
- src/Parser/Mage/Frost/Modules/Items/Tier21_2set.js
- src/Parser/Mage/Frost/Modules/Items/Tier21_4set.js
- src/Parser/Mage/Frost/Modules/Items/ZannesuJourney.js
- src/Parser/Mage/Shared/Modules/Features/CancelledCasts.js
- src/Parser/Mage/Shared/Modules/Features/MirrorImage.js
- src/Parser/Mage/Shared/Modules/Features/RuneOfPower.js
- src/Parser/Mage/Shared/Modules/Features/UnstableMagic.js
- src/Parser/Mage/Shared/Modules/Items/ShardOfTheExodar.js
Went through all the frost modules to make the following adjustments based on new standards and new features.
- use spellId constants instead of event.ability.guid directly
- Replace Span with Wrapper
- Move some local constants to getters
- Replace getDamageBonus with calculateEffectiveDamage
- New Suggestion Format
- Suggestion Thresholds (where they werent already done)
> [Frost Mage] Code Cleanup/Refactor

- src/Parser/Druid/Restoration/Modules/Features/Abilities.js
- src/Parser/Druid/Restoration/Modules/Features/AlwaysBeCasting.js
Sunfire and Moonfire are very common damaging spells for a Resto Druid to cast during healing downtime, but they were missing from Abilities and ABC.
Also, several spells in Abilities were in the wrong categories, this fixes that.
> [resto druid] Added Sunfire and Moonfire to ABC. Fixed spell categories in Abilities, and also added Sunfire and Moonfire

- src/Parser/Hunter/BeastMastery/Modules/Traits/TitansThunder.js
- src/Parser/Hunter/Marksmanship/Modules/Talents/LoneWolf.js
I goofed when I made this originally. Now it checks for 30 seconds remaining properly
also fixes Lone Wolf to not account friendly damage if that happens
> [BM] Fix Titans Thunder bug

- src/Parser/Druid/Restoration/Modules/Features/Clearcasting.js
- src/Parser/Druid/Restoration/Modules/Features/Innervate.js
- src/Parser/Druid/Restoration/Modules/Talents/TreeOfLife.js
MoC module was unable to see refreshes how I thought, switched up the display to account for this (fixes #1172 )
Innervate stat display wasn't formatted right, fixed that.
Tree of Life had some uptime tallying issues when player took both talent and legendary helm, also the module was in *desperate* need of a rewrite, so I gave it a complete rewrite and also fixed the issue while I was there (fixes #1159 ) It may be easier to look at the changes here as a new file, because it really is a full rewrite: https://github.com/kfinch/WoWAnalyzer/blob/038878f90290691d8e835c710f96704592f7b32a/src/Parser/Druid/Restoration/Modules/Talents/TreeOfLife.js
> [resto druid] ToL rewrite + some minor fixes

- src/Parser/Core/Modules/Haste.js
- src/Parser/Monk/Brewmaster/CHANGELOG.js
- src/Parser/Monk/Brewmaster/CombatLogParser.js
- src/Parser/Monk/Brewmaster/Modules/Core/BrewCDR.js
- src/Parser/Monk/Brewmaster/Modules/Spells/HighTolerance.js
This implements the haste gain from the High Tolerance for BrM monks. The haste is integrated into the core `Haste` module. I also changed the `BrewCDR` module to use the *mean* haste instead of the haste at the last event. This more accurately reflects the amount of additional CDR you need over the course of a fight, especially in conjuction with the extra 12%+ haste from using HT on an appropriately high-damage fight. A couple logs I've looked at it reduced the CDR suggestion threshold by almost 5% (additive).
> [BrM Monk] Implemented High Tolerance Talent

- src/Parser/Rogue/Subtlety/CombatLogParser.js
- src/Parser/Rogue/Subtlety/Modules/Features/AlwaysBeCasting.js
Rogue GCD always 1 second, except for outlaw during AR.
Thresholds expected to be high, as rogue is a class that does not have free abilities - everything costs energy or combo points to cast.
> [Sub rogue] ABC

- src/Parser/Core/Modules/SpellUsable.js
- src/Parser/Core/Modules/SpellUsable.test.js
- src/Parser/Druid/Balance/CONFIG.js
- src/Parser/Druid/Balance/CombatLogParser.js
- src/Parser/Druid/Balance/Modules/Features/Abilities.js
- src/Parser/Druid/Balance/Modules/Features/Checklist.js
- src/Parser/Druid/Balance/Modules/Features/MoonSpells.js
- src/Parser/Druid/Balance/Modules/Items/RadiantMoonlight.js
- src/Parser/Monk/Brewmaster/Modules/Core/BrewCDR.test.js
Also changed balance spec completeness to GREAT. Sorry it's all in one PR, should've done the reduceCooldown on it's own, but without it the cooldown reduction on Radiant Moonlight is incorrect.
The fix to cooldown reduction was that any cooldown reduction that overlapped a charge would only return the value from replenishing the rest of the charge. For instance when at 2 charges and 2 seconds from finishing cd, reducing it by 5 would only return 2, even thought you went to 3 charges and 3 seconds recharged. It should now return the correct value.
> [Balance] Added RM, merged moon spells and changed SpellUsable.reduceCooldown to return correct value for charge spells.

- src/Parser/Mage/Frost/Modules/Items/ShatteredFragmentsOfSindragosa.js
A simple spelling error caused this module to not work, this fixes that.
> [Frost Mage] fix sindragosa head bug

- src/Parser/Core/Modules/Features/Checklist/performanceForThresholds.js
- src/Parser/Core/Modules/Features/Checklist/performanceForThresholds.test.js
**tl;dr** - prior to this PR, the `isGreaterThan` section of `performanceForThresholds` was actually pretty wonky. If you plotted it out, you'd go from `1` down to `0.666` then slowly back up to `1` then down to `0.333` up to `0.666` and then start dropping below `0.333`.
This PR adds a bunch of behavior tests to check that on each side of the main threshold points (minor, average, major) we get similar values out. For example, if the actual is very slightly (say, `10^-16`) above the average value, that value should be virtually the same as `0.666`. Likewise for very slightly below. 
These tests codify that intuition, along with an additional regression test from the example @yajinni showed me.
> Make the output of performanceForThresholds more sane

- src/Parser/DeathKnight/Frost/CONFIG.js
- src/Parser/DemonHunter/Vengeance/CONFIG.js
- src/Parser/Paladin/Protection/CONFIG.js
- src/Parser/Shaman/Enhancement/CONFIG.js
- src/Parser/Warrior/Protection/CONFIG.js
Updating specs to Not Actively Maintained.
Current criteria is if there have been no updated in 2.5 months, we review the specs and reach out to the maintainers to see if the spec either needs updating, or if it still being maintained. After confirmation, we make the swap to ensure any users are informed that the information being presented may be out of date.
Thanks.
> Not Actively Maintained Spec Updates

- src/Parser/Druid/Feral/CHANGELOG.js
- src/Parser/Druid/Feral/CombatLogParser.js
- src/Parser/Druid/Feral/Modules/Traits/AshamanesRip.js
- src/common/SPELLS/DRUID.js
Added a statistic and suggestion for the uptime of Ashamane's Rip from the artifact trait Ashamane's Bite.
I'm a little uncertain what statisticOrder to set for it. It usually provides around 5% of total damage, so have put it as OPTIONAL(0) for now.
> [Feral] Add tracking of Ashamane's Rip uptime

- src/Parser/Warlock/Affliction/Modules/Talents/EmpoweredLifeTap.js
- src/Parser/Warlock/Destruction/Modules/Talents/EmpoweredLifeTap.js
Before the rework with fabricated `applybuff` events on fight start, we weren't able to track buffs that didn't have `applybuff` event, leading to reported 0% uptime, when in fact it should be 100% (buff applied pre-pull and maintained throughout the fight without `removebuff`)). It's fixed now so the part where I explained the behavior is removed.
> [Affliction, Destruction] Fixed the ELT suggestion text.

- src/Main/DamageTakenTable.js
- src/Parser/Core/Modules/DamageValue.js
- src/Parser/Monk/Brewmaster/CHANGELOG.js
- src/Parser/Monk/Brewmaster/CombatLogParser.js
- src/Parser/Monk/Brewmaster/Modules/Core/DamageTaken.js
- src/Parser/Monk/Brewmaster/Modules/Features/DamageTakenTable.js
- src/Parser/Monk/Brewmaster/Modules/Spells/IronSkinBrew.js
- src/common/SPELLS/MONK.js
This stems from the discussion we had today in discord. tldr its a table that shows the abilities you, as a tank, took damage from, categorized by whether it was mitigated by physical or magical mitigation, the total amount you took, and the maximum single hit you got.
It looks [like](https://imgur.com/a/p8rsi) [this](https://imgur.com/a/xiT3q). Importantly, (at least for BrMs) it doesn't rely on the spell data so it catches things like Jagged Abrasion (Harjatan) being mitigated by physical reduction unlike *literally every other bleed effect.*
The component itself can be used by other tank specs by importing the component and then feeding it your own data. The way I classified abilities for BrM depends on stagger, and so won't work for other tanks. Spell data isn't reliable (see also: …
> Add a DamageTakenTable component (and implementation for BrM)

- src/Parser/Mage/Frost/Modules/Features/IceLance.js
The Ice Lance Shatter % were always 100% because when i did my refactor, my find/replace replaced event.targetID with event.targetId, which broke the check.
> [Frost Mage] Fix for Ice Lance

- src/Main/Changelog.js
See issue #1273 
Still using `toLocaleDateString` but with `timeZone` set to UTC rather than the user's local timezone.
> display date in UTC

- src/Parser/Warlock/Affliction/Modules/Items/Tier21_2set.js
If by any chance `damage` event happened before `applydebuff` event for UA, the object representing the target didn't exist causing the tick tracking to crash. This ensures the object exists with all the debuff fields reset so it shouldn't crash again and its behavior for normal logs should be the same.
> [Affliction] Bugfix in T21 2p

- src/CHANGELOG.js
- src/Main/Results.js
Added <i>How It's Made</i>, <i>How To Change</i>, <i>Spec Maintainer</i> and <i>State Of The Spec</i> boxes to the results page at the dividers between the sections.
> Results contribute/spec boxes

- src/Parser/Warlock/Affliction/CHANGELOG.js
- src/Parser/Warlock/Affliction/Modules/Features/AgonyUptime.js
- src/Parser/Warlock/Affliction/Modules/Features/Checklist.js
- src/Parser/Warlock/Affliction/Modules/Features/CorruptionUptime.js
- src/Parser/Warlock/Affliction/Modules/Talents/MaleficGrasp.js
- src/Parser/Warlock/Affliction/Modules/Talents/SiphonLifeUptime.js
After talking to Motoko, I updated the thresholds for dot uptimes. Since the thresholds were the same regardless of talents/set bonuses, I removed the extra threshold object (and the respective Requirement in checklist), but since the suggestions have different wording, I extracted it to variable.
> [Affliction] Update thresholds

- src/Parser/Core/Modules/StatTracker.js
- src/common/ITEMS/OTHERS.js
- src/common/SPELLS/OTHERS.js
Missing Khaz'goroth's Shaping which for some reason uses the same buff ID for all 4 secondary procs and I didn't have time to implement it tonight.
> Added most common haste proc trinkets to stat tracker

- src/Parser/Druid/Feral/CHANGELOG.js
- src/Parser/Druid/Feral/CombatLogParser.js
- src/Parser/Druid/Feral/Modules/Features/FerociousBiteEnergy.js
_This is a replacement for pull request #1263 after I did something mysterious to that branch which made a mess of the commit history. My apologises again for any disruption._
This is a module to check for Feral druids using Ferocious Bite with less energy than the recommended 50. After a very useful discussion, its suggestion threshold is based on average energy spent by the player on Bite.
It also calculates how much Ferocious Bite damage was lost due to the low energy. This measure is not the same as overall damage lost, as the "saved" energy likely contributed damage in other ways during the fight. But it does provide a general guide to how much (or how little) damage is in play.
> [Feral] Ferocious Bite energy check

- src/Parser/Monk/Windwalker/Modules/Items/DrinkingHornCover.js
It would create a negative gain for SEF/Serenity uses that were ended early, typically only in case of death, which would then lower the average time gained more than it should. 
old result:
new result:
https://wowanalyzer.com/report/cHqZ2A4C8TvtLjYx/4-Mythic+Felhounds+of+Sargeras+-+Kill+(4:54)/Rollinrey
> [Windwalker] Fixing DHC gain calculation

- src/Parser/Monk/Brewmaster/CHANGELOG.js
- src/Parser/Monk/Brewmaster/CombatLogParser.js
- src/Parser/Monk/Brewmaster/Modules/Core/MasteryValue.js
- src/Parser/Monk/Brewmaster/Modules/Normalizers/GarothiWorldbreakerMelee.js
- src/common/SPELLS/MONK.js
This PR adds a statistic for Brewmasters that shows both an estimate of the actual damage mitigated by [their mastery](www.wowhead.com/spell=117906/mastery-elusive-brawler) and the expected damage that would be mitigated if they repeated this fight a bunch of times.
Much of the code is dedicated to that latter part, which I opted to highlight over the actual because it depends only on player performance and gear, and not on RNG (if you didn't click the link, brewmaster mastery boosts dodge chance).
The math for calculating the expectation is relatively complicated, but I tried to comment well enough that it is reasonably clear what is going on. There are a couple of improvements that could tighten things up but aren't essential for giving useful output. I'd be fine with merging this …
> [BrM Monk] Mastery Evaluation

- src/Parser/DemonHunter/Havoc/Modules/Abilities.js
- src/Parser/DemonHunter/Havoc/Modules/Items/DelusionsOfGrandeur.js
- src/Parser/DemonHunter/Havoc/Modules/Traits/FeastOnTheSouls.js
- src/Parser/Paladin/Retribution/Modules/PaladinCore/Retribution.js
The Delusions of Grandeur suggestion was showing up regardless of fight time and the meta CD was in seconds vs the fight duration in ms.
The CDR from the feast on the souls trait didn't account for it there was < 5 seconds left on the cooldown on eye beam when you picked up a soul and now it does.
Also hid the stat boxes for the Feat of Souls CDR and Retribution paladins retribution if they didn't attribute anything to the fight.
> [Havoc] Bug Fixes

- src/Parser/Hunter/Survival/CHANGELOG.js
- src/Parser/Hunter/Survival/CombatLogParser.js
- src/Parser/Hunter/Survival/Modules/Items/ButchersBoneApron.js
- src/Parser/Hunter/Survival/Modules/Items/FrizzosFingertrap.js
- src/Parser/Hunter/Survival/Modules/Items/HelbrineRopeOfTheMistMarauder.js
- src/Parser/Hunter/Survival/Modules/Items/NesingwarysTrappingTreads.js
- src/Parser/Hunter/Survival/Modules/Items/UnseenPredatorsCloak.js
- src/common/SPELLS/HUNTER.js
This adds the 5 spec specific legendaries. 
Helbrine: 
Report: https://www.warcraftlogs.com/reports/QtDF2PBh4Aa1Xxgr/#fight=22&source=11
Frizzo's: 
Report: https://www.warcraftlogs.com/reports/AbdZzH3WFxGhyYfN#fight=9&type=damage-done&source=16
Unseen Predator's Cloak: 
Report: https://www.warcraftlogs.com/reports/ZxVMjQCLfqcRmtKH#fight=8&type=auras&translate=true&hostility=1&spells=debuffs&target=19
Butcher's Bone Apron: 
Report: https://www.warcraftlogs.com/reports/Rt9cXWGzC7bhdL6v#fight=1&type=damage-done
Nesingwary's Trapping Treads:
Report: https://www.warcraftlogs.com/reports/nWMF8h1vTq3cbCKw#fight=1&type=damage-done
> [Survival] adding the 5 spec specific legendaries 

- src/Main/Timeline/SpellTimeline.js
- src/Parser/Druid/Restoration/CHANGELOG.js
- src/Parser/Druid/Restoration/Modules/Features/Clearcasting.js
Apparently Clearcasting does or doesn't get a refreshbuff when it's refreshed depending on if player took MoC ????
Anyway, fixed things so it will display properly when player doesn't have MoC.
Also made a stopgap fix to SpellTimeline so it doesn't spam the console with "same ID" errors if the overlapping GCD bug happens. Note this doesn't fix the overlapping GCDs... that will require more effort. It just makes the console more usable until it is fixed.
> [resto druid] Fixed bug in clearcasting module

- src/Parser/Priest/Shadow/Modules/Items/Tier21_4set.js
Void Bolt also benefits from the crit chance increase of the T21 4pc, but not from the T21 2pc crit damage modifier.
> [Priest] Update Tier21_4set.js

- src/Parser/Hunter/Marksmanship/Modules/Spells/Trueshot.js
- src/Parser/Hunter/Survival/CHANGELOG.js
- src/Parser/Hunter/Survival/CombatLogParser.js
- src/Parser/Hunter/Survival/Modules/Talents/SpittingCobra.js
- src/common/SPELLS/HUNTER.js
Short and sweet one to finish off the day with.
This adds a module to track damage and focus gained through the Spitting Cobra talent.
It fixes cast efficiency issues with Trueshot and Spitting Cobra if they were cast before combat started. 
Report: https://www.warcraftlogs.com/reports/RFBPbDJYt93G4xnv/#fight=8&type=damage-done&source=7
Live:
This version:
> [Survival] Spitting cobra

- src/Parser/Core/Modules/DeathTracker.js
Death Tracker was not counting Soulstone as a ressurect and there are no events to indicate that the player used their soulstone. So instead, I made it so that if you are healed, take damage, start casting something, or cast something while you are marked as dead, then it will count as a ressurect.
Fixes #1207 
Fixes #443
> [Core] Fix Death Tracker

- src/Parser/Core/Modules/Items/Legion/AntorusTheBurningThrone/NorgannonsProwess.js
- src/Parser/Core/Modules/StatTracker.js
Instead of showing the percent uptime on the intellect buff it now shows the average amount of int gained.
new
old
cZhfdNGR4LQBwj32
test log
https://www.warcraftlogs.com/reports/cZhfdNGR4LQBwj32#fight=4&type=damage-done&source=2
> [Core] Updated Norgannons

- src/Parser/Druid/Feral/Modules/Features/Abilities.js
- src/common/SPELLS/DRUID.js
Rearranged abilities to be roughly organized by category.
Also fixed the following issues:
- Brutal Slash wasn't shown scaling with haste OR having charges
- Shadowmeld wasn't marked 'isUndetectable'
- Berserk was missing entirely
- Thrash was included with the wrong ID (the Guardian version)
- Survival Instincts was missing charges
- Survival Instincts and Renewal were listed as UTILITY, now listed as DEFENSIVE
- Thrash and Swipe were listed as ROTATIONAL, now listed as ROTATIONAL_AOE
- Regrowth and Maim were listed as ROTATIONAL, now listed as UTILITY (I felt this appropriate as few players use Bloodtalons anymore, or Fiery Red Memers)
- Dropped Incarnation cast effic from 1.0 to 0.9 (effic requirement should never be 1.0)
> [Feral Druid] Fixed several issues in Abilities

- src/Main/PlayerSelectionList.js
Separate Player Selector List into columns so some of the players arent going off the screen.
Part of #824 
Fixes #828
> [Core] Separate Player list into Columns

- src/Parser/Mage/Frost/Modules/Features/SplittingIce.js
Looks like it got caught in an errant search replace a few weeks ago. This bug was making the results VERY wrong.
> [frost mage] Fixed a bug in SplittingIce where targets were not correctly registering

- src/Parser/Priest/Discipline/CombatLogParser.js
- src/Parser/Priest/Discipline/Normalizers/PowerWordRadianceNormalizer.js
- src/common/SPELLS/PRIEST.js
Because of latency, after casting Power Word: Radiance, the atonement applications
don't always register right away and an instant cast spell can be recorded before
the atonements. Example: Evangelism casted right after a Power Word Radiance will
be before the applications of the atonements. For this reason we reorder the
events so that the applications are always right after the cast.
> Power Word Radiance Normalizer

- src/Parser/Hunter/BeastMastery/Modules/Features/TraitsAndTalents.js
- src/Parser/Hunter/Marksmanship/Modules/Features/TraitsAndTalents.js
- src/Parser/Hunter/Survival/CHANGELOG.js
- src/Parser/Hunter/Survival/CombatLogParser.js
- src/Parser/Hunter/Survival/Modules/Features/TraitsAndTalents.js
- src/Parser/Hunter/Survival/Modules/Spells/ExplosiveTrap.js
- src/Parser/Hunter/Survival/Modules/Talents/Caltrops.js
- src/Parser/Hunter/Survival/Modules/Talents/SteelTrap.js
- src/Parser/Hunter/Survival/Modules/Talents/WayOfTheMokNathal.js
- src/common/SPELLS/HUNTER.js
Taking the approach as I did with Beast Mastery and Marksmanship hunters for some basic talent contribution statistics by making a list - this time around it includes a baseline spell in Explosive Trap, because it doesn't really deserve it's entire own statistic module, but I was fixing prepull events regardless so decided to add it, atleast for now. 
Log: https://www.warcraftlogs.com/reports/kN9d6pfYwgt4yDGJ/#fight=1&source=3
Example of prepull events not registering: 
Live: 
Post-fix:
fixes #1216
> [Survival] Prepull traps and traits/talent listbox

- src/Parser/Druid/Restoration/CHANGELOG.js
- src/Parser/Druid/Restoration/CombatLogParser.js
- src/Parser/Druid/Restoration/Modules/Talents/TreeOfLife.js
- src/Parser/Druid/Restoration/Normalizers/TreeOfLifeNormalizer.js
- src/common/SPELLS/DRUID.js
In some circumstances, Tree of Life could generate extra casts events, so I added a Normalizer to remove them. For the gritty details, see my documentation in the Normalizer.
Also made the CS proc count calculator less dumb, it should no longer under count if the fight ends during a proc.
Finally, made the reported uptime be the amount of time the player was allowed to be in the form rather than the time the player was actually in form. This may seem odd, but some of a resto's movement / defensive abilities cause the player to briefly drop form, and it was making the numbers look confusing / weird.
Fixes #1369
> [resto druid] Fixed some Tree of Life bugs

- src/Parser/Priest/Discipline/Modules/Abilities.js
After talking with the disc priest community, we all came to the conclusion that with the new T21, Penance should not be used on cooldown like it should have been before. 
Removing the suggestion for now but will be doing some work on suggesting to at least do 1 penance after each radiance in another PR
> [Discipline Priest] Removed Suggestion for Penance

- src/Parser/DeathKnight/Frost/Modules/Items/Tier20_2p.js
Fixes a crash that occurs with odd melee casts in logs with the T20 2p bonus.  I also verified that classResources[0] is no longer used anywhere in the Frost modules
> [Frost Death Knight] Fixed crash with classResources in T20 file

- src/Parser/Paladin/Retribution/Modules/Abilities.js
- src/Parser/Paladin/Retribution/Modules/Features/AlwaysBeCasting.js
- src/Parser/Paladin/Retribution/Modules/Features/Checklist.js
- src/common/SPELLS/PALADIN.js
removed the array of the abilities on the GCD from the cast efficiency and added the isOnGcd value to all the abilities. Also updated the abilities to include all utility spells. Also updated the lay on hands checklist value to a cast efficiency with a low requirement. There are a lot of additions but its mostly added isOnGcd.
current:
updated:
test log: https://www.warcraftlogs.com/reports/Dyb9GFz4XR3LZaBM#fight=1&type=summary
> [Retribution] Abilities update

- src/Parser/Druid/Restoration/Modules/Features/Checklist.js
- src/Parser/Druid/Restoration/Modules/Features/Lifebloom.js
Made some changes to Lifebloom suggestion / checklist item in response to feedback from Resto discord.
- Efflo / Lifebloom Rule moved down one position in the checklist (slightly deemphasizing importance)
- Lifebloom suggested uptime lowered slightly, but if player has The Dark Titan's Advice equipped (which buffs Lifebloom) then the suggested uptime raised.
- Added tooltip explaining additional importance of Lifebloom when The Dark Titan's Advice is equipped.
> [resto druid] Updates to lifebloom suggestion and checklist item

- src/Parser/Hunter/BeastMastery/CHANGELOG.js
- src/Parser/Hunter/BeastMastery/Modules/Abilities.js
- src/Parser/Hunter/BeastMastery/Modules/Features/AlwaysBeCasting.js
- src/Parser/Hunter/BeastMastery/Modules/Items/ParselsTongue.js
- src/Parser/Hunter/BeastMastery/Modules/Items/QaplaEredunWarOrder.js
- src/Parser/Hunter/BeastMastery/Modules/Items/Tier21_4p.js
- src/Parser/Hunter/BeastMastery/Modules/Spells/AspectOfTheWild.js
- src/Parser/Hunter/BeastMastery/Modules/Spells/BestialWrath/BestialWrathAverageFocus.js
- src/Parser/Hunter/BeastMastery/Modules/Spells/BestialWrath/GainedBestialWraths.js
- src/Parser/Hunter/BeastMastery/Modules/Spells/DireBeast/DireBeast.js
- src/Parser/Hunter/BeastMastery/Modules/Talents/AMurderOfCrows.js
- src/Parser/Hunter/BeastMastery/Modules/Talents/DireFrenzy.js
- src/Parser/Hunter/BeastMastery/Modules/Talents/KillerCobra.js
- src/Parser/Hunter/BeastMastery/Modules/Traits/TitansThunder.js
- src/Parser/Hunter/Marksmanship/Modules/Features/VulnerableUptime.js
- src/Parser/Hunter/Marksmanship/Modules/Talents/PatientSniper/PatientSniperDetails.js
- src/Parser/Hunter/Marksmanship/Modules/Talents/TrueAim.js
- src/Parser/Hunter/Marksmanship/Modules/Traits/Bullseye.js
- src/Parser/Hunter/Shared/Modules/Features/TimeFocusCapped.js
- src/Parser/Hunter/Shared/Modules/Items/SoulOfTheHuntmaster.js
- src/Parser/Hunter/Shared/Modules/Talents/AspectOfTheBeast.js
- src/Parser/Hunter/Shared/Modules/Talents/Volley.js
- src/Parser/Hunter/Survival/CHANGELOG.js
- src/Parser/Hunter/Survival/Modules/Features/AlwaysBeCasting.js
- src/Parser/Hunter/Survival/Modules/Talents/Caltrops.js
Part 2 of more icons
Also adds a small uptime module for Survival on Caltrops dot:
Fixes a missing formatPercentage in Dire Frenzy module aswell.
> [Hunter] More cleaning and Caltrops module

- src/Parser/Monk/Brewmaster/Modules/Features/StaggerPoolGraph.js
This is a super simple PR. tl;dr the plot as it is now on the site is extremely difficult to mouseover the data points (aside from Purifies) since the point radius for them is set to 0. This sets the hit/hover radius to 4 so that you can actually see the exact values by mousing over the lines.
There is nothing I can really screenshot about this change. On live you *can* get the tooltip, its just a pain in the ass.
> [BrM] Fix Stagger Pool Plot Hitboxes

- src/Parser/Monk/Mistweaver/CombatLogParser.js
- src/Parser/Monk/Mistweaver/Modules/Items/DrapeOfShame.js
[test log](https://www.warcraftlogs.com/reports/DLRvBJX4x1Ft9pnh#fight=12&type=healing&source=30)
Added in a display to show the effective itemlevel of Drape of Shame for mistweaver monks.
> [Mistweaver] Drape of Shame effective ilvl

- src/Parser/Mage/Fire/CHANGELOG.js
- src/Parser/Mage/Fire/CombatLogParser.js
- src/Parser/Mage/Fire/Modules/Features/HeatingUp.js
- src/Parser/Mage/Fire/Modules/Items/KoralonsBurningTouch.js
Added a suggestion for casting Fireball instead of Scorch when the target is under 30% health when using Koralon's Burning Touch. Also adjusted Heating Up to take Scorch guaranteed crits into account when using Koralons.
> [Fire Mage] Support for Koralon's Burning Touch

- src/Parser/Monk/Windwalker/Modules/Spells/ComboBreaker.js
- src/common/SPELLS/MONK.js
The part telling how many blackout kicks were used without the proc is irrelevant and pretty much just a leftover from the clearcasting/uplifting trance modules i initially took inspiration from. Providing a simple measure of how lucky/unlucky the player was with procs is more interesting.
> [Windwalker] Updating Combo Breaker tooltip

- src/Parser/Priest/Discipline/Modules/Features/AtonementSource.js
- src/common/SPELLS/OTHERS.js
- src/common/SPELLS/RACIALS.js
Some spells do not generate atonement even though they are spells that generate damage. Added a blacklist to fix this issue in the atonement sources modules
> [Discipline Priest] Added Blacklist for Atonement Sources

- src/Parser/Core/Modules/Items/Legion/DarkmoonDeckImmortality.js
- src/Parser/Core/Modules/StatTracker.js
- src/common/SPELLS/MONK.js
Fairly self-explanatory. Armor gets tracked. The only buffs currently represented are from DMD:I. This is going to be more important as we ramp up for BfA as a bunch of tank AM is getting switched to bonus armor.
I worked around a bug (?) in the `combatantinfo` armor value. It doesn't include the bonuses from artifacts or passives. For BrM this nearly doubles the amount of armor I have pre-pull. However, while these passives do multiply together they do not multiply other temporary buffs and so cannot be used with the overall stattracker infrastructure to update stats.
I was waffling over whether to do this in `StatTracker` or adding a normalizer for a bit and ended up just doing it here. If it'd be better in a normalizer it's not much effort for me to move it before the PR is accepted.
> Added Armor to stat tracker

- src/Parser/DeathKnight/Unholy/CombatLogParser.js
- src/Parser/DeathKnight/Unholy/Modules/Features/RpPoolingDA.js
- src/Parser/DeathKnight/Unholy/Modules/Features/VirulentPlagueEfficiency.js
- src/Parser/DeathKnight/Unholy/Modules/Items/ColdHeartEfficiency.js
Removed some console.logs in Coldheart. Reworked the suggestiontreshold in Apocalypse so that they work correctly. Added a new module that tracks the reapplication of Virulent Plague.
> VP Effiency, Apocalypse change to suggestiontresh and some rogue Console.logs

- src/Parser/DemonHunter/Havoc/CHANGELOG.js
- src/Parser/DemonHunter/Havoc/Modules/ResourceTracker/FuryDetails.js
- src/Parser/DemonHunter/Havoc/Modules/ResourceTracker/FuryTracker.js
[Blind Fury](http://www.wowhead.com/spell=203550/blind-fury) does not have an energize event so I added a process fake events for it. Also increased the tolerance since it usually wastes 300 over the fight but it is more important to keep eye beam on cooldown.
[Test Log](https://www.warcraftlogs.com/reports/BHyhvwRqYjrMVfk8#fight=18&type=damage-done&source=1)
> [Havoc] Blind Fury

- src/Parser/Monk/Brewmaster/Modules/Core/MasteryValue.js
- src/common/SPELLS/MONK.js
Small change to the mastery value module. I'd forgotten about the Brew-Stache buff, which gives 10% dodge for 4.5 sec after drinking. This has some impact on mastery because it changes the effective mastery "cap" beyond which more mastery has no value (because you're increasing from e.g. 101% to 102% dodge).
This also makes the expected and actual dodge rates much closer in cases where someone had good brew-stache uptime.
> [BrM] Added Brew-Stache to mastery value

- src/Parser/Druid/Restoration/Modules/Features/Checklist.js
`this.treeOfLife.active` was also true when player was wearing leggo helm that procs treeOfLife
> [resto druid] Fixed a bug where ToL could show up in a checklist item when you didn't have the talent

- src/Parser/Core/Modules/StatTracker.js
Added a comment in StatTracker to make it more clear that `currentHastePercentage` doesn't include buffs like Bloodlust.
> Added comment for clarity to StatTracker

- src/Parser/DeathKnight/Blood/CombatLogParser.js
- src/Parser/DeathKnight/Blood/Modules/Features/DeathStrikeTimingGraph.js
Adds a plot to the BDK analysis thats showing Death Strike casts and the HP.
Goal is to help spotting low HP situations where the BDK relied on external healing instead of DS-selfhealing.
> [Blood DK] added DS timing graph

- src/Parser/DeathKnight/Blood/Modules/Abilities.js
- src/Parser/DeathKnight/Blood/Modules/Features/BloodPlagueUptime.js
- src/Parser/DeathKnight/Blood/Modules/Features/BoneShieldUptime.js
- src/Parser/DeathKnight/Blood/Modules/Features/Checklist.js
- src/Parser/DeathKnight/Blood/Modules/Features/CrimsonScourge.js
- src/Parser/DeathKnight/Blood/Modules/Features/UnendingThirstTracker.js
- src/Parser/DeathKnight/Blood/Modules/Items/ShacklesofBryndaor.js
- src/Parser/DeathKnight/Blood/Modules/Items/SkullflowersHaemostasis.js
- src/Parser/DeathKnight/Blood/Modules/Items/T21_2pc.js
- src/Parser/DeathKnight/Blood/Modules/RunicPower/RunicPowerDetails.js
- src/Parser/DeathKnight/Blood/Modules/Talents/Ossuary.js
- src/Parser/Druid/Balance/Modules/Features/L90_talents.js
- src/Parser/Druid/Balance/Modules/ResourceTracker/AstralPowerDetails.js
- AsP suggestion was using an inverted threshold and wrong var for percent in tooltip.
- L90 talents was including BoE value even when BoA was active
- fixed ms -> s in 2p21 blood tooltip
- fix BDK bracers % of max RP (was broken by RP module update)
- fix BDK shoulders on vari (no heal event when absorbed) and wasted stacks.
> [Boomkin & BDK] Bug fixes

- src/Parser/Core/calculateEffectiveDamageStacked.js
- src/Parser/DemonHunter/Havoc/CombatLogParser.js
- src/Parser/DemonHunter/Havoc/Modules/Traits/CriticalChaos.js
- src/Parser/DemonHunter/Havoc/Modules/Traits/DemonRage.js
- src/Parser/DemonHunter/Havoc/Modules/Traits/RelicTraits.js
- src/Parser/DemonHunter/Havoc/Modules/Traits/SharpenedGlaives.js
- src/Parser/Paladin/Retribution/Modules/PaladinCore/Retribution.js
- src/common/SPELLS/DEMON_HUNTER.js
[Test Log](https://www.warcraftlogs.com/reports/BHyhvwRqYjrMVfk8#fight=13&type=damage-done&source=1)
Didn't account for the traits that did not have a direct damage increase since I am currently unsure how I would calculate that.
also changed the ordering on the ret paladin stat boxes to make it look nicer.
New:
Old:
> [Havoc] Artifact Traits

- src/Main/Timeline/Events.js
- src/Main/Timeline/SpellTimeline.css
- src/Parser/Paladin/Holy/CHANGELOG.js
- src/Parser/Paladin/Holy/Modules/Abilities.js
- src/Parser/Paladin/Holy/Modules/PaladinCore/FillerFlashOfLight.js
It also has a tooltip to explain the issue:
Example log: http://localhost:3000/report/kzKnrR4qdhXGjB38/16-Heroic+Aggramar+-+Kill+(6:50)/13-Seed%C3%BF
> Highlight inefficient Flash of Light casts in the timeline

- src/Parser/DeathKnight/Blood/CHANGELOG.js
- src/Parser/DeathKnight/Blood/CombatLogParser.js
- src/Parser/DeathKnight/Blood/Modules/Features/Souldrinker.js
- src/common/SPELLS/DEATH_KNIGHT.js
Tracking for the Souldrinker-Trait
(tracking the % is done manually since the combatlog event doesn't contain the exact values)
> [BDK] added Souldrinker

- src/Parser/Hunter/BeastMastery/CombatLogParser.js
- src/Parser/Hunter/Marksmanship/CombatLogParser.js
- src/Parser/Hunter/Shared/Modules/Core/SpellUsable.js
- src/Parser/Hunter/Survival/CombatLogParser.js
All 3 hunter specs were getting their GCD and Cooldown duration disabled under the new requirements. 
Returning true always on them as I am actively maintaining them and they aren't inaccurate (in any trackable degree), some things are merely untrackable (Convergence which is widely used in the specs and Animal Instincts for SV aswell as BM/SV using haste affected CD spells often enough to trigger off racials) 
and I don't feel like completely ruining a ton of metrics by  disabling the CD properties on these spells like I've reluctantly done on DireFrenzy/DireBeast/MongooseBite already. That would reach a point of no big point in having the analyzer if start disabling that much.
> [Hunter] remove errors from timeline

- src/Parser/Monk/Windwalker/Modules/Chi/ChiDetails.js
- src/Parser/Monk/Windwalker/Modules/Features/Checklist.js
- src/Parser/Monk/Windwalker/Modules/Spells/BlackoutKick.js
- src/Parser/Monk/Windwalker/Modules/Spells/ComboBreaker.js
- src/Parser/Monk/Windwalker/Modules/Spells/FistsofFury.js
- src/Parser/Monk/Windwalker/Modules/Spells/StormEarthAndFire.js
- src/Parser/Monk/Windwalker/Modules/Spells/TouchOfKarma.js
- src/Parser/Monk/Windwalker/Modules/Talents/HitCombo.js
Also editing Combo Breaker to %procs used rather than %wasted
Before: 
After:
> [Windwalker] Refactoring order of statistics

- src/Main/Timeline/SpellTimeline.js
- src/Parser/Core/Modules/Abilities.js
- src/Parser/Core/Modules/Ability.js
- src/Parser/Druid/Balance/Modules/Features/Abilities.js
Currently it is sorted by Cooldown length and secondary is spellID, which is not ideal for utility spells with no cooldown as they will show up at the top of the timeline (Druid forms for instance).
This change will allow devs to customize the order as they see fit.
Before:
After:
> [core] Sort timeline to match abilities.js ordering

- src/Parser/Shaman/Restoration/Modules/Items/Tidecallers.js
Fix for tidecallers not working anymore since 7.3.5 because totems became pets.
Before ![image](https://user-images.githubusercontent.com/2842471/37547682-6e49ff76-2973-11e8-9507-e68eb1484378.png)
After ![image](https://user-images.githubusercontent.com/2842471/37547688-77da3b1e-2973-11e8-9ae4-f12301067951.png)
https://wowanalyzer.com/report/gkmp4DxyGhVAjbnz/4-Mythic+Antoran+High+Command+-+Kill+(5:55)/14-Xuany
> [Restoration Shaman] Tidecallers fix for the 7.3.5 totem change

- src/Parser/Priest/Shadow/Modules/Features/Abilities.js
Fixed the potential max void bolts casts. Previously it calculated based on average void form haste, but seems like the cast efficiency module was updated to take current haste into account at all times, which made the old solution double dip on haste.
> Hotfix: max void bolts casts.

- src/Parser/Mage/Arcane/CombatLogParser.js
- src/Parser/Mage/Arcane/Modules/Features/ArcaneMissiles.js
Checks to ensure that the player doesnt have the Arcane Missiles buff when they cast Barrage as they should be using all of their missiles procs before they cast barrage.
> [Arcane Mage] Arcane Missiles Module

- src/Parser/Druid/Restoration/Modules/Talents/Flourish.js
`CENARION_WARD_TALENT` is the cast id, I needed to use the buff id.
> [resto druid] Fixed a bug where Cenarion Ward wasn't being correctly counted by the Flourish tracker

- src/Parser/Shaman/Restoration/CombatLogParser.js
- src/Parser/Shaman/Restoration/Normalizers/CloudburstNormalizer.js
- src/common/SPELLS/SHAMAN.js
Cloudburst has odd behaviour, where, if there is no injured target in range after its done gathering healing, it will explode but create no healing events at all. That is throwing off the cooldown tracker badly, either not creating the CBT cooldown at all if its the first one in combat, or combining that and the next CBT into a mega-CBT.
The normalizer fixes that by creating a dummy heal event with 100% overheal (which is basically what happened anyway) if there aren't any healing events to be found within 20 seconds after casting.
Now i wasn't 100% sure what properties an event needs, so i added all that i thought of important enough, and hitpoints/maxhitpoints so the masteryeffectiveness module doesn't give it NaN.
Example 1 (before and after)
Example 2 (before and after)
> [Restoration Shaman] Cloudburst Totem normalizer

- src/Parser/Hunter/BeastMastery/Modules/Talents/AMurderOfCrows.js
- src/Parser/Hunter/Marksmanship/CHANGELOG.js
- src/Parser/Hunter/Marksmanship/CombatLogParser.js
- src/Parser/Hunter/Marksmanship/Modules/Spells/Trueshot.js
- src/Parser/Hunter/Marksmanship/Modules/Talents/AMurderOfCrows.js
- src/Parser/Hunter/Marksmanship/Modules/Talents/Sentinel.js
- src/Parser/Hunter/Marksmanship/Modules/Traits/Windburst.js
- src/Parser/Hunter/Survival/Modules/Spells/ExplosiveTrap.js
- src/Parser/Hunter/Survival/Modules/Talents/AMurderOfCrows.js
- src/Parser/Hunter/Survival/Modules/Talents/Caltrops.js
- src/Parser/Hunter/Survival/Modules/Talents/DragonsfireGrenade.js
- src/Parser/Hunter/Survival/Modules/Talents/SpittingCobra.js
- src/Parser/Hunter/Survival/Modules/Talents/SteelTrap.js
Fixes the Sentinel module after Blizzard fixed the talent. 
Orange now represents completely missed hits
Also fixes some precast events better than before
Report: https://www.warcraftlogs.com/reports/pXWnbD2aNVF6jGzY/#fight=42&source=41
New: 
Old: 
AoE scenario: 
Report: https://www.warcraftlogs.com/reports/gWxmnqPMfCYZGvtF/#fight=11&source=38
New: 
Old:
> [Marksmanship] Sentinel fix

- src/Parser/Shaman/Restoration/CombatLogParser.js
- src/Parser/Shaman/Restoration/Modules/Features/MasteryEffectiveness.js
- src/Parser/Shaman/Restoration/Modules/Features/TidalWaves.js
- src/Parser/Shaman/Restoration/Modules/Items/UncertainReminder.js
- src/Parser/Shaman/Restoration/Modules/ShamanCore/HealingDone.js
- src/Parser/Shaman/Restoration/Modules/Spells/GiftOfTheQueen.js
- src/Parser/Shaman/Restoration/Modules/Spells/HealingSurge.js
- src/Parser/Shaman/Restoration/Modules/Spells/HealingWave.js
- src/Parser/Shaman/Restoration/Modules/Talents/EarthenShieldTotem.js
- src/Parser/Shaman/Restoration/Modules/Talents/HighTide.js
Finished the High Tide module which appeared to be abondoned.
Removed Spirit Link healing by subtracting the damage done of it and fixed some spacing inconsistencies in the modules, while also removing spaces before % signs in suggestions.
> [Restoration Shaman] High Tide module, Spirit Link removal & spacing fixes

- src/Parser/Shaman/Restoration/CHANGELOG.js
- src/Parser/Shaman/Restoration/Modules/Abilities.js
- src/Parser/Shaman/Restoration/Modules/Features/AlwaysBeCasting.js
- src/Parser/Shaman/Restoration/Modules/Features/CastBehavior.js
- src/Parser/Shaman/Restoration/Modules/Features/TidalWaves.js
- src/common/SPELLS/SHAMAN.js
Removed 
in favour of this style
Added a bunch of abilities and ordered the timeline to group similar spells together.
->
> [Restoration Shaman] Changed Tidal Waves statistics boxes, added missing abilities

- src/CHANGELOG.js
- src/Parser/Core/CombatLogParser.js
- src/Parser/Core/Modules/Items/Legion/AntorusTheBurningThrone/DiimasGlacialAegis.js
- src/Parser/Core/Modules/Items/Legion/AntorusTheBurningThrone/RiftworldCodex.js
- src/Parser/Core/Modules/Items/Legion/AntorusTheBurningThrone/SmolderingTitanguard.js
- src/common/ITEMS/OTHERS.js
- src/common/SPELLS/OTHERS.js
Adds Antorus Trinkets (fixes #1516).
"Eye of F'harg" is not possible to implement as it appears as [Eye of'](http://www.wowhead.com/item=151974/eye-of&bonus=3610:1472) in the log. 
But the actual versions are [Eye of Shatug](http://www.wowhead.com/item=153544/eye-of-fharg&bonus=3610:1472) and [Eye of F'harg](http://www.wowhead.com/item=153544/eye-of-fharg&bonus=3610:1472), with the on-use to switch between both versions during combat. This makes it impossible to track unless the player used the trinket at least once (which happens very very rarely (looked into 20 logs, not a single cast)). The "empowerment" buff between both trinkets is also not trackable as the [buff](http://www.wowhead.com/spell=255769/eye-of-the-hounds) that grands the bonus armor/versatility is invisible and does not …
> [Tanks] Antorus Trinkets

- src/Parser/Core/Modules/HealEventTracker.js
Doing this in a separate PR as it will affect all healers since i couldn't find a good way to only change it for Shamans without extending multiple files. I want this so that Healing Tide / Healing Stream and Spirit Link totems show in the tab as well, which they should (especially Spirit Link).
Not sure why pets are filtered out in the first place, but I guess they're not as impactful for other classes.
> Low Health Healing Tab - Adding Pet Heals

- src/Parser/Core/Modules/Items/PrePotion.js
Brought to my attention by somebody in BrM discord:
**Old:**
**New:**
> Fixed grammar in potion suggestion

- src/Parser/Druid/Guardian/CHANGELOG.js
- src/Parser/Druid/Guardian/Modules/Abilities.js
- src/Parser/Druid/Guardian/Modules/Ability.js
- src/Parser/Druid/Guardian/Modules/Features/AntiFillerSpam.js
I slightly rewrote it to use two different props for isFiller and "Should be prioritized over a filler" (isHighPriority) since there are situations where it might be okay to cast either moonfire or swipe (for instance even with 4> targets you might want to cast moonfire for ST dps).
I also reduced the suggestionThreshold for Mangle to account for resets until we implement a way to account for the GCD after the proc. It was basically always a major issue unless you had terrible procs.
> [Guardian Druid] Highlight bad filler casts.

- server/api.js
Since `https://www.warcraftlogs.com/v1/parses/character/Korudk/Ragnaros/EU?api_key=c02be7c4f23394d13dfe1ed7036f4057` starts with [
> update for WoWA API to support char parses

- src/Main/Cooldown.js
- src/Main/DamageTakenTable.js
- src/Main/LowHealthHealing.js
- src/Parser/Core/Modules/ResourceTracker/ResourceBreakdown.js
- src/Parser/DeathKnight/Shared/RuneBreakdown.js
- src/Parser/Druid/Feral/Modules/ComboPoints/ComboPointBreakdown.js
- src/Parser/Monk/Windwalker/Modules/Spells/SpinningCraneKick.js
- src/Parser/Monk/Windwalker/Modules/Spells/StormEarthAndFire.js
- src/Parser/Priest/Discipline/Modules/Features/AtonementHealingBreakdown.js
- src/Parser/Shaman/Shared/MaelstromChart/MaelstromComponent.js
- src/Parser/Warlock/Destruction/Modules/Features/DimensionalRift.js
- src/Parser/Warlock/Destruction/Modules/SoulShards/SoulShardBreakdown.js
A lot of places have double icons after the icon prop change, i looked for and fixed those that i found.
(and so on)
> Removed double icons

- src/CONTRIBUTORS.js
- src/Main/App.css
- src/Main/App.js
- src/Main/Contributor.js
- src/Main/Contributors/ContributorDetails.js
- src/Main/Portal.js
- src/Parser/DeathKnight/Blood/CONFIG.js
Adresses suggested changes from the last version
- JSX returns wrapped in parenthesis
- removed unnecessary `== true` & `== undefined` & `else` checks
- changed paddings from 30px to the 20px for more layout-consistency
- using AVAILABLE_CONFIGS instead of manual importing all changelogs
- pulling maintained specs from AVAILABLE_CONFIGS instead of CONTRIBUTORS
Also changed to contributor-component to open a modal instead of a new link. 
The ability to link a contributor is still available, might be usefull for something.
Wrapping the modal inside of the portal-component was necessary due to CSS inheritance (e.g. the contributor-components in the changelog-tab would inherit the text-mute & text-align style). I think its cleaner than overwriting the styles that cause issues.
Also might be a …
> Contributors

- src/Parser/Core/Modules/Spells/VantusRune.js
- src/Parser/Monk/Brewmaster/CHANGELOG.js
- src/Parser/Monk/Brewmaster/Modules/Features/Checklist.js
- src/Parser/Monk/Brewmaster/Modules/Spells/BlackoutCombo.js
- src/Parser/Monk/Brewmaster/Modules/Spells/TigerPalm.js
Realized I missed one important item for BrM damage. The current checklist only checks that you didn't cast TP unless you had BoC. This adds the opposite direction: did you have BoC but not cast TP?
Also: fixed Vantus runes having a second icon because it was crashing the page in dev ("Current" screenshot is from current live)
**Current:**
**New:**
> [BrM] Added missing item to damage checklist (+ small vantus rune fix)

- src/Parser/Warrior/Arms/CHANGELOG.js
- src/Parser/Warrior/Arms/Modules/Features/BattleCry.js
Added a Battle Cry damage statistic block that lets you see how much damage you dealt during your burst window. I likely won't add a suggestion for this as smaller suggestions I'll be adding would lead to this metric being reached anyway.
Also addressed a few code review comments from #1560.
> [Arms Warrior] Add Battle Cry damage statistic block

- src/Parser/Monk/Windwalker/Modules/Chi/ChiDetails.js
- src/Parser/Monk/Windwalker/Modules/Chi/ChiTracker.js
Was being used by checklist and ChiDetails, but was accidentally removed when updating to use core resource tracker.
> [Windwalker] Fixed missing "Wasted Chi" tracking

- src/Parser/Hunter/Marksmanship/CHANGELOG.js
- src/Parser/Hunter/Marksmanship/Modules/Talents/AMurderOfCrows.js
As realised in #1564 , the marksmanship AMoC module was actually broken and not working as intended. 
This fixes that.
> [Marksmanship] fix Crows to work again

- src/Parser/Druid/Guardian/CHANGELOG.js
- src/Parser/Druid/Guardian/Modules/Abilities.js
Addresses an issue during Moonfire filler spam detection where if the return value of `this.enemies.getEntity(event)` is `null` (ie, if the target did not have enemy combatant info), then the analyzer would crash.
> [Guardian] Fix a crash with filler spam detection

- src/Main/PlayerBreakdown.js
- src/Parser/Shaman/Restoration/Modules/Features/CastBehavior.js
- src/Parser/Shaman/Restoration/Modules/Features/MasteryEffectiveness.js
- src/Parser/Shaman/Restoration/Modules/Spells/HealingSurge.js
- src/Parser/Shaman/Restoration/Modules/Spells/HealingWave.js
- src/Parser/Shaman/Restoration/Modules/Spells/Resurgence.js
Adjusted some thresholds as T21 shifted the priority a bit.
Removed the spell icons from TW
Fixed the exploding Resurgence Icons 
As the new mastery tab nicely visualized, mastery effectiveness can break if something in the log is corrupt. I haven't been able to confirm what actually caused this, but added a Math.max to circumvent negative effectiveness.
(log: https://www.warcraftlogs.com/reports/M1w2Vcd9jDPTFftA/#fight=12&type=healing&source=19)
> [Restoration Shaman] Tidal Waves thresholds & various fixes

- src/CONTRIBUTORS.js
- src/Parser/Core/Modules/Features/BaseHealerStatValues.js
- src/Parser/Shaman/Restoration/CHANGELOG.js
- src/Parser/Shaman/Restoration/CombatLogParser.js
- src/Parser/Shaman/Restoration/Modules/Features/CooldownThroughputTracker.js
- src/Parser/Shaman/Restoration/Modules/Features/StatValues.js
- src/Parser/Shaman/Restoration/Modules/Features/StatValuesSpellInfo.js
- src/common/SPELLS/SHAMAN.js
Log shown: https://www.warcraftlogs.com/reports/Yj9hc4NWRvxLCaq3#fight=17&type=healing&source=22
Implemented Stat Values for resto shamans. 
It does not include resurgence as mana to HPS appears to be pretty subjective, i plan to add that later as a seperate weight if I find a good middle-ground.
I'm (ab-)using the CooldownThroughputTracker, which stores the healing events per cooldown already anyway - to create feeding events which get processed for statvalues. It's taking the effective feeding value including possible double dipping from combined cooldowns, while accounting for overheal.
> [Restoration Shaman] Stat Values

- src/Parser/Warrior/Arms/Modules/Features/BattleCry.js
Because I accidentally capitalized the parameter.
> [Arms Warrior] Fix Battle Cry suggestion icon

- src/Parser/Warrior/Arms/CHANGELOG.js
- src/Parser/Warrior/Arms/CombatLogParser.js
- src/Parser/Warrior/Arms/Modules/Core/ColossusSmash.js
Adds a suggestion to avoid using Colossus Smash with Shattered Defenses already active.
> [Arms Warrior] Add wasted Colossus Smash/Shattered Defenses suggestion

- src/Parser/Warrior/Arms/CHANGELOG.js
- src/Parser/Warrior/Arms/CombatLogParser.js
- src/Parser/Warrior/Arms/Modules/Core/Execute.js
Adds a suggestion to avoid using execute if the target has two stack of executioner's precision and mortal strike is available.
I actually thought I'd coded it wrong, but it turns out my test subject might need a bit of practice on his execute phase execution.
> [Arms Warrior] Add wasted Executioner's Precision suggestion

- src/Parser/Warrior/Arms/CHANGELOG.js
- src/Parser/Warrior/Arms/CombatLogParser.js
- src/Parser/Warrior/Arms/Modules/Abilities.js
- src/Parser/Warrior/Arms/Modules/Talents/Rend.js
Added Rend to the ability list along with a suggestion to not use it during Execute range. 
I was limited by the cast and debuff events not having access to the enemy health, so I flagged the target id to be checked in the next damage event. This lead to an issue where damage from a good Rend would leak over into the Execute range.
As a workaround I would only flag a Rend as bad if it wasn't the first one whose first damage instance occurred in Execute range, which is probably fine as the player's triggering this suggestion are likely using Rend more than once in Execute range on the same target.
> [Arms Warrior] Add Rend tracking and Rend/Execute range suggestion

- src/Parser/Warrior/Arms/CHANGELOG.js
- src/Parser/Warrior/Arms/CombatLogParser.js
- src/Parser/Warrior/Arms/Modules/Core/MortalStrike.js
Suggests not using mortal strike without shattered defenses where possible.
> [Arms Warrior] Add unshattered Mortal Strike suggestion

- src/Parser/Warrior/Arms/Modules/Abilities.js
Removed bladestorm suggestion because there's no way to realistically get rage starved enough for it to be viable outside of AOE.
> [Arms Warrior] Remove Bladestorm cast efficiency suggestion

- src/Parser/Shaman/Restoration/CHANGELOG.js
- src/Parser/Shaman/Restoration/CONFIG.js
- src/Parser/Shaman/Restoration/CombatLogParser.js
- src/Parser/Shaman/Restoration/Modules/Features/CastBehavior.js
- src/Parser/Shaman/Restoration/Modules/Spells/HealingSurge.js
- src/Parser/Shaman/Restoration/Modules/Spells/HealingWave.js
- src/Parser/Shaman/Restoration/Modules/Talents/AncestralGuidance.js
- src/Parser/Shaman/Restoration/Modules/Talents/Ascendance.js
- src/Parser/Shaman/Restoration/Modules/Talents/CloudburstTotem.js
- src/Parser/Shaman/Restoration/Modules/Talents/EarthenShieldTotem.js
- src/Parser/Shaman/Restoration/Modules/Talents/HighTide.js
- src/Parser/Shaman/Restoration/Modules/Talents/TalentStatisticBox.js
- src/Parser/Shaman/Restoration/Modules/Talents/Torrent.js
- src/Parser/Shaman/Restoration/Modules/Talents/Undulation.js
- src/Parser/Shaman/Restoration/Modules/Talents/UnleashLife.js
- src/Parser/Shaman/Restoration/Modules/Talents/Wellspring.js
- src/common/SPELLS/SHAMAN.js
Added modules for all HPS increasing talents (crashing waves, deluge and echo aren't really possible to value), and a statistics list to display them. The purpose of this is to show the overall HPS impact of each talent. So not only what the talent itself did, but also feeding and synergy / interactions with other spells or talents, the percentage is what you'd lose without the talent, ignoring what you'd gain from the other options.
Since i had to work on Unleash Life already anyway, i also added a module detailing what Spells you used the healing increase on.
> [Restoration Shaman] Talents

- src/CHANGELOG.js
- src/Main/EventsTab.js
Added search functionality to the events tab because I really wanted it. The search box takes a comma delimited list of search terms and matches any event in which the ability, source or target includes one of those terms.
> [Core] Add search function to events tab

- src/Parser/Warrior/Protection/Modules/Abilities.js
- src/common/SPELLS/WARRIOR.js
Added [tier 20 2P](http://www.wowhead.com/spell=242302/item-warrior-t20-protection-2p-bonus) as a condition for the berserker rage suggestion, so it doesn't suggest it for no reason.
> [Protection Warrior] Add tier condition for Berserker Rage suggestion

- src/Main/DamageTakenTable.js
- src/Parser/Monk/Brewmaster/CHANGELOG.js
- src/Parser/Monk/Brewmaster/Modules/Features/DamageTakenTable.js
Fixes #1593.
The tl;dr of the problem (almost exclusively with Agg's Sacrifice on Argus) is that for very small hits you could have less-than-physical stagger mitigation just due to the fact that damage is dealt in whole numbers. Because of how Agg's Sacrifice deals damage it frequently hits for ~2 at least once per fight, causing it to be incorrectly classified as magic mitigation.
**Before:** (Agg sac in magic, at the very bottom so I'm not including the whole list)
**After:**
> [BrM] Damage Type Classification now ignores very small hits

- src/Parser/DeathKnight/Blood/Modules/Features/Checklist.js
MoB should only be displayed in the checklist when MoB is actually specced
> [BDK] remove MoB from checklist if not specced

- src/Parser/Core/Modules/StatTracker.js
This build nerfed all secondaries by about 20%. These numbers are from Dhaubbs as i don't have a level 120 character, will double check them during the raid testing.
Edit: confirmed the numbers myself in the raid
> [BFA] Build 26530 - Updated stat ratings

- src/Parser/Monk/Windwalker/Modules/Features/Checklist.js
- src/Parser/Monk/Windwalker/Modules/Spells/BlackoutKick.js
- src/common/SPELLS/MONK.js
Adding some energize ID's from talents to prevent crashing when loading chi tab. 
Blackout Kick module will have more work done before 8.0 goes live. Right now the statistic box is just a copy from Crusaders Might
> [BfA][Windwalker] Further updating Blackout Kick module and SPELLS.MONK

- src/Main/Timeline/Events.js
- src/Main/Timeline/SpellTimeline.css
- src/Parser/Monk/Windwalker/CHANGELOG.js
- src/Parser/Monk/Windwalker/Modules/Spells/BlackoutKick.js
Implemented specifically for Blackout Kick for Windwalker monk when having the Combo Breaker proc up and T21 2-piece equipped.
Implemented the generic "isEnhancedCast" and "enhancedCastReason" fields to the Spelltimeline event definition so other classes can make use of it too.
Added CSS rule for .enhanced cast in spell timeline.
> Allow highlighting spellcasts in Timeline to indicate a buffed or enhanced cast

- src/Parser/Warrior/Protection/CHANGELOG.js
- src/Parser/Warrior/Protection/CONFIG.js
- src/Parser/Warrior/Protection/CombatLogParser.js
- src/Parser/Warrior/Protection/Modules/Abilities.js
- src/Parser/Warrior/Protection/Modules/Features/AlwaysBeCasting.js
- src/Parser/Warrior/Protection/Modules/Features/SpellUsable.js
- src/Parser/Warrior/Protection/Modules/Talents/BoomingVoice.js
- src/Parser/Warrior/Protection/Modules/Talents/RenewedFury.js
- src/common/SPELLS/WARRIOR.js
- added Booming Voice (with tighter suggestion for AM and casts that cap rage in timeline)
- added Renewed Fury
- updated timeline
- updated several abilities to reflect changes from 7.1.5 (Revenge rework)
- removed onGCD abilities from ABC and updated it in abilties
- added pseudo tracking of Shield Slam resets (acts log-wise like protadins AS, the resets emit no events, if SS was used while its still "on cooldown" it'll use the last possible reset as reset (added warning that its not 100% acurate and SS might have a lower CD))
- added charges to Shield Block
- ordered timeline to be more organized
> [Protection Warrior] some stuff

- src/Parser/Warrior/Protection/CHANGELOG.js
- src/Parser/Warrior/Protection/CombatLogParser.js
- src/Parser/Warrior/Protection/Modules/Abilities.js
- src/Parser/Warrior/Protection/Modules/Core/Haste.js
- src/Parser/Warrior/Protection/Modules/Features/SpellUsable.js
- src/Parser/Warrior/Protection/Modules/Items/T21_2pc.js
- src/Parser/Warrior/Protection/Modules/Talents/Avatar.js
- src/Parser/Warrior/Protection/Modules/Talents/HeavyRepercussions.js
- src/Parser/Warrior/Protection/Modules/Talents/IntoTheFray.js
- src/common/SPELLS/WARRIOR.js
- adds Into the fray
average haste gained + detailed stack uptime + stattracker takes stacks into account
- adds heavy repercussions
adds suggestion when refreshing the SS damage buff (by casting two SBs without an SS inbetween)
- adds avatar
- updates T21 2p & shield slam resets to take the GCD into account 
eg. TC cast would reset SS, SS is of CD but the GCD is still going, resulting in inaccurate SS efficiency
> [Protection Warrior] Into the Fray, Heavy Repercussions, Avatar, Shield Slam Resets update

- src/Main/Character/CharacterParses.js
- src/Main/Character/CharacterSelecter.js
Shows this when a user is hiding his character on WCL.
*also fixed the wen't-mistake*
> [Core] hidden characters fix

- src/Parser/Warrior/Protection/CHANGELOG.js
- src/Parser/Warrior/Protection/CombatLogParser.js
- src/Parser/Warrior/Protection/Modules/Talents/Vengeance.js
- src/common/SPELLS/WARRIOR.js
Adds a breakdown and a statistic for Vengeance usage (Ignore Pain reduces the rage cost of the next Revenge and Revenge the next rage cost of Ignore Pain).
Would've added the a "rage saved" value for Vengeance but WCL isn't sending the correct amount of rage for each cast (eg Revenge has always the 30 baseline cost and IP has 60 when not buffed and 46 when buffed (even when the player had 60+ rage)).
Will add that later on when I figured that out or when WCL is sending something back thats usable.
> [Protection Warrior] added Vengeance

- src/Main/DeathRecap.js
- src/Main/DeathRecapTracker.js
- src/common/DEFENSIVE_BUFFS.js
Adds a new column to the table with all defensive debuffs up on the target for the damage event. Still takes the IDs from all defensive cooldowns (with the same spellID as the ability, the buffSpellId or the `DEFENSIVE_BUFFS`-file).
Might add debuffs for the player aswell (like tank major debuffs that increase damage taken) but I'm right now not quite sure how to add that without making the recap too cluttered.
> [Core] debuffs in Deathrecap 

- src/Parser/Core/Modules/ResourceTracker/ResourceBreakdown.js
- src/Parser/Warrior/Protection/CHANGELOG.js
- src/Parser/Warrior/Protection/CombatLogParser.js
- src/Parser/Warrior/Protection/Modules/Core/RageDetails.js
- src/Parser/Warrior/Protection/Modules/Core/RageTracker.js
- src/Parser/Warrior/Protection/Modules/Features/Checklist.js
- src/Parser/Warrior/Protection/Modules/Features/IgnorePain.js
- src/Parser/Warrior/Protection/Modules/Spells/ShieldBlock.js
- src/Parser/Warrior/Protection/Modules/Talents/Vengeance.js
- src/common/SPELLS/WARRIOR.js
- adds rage tracker & rage breakdown (tracker adjusts the rage cost of Revenge and Ignore Pain when Vengeance is talented as WCL is sending wrong numbers)
- adds rage saved by using Vengeance
- adds a basic checklist
> [Protection Warrior] proper rage tracking + breakdown & checklist

- src/Parser/Monk/Brewmaster/CombatLogParser.js
- src/Parser/Monk/Brewmaster/Modules/Core/StaggerFabricator.js
- src/Parser/Monk/Brewmaster/Modules/Features/Abilities.js
- src/Parser/Monk/Brewmaster/Modules/Features/StaggerTable.js
- src/common/ITEMS/MONK.js
Two things in this PR:
1. Addressed @Gebuz's comments from my previous PR that I wanted to get in quickly so it'd be functional for early testing (and that I didnt have much time to work on in the last couple weeks because of IRL deadlines).
2. Added a stagger events table. The tl;dr on this is that we have literally no idea how the stagger formula works right now, and this gives valuable data as output with a downloadable CSV. Once we do know the formula, the table will be removed and the machinery merged into other things where appropriate.
> [BFA] [BrM] Stagger Data Table

- src/Main/DeathRecapTracker.js
- src/Parser/Monk/Brewmaster/Modules/Features/Abilities.js
Checked previously in the spell for the prop `buffSpellId`, which would always return undefined and then check if the spells ID.
> [Core] Death recap fix for different spellIds

- src/Main/DeathRecap.js
- src/Main/DeathRecapTracker.js
- abilities have now spell-links
- the amount reveals who healed/damaged you (and shows how much absorbed/overhealing was done, should also help explaining what `O` and `A` means)
- cooldowns are now ordered by their timelineIds, regardless of their cooldown-state
- new link to take the user to WCLs death-pane
> [Core] Death Recap with SpellLinks, sourceName, new cooldown order & link to WCLs death pane

- src/CONTRIBUTORS.js
- src/Parser/Druid/Feral/CHANGELOG.js
- src/Parser/Druid/Feral/CombatLogParser.js
- src/Parser/Druid/Feral/Modules/Bleeds/RakeSnapshot.js
- src/Parser/Druid/Feral/Modules/FeralCore/Snapshot.js
- src/common/SPELLS/DRUID.js
The snapshotting of DoTs is a unique feral mechanic. This is a snapshot analyzer that keeps track of what applicable buffs were active when rake is cast, marks "bad" casts on the timeline and offers suggestions to fix lost damage from poor management of snapshots.
The generic tracking is handled in Snapshot while the rake-specific parts are in RakeSnapshot. Additional analyzers for the important feral DoTs can be made that also extend Snapshot, but I didn't want to cram too much into a single PR.
RakeSnapshot enforces 2 rules that are recommended by the feral theorycraft community. In order of precedence:
- Only ever refresh a rake buffed by prowl/incarnation if the one you apply would have that buff too.
- When you have a less powerful set of buffs than is already present on the DoT, …
> [Feral] Snapshot Tracking for Rake

- src/Parser/Shaman/Restoration/Modules/Spells/HealingRain.js
- src/Parser/Shaman/Restoration/Modules/Spells/HealingRain.test.js
Currently the healing rain module divides ticks by looking at the exact millisecond, but looking at logs it appears that ticks can be split up a bit (seen up to 83ms). Often you have 1 hit followed by 5 hits within 5ms, which it currently interprets as 2 different sets of ticks even though its just 1.
I gave it a buffer of 85ms to correct that behaviour, and average ticks went up in all logs as you'd expect, and checking the array i haven't found wrong groupings.
Varimathras rank 1 log where you'd expect 6 hits per tick (before & after):
Argus (again you'd expect high amount of hits):
Kingaroth:
> [Restoration Shaman] Healing Rain tick calculation change

- src/Parser/Druid/Feral/CHANGELOG.js
- src/Parser/Druid/Feral/Modules/Features/Abilities.js
- src/common/SPELLS/DRUID.js
Added buffSpellId to applicable Feral abilities.
Gave each a timelineSortIndex, grouping up similar abilities and putting the core rotation at the top.
Marked movement and additional survival abilities as isDefensive so they show up on the death recap.
Added in a couple of missing abilities.
Sprinkled in comments for GCDs (as they are in 7.3.5), to save finding it again when ability-specific GCD handling is added.
The icon name `spell_druid_stamedingroar` misspelling is intentional, it's how Blizzard named it.
> [Feral] Add details to Abilities

- src/Parser/Druid/Feral/CHANGELOG.js
- src/Parser/Druid/Feral/CombatLogParser.js
- src/Parser/Druid/Feral/Modules/Bleeds/RipSnapshot.js
- src/Parser/Druid/Feral/Modules/FeralCore/Snapshot.js
This analyzer keeps track of the power of the player's Rip bleeds. It provides suggestions when they are downgrading a snapshot or failing to use Bite when they could have extended a good snapshot.
Feral's Rip bleed benefits from snapshotting the effect of Tiger's Fury and Bloodtalons over its full duration, even after the buffs have worn off. Unlike Feral's other DoTs Rip's base damage also varies by how many combo points were used when it was cast. At <25% health, or always with the Sabertooth talent, Rip's duration can be extended with Ferocious Bite. Extending with Bite maintains the existing snapshot effect.
As well as adding RipSnapshot, there's some refactoring in Snapshot (which is now used by RipSnapshot and RakeSnapshot) to expose the power calculation so RipSnapshot can add to …
> [Feral] Snapshot tracking for Rip

- src/CHANGELOG.js
- src/Main/DeathRecap.js
- src/Main/DeathRecapTracker.js
- src/Parser/Core/CombatLogParser.js
- src/Parser/Core/Modules/Items/Healthstone.js
- src/Parser/Monk/Brewmaster/Modules/Features/Abilities.js
- src/common/DEFENSIVE_BUFFS.js
- src/common/SPELLS/OTHERS.js
Also fixed an issue with death recap not working with multi id spells in the spellbook (such as healthstone/pot).
> [Core] Add healthstone/health pots to spellbook and death recap.

- src/Parser/Druid/Feral/CHANGELOG.js
- src/Parser/Druid/Feral/CombatLogParser.js
- src/Parser/Druid/Feral/Modules/Bleeds/MoonfireSnapshot.js
Moonfire (granted to Feral only with the Lunar Inspiration talent) is the simplest of the snapshot-benefiting abilities as it only benefits from the damage bonus of Tiger's Fury, and unlike Rip has no other mechanics affecting its base damage.
The same rule applies for Moonfire as the rest: only refresh before pandemic if you would upgrade the snapshot. Using the Snapshot class shared with RakeSnapshot and RipSnapshot, this analyzer checks for the combatant "downgrading" their Moonfire DoTs. Inefficient casts are marked on the timeline and a suggestion is generated if they do it often.
> [Feral] Snapshot tracking for Moonfire

- src/Parser/Mage/Frost/Modules/Features/Checklist.js
- src/common/SPELLS/MAGE.js
Missed a reference to SPELLS.EBONBOLT which caused a crash when loading logs.
> [BFA] [Frost Mage] Fix Checklist Crash

- src/Parser/Druid/Feral/CombatLogParser.js
- src/Parser/Druid/Feral/Modules/Bleeds/MoonfireSnapshot.js
- src/Parser/Druid/Feral/Modules/Bleeds/RakeSnapshot.js
- src/Parser/Druid/Feral/Modules/Bleeds/RipSnapshot.js
- src/Parser/Druid/Feral/Modules/FeralCore/Snapshot.js
- src/Parser/Druid/Feral/Modules/Normalizers/RakeBleed.js
This adds a RakeBleed normalizer which ensures the `applydebuff` or `refreshdebuff` for Rake's bleed always appear after that Rake's `cast` event. With this normalizer in place the code in Snapshot that handled them being out of order is now removed. After checking with a lot of logs it's only ever Rake that had the events in the wrong order, and only when used from stealth.
I also made some minor changes to the Snapshot, RakeSnapshot, RipSnapshot, and MoonfireSnapshot modules from my recent pull requests.
- `castCount` is now maintained on Snapshot rather than having near identical code on each subclass.
- The threshold for "major" suggestions about snapshot downgrading has been significantly pushed up. With current Feral tuning even completely messing up the snapshot mechanic is a …
> [Feral] Rake normalizer, minor changes in Snapshots

- src/Parser/Druid/Feral/Modules/Bleeds/MoonfireSnapshot.js
- src/Parser/Druid/Feral/Modules/Bleeds/RakeSnapshot.js
- src/Parser/Druid/Feral/Modules/Bleeds/RipSnapshot.js
- src/Parser/Druid/Feral/Modules/FeralCore/Snapshot.js
- src/Parser/Druid/Feral/Modules/Normalizers/RakeBleed.js
- src/Parser/Druid/Feral/Modules/Normalizers/RakeBleed.test.js
Adds a test for Feral's RakeBleed normalizer. A second set of eyes for any missed missed combinations to test is very welcome. It get picked up by and passes locally with `npm run test`
There are also a number of fixes from the review of #1770, with the bulk of the changes coming from making the properties of Snapshot which don't change during event parsing be static.
> [Feral] Test for RakeBleed normalizer, plus fixes from review

- src/Parser/Warrior/Protection/Modules/Talents/AngerManagement.js
https://wowanalyzer.com/report/VBxMtwKyr3aq4gTb/4-Heroic+Garothi+Worldbreaker+-+Kill+(6:21)/1-Ata
Would crash due to the missing `classResources` prop on some spells (in this case KJBW). 
Also updated the `classResources`-check to look into all elements and check if it has infos on rage-cost.
Doesn't cause any issues right now, but should be more robust this way if Blizzard decides to mess with the `classResources`-field.
> [Protection Warrior][Bug] Ragetracker fix

- src/Parser/Druid/Feral/CHANGELOG.js
- src/Parser/Druid/Feral/CombatLogParser.js
- src/Parser/Druid/Feral/Modules/Bleeds/RakeSnapshot.js
- src/Parser/Druid/Feral/Modules/Bleeds/RipSnapshot.js
- src/Parser/Druid/Feral/Modules/FeralCore/Snapshot.js
- src/Parser/Druid/Feral/Modules/Talents/MoonfireSnapshot.js
Adds tick and damage counting to the existing Snapshot analyzer, and uses that to generate statistics for how each DoT benefited from the snapshot buffs.
How much a DoT benefited is measured by counting the damage tick events and checking what snapshot buffs were active for the DoT on that target at the time. The increase in damage due to each buff is also calculated from the tick. It only deals with the DoT ticks, not the initial damage that Rake and Moonfire also apply.
The % of ticks benefiting from each snapshot buff could be a useful measure in a future checklist for the spec. Although care should be taken as there's quite a lot of variability in what's possible even on a simple fight depending on legendaries and talents.
> [Feral] Statistic for uptime of snapshot on DoTs

- src/Parser/Warrior/Protection/CombatLogParser.js
- src/Parser/Warrior/Protection/Modules/Abilities.js
- src/Parser/Warrior/Protection/Modules/Core/RageTracker.js
- src/Parser/Warrior/Protection/Modules/Features/Avatar.js
- src/Parser/Warrior/Protection/Modules/Features/Checklist.js
- src/Parser/Warrior/Protection/Modules/Talents/BoomingVoice.js
- src/Parser/Warrior/Protection/Modules/Talents/Punish.js
- src/common/SPELLS/TALENTS/WARRIOR.js
- src/common/SPELLS/WARRIOR.js
- makes Avatar baseline (and removes Battle Cry) (still using `AVATAR_TALENT` even if its a baseline ability for prot, but its a shared spell with Arms)
- adds the "Punish" talent
- updates talent nerfs
- adds "Bolster" and "Unstoppable force" CDR
> [BfA][Protection Warrior] initial update

- src/Parser/Monk/Brewmaster/CombatLogParser.js
- src/Parser/Monk/Brewmaster/Modules/Core/StaggerFabricator.js
- src/Parser/Monk/Brewmaster/Modules/Spells/Guard.js
This adds a stat for Guard to the BrM analysis.
The way guard is logged is mildly annoying: when the buff is applied (if applied in the fight--due to the 15s duration it could be applied prior) we get an `absorb` field on the `applybuff` event that tells how much damage it will absorb. Then, each stagger `absorbed` event is logged exactly as normal. When the last of the Guard absorb is consumed, we get a `removebuff` event with `absorb` equal to the amount absorbed by the last Stagger absorb (I'm 99% sure, I don't actually use that bit so I didn't do more than a cursory check).
I represent the absorbed stagger damage by immediately removing stagger after adding it. While not technically correct, it does have the correct impact on other modules in the codebase (including the plot, which …
> [BFA] [BrM] Guard!

- src/Parser/Monk/Brewmaster/Modules/Spells/Guard.js
This PR addresses two things:
1. Sometimes the buff fades not exactly 15000 MS after the application but a bit after; those events are now counted.
2. Changed the presentation of Guard's effect. I realized that although technically it can be counted as healing, presenting it this way is misleading. Guarded damage doesn't show up as damage taken, and so showing it as healing made it appear more effective than it actually was (e.g. 1.2k HPS with 4.5k DTPS is "25% of damage healed" but it actually only mitigated 21%).
> [BFA] [BrM] Quick Guard Fix

- src/Parser/Monk/Windwalker/Modules/Talents/HitCombo.js
- src/Parser/Paladin/Retribution/CHANGELOG.js
- src/Parser/Paladin/Retribution/CombatLogParser.js
- src/Parser/Paladin/Retribution/Modules/Abilities.js
- src/Parser/Paladin/Retribution/Modules/Features/Checklist.js
- src/Parser/Paladin/Retribution/Modules/Items/AshesToDust.js
- src/Parser/Paladin/Retribution/Modules/Items/ChainOfThrayn.js
- src/Parser/Paladin/Retribution/Modules/Items/Tier20_2set.js
- src/Parser/Paladin/Retribution/Modules/Items/Tier21_2set.js
- src/Parser/Paladin/Retribution/Modules/Items/WhisperOfTheNathrezim.js
- src/Parser/Paladin/Retribution/Modules/PaladinCore/Haste.js
- src/Parser/Paladin/Retribution/Modules/PaladinCore/Judgment.js
- src/Parser/Paladin/Retribution/Modules/PaladinCore/Retribution.js
- src/Parser/Paladin/Retribution/Modules/Talents/Inquisition.js
- src/Parser/Paladin/Retribution/Modules/Talents/RighteousVerdict.js
- src/Parser/Paladin/Shared/Modules/GetDamageBonus.js
- src/Parser/Paladin/Shared/Modules/getDamageBonusStacked.js
- src/common/SPELLS/PALADIN.js
New checklist rule: 
New statistics: 
Unfortunately i couldn't find any logs where the player using Righteous Verdict wasn't AFK, so it's 0 in everything here because of that
> [BfA][Ret]Adding Inquisition and Righteous Verdict modules and updating checklist

- src/Parser/Warrior/Protection/Modules/Core/RageTracker.js
- src/common/SPELLS/WARRIOR.js
Warriors dont generate rage from damage taken anymore in BfA.
Instead they'll generate 2 rage per melee swing, and 3 rage for every melee hit taken (with an 1sec ICD).
Adjusts the IP cost to the static 40 rage from the old 20-60 range.
> [BfA][Protection Warrior] Rage generation

- src/Parser/Mage/Fire/CHANGELOG.js
- src/Parser/Mage/Fire/CONFIG.js
- src/Parser/Mage/Fire/Modules/Features/CombustionCharges.js
- src/Parser/Mage/Fire/Modules/Features/Pyroclasm.js
- Updated Patch Compatibility to 8.0
- Removed Spell Links to legendary items in Changelog
- Added Changelog entry for updated spec
- Updated Pyroclasm to 250% damage buff instead of 300%, per most recent balacing update.
> [Prepatch] [Fire Mage] Final Fire Changes

- src/Parser/Core/Modules/Ability.js
- src/Parser/Core/Modules/GlobalCooldown.js
We recently gained support for having an ability's GCD vary with more than just haste by defining its GCD's `static` or `base` prop as a function:
```
gcd: {
static: combatant => 1000 * (1 - (combatant.hasBuff(SPELLS.ADRENALINE_RUSH.id) ? 0.2 : 0)),
},
```
But some abilities switch between static and haste-affected GCDs depending on the situation. This PR gives support for an ability's whole GCD definition to be a function:
```
gcd: (combatant => {
if (combatant.hasBuff(SPELLS.CAT_FORM.id)) {
return {
base: 1000,
};
}
if (combatant.hasBuff(SPELLS.BEAR_FORM.id)) {
return {
base: 1500,
};
}
return {
static: 1500,
};
}),
```
It doesn't support a function that returns `null`or`false` (meaning the ability is unaffected by the GCD), as quite a lot of existing code is built on the assumption …
> [BFA][Core] Allow an ability's GCD prop to be a function

- src/Main/EventsTab.js
Fixes this bug.  Was only happening specifically in this component.
> Fixes #1843.  ReactTooltip enabled for EventsTab.

- src/Parser/Core/Modules/StatTracker.js
- src/Parser/Druid/Feral/Modules/Abilities.js
- src/common/SPELLS/DRUID.js
Went through the in-game spell book systematically on a couple of Feral Druids, and believe I have everything now. I also re-checked GCDs for build 26936.
There's some spells in there which are unlikely to see use during a raid fight (e.g. teleporting to the Emerald Dreamway or befriending a passing rabbit) but I included them for the sake of completeness.
None of the Feral-specific legendaries trigger visible procs in 8.0.1 (Fiery Red Maimers do in 7.3.5, but are changed in the patch) so there's no SPELLS entries for them. But did add the hidden buffs and visible procs for all the Legion Feral tier sets.
The diff might show some "shared talent spells" in SPELLS being removed, but they're just moved up to the top to be next to the other shared spells. There was nothing related to the …
> [BFA][Feral] Missing spells

- src/Parser/Druid/Feral/CHANGELOG.js
- src/Parser/Druid/Feral/CombatLogParser.js
- src/Parser/Druid/Feral/Constants.js
- src/Parser/Druid/Feral/Modules/Bleeds/RakeSnapshot.js
- src/Parser/Druid/Feral/Modules/Bleeds/RipSnapshot.js
- src/Parser/Druid/Feral/Modules/Features/Abilities.js
- src/Parser/Druid/Feral/Modules/Features/SpellUsable.js
- src/Parser/Druid/Feral/Modules/FeralCore/Snapshot.js
- src/Parser/Druid/Feral/Modules/Talents/MoonfireSnapshot.js
- src/Parser/Druid/Feral/Modules/Talents/Predator.js
- src/Parser/Druid/Feral/Modules/Talents/SavageRoarDmg.js
"The cooldown on Tiger's Fury resets when a target dies with one of your Bleed effects active, and Tiger's Fury last 4 additional seconds."
Set up SpellUsable for Feral which attempts to track when an enemy last died with a bleed active, and uses that timestamp to reset Tiger's Fury cooldown when it's used early with the Predator talent. Possible deaths are based on bleed debuffs fading early. There can be other causes of DoTs being removed early so it doesn't make any firm claims about how many enemies died with bleeds on them.
Made a Predator analyzer that assesses how many extra Tiger's Fury casts Predator has given the player, providing a statistic and suggestion. It tracks both overall cast count increase and how many casts were earlier than would have been possible without the …
> [Feral] Predator talent

- src/Parser/Mage/Frost/Modules/Features/Abilities.js
- src/Parser/Mage/Frost/Modules/Features/Checklist.js
- src/Parser/Mage/Frost/Modules/Features/GlacialSpike.js
The rotation for Glacial Spike was slightly changed.
Now it is a DPS increase (something like 2-3%) to hold Glacial Spike until you have a Brain Freeze Proc to cast with it as opposed to getting as many Glacial Spike's out as possible.
Additionally, because of this, if the player is spec'd into Ebonbolt, they should hold Ebonbolt and purposely not cast it just incase they have Glacial Spike and need a proc in a pinch. Because of this, it is acceptable (if they player has good luck) for them to never cast Ebonbolt in the fight.
> [Prepatch] [Frost Mage] Glacial Spike Changes

- src/Parser/Druid/Feral/CHANGELOG.js
- src/Parser/Druid/Feral/CombatLogParser.js
- src/Parser/Druid/Feral/Modules/Spells/PredatorySwiftness.js
> Your finishing moves have a 20% chance per combo point to make your next Regrowth or Entangling Roots instant, free, and castable in all forms.
Normally this passive just provides some free heals or utility, but with the Bloodtalons talent it becomes part of the core rotation. This Analyzer tracks if the Predatory Swiftness buffs are being wasted.
It only provides a suggestion if the buff is being being wasted while the player has the Bloodtalons talent. The statistic is always shown as the information might be interesting to the player.
Unfortunately the Feral legendary [Ailuro Pouncers](http://bfa.wowhead.com/item=137024/ailuro-pouncers) breaks this Analyzer. The Pouncers allow Predatory Swiftness to have up to 3 stacks, but the combat log still only shows an event for gaining or …
> [BFA][Feral] Tracking for Predatory Swiftness

- src/Interface/Character/Parses.js
- src/Interface/Character/ParsesList.js
Now links logs without advanced logging to the combatantSelector of the log (which is already checking if the log was made with advanced logging or not)
> [Core][Bug] Fix for logs without advanced logging

- .env.local.example
WarcraftLogs changed the page where the API key is displayed.
(Same change needed on master too)
> [BFA] Update WarcraftLogs url in .env.local.example

- src/Parser/Core/Modules/Items/Healthstone.js
I got a complaint from the mage discord that the wording on the healthstone suggestion was misleading. When I looked into it, it seems that this was some confusion caused by the default Cast Efficiency suggestion text which essentially stated you should keep Healthstone on cooldown for 60% of the fight or else you are doing it wrong. This made the player think that we were telling them that they should use the healthstone early in the fight so that it is on cooldown for more than 60% of the fight, which isnt what we were saying. 
So, I changed the importance to minor (to match the changes in BFA), turned off the default suggestion, and made a custom suggestion for it with different wording.
Im assuming this is going to cause a conflict with the BFA Branch. Not sure if i should put up a …
> Healthstones Suggestion Rework

- src/Parser/Core/Modules/SpellUsable.js
- src/Parser/Monk/Windwalker/CombatLogParser.js
- src/Parser/Monk/Windwalker/Modules/Abilities.js
- src/Parser/Monk/Windwalker/Modules/Spells/BlackoutKick.js
- src/Parser/Monk/Windwalker/Modules/Talents/Serenity.js
Adding extendCooldown() to spellUsable for maintainability. The Serenity module so far has no statistics or suggestions, but might be adding some tracking on the CDR gained through it later.
> [BfA][Windwalker] Updating cooldown handling with Serenity

- src/Parser/Mage/Fire/Modules/Features/HeatingUp.js
- src/Parser/Mage/Fire/Modules/Features/Pyroclasm.js
- src/Parser/Mage/Fire/Modules/Features/SearingTouch.js
- Fixed the Statistic Box for Heating Up so it displays the double stat box if they have Phoenix Flames, and a single box if they dont.
- Updated Pyroclasm and Searing Touch to use the new constructor instead of on_initialized() and selectedCombatant instead of combatants.selected
> [Prepatch] [Fire Mage] Fixes for Heating Up, Pyroclasm, Searing Touch

- src/Parser/Core/CombatLogParser.js
- src/Parser/Core/Modules/Items/BFA/Dungeons/FangsOfIntertwinedEssence.js
- src/Parser/Core/Modules/Items/BFA/Dungeons/LingeringSporepods.js
- src/common/ITEMS/BFA/Dungeons/index.js
- src/common/SPELLS/BFA/Dungeons/ITEMS.js
Related issue: #1695 
Fangs of Intertwined Essence [(wowdb)](https://beta.wowdb.com/items/158368-fangs-of-intertwined-essence)
> Use: Your next 6 healing spells restore [x] mana. (2 Min Cooldown)
A trinket intended for healers that drops from Avatar of Sethraliss in the Temple of Sethraliss (dungeon.) As with other "on use" trinkets, the activation of the trinket is added as an ability with a cast efficiency suggestion. The analyzer tracks the total mana it restores and how many times the restoration is triggered. If the player doesn't trigger all 6 mana restorations in the time when the buff is active an additional suggestion is generated.
Example logs:
Holy Priest in M+ https://www.warcraftlogs.com/reports/yt9FDTXwfHcm8V6K#fight=1&source=57
Mistweaver Monk in M+ …
> [BFA] Trinket: Fangs of Intertwined Essence

- src/common/stats.js
- src/common/stats.test.js
WCL now reports ranks as the full ilvl rather than the difference from ilvl 251. Updated the scaling function and tests to match this.
> [BFA][Core] Azerite Rank change

- src/Parser/Core/CombatLogParser.js
- src/Parser/Core/Modules/Items/BFA/Dungeons/BalefireBranch.js
- src/Parser/Core/Modules/Items/BFA/Dungeons/LingeringSporepods.js
- src/Parser/Core/Modules/StatTracker.js
- src/common/SPELLS/BFA/Dungeons/ITEMS.js
Related issue: #1698 
**Balefire Branch** [(wowdb)](https://beta.wowdb.com/items/159630-balefire-branch)
>Use: Kindle your soul, gaining [x] Intellect, which decays over 20 sec or when taking damage. (1 Min, 30 Sec Cooldown)
Fortunately the decaying intellect is represented as a stacking buff that is mostly reported correctly in the combat log (the exception is when it's first applied at 100 stacks, which shows as 1.)
As with other "on use" trinkets an ability is added with a default cast efficiency suggestion. There's no cast event shown in the log when the trinket is used, so an event is fabricated when trinket use is detected through applybuff.
Using the same technique as the Eye of Command trinket from Legion, the analyzer tracks the average number of stacks and so the average …
> [BFA] Trinket Balefire Branch

- src/Parser/Core/CombatLogParser.js
- src/Parser/Core/Modules/Features/SpellInfo.js
- src/Parser/Core/Modules/Items/BFA/Crafted/DarkmoonDeckTides.js
- src/Parser/Shaman/Restoration/Constants.js
- src/common/ITEMS/BFA/Crafted/index.js
- src/common/SPELLS/BFA/Crafted/ITEMS.js
- src/common/SPELLS/BFA/Crafted/index.js
- src/common/SPELLS/BFA/index.js
>Equip: Restores a moderate amount of mana when the deck is shuffled. Chance to throw a card to a random party member, healing them and bouncing to other party members. Amount of mana restored and number of bounces depends on the topmost card in the deck. 
>Equip: Periodically shuffle the deck while in combat.
Nothing extraordinary about this trinket, apart from that only the Ace card restores mana currently. I'm assuming that it gets fixed for live.
Using its actual Icon seems to break it though 
since [wowdb](https://beta.wowdb.com/items/159127-darkmoon-deck-tides) doesn't have that icon for some reason.  
Keeping the promises icon as a placeholder for now.
Log used: https://www.warcraftlogs.com/reports/h6RvrVTAJLHY4ndz#fight=last&type=healing&source=3
closes #1723
> [BFA] Trinket: Darkmoon Deck: Tides

- src/Parser/Druid/Feral/Modules/Features/SpellUsable.js
- src/Parser/Druid/Feral/Modules/Talents/Predator.js
A couple of classes snuck through the change and were still using `on_initialised` and `this.combatants.selected`
> [BFA][Feral] Update to use selectedCombatant and constructor (minor)

- src/Parser/Druid/Feral/CHANGELOG.js
- src/Parser/Druid/Feral/CombatLogParser.js
- src/Parser/Druid/Feral/Modules/FeralCore/HitCountAoE.js
- src/Parser/Druid/Feral/Modules/Spells/SwipeHitCount.js
- src/Parser/Druid/Feral/Modules/Spells/ThrashHitCount.js
- src/Parser/Druid/Feral/Modules/Talents/BrutalSlashHitCount.js
Feral has two primary AoE abilities: Thrash and Swipe. These should only be used if they'll hit more than one target, as on one target the player would do more damage filling with Shred instead. The talent Brutal Slash replaces Swipe with a more powerful ability. With that talent selected it should be used even against a single target. But if Brutal Slash is mostly only hitting one target the player would do more damage if they'd picked a different talent (the exact threshold will need to be found from simulations once they properly support BFA, but for now an average of 1.2 targets hit is used as a conservative estimate.)
This adds a generic HitCountAoE analyzer to find how many targets are hit by each use of an AoE ability. This is extended to track each of the Feral AoE abilities, then …
> [BFA][Feral] Add hit count tracking for AoE abilities

- src/Parser/Druid/Feral/Modules/Bleeds/RakeUptime.js
- src/Parser/Druid/Feral/Modules/Bleeds/RipUptime.js
- src/Parser/Druid/Feral/Modules/Features/AlwaysBeCasting.js
- src/Parser/Druid/Feral/Modules/Talents/MoonfireUptime.js
- src/Parser/Druid/Feral/Modules/Talents/SavageRoarUptime.js
Pulled out the suggestion thresholds for Feral's uptime trackers into getters so they'll be easily available to the checklist (#1883)
Also took the opportunity to add a little more detail to the suggestion texts.
> [BFA][Feral] Small refactor of uptime trackers

- src/Parser/Shaman/Restoration/CHANGELOG.js
- src/Parser/Shaman/Restoration/CombatLogParser.js
- src/Parser/Shaman/Restoration/Modules/Abilities.js
- src/Parser/Shaman/Restoration/Modules/Talents/NaturesGuardian.js
- src/Parser/Shaman/Restoration/Modules/Talents/TalentStatisticBox.js
- Added support for the Nature's Guardian talent by creating a cast event for every heal event. Probably doesn't add much of value but might be interesting for some people.
- Changed Tremor Totem's GCD to be reduced by haste.
https://bfa.wowhead.com/spell=30884/natures-guardian
>When your health is brought below 35%, you instantly heal for 20% of your maximum health.  Cannot occur more than once every 45 sec.
> [BFA][Restoration Shaman] Nature's Guardian

- src/Parser/Mage/Arcane/CONFIG.js
- src/Parser/Mage/Frost/CONFIG.js
Updated the Frost Compat Version to match the other specs (8.0.1 instead of 8.0.0)
Updated Arcane to Compatible with 8.0.1
I did the Arcane updates a few weeks ago, forgot to update the version.
> Mage Compat Version

- src/Parser/Mage/Fire/Modules/Features/Pyroclasm.js
Blizzard released another wave of tuning updates and Pyroclasm went from 250% bonus damage to 225%
> [Fire Mage] Pyroclasm Tuning

- src/Parser/Druid/Feral/Modules/Spells/ThrashHitCount.js
With pre-patch tuning using Thrash on a single target is roughly damage-neutral with using Shred (varies a bit depending how much mastery and haste they have). It's a worthwhile damage gain with certain legendaries.
A new analyzer can be added in the future to find exactly when it's worth using based on the player's stats, but for now we should stop yelling at people for doing it.
> [Feral] Remove single target Thrash suggestion

- src/Parser/Hunter/Marksmanship/Modules/Talents/HuntersMark.js
Critical Error preventing (as far as I can tell all) most logs using Hunter's Mark, stalling the analyzer. Non-existant enemy still has hasBuff called.
Example: https://wowanalyzer.com/report/AVca2P6YXfxmkdDQ/1/7
Hunter's Mark is still bugged if cast before the fight, but this is a quick fix to get the analyzer working.
Accidentally closed the previous PR, #1920
> [MMS] Hunter's Mark Bug Fix

- src/Parser/Core/EventGrouper.js
- src/Parser/Core/EventGrouper.test.js
- src/Parser/Priest/Discipline/CHANGELOG.js
- src/Parser/Priest/Discipline/CONFIG.js
- src/Parser/Priest/Discipline/Modules/Spells/Penance.js
Penance has broken due to a regression in how the game handles Penance cast events. Previously, one was generated for each bolt, now this only seems to happen for heals. This PR will fix that and hopefully future proof it a little.
It's currently impossible to accurately account for Penance in the timeline because of this though :(
---
* Fixed Penance
* Updated the spec compatibility
* Added a changelog message to indicate bfa readiness
* Added a new EventGrouper tool that will automatically group incoming events to a previous stem event, this is based off a provided threshold. (It's also iterable, which is amazing)
> Penance Bugfix

- src/Parser/Druid/Feral/Modules/Abilities.js
- src/Parser/Druid/Feral/Modules/FeralCore/HitCountAoE.js
Fixes a crash that can happen if damage from an AoE cast is reported before the cast. That ordering seems to only happen if the ability is used while stealthed, which is unusual player behaviour. Ideally would be fixed with a normalizer but just avoid crashing for now.
Example log which triggers the bug: https://www.warcraftlogs.com/reports/v7nLNGj3ACBY91kq/#fight=9&source=92
Also added the other spellId for Skull Bash to the abilities spellbook.
> [Feral] HitCountAoE bug fix

- src/Parser/Paladin/Retribution/Modules/Items/WhisperOfTheNathrezim.js
- src/Parser/Paladin/Retribution/Modules/Talents/RighteousVerdict.js
For some reason, it wasn't checking for the buff correctly in `on_byPlayer_cast`, so it's been moved to check in `on_byPlayer_damage` instead. 
Suggestions thresholds have been changed by request of class experts.
> [Ret] Fixing Righteous Verdict and Whispers of the Nathrezim

- src/Parser/Paladin/Retribution/Modules/Talents/DivinePurpose.js
The statistic wasn't counting back to back procs with `getBuffTriggerCount` since that only tracks when the buff is applied and not when it's refreshed.
> [Ret] Quick fix for Divine Purpose

- src/Parser/Hunter/Marksmanship/Modules/Talents/HuntersMark.js
Hunter's Mark is a permanent debuff that does not draw boss aggro, and as such it is often optimally cast before the fight has started. WCL's API seems unable to handle this, as hasBuff and stackHistory both have issues detecting this buff being active. The live implementation does not account for any damage done to a marked target if the target was marked before the fight began.
The fix for this involves determining whether the debuff was precast by looking for the first removedebuff event cast and (after ensuring that it comes before the first applydebuff cast of marked shot) determining the target, and then retroactively adding the marked damage done to that target to the marked damage total.
While this fixes the bug, it is my personal opinion that this seems like a bug in WCL's API, …
> [MMS Hunter] Fixed Hunter's Mark Damage Calculation

- src/Parser/Monk/Brewmaster/CHANGELOG.js
- src/Parser/Monk/Brewmaster/CONFIG.js
- src/Parser/Monk/Brewmaster/Modules/Core/MasteryValue.js
- src/Parser/Monk/Brewmaster/Modules/Spells/HighTolerance.js
Three small pieces:
1. Places that care about HT now also check for the talent ring.
2. Temporarily disable the mastery module (just `this.active = false`) until I get new coefficients in.
3. bump version + update example log + update description so people maybe stop asking questions in #craft-brewing.
> [BFA] [BrM] Last bit of brew cleanup, plus version bump

- src/Parser/Monk/Brewmaster/CHANGELOG.js
- src/Parser/Monk/Brewmaster/CONFIG.js
- src/Parser/Monk/Brewmaster/CombatLogParser.js
- src/Parser/Monk/Brewmaster/Modules/Abilities.js
- src/Parser/Monk/Brewmaster/Modules/Core/MasteryValue.js
- src/Parser/Monk/Brewmaster/Modules/Items/T20_2pc.js
- src/Parser/Monk/Brewmaster/Modules/Items/T20_2pc.test.js
- src/Parser/Monk/Brewmaster/Modules/Items/T20_4pc.test.js
- src/Parser/Monk/Brewmaster/Modules/Normalizers/GiftOfTheOx.js
- src/Parser/Monk/Brewmaster/Modules/Spells/HighTolerance.js
This is what the console looks like currently:
this eliminates those messages by marking the casts as 'ticks' (which really, they aren't, but they also aren't really casts so who even knows).
Depends on PR #1956 for no other reason than I didn't switch to master before committing.
> [BrM] Updated Gift of the Ox handling to eliminate spurious warnings about missing spells

- src/Parser/Core/Modules/MitigationCheck.js
MitigationCheck currently causes a crash if the user attempts to analyze a boss that cannot be found. This can occur whenever a user attempts to analyze a non-Antorus boss.
> [Bug] Fix crash when attempting to view report for a boss that cannot be found.

- src/Parser/Shaman/Restoration/Modules/Talents/EarthShield.js
- src/Parser/Shaman/Restoration/Modules/Talents/FlashFlood.js
- Removed Earth Shield's special cases:
- Flash Flood has a high chance to bug out, give you its buff correctly but immediately removes it again - for the hasBuff function that counts as having the buff so results of the Flash Flood module showed wrong results. This bug can happen up to 50% of the time.
- Changed Flash Flood's logic so that it doesn't catch bugged buffs anymore. 1ms should be enough to catch it but i checked for 50ms after cast start just to be safe.
**Example of the bug** (Healing Rain would think it consumed the FF buff):
**Before fix:**
**After fix**:
> [Restoration Shaman] Hotfixes & Flash Flood bug fix

- src/Parser/Mage/Arcane/CombatLogParser.js
- src/Parser/Mage/Arcane/Modules/Features/ArcaneOrb.js
- src/common/SPELLS/MAGE.js
Adds support for Arcane Orb.
- Gets the average number of hits per cast to determine if you are getting the most out of the talent
- Checks for casts with no damage events (i.e. it was cast again or the fight ended without a damage event hitting)
I have it disabled if you have the Legendary Shoulders because it spawns Arcane Orbs. This way I can add it for those that dont use Shoulders to use during Prepatch.
Towards #1961
> [Arcane Mage] Arcane Orb

- src/Parser/Mage/Arcane/CombatLogParser.js
- src/Parser/Mage/Arcane/Modules/Features/ArcaneChargeTracker.js
Accidentally deleted the branch for the previous PR so here is a new one.
This adds an arcane charge tracker since combat logs dont have the ability to see how many charges you have or list the times you lose arcane charges.
Adding just this for now to make sure its solid before i refer to it from other modules.
Towards #1961
> [Arcane Mage] Arcane Charge Tracker

- src/CONTRIBUTORS.js
- src/Parser/Rogue/Assassination/CHANGELOG.js
- src/Parser/Rogue/Assassination/CONFIG.js
- src/Parser/Rogue/Assassination/CombatLogParser.js
- src/Parser/Rogue/Assassination/Modules/Talents/ElaboratePlanning.js
- src/common/SPELLS/ROGUE.js
Adds support for tracking Elaborate Planning buff uptime, including tooltip describing ideal uptime.
Adds Elaborate Planning buff to spells list.
Updates my entry in `CONTRIBUTORS.js`.
> [Assassination Rogue] Add tracking for Elaborate Planning talent

- src/Interface/Others/ExpandableStatisticBox.js
Bugged me for a while now since blood has quite a few expandable boxes already.
Simply increases the z-index for the boxes that are open.
**Old**
**New**
> [Core] expandableStatisticBox z-index fix

- src/Parser/Hunter/Marksmanship/Modules/Talents/HuntersMark.js
The Hunter's Mark module was broken when the enemyID variable was changed from `event.targetID ` to `encodeTargetString(event.targetID, event.targetInstance)` because calculateMarkDamage was still using enemy.id, which corresponded to event.targetID. Now the sourcing for the enemyID variable (used primarily as an array index) is standardized across the module. 
Example bug: 
WoWA: https://wowanalyzer.com/report/Ck7VZnyRXfc4YjAz/17-Mythic+Portal+Keeper+Hasabel+-+Kill+(5:22)/40-Blaz/events
WCL Hunter's Mark Uptime: https://www.warcraftlogs.com/reports/Ck7VZnyRXfc4YjAz/#fight=17&type=auras&spells=debuffs&hostility=1&ability=257284
> [MMS Hunter] Fixed Hunter's Mark Bug

- src/Parser/DemonHunter/Vengeance/Modules/PainChart/Pain.js
- src/Parser/DemonHunter/Vengeance/Modules/PainChart/PainComponent.js
- src/common/SPELLS/DEMON_HUNTER.js
Pain chart won't break anymore with undefined spells with painCost or maxPain undefined.
Removed SpellIcon from pain chart breakdown. The img was duplicated, now that SpellLink has it own img.
> [Vengeance DH] Pain chart improvement

- src/Parser/DemonHunter/Havoc/CHANGELOG.js
- src/Parser/DemonHunter/Havoc/CONFIG.js
- src/Parser/DemonHunter/Havoc/Modules/Abilities.js
- src/Parser/Shaman/Elemental/CHANGELOG.js
- src/Parser/Shaman/Enhancement/CHANGELOG.js
- src/common/SPELLS/DEMON_HUNTER.js
- src/common/SPELLS/TALENTS/DEMON_HUNTER.js
I've updated some new spells, added some new talents (manually) and removed the artifact cast suggestion (#2006 ).
Also I've renamed some old "class" props to "className", so React doesn't complain about it anymore.
> [Havoc DH] Class BfA talents and spells updates

- src/Parser/Mage/Arcane/CHANGELOG.js
- src/Parser/Mage/Arcane/CombatLogParser.js
- src/Parser/Mage/Arcane/Modules/Features/ArcanePower.js
Adds support for Arcane Power. Checks the following
- Arcane Power is only cast if the player has 4 Arcane Charges, Rune of Power was cast immediately before AP (If RoP Talent), and the player has more than 40% mana (Unless they have OP Talent).
- The player is only casting Arcane Blast, Arcane Missiles, and Presence of Mind while the Arcane Power buff is up (this includes the buff given by Time Anomaly).
Additionally, caught up on changelog entries for the previous PRs (Didnt want to add changelog entries to each PR so i can avoid conflicts).
Towards #1961
> [Arcane Mage] Arcane Power Support

- src/Parser/DemonHunter/Vengeance/Modules/Abilities.js
Shear is the default ability. It has no cd and no charges. Fully spamable.
Fracture is a talent that can be taken. It replaces shear.
It has a 4.5 sec cd that is affected by haste. And has 2 charges.
Also updated some abilities/efficiencies.
When they were separate it showed both spells in the abilities list. So one would always be 0. Combined them to avoid this. Logs to show how it works now:
Without fracture talent:
https://www.warcraftlogs.com/reports/p7LdrP8JXZqMNmaC/#fight=12&source=4
With fracture talent:
https://www.warcraftlogs.com/reports/TMwm6JfZdy43aLVY/#fight=1&source=12
How it looked when broken:
> Combined shear and fracture into one

- src/Parser/DemonHunter/Vengeance/Modules/Features/SoulFragmentsTracker.js
- src/Parser/DemonHunter/Vengeance/Modules/PainChart/PainComponent.js
- src/common/SPELLS/DEMON_HUNTER.js
- Fixed a bug with the Soul Fragments Tracker
- The removebuffstack and removebuff events were duplicated for 1 buff stack removal. It triggers removebuffstack and removebuff for the same soul fragment consume. So, we were counting them as +2 spent and -2 buff stacks, but they refer only to +1 spent and +1 buff stack.
Before:
After:
- Updated Soul Cleave painCost to Pain Chart breakdown.
- Removed wrong data-tip from Pain Chart (they are now exact and correct for pain costs, not 'approximately' anymore).
> [Vengeance DH] Soul Tracker bugfix and Pain Chart update

- src/Parser/Core/Modules/Haste.js
- src/Parser/Mage/Arcane/Modules/Features/ArcanePower.js
- src/Parser/Mage/Arcane/Modules/ManaChart/ManaValues.js
- src/common/SPELLS/MAGE.js
- Arcane Power has an Unacceptable List now instead of an Acceptable List.
- Moved 40% mana threshold to constant as per previous PR feedback
- Added check for Arcane Power to see if it was available when the boss died
- Modified ManaLevels to not show the ending mana suggestion if the player was dead when the boss died.
- Added Arcane 4pc tier to Haste
Towards #1961
> [Arcane Mage] Fixes & Tweaks

- src/Parser/Mage/Arcane/CHANGELOG.js
- src/Parser/Mage/Arcane/CombatLogParser.js
- src/Parser/Mage/Arcane/Modules/Features/ArcaneMissiles.js
- src/Parser/Mage/Arcane/Modules/Features/RuleOfThrees.js
- src/common/SPELLS/MAGE.js
Added support for Rule of Threes and fixed the Arcane Missiles Module to point to Clearcasting instead of "ArcaneMissiles!" which was removed
Towards #1961
> [Arcane Mage] Rule of Threes & Arcane Missiles/Clearcasting

- src/Parser/DemonHunter/Vengeance/Modules/Spells/SoulCleaveSoulsConsumed.js
- src/Parser/DemonHunter/Vengeance/Modules/Talent/SoulBarrier.js
The Soul Cleave suggestion was trying to use `SoulFragmentsConsume` to find `soulsGenerated` and `soulsWasted`, but those are actually properties of `SoulFragmentsTracker` so it was always producing `NaN`. Also added a division by zero check.
Corrected a couple of typos in the Soul Barrier suggestion (the uptime should be above the recommended value, not below.)
> [Vengeance] Soul Cleave fix (small)

- src/Parser/DemonHunter/Vengeance/Modules/Features/SoulFragmentsTracker.js
- src/Parser/DemonHunter/Vengeance/Modules/Statistics/SoulFragmentsConsume.js
- src/Parser/DemonHunter/Vengeance/Modules/Talents/SpiritBombSoulsConsume.js
- Soul Bomb tracker was showing wrong casts:
``` js
Soul Fragment buff removal counts +2 for the -1 stack with 1 buff stack
-1 for the on_byPlayer_removebuffstack(event)
-1 for the on_byPlayer_removebuff(event)
```
So, removing the on_byPlayer_removebuff(event) counter fixes the Soul Fragments consumed count.
Before:
After:
> [Vengeance DH] Soul Bomb tracker bugfix

- src/Parser/Mage/Arcane/CHANGELOG.js
- src/Parser/Mage/Arcane/CombatLogParser.js
- src/Parser/Mage/Arcane/Modules/Checklist/Component.js
- src/Parser/Mage/Arcane/Modules/Checklist/Module.js
- src/Parser/Mage/Arcane/Modules/Features/ArcaneFamiliar.js
- src/Parser/Mage/Arcane/Modules/Features/ArcaneMissiles.js
- src/Parser/Mage/Arcane/Modules/Features/ArcaneOrb.js
- src/Parser/Mage/Arcane/Modules/Features/ArcanePower.js
- src/Parser/Mage/Arcane/Modules/Features/TimeAnomaly.js
- src/Parser/Mage/Shared/Modules/Features/ArcaneIntellect.js
- src/Parser/Mage/Shared/Modules/Features/MirrorImage.js
- src/Parser/Mage/Shared/Modules/Features/RuneOfPower.js
Added Time Anomaly Module to ensure the player is conserving mana below 70% so that if Evocation procs, it wont cap out the player's mana.
Also added check to make sure Arcane Missiles is only cast if the player has Clearcasting.
Also added some fixes
- Buff End Time was returning null in Arcane Power, so I added some buff tracking to calculate the end time
- Removed some leftover console log entries that I forgot to remove
- Fixed Mana Utilization suggestion to point to the correct actual value
Completes #1961
> [Arcane Mage] Time Anomaly Mana Mgmt, Arcane Missiles, and Fixes

- README.md
Now that BFA has been launched, https://bfa.wowanalyzer.com has been
taken down and the main branch is once again master
> Remove Battle for Azeroth section from README

- src/Parser/Priest/Discipline/Modules/Spells/SinsOfTheMany.js
- src/Parser/Priest/Discipline/SpellCalculations.js
- src/Parser/Priest/Discipline/SpellCalculations.test.js
- src/common/SPELLS/PRIEST.js
self explanatory fixes;
- Smite spellpower coefficient was incorrect (only used right now to offset Schism direct damage by damage of 1 Smite to account for the fact that you would be casting Smite instead)
- Sins of the Many doesn't scale linear at all
> Disc priest smite coefficient & sins fix

- src/game/SPECS.js
First contribution to fix issue #1979 , All the updates made are solely taken from wowhead, but I have almost every class in mastery range, do you want me to double check some in-game ?
> Update mastery coefficients to bfa latest version (8.0.1 25902)

- src/Parser/Mage/Arcane/CHANGELOG.js
- src/Parser/Mage/Arcane/Modules/Checklist/Module.js
- src/Parser/Mage/Arcane/Modules/Features/ArcaneMissiles.js
- src/Parser/Mage/Frost/CHANGELOG.js
- src/Parser/Mage/Frost/CombatLogParser.js
- src/Parser/Mage/Frost/Modules/Cooldowns/FrozenOrb.js
- src/Parser/Mage/Frost/Modules/Features/BrainFreeze.js
- src/Parser/Mage/Frost/Modules/Traits/WintersReach.js
- src/common/SPELLS/MAGE.js
Added support for the following azerite traits which have an affect on the analysis other than damage.
Anomalous Impact (Arcane) - Makes Arcane Missiles do extra damage based on Arcane Charges. This affects rotation.
Whiteout (Frost) - Reduces the cooldown on Frozen Orb by 0.5 Seconds when Ice Lance does damage.
Winter's Reach (Frost) - Proc that makes hard cast Flurry do extra damage (Its essentially Pyroclasm/Legion Fire Bracers but for Frost.
Also updated the Arcane Changelog to the new standard.
I had planned on adding support for Galvanizing Spark as well as it gives Arcane Blast a chance to generate a second Arcane Charge, but it looks like the energize events already covered it so i didnt have to add anything special for it.
Fixes #2099
> [Mage] Azerite Traits & Arcane Changelog Update

- src/Interface/Others/Report/Results/EncounterStats.js
Should fix this showing: 
https://i.gyazo.com/thumb/1200/bbdc511ff8f9671102e11f2932a202b6-png.jpg
Can't test right now because WCL - but theoretically seems fine.
> [Core] Removes most used legendaries from encounter stats 

- src/Interface/common/TooltipProvider/Wowhead.js
- src/Parser/Priest/Discipline/CombatLogParser.js
- src/Parser/Priest/Discipline/Modules/AzeriteTraits/GiftOfForgiveness.js
- src/Parser/Priest/Discipline/Modules/Features/AtonementDamageSource.js
- src/Parser/Priest/Discipline/Modules/Spells/Atonement.js
- src/Parser/Priest/Discipline/Modules/Spells/Schism.js
- src/Parser/Priest/Discipline/Modules/Spells/SinsOfTheMany.js
- src/Parser/Priest/Discipline/SpellCalculations.js
- src/Parser/Priest/Discipline/SpellCalculations.test.js
- src/common/SPELLS/BFA/AzeriteTraits/Priest.js
- src/common/SPELLS/BFA/AzeriteTraits/index.js
- src/common/SPELLS/PRIEST.js
- src/common/SpellIcon.js
- src/common/SpellLink.js
Depends on https://github.com/WoWAnalyzer/WoWAnalyzer/pull/2107 (first 2 commits are from that PR) for:
- Smite spellpower coefficient was incorrect (only used right now to offset Schism direct damage by damage of 1 Smite to account for the fact that you would be casting Smite instead)
- Sins of the Many doesn't scale linear at all
----------
Gift of Forgiveness adds to Smite base damage so I've added it to `SmiteEstimation` so that it's included into the Schism direct damage offset.
When you have no Gift traits it still displays a box to show how many of your Smites were casted with 3+ atonements,  
considering the Gift trait is a bit hyped atm I think it's interesting to know how many of your Smite casts would have boosted if you'd have the trait. 
I still need to review it 1 final time …
> Disc priest azerite trait Gift of Forgiveness

- src/Parser/Priest/Discipline/Modules/AzeriteTraits/GiftOfForgiveness.js
- src/Parser/Priest/Discipline/SpellCalculations.js
A quick and dirty fix for the trait, the .map on undefined caused a crash for all priests without the "Gift of Forgiveness" trait.
@rubensayshi might want to double-check it if I messed something up. Should be good for a merge tho, worst case is that people without the trait might get a suggestion with wrong numbers.
> [Bug] [Disc Priest] Gift of Forgiveness fix

- src/Parser/Core/Modules/Items/EnchantChecker.js
I don't know if there is a `Good` way to handle offhand weapon checks. Checking the icon string hit all of the off hand items that I found correctly.
First time contributing, I don't know if I missed anything.
> Update the enchant checker to support BfA enchants.

- src/Interface/Character/Parses.js
The spec filter does currently not work on spec-names with spaces in it (like Beast Mastery).
Pretty sure it used to be `BeastMastery` before the character-endpoint rewrite (was first a specID and was changed later on to a readable-format)
> [Core] [Bug] Character spec space fix

- src/Parser/Core/Modules/Racials/BloodElf/ArcaneTorrent.js
- src/Parser/Hunter/Survival/Modules/Abilities.js
Adds a buffspellid for a survival spell
Adds an exclusion list for arcane torrent and I added fire/frost mage and MM hunter as they don't benefit from the racial (marks never casts it ideally)
> [Hunter/Core] Arcane Torrent exclusion and buffSpellID

- src/Parser/Mage/Frost/Modules/Features/Abilities.js
Disabling Ebonbolt based on glacial spike is causing a crash in the checklist.
This will fix the crash, but might show a "wrong" suggestion for Ebonbolt. But I'm not sure how likely the "dont have to cast ebonbolt once with good procs" is.
> [Frost Mage] [Bug] Checklist fix

- src/Parser/Core/Modules/Items/EnchantChecker.js
Adds Death Knight's rune enchants and removes the check for enchants on items with the string "shield" in it (since thats the most reliable way for now to check wether an item is enchantable or not)
> [Core] Added Enchants for DKs and removed check for Shields

- src/Parser/Core/Modules/Features/RaidHealthTab/TabComponent/Graph.js
Small change that lets the raid health tab graph scale with the member size, as its currently hardcoded for 20 people which creates issues.
Before, 25 people and the graph gets cut off at 20:
After:
Log: https://www.warcraftlogs.com/reports/TKAabrZjwdJcFq67/#fight=18&source=56
5 man example:
After:
Log: https://www.warcraftlogs.com/reports/KQgVRXZzHraNhP7x/#fight=1&source=1
> Scale Raid Health graph with Group / Raid size

- src/Parser/Shaman/Restoration/CHANGELOG.js
- src/Parser/Shaman/Restoration/Modules/Talents/FlashFlood.js
Adds a more detailed breakdown to how the Flash Flood cast speed buff was used, in addition to the total value in the talents module. Also makes it slightly more accurate as before any cast faster than the GCD got ignored, while now the part up until the GCD still gets counted.
I didn't add something like unused or wasted buffs, since, if you really don't cast any healing spell for 10 seconds after using a tidal wave, it's doubtful that there was anything to heal regardless.
> [Restoration Shaman] Flash Flood breakdown

- src/Parser/Warlock/Demonology/Modules/Features/DoomUptime.js
Fixes this error:
TypeError: Cannot read property 'icon' of undefined
Log: https://wowanalyzer.com/report/FWy6qGfHm7JwB3an/2-Normal+Mythrax+-+Kill+(7:45)/21-Beware
> Warlock Demo Icon Fix

- package-lock.json
- src/Parser/Monk/Windwalker/Modules/Spells/TouchOfDeath.js
Error was flagged by @MartijnHols - basically, if the combatant didn't have any meridian strikes traits it was assumed that the helper getTraits rank function would return 0, but instead it returned undefined which caused the error.
Fixed by checking for undefined and manually setting modifier to 0.0 if undefined.
Also reduced some line lengths for readability.
> Fix TouchOfDeath Meridian Strikes trait damage error

- src/Parser/Core/Modules/Items/EnchantChecker.js
Noticed the `Be Well Prepared` checklist section didn't complain at me with my cheap enchants, seems they slipped into the maximum enchants list.
> Enchant Checker - Remove cheap enchants

- src/Parser/Core/Combatant.js
- src/Parser/Monk/Brewmaster/CHANGELOG.js
- src/Parser/Monk/Brewmaster/CombatLogParser.js
- src/Parser/Monk/Brewmaster/Modules/Spells/AzeriteTraits/ElusiveFootwork.js
This is one of the traits related to issue #2088.
In the logs I tested, I didn't get any `attackPower` values from the log (they were all 0) so I instead just used the ratio of `amount / unmitigatedAmount` to estimate the ratio of damage mitigated by e.g. boss armor. Checking the end of the [MOTHER](https://www.warcraftlogs.com/reports/TfcmpjkbNhq18yBF#fight=4&type=summary&source=14) fight (where she takes increased damage), the ratio is > 1 so the extra damage taken is accounted for.
I don't know that this is totally correct, but I'm willing to bet that it is close enough.
This PR also adds mainHand/offHand props for combatants, which were previously missing. I was going to use them to calculate WDPS but then switched to the ratio method above.
> [BrM] Elusive Footwork trait

- src/CHANGELOG.js
- src/Parser/Core/CombatLogParser.js
- src/Parser/Core/Modules/Spells/BFA/AzeriteTraits/MeticulousScheming.js
- src/Parser/Core/Modules/StatTracker.js
- src/common/SPELLS/BFA/AzeriteTraits/General.js
- src/common/SPELLS/BFA/AzeriteTraits/__UNUSED.js
Adds Meticulous Scheming's haste to the statTracker and adds a suggestion when the player failed to trigger `Seize the Moment` every `Meticulous Scheming`-proc
> [Core] Meticulous Scheming trait

- src/Parser/Core/Modules/StatTracker.js
- src/Parser/DeathKnight/Blood/CombatLogParser.js
- src/Parser/DeathKnight/Blood/Modules/Spells/AzeriteTraits/EternalRuneWeapon.js
- src/common/SPELLS/BFA/AzeriteTraits/DeathKnight.js
Adds statistics & stats from Eternal Rune Weapon
**Eternal Rune Weapon**
Gain x strength while Dancing Rune Weapon is up
Every rune spend during DRW extends it's duration by .5sec up to a max of 5sec
The strength and bonus duration stacks with multiple traits while the 5sec cap remains the same
one trait  would provide 100 strength & .5sec per rune up to 5sec
two traits would provide 200 strength &  1sec per rune up to 5sec
Example report: https://www.warcraftlogs.com/reports/kmtH7VRnJ4fAhg6M/#fight=46&source=7
Example report: https://www.warcraftlogs.com/reports/fCBX6HMK372AZxzp/#fight=62&source=20 (with two ERW traits)
> [Blood Death Knight] [Azerite Trait] Eternal Rune Weapon

- src/Parser/Warrior/Arms/Modules/Talents/DefensiveStance.js
Added damage lost statistic to the Defensive Stance tooltip. Icons scale based on the tradeoff between Damage Prevented and Damage Lost.
> Defensive Stance Statistic (Damage-lost)

- src/CHANGELOG.js
- src/Parser/Core/Modules/Features/CharacterTab/Component/Azerite.js
- src/Parser/Core/Modules/Features/CharacterTab/Component/index.js
Lists all active azerite traits and loads missing icons for traits that aren't in the `SPELLS/BFA/AzeriteTraits`-files from Blizzards API
> [Core] List Azerite Traits in the character-pane

- src/Parser/Warlock/Affliction/CHANGELOG.js
- src/Parser/Warlock/Affliction/CombatLogParser.js
- src/Parser/Warlock/Affliction/Modules/Talents/Deathbolt.js
- src/Parser/Warlock/Affliction/Modules/Talents/Haunt.js
Added a small Deathbolt module and updated Haunt module, reflecting a change in playstyle. We no longer care about burst windows and care about the uptime more. Still showed the bonus damage (10%) and percentage of buffed UA ticks, but it's not as important as it was.
> [Affliction] Deathbolt and Haunt modules

- src/Parser/Monk/Brewmaster/CHANGELOG.js
- src/Parser/Monk/Brewmaster/Modules/Spells/BreathOfFire.js
- src/Parser/Monk/Brewmaster/Modules/Spells/IronSkinBrew.js
This has been popping up a lot on BrM discord because of the xpac launch. tl;dr the current implementation of the suggestion for ISB looks at uptime % (which is wrong) and the current suggestion for BoF says "uptime" but is actually "hits mitigated". This PR fixes both of those to say "hits mitigated". 
Example Log: https://www.warcraftlogs.com/reports/AbZ38fQBJYxPdGqp/#fight=6&source=104
New version:
> [BrM] Updated Suggestions for ISB/BoF

- src/Parser/Warrior/Fury/CombatLogParser.js
- src/Parser/Warrior/Fury/Modules/Abilities.js
- src/Parser/Warrior/Fury/Modules/Features/AlwaysBeCasting.js
- src/Parser/Warrior/Fury/Modules/Features/Checklist/Component.js
- src/Parser/Warrior/Fury/Modules/Features/Checklist/Module.js
- src/Parser/Warrior/Fury/Modules/Spells/MissedRampage.js
Hi,
I am not a fury warrior expert, but I thought it would be useful to add a basic checklist to the spec, since previously nothing at all was available. As such, I added the basic cooldowns, downtime, and preparation checklists that are available for most other specs. Furthermore, in the attempt to add at least something specific to Fury, I added a checklist that counts how often generators were used when there is no doubt that it would have been better to use Rampage (I follow the Icy Veins guide, which says that Rampage should be used any time your rage is >= 90).
In addition to the checklist changes, I removed the Raging Blow efficiency suggestion. You can consult either fury warrior guides or top logs to see that efficiency Raging Blow usage is not an important part of the spec at …
> [Fury Warrior] Add Basic Checklist, Prune Unnecessary Warnings

- src/CHANGELOG.js
- src/Parser/Core/CombatLogParser.js
- src/Parser/Core/Modules/Spells/BFA/AzeriteTraits/HeedMyCall.js
- src/common/SPELLS/BFA/AzeriteTraits/General.js
- src/common/SPELLS/BFA/AzeriteTraits/__UNUSED.js
Very simple Heed My Call module. Totals all damage and shows a DPS and DPS % statistic with the total damage tooltip. 
Note: Code for this is basically identical to gutripper, and probably can be the same for all flat damage proc traits that have their own damage spell ids. Maybe they can be merged together?
Issue #2242
> [General Azerite] Heed My Call trait module

- src/Parser/Core/Combatant.js
This fixes an issue when a trait is missing the `traits.json`-file.
Simply iterating over the `traitsBySpellId` and assuming that the ID is defined could lead to issues in several modules in the future.
Issues happens currently in the Azerite-module in the character pane when a character has [Unstable Catalyst](https://www.wowhead.com/spell=281514/unstable-catalyst). Thats just one of the traits thats missing in the `traits.json`-file.
> [Core][Bug] Fix for missing traitIds

- src/Parser/Shaman/Restoration/CombatLogParser.js
- src/Parser/Shaman/Restoration/Modules/Talents/Downpour.js
- src/Parser/Shaman/Restoration/Modules/Talents/EarthShield.js
- src/Parser/Shaman/Restoration/Modules/Talents/EarthenWallTotem.js
- src/Parser/Shaman/Restoration/Modules/Talents/FlashFlood.js
- src/Parser/Shaman/Restoration/Modules/Talents/TalentStatisticBox.js
- src/Parser/Shaman/Restoration/Modules/Talents/UnleashLife.js
Also moved the "total time saved" from the talent overview box to flash floods own module, since it was the only one that wasn't about how much healing it contributes.
Examples
Log: https://wowanalyzer.com/report/Dg3G7BnMH2zxrCZd/21-Heroic+Zul+-+Wipe+19+(7:27)/12-%D0%90%D0%BD%D1%82%D1%82%D0%B0%D1%80%D0%B5%D1%81
> [Restoration Shaman] Modified talents to use the talent specific category

- src/Interface/Others/Report/Results/EncounterStats.js
Fixes #2277 
Also fixes an issue with certain logs being anonymised, reducing the amount of information we pull - as this will then just lower the amount we divide by, still giving accurate percentages. 
Logs: https://www.warcraftlogs.com/reports/GThW1Z3pAFdN2RwD#fight=1&type=damage-done
Statistics: https://www.warcraftlogs.com/zone/rankings/19#boss=2135&class=Hunter&spec=BeastMastery
> [Core] Add in amount of parses logic to EncounterStats

- src/Parser/Core/Modules/Items/BFA/Raids/Uldir/ConstructOvercharger.js
- src/Parser/Core/Modules/StatTracker.js
- src/Parser/Hunter/BeastMastery/CombatLogParser.js
- src/Parser/Hunter/BeastMastery/Modules/Abilities.js
- src/Parser/Hunter/BeastMastery/Modules/Core/SpellUsable.js
- src/Parser/Hunter/BeastMastery/Modules/Spells/BarbedShot.js
- src/Parser/Hunter/Survival/Modules/Abilities.js
- src/Parser/Hunter/Survival/Modules/Spells/KillCommand.js
- src/Parser/Hunter/Survival/Modules/Spells/SerpentSting.js
- src/articles/2018-04-14-Battle-For-Azeroth/index.js
Adds Construct Overcharger to stat-tracker
Adds some sort of cooldown resetting to Barbed Shot as seen in [Avengers Shield](https://github.com/WoWAnalyzer/WoWAnalyzer/blob/master/src/Parser/Paladin/Protection/Modules/Features/SpellUsable.js) and [Shield Slam](https://github.com/WoWAnalyzer/WoWAnalyzer/blob/master/src/Parser/Warrior/Protection/Modules/Features/SpellUsable.js).
Fixes Quick nav buff in stat tracker
Fixes a SV suggestion and removes part of kill command reset tooltip as it never could happen.
> Various minor updates

- src/Parser/Priest/Discipline/Modules/Abilities.js
Undefined error:
log: https://www.wowanalyzer.com/report/64aM8HdAC2fLpD1q/2-Normal+Taloc+-+Kill+(4:25)/3-Amu
Not sure why this casts code exists but its causing the undefined. Removing it didnt seem to break anything.
casts: castCount => castCount.casts,
Was reported to me by a friend.
> Disc Priest: Removed error causing code

- src/Parser/Core/CombatLogParser.js
- src/Parser/Core/Modules/Items/BFA/Crafted/DarkmoonDeckBlockades.js
- src/common/SPELLS/BFA/Crafted/ITEMS.js
The items section should now correctly track the healing percentage and
HPS that Darkmoon Deck: Blockades provides when equiped.
> Fixes #1724 Add Darkmoon Deck: Blockades healing component

- src/CHANGELOG.js
- src/Parser/Core/CombatLogParser.js
- src/Parser/Core/Modules/Features/SpellInfo.js
- src/Parser/Core/Modules/Spells/BFA/AzeriteTraits/BlessedPortents.js
- src/common/SPELLS/BFA/AzeriteTraits/General.js
Issue #2242 
Back again with another azerite trait. Tracks Blessed Portents healing contribution and shows number of buffs applied, refreshed, procced, expired, and active at the end of the fight.
> [General Azerite] Blessed Portents trait module

- src/Parser/Monk/Brewmaster/CHANGELOG.js
- src/Parser/Monk/Brewmaster/Modules/Features/StaggerPoolGraph.js
Currently, the stagger plot uses the *right edge* of a bin for determining the y value. This can make purifies look bad when a player purifies very quickly after a hit, since the previous bin was small and we sometimes get an extra stagger tick within the current bin. This PR changes that by doing two things:
1. Bins are now plotted using the *max* value within the bin instead of the rightmost value.
2. (1) introduced an issue where if a hit occurred right after a purify, it would look like the purify did literally nothing. I fixed this by upping the resolution of the plot from 1s bins to 0.5s bins.
I also cleaned up how purifies are positioned. It should now always place them in the correct bin instead of occasionally putting them back an extra bin.
**M Fetid, before & after**
**M …
> [BrM] Clarify purify usage in stagger plot

- src/parser/deathknight/blood/CHANGELOG.js
- src/parser/deathknight/blood/modules/features/MarrowrendUsage.js
- src/parser/deathknight/blood/modules/talents/Heartbreaker.js
Updates the Marrowrend usage module to default to a 7 stack refresh and only use 6 stacks when running Bones of the Damned.
Also removes the suggestion for running Hearth Breaker since it's now a more or less viable choice for pure defensive purpose (primarily due to the relative damage/healing loss on BD going into BfA).
> [Blood Death Knight] update HB and MR-modules

- src/parser/core/modules/items/bfa/crafted/DarkmoonDeckBlockades.js
The items section should now correctly track the stamina contribution
Darkmoon Deck: Blockades provides when equiped.
The information is broken down into the contribution and uptime of each
individual card, as well as the average stamina the deck provided during
the entire encounter.
> Fixes #1724 Add Darkmoon Deck: Blockades Stamina Component

- src/parser/warlock/affliction/CHANGELOG.js
- src/parser/warlock/affliction/CombatLogParser.js
- src/parser/warlock/affliction/modules/features/Darkglare.js
Added Summon Darkglare module. 
It's a little longer so I tried to add comments where I felt it was necessary but the gist of it is this:
- manually track dots on targets, when they were cast and when they should drop off
- when Summon Darkglare is cast, record the current "state" of dots on targets, and extend the remaining time on them by 8 seconds
- after the "original" dot is expired, and we actually get to the extended part, count the bonus damage from those dots
- show some statistics for this
There's also some weird moments where things happen when they shouldn't (one example is I think this report `/report/kmJV8jPGCXFrxYDy/21-Heroic+Mythrax+-+Wipe+20+(7:15)/11-Chizu` where `removedebuff` event for Corruption on Vision of Madness add triggered `on_byPlayer_damage` event handler …
> [Affliction] Summon Darkglare module

- src/parser/demonhunter/havoc/modules/Abilities.js
The damage increase to it was removed in BFA so no longer worth using on CD
> [Havok DH] Removed fel eruption suggestion

- src/parser/paladin/protection/CONFIG.js
- src/parser/paladin/protection/modules/Abilities.js
- src/parser/paladin/protection/modules/spells/Judgment.js
- src/parser/paladin/protection/modules/talents/Seraphim.js
Updates the existing protection paladin work for patch 8.0.1. The spec has gone through minimal changes since last work done in 7.3.5, so updates are minor.
> [Prot Paladin] Update for patch 8.0.1

- src/common/format.js
- src/parser/mage/arcane/modules/features/Abilities.js
- src/parser/mage/fire/modules/features/Abilities.js
- src/parser/mage/frost/modules/features/Abilities.js
formatDuration now will properly handle negative durations. This has no effect on how positive durations on displayed. Added to support potentially adding pre-pull features later on.
Also fixing time warp GCDs
> [Core] Fix negative formatDuration; [Mage] Fix Time Warp GCD info

- src/parser/core/modules/items/PrePotion.js
Fixes the error where some specs would get a wrong potion suggested as mentioned by Sharrq on discord. 
Specifically it was about frost mages and shadow priests, here is an example from frost mages. 
I made the code more readable imo aswell. 
Just to show that even if some specs are in multiple places (both bursting and agi for example), it'll still be accurate:
> [Core] update prepots

- src/common/format.js
- src/parser/mage/arcane/CombatLogParser.js
- src/parser/mage/fire/CombatLogParser.js
- src/parser/mage/frost/CombatLogParser.js
- src/parser/mage/shared/normalizers/PrePullCooldowns.js
This normalizer attempts to solve a problem throughout the WoWAnalyzer castefficiency module. While the castefficiency module can (with the ApplyBuff normalizer checking for event.prepull) properly deduce cooldown percentages, it does not accurately count the actual casts.
For example, the analyzer can tell I have _had_ the Icy Veins buff 3 times, but it can't tell that I have _cast the spell_ 3 times:
With this PR, cast events are fabricated pre-pull (with pre-pull timestamps, to avoid the "you cast spell X while still on the GCD from Y!" error) which will be accounted for castefficiency percentages AND counts.
Example:
The goal of this pull request is to test the concept for mages first, and then if it works and gets optimized it can be made global and all specs can remove their prepull …
> [Mage] Pre-pull cooldown normalizer

- src/parser/warlock/destruction/CombatLogParser.js
- src/parser/warlock/destruction/modules/talents/index.js
My module for Fire and Brimstone talent is currently broken (it was wired to my custom fragment tracking which was removed) and so it was showing 0 fragments gained (in cleave fights) which only confuses people. Because the logic isn't really flawed that much, it's just not updated to the ResourceTracker changes, I don't want to delete the whole module, just commented it out till I find the time to fix it.
> [Destruction] Temporarily disable Fire and Brimstone module

- src/parser/mage/shared/normalizers/PrePullCooldowns.js
Fixes an issue with the ArcanePower module that was trying to grab the mana value from these events
> [Mage] Add guesstimated classResources to fabricated prepull cast events

- src/parser/druid/feral/CONFIG.js
- src/parser/druid/feral/modules/bleeds/RakeSnapshot.js
- src/parser/druid/feral/modules/bleeds/RakeUptime.js
- src/parser/druid/feral/modules/bleeds/RipSnapshot.js
- src/parser/druid/feral/modules/bleeds/RipUptime.js
- src/parser/druid/feral/modules/combopoints/ComboPointDetails.js
- src/parser/druid/feral/modules/combopoints/ComboPointTracker.js
- src/parser/druid/feral/modules/core/HitCountAoE.js
- src/parser/druid/feral/modules/core/Snapshot.js
- src/parser/druid/feral/modules/features/AlwaysBeCasting.js
- src/parser/druid/feral/modules/features/EnergyCapTracker.js
- src/parser/druid/feral/modules/features/SpellEnergyCost.js
- src/parser/druid/feral/modules/spells/FerociousBiteEnergy.js
- src/parser/druid/feral/modules/spells/PredatorySwiftness.js
- src/parser/druid/feral/modules/spells/SwipeHitCount.js
- src/parser/druid/feral/modules/spells/ThrashHitCount.js
- src/parser/druid/feral/modules/talents/Bloodtalons.js
- src/parser/druid/feral/modules/talents/BrutalSlashHitCount.js
- src/parser/druid/feral/modules/talents/MoonfireSnapshot.js
- src/parser/druid/feral/modules/talents/MoonfireUptime.js
- src/parser/druid/feral/modules/talents/Predator.js
- src/parser/druid/feral/modules/talents/SavageRoarDmg.js
- src/parser/druid/feral/modules/talents/SavageRoarUptime.js
- src/parser/druid/feral/normalizers/ComboPointsFromAoE.js
This is some general housekeeping, with no user-visible changes.
Removed special handling for the old Legion tier sets, legendaries, and a few items with unusual effects (just like legendaries they stopped functioning at level 116.)
Replaced all uses of `statisticOrder` with the `position` property on the StatisticBox (or equivalent) itself.
Also updated the spec's example log to be from the live version of the game instead of the beta.
> [Feral] Remove Legion items and update from statisticOrder

- src/parser/monk/brewmaster/modules/constants/AbilityBlacklist.js
- src/parser/monk/brewmaster/modules/spells/BreathOfFire.js
The hit mitigation blacklist is used to ignore abilities for the purpose of counting % of hits mitigated, as some kinds of effects (dots, background aoes) generate many hits but aren't of concern for mitigation. This adds spells for bosses in uldir.
> [BrM] Updated Hit Mitigation Blacklist for Uldir

- src/parser/mage/frost/modules/traits/WintersReach.js
https://wowanalyzer.com/report/hRNnK37cCfpgBzD2/47-Heroic+G'huun+-+Kill+(6:24)/15-Remyhadley
He reported an issue (winters reach 0% utilization), claiming he used all of his procs. Looking at the events it looks like he was right. This PR should greatly simplify the logic behind this module and resolve the issue of it not counting procs. I also made some convention changes such as using this.debug and capitalization changes to fit with other modules.
> [Frost Mage] Fix Winters Reach module

- src/CHANGELOG.js
- src/CONTRIBUTORS.js
- src/common/SPELLS/racials.js
- src/parser/core/CombatLogParser.js
- src/parser/core/modules/racials/dwarf/Stoneform.js
Stoneform reduces physical damage taken by 10% when active, this adds a statistic for the approximate damage reduction provided by Stoneform. Fixes #2063.
> Dwarf: Track Stoneform damage reduced

- src/parser/druid/feral/CHANGELOG.js
- src/parser/druid/feral/CombatLogParser.js
- src/parser/druid/feral/modules/features/checklist/Component.js
- src/parser/druid/feral/modules/features/checklist/Module.js
- src/parser/druid/feral/modules/racials/Shadowmeld.js
The Night Elf racial ability Shadowmeld provides a stealth effect which for a Feral druid is best used to buff the damage of Rake.
This adds tracking of Shadowmeld use for Night Elf Feral players. It provides a statistic showing how Shadowmeld was used, suggestions for failure to use it to buff Rake or wasting it by using when the player already had an effect that provides the damage buff, and adds it to the checklist.
All of these features are disabled and hidden if the player is not a Night Elf.
> [Feral] Track Shadowmeld use

- src/common/SPELLS/bfa/azeritetraits/paladin.js
- src/parser/paladin/protection/CHANGELOG.js
- src/parser/paladin/protection/CombatLogParser.js
- src/parser/paladin/protection/modules/core/GrandCrusader.js
- src/parser/paladin/protection/modules/features/SpellUsable.js
- src/parser/paladin/protection/modules/spells/azeritetraits/InspiringVanguard.js
Starting my work on the prot paladin module. One of the hardest things with it is that a core mechanic (Grand Crusader) can't normally be detected. However, the trait Inspiring Vanguard can be used to detect it since it triggers `applybuff`/`refreshbuff` when GC triggers.
This PR implements support for IV and for using it to detect exact resets. It also shows a distribution for GC resets similar to what I did for BrM mastery.
Log: https://www.warcraftlogs.com/reports/vmcGHZWhRVnQkXxK/#fight=7&source=13
P.S. sorry for PR size. This started as the GC PR and then woli pointed out the power of IV and I got carried away.
> [Prot Paladin] Grand Crusader + Inspiring Vanguard

- src/parser/druid/feral/modules/Abilities.js
Fixes a timeline-disabling error in Feral logs where the druid uses Treant form.
Example log which caused the error: report/qr2JtNvkXFby7GVA/4-Heroic+MOTHER+-+Kill+(4:59)/5-Lederbärbel/timeline
> [Feral] Fix typo in Treant Form ability

- src/parser/druid/restoration/modules/talents/Flourish.js
Fixes an issue in the suggestions tab for resto druid that was incorrectly displaying the percentage of wild growths extended by flourish.
> Fixed issue in resto druid suggestions for extending wild growth and cenarion ward with flourish

- src/parser/mage/fire/CHANGELOG.js
- src/parser/mage/fire/modules/features/CombustionPyroclasm.js
Fixes a crash in suggestions  caused by a leftover ItemLink that didnt get updated when the module was renamed from the Fire Legendary Bracers to Pyroclasm
> [Fire Mage] Fixes Suggestions Crash

- src/parser/paladin/protection/CHANGELOG.js
- src/parser/paladin/protection/CONFIG.js
- src/parser/paladin/protection/modules/features/Checklist/Component.js
- src/parser/paladin/protection/modules/features/ShieldOfTheRighteous.js
A *good* SotR cast (based on feedback from protadin vets) satisfies one of:
- mitigates 2+ melees
- mitigates a tankbuster
- prevents capping charges
The SotR module now tries to assign every melee and (physical) tankbuster to exactly one SotR cast. Then these casts are processed to count the amount of casts that were good.
This also is a first step in updating the prot paladin checklist.
> [Prot Pal] Added tracking for good SotR casts.

- src/parser/shaman/enhancement/modules/core/FlametongueRefresh.js
The Searing Assault talent makes Flametongue apply a DoT on hit. This means that refreshing Flametongue early is desirable.
This prevents the suggestion to not refresh Flametongue early when the character has the Searing Assault talent.
Sample parse: https://www.warcraftlogs.com/reports/LFdnzNtybGkDRwrT#fight=23&source=12
> [Enhancement Shaman] Allow early refreshes of Flametongue with Searing Assault talent

- src/interface/others/RestorationShamanSpreadsheet.js
- src/parser/shaman/restoration/CHANGELOG.js
- src/parser/shaman/restoration/CombatLogParser.js
- src/parser/shaman/restoration/modules/core/Spreadsheet.js
- src/parser/shaman/restoration/modules/features/MasteryEffectiveness.js
Since i was asked to export some data to make life easier. Based on the Mistweaver / Hpriest player log data, i chose to omit the text descriptions to make copy / pasting easier.
The Spreadsheet.js file is a temporary collection of azerite information, and a bit of a mess, that will be moved into their respective azerite modules once i implement them. The link given is dead right now but will be active within the next few days.
> [Restoration Shaman] Spreadsheet export

- src/parser/monk/windwalker/modules/chi/ChiDetails.js
- src/parser/monk/windwalker/modules/features/CooldownThroughputTracker.js
- src/parser/monk/windwalker/modules/features/checklist/Component.js
- src/parser/monk/windwalker/modules/spells/BlackoutKick.js
- src/parser/monk/windwalker/modules/spells/ComboBreaker.js
- src/parser/monk/windwalker/modules/spells/ComboStrikes.js
- src/parser/monk/windwalker/modules/spells/FistsofFury.js
- src/parser/monk/windwalker/modules/spells/SpinningCraneKick.js
- src/parser/monk/windwalker/modules/spells/TouchOfDeath.js
- src/parser/monk/windwalker/modules/spells/TouchOfKarma.js
- src/parser/monk/windwalker/modules/talents/EnergizingElixir.js
- src/parser/monk/windwalker/modules/talents/HitCombo.js
- Reducing some duplicate code
- Small edits for consistency in the code layout
- Using position prop instead of deprecated statisticOrder
- Removed Xuen from CooldownThroughputTracker, it's not relevant to track what happens during it since there's no interaction with other abilities.
> [WW] Cleanup and updating use of position prop

- src/parser/paladin/protection/modules/features/ShieldOfTheRighteous.js
Fixed a bug revealed by [this log](https://wowanalyzer.com/report/a3zyYvVfBDgPFrTc/6-Heroic+Zul+-+Kill+(3:32)/10-%D0%A4%D0%B8%D1%80%D1%81%D0%B1%D1%80%D1%83%D1%82). `this._markupCast` was being called on an undefined `_activeCast`.
> [Prot Pal] Fixed bug in SotR module

- src/parser/warrior/fury/modules/Abilities.js
https://wowanalyzer.com/report/v2BRda7cVT6nfktw/29-Normal+Mythrax+-+Kill+(7:23)/16-Deadlywarior
Log was causing a redering error due to ID
Based on the log i updated the heroic leap to match the id
Seems no need for separate fury spell
> Fix for heroic leap

- src/parser/shaman/restoration/modules/talents/HighTide.js
Chain Heals combat log events are all over the place and mess up the High Tide analysis. Usually they're backwards (4 -> 3 -> 2 -> Initial) but if any of them hits the player it'll be the first entry. Can't do a normalizer for this as to order it correctly (even if it's only the player itself that's wrong), you'd need mastery effectiveness and current mastery rating - the normalizer happens before you get that information (current rating at least).
Example: 3rd Hit -> 4th Hit -> 2nd Hit -> 1st Hit
I remove the variables affecting the heals (mastery, crits), buffer them and sort by their base + parse them when it has all events of a cast.
> [Restoration Shaman] Fix Chain Heal ordering

- src/interface/others/DeathRecap.js
Colored yellow unless there was effective healing.
Before
After
https://wowanalyzer.com/report/RMN8HfkdyhFCJ4vT/28-Mythic+Vectis+-+Wipe+12+(4:28)/111-Tianchu/death-recap
> [Death Recap] Add absorbed healing

- src/parser/monk/brewmaster/CHANGELOG.js
- src/parser/monk/brewmaster/CONFIG.js
- src/parser/monk/brewmaster/modules/features/StaggerPoolGraph.js
- src/parser/monk/brewmaster/modules/features/checklist/Component.js
- src/parser/monk/brewmaster/modules/features/checklist/Module.js
- src/parser/monk/brewmaster/modules/spells/PurifyingBrew.js
This has been a *long* time coming. I had been putting off doing this until I nailed down more than just "don't use it unless in heavy stagger". Recently, we had a discussion about *delays* after a peak in stagger which made me realize that its actually pretty easy to measure that. So, at long last, we have a reasonable checklist item for PB.
I'm too lazy to manually do a screenshot that has the delay tooltip, but the delay is only counted from the most recently available charge if no charges were available when you were hit. This means that, for example, if you take a big hit with 1s left on PB, then purify 1.5s after the hit, it counts as a .5s delay.
> [BrM] Added Purifying Brew checklist item

- src/parser/shaman/elemental/CombatLogParser.js
- src/parser/shaman/elemental/modules/features/StormFireElemental.js
title.
Depends on the fact that Fire and Storm Elementals count as the only pets so it should works as long as there are no trinkets, azerite traits or w/e that spawn "pets" in the sense of the "byPlayerPet_damage" check.
AFAIK and what I checked the only thing I can think of is Echo Of The Elementals Trait whit which the logic still works because the casts are interlinked.
TBF Storm Elemental should not be cast precombat anyway, because it is a .05% damage loss, so it shouldn't be relevant for anyone who plays a proper rotation ^^
Checked with **https://www.warcraftlogs.com/reports/gxWQvyP9dbDtkHpw/#fight=3&source=24**
> Extend the precast FireElemental checker for StormElemental

- src/CONTRIBUTORS.js
- src/common/SPELLS/mage.js
- src/parser/mage/arcane/modules/features/Abilities.js
- src/parser/mage/fire/modules/features/Abilities.js
- src/parser/mage/frost/modules/features/Abilities.js
Added Polymorph to the spellbook and all mage specs.
It will always show up as Polymorph (Sheep) in the Abilities tab even if other variant was used..
Happy Hacktoberfest!
> Added Polymorph to spellbook

- src/parser/priest/holy/modules/Abilities.js
These numbers were theory-crafted by the Holy Priest discord. The 1% suggestions are for abilities that just need to be cast one or more times during a fight.
> [Hpriest] Suggestion threshold updates

- src/common/SPELLS/priest.js
- src/parser/priest/shadow/CombatLogParser.js
- src/parser/priest/shadow/modules/talents/AuspiciousSpirits.js
This adds support for an Auspicious Spirits talent card.
> [SPriest] Adding Auspicious Spirits

- src/parser/monk/brewmaster/modules/core/StaggerFabricator.js
- src/parser/monk/brewmaster/modules/spells/PurifyingBrew.js
There are only 3 sources of purification in the game right now: PB, Stagger ticks, and SS. PB & Stagger ticks can only happen after you get hit (the game won't let you purify with an empty pool), but SS is tied to BoS and can be used without having anything in the stagger pool. This fixes that edge case in the `PurifyingBrew` module.
> [BrM] fixed bug with purifying brew module & staggering strikes

- src/parser/monk/brewmaster/modules/spells/PurifyingBrew.js
missed an important check that the `event.trigger` object has `.ability` before trying to access `.ability.guid`
side note: turns out death events don't have an `ability` associated with them
fixes errors with:
https://wowanalyzer.com/report/K2kVtAM4HNnDc9Pr/11-Mythic+Mythrax+-+Kill+(8:23)/4-Rngbrew
https://wowanalyzer.com/report/1qVA8G6P9rgabHJ4/2-Heroic+Taloc+-+Kill+(6:25)/3-T%C3%ADdes
and several more
> [BrM] another purifying brew fix

- src/parser/monk/brewmaster/modules/Abilities.js
- src/parser/monk/brewmaster/modules/features/checklist/Component.js
show cast efficiency for ISB/PB in the relevant checklist sections (and fix an outdated way of doing a tooltip).
This has historically not been a huge issue because you'd fail one of the other metrics if you weren't actually using your brews, but in some scenarios we can get brew-flooded now.
Also this gives a direct way of identifying the people who keep posting logs with 0 brews used on fetid. *(Please stop)*
> [BrM] Checklist updates, now featuring Anti-Fetid Log Meme technology

- src/parser/druid/restoration/modules/features/Clearcasting.js
Fixed an issue where the statistic for clearcasting was displaying incorrect regrowth information as a result of recent abundance change
> Resto Druid - Clearcasting statistic text abundance fix

- src/parser/mage/arcane/CHANGELOG.js
- src/parser/mage/arcane/CombatLogParser.js
- src/parser/mage/arcane/modules/features/ArcanePower.js
- src/parser/mage/arcane/modules/features/RuleOfThrees.js
- src/parser/mage/arcane/normalizers/ArcaneCharges.js
- src/parser/mage/arcane/normalizers/ArcanePower.js
- Fixed Arcane Charge Normalizer so that it will put the energize events after the cast that generated them, but before the Arcane Barrage cast if they were cast on the same time stamp.
- Fixed bug in Rule of Threes where it would count Arcane Barrage as being cast with the Rule of Threes active if Rule of Threes was removed on the same timestamp as the Arcane Barrage cast (even if the Remove Buff event happened first)
- Modified Arcane Power module to count each pre-req separately and use only failed checks for determining utilization instead of failed casts.
- Updated Arcane Power tooltip and suggestion to show which checks were failed
For the AP Change, the difference here is that before these changes, if you cast Arcane Power twice and you missed one check on one of the casts, your …
> [Arcane Mage] Bug Fixes & Updates

- src/parser/shared/modules/spells/bfa/azeritetraits/BlightborneInfusion.js
Apparently multiple traits can trigger the same buff with different properties
> Blightborne Infusion bug fix

- src/common/SPELLS/bfa/azeritetraits/__UNUSED.js
- src/common/SPELLS/bfa/azeritetraits/shaman.js
- src/common/SPELLS/shaman.js
- src/interface/others/RestorationShamanSpreadsheet.js
- src/parser/shaman/restoration/CombatLogParser.js
- src/parser/shaman/restoration/modules/azerite/EbbAndFlow.js
- src/parser/shaman/restoration/modules/azerite/SoothingWaters.js
- src/parser/shaman/restoration/modules/azerite/SwellingStream.js
- src/parser/shaman/restoration/modules/core/Spreadsheet.js
The 2 azerite traits that require splitting healing off of other spells.
Relevant issue: #2009 
- https://www.wowhead.com/spell=273597/ebb-and-flow
- Requires finding out the range of the totem to the target to know how much the trait actually contributed.
- Healing contributed towards Healing Tide Totem
- https://www.warcraftlogs.com/reports/fBnXhkHWJQT1yb32/#fight=26&source=8
- Also moves the spreadsheet export from the dedicated file to this module, as there is no reason to do the same math twice.
- https://www.wowhead.com/spell=272989/soothing-waters
- Requires finding out the initial heal of Chain Heal as no other heals are affected.
- Healing contributed towards Chain Heal
- https://www.warcraftlogs.com/reports/BZk41mDxqQyjw7TJ/#fight=9&source=11
over 20% overheal even though his CH …
> [Restoration Shaman] Ebb and Flow & Soothing Waters

- src/parser/monk/brewmaster/modules/features/MitigationCheck.js
- src/parser/monk/brewmaster/modules/features/checklist/Component.js
Breath of Fire is only a 5% damage reduction, and shouldn't count as a means to deal with a soft mitigation check.
**Before**
**After**
I also changed the ISB checklist rule to use hits mitigated only instead of averaging with cast efficiency. Cast efficiency is mostly informative and not evaluative for this checklist item.
> [BrM] Removed bof from brm's soft mit checks

- src/parser/shared/modules/features/TimelineTab/TabComponent/SpellTimeline.js
Provides better accuracy and shows more precisely whenever we hit the GCD cap at 0.75s (instead of showing 0.8s
> [Core] update timeline to double decimal

- src/common/SPELLS/bfa/azeritetraits/druid.js
- src/common/SPELLS/bfa/azeritetraits/general.js
- src/parser/core/CombatLogParser.js
- src/parser/druid/restoration/CombatLogParser.js
- src/parser/shared/modules/spells/bfa/azeritetraits/SynergisticGrowth.js
- src/parser/shared/modules/spells/bfa/azeritetraits/WoundBinder.js
Synergistic Growth was created for druids, but not for other classes. This PR moves the existing trait module and updates it to match some of the existing traits.
Old trait: 
New Trait: 
I built this on top of #2512 and it should not be merged until that PR is.
> [Azerite] Adding Synergistic Growth to other healing classes

- src/parser/paladin/protection/CombatLogParser.js
- src/parser/shared/modules/racials/bloodelf/ArcaneTorrent.js
pretty much what it says in the title :man_shrugging: 
Prot pallies don't actually use mana for anything, so the mana returned by AT is mostly wasted.
Also fixes a bug in the AT module where you actually couldn't turn *off* the AT suggestion via options as was intended.
> [Prot] removed arcane torrent suggestion

- src/CONTRIBUTORS.js
- src/parser/hunter/beastmastery/CHANGELOG.js
- src/parser/hunter/beastmastery/CombatLogParser.js
- src/parser/hunter/beastmastery/modules/spells/MultiShotSingleTarget.js
Implementation for the following issue: https://github.com/WoWAnalyzer/WoWAnalyzer/issues/1145
This is how it looks like: https://i.imgur.com/t3p8ngF.png
Currently, it checks for cases where multishot has been used (and thus beast cleave has been applied), and no beast cleave damage has been done within that 4 second Beast Cleave window. 
It adds an _avarage_ suggestion for 1-3 multi-shot casts, and a _major_ suggestion for any more than that. These are just numbers I came up with, so if you feel these numbers should be altered, feel free to do so/recommend better ones!
This is my first contribution to WoWAnalyzer. If there's anything important I should know or something I may have forgotten, please let me know 🙂
> [Beast Mastery] add a suggestion if people use Multishot on ST bosses

- src/parser/priest/holy/modules/checklist/Component.js
The checklist had the wrong spell ID.
> [HPriest] Making Halo show up in checklist

- src/parser/shaman/elemental/modules/Abilities.js
This custom category didn't match with any existing abilities conventions, current contributor (HawkCorrigan) agrees that it can be removed
> [Ele Shaman] Remove 'dot' category for flame shock

- src/parser/demonhunter/havoc/modules/Abilities.js
- src/parser/shaman/elemental/modules/Abilities.js
These deps are declared in CoreAbilities and not needed inside the extension
> [Havoc DH] Remove redundant dependencies from Abilities.js

- src/parser/hunter/beastmastery/modules/core/GlobalCooldown.js
Currently BM is showing an error on the Timeline for users that the Global Cooldown has not been configured properly, and after investigating, I found that the haste values used during our cooldown AOTW use the wrong numbers with certain buffs up, such as time-warp and bloodlust.
The reason this happens, is because currently it is using the StatTracker to calculate the current haste, but buffs like Time Warp is a percentage based buff, and thus not representable using a stat tracker. Arguably this may even be a different issue itself.
To ensure the `GlobalCooldown.js` module for Beast Mastery is consistent with the shared `CoreGlobalCooldown` module, I've changed it to instead use `this.haste.current` instead, which the shared module also uses.
> [Beast Mastery] Make the Global Cooldown during AOTW use proper haste values.

- src/parser/paladin/protection/CHANGELOG.js
- src/parser/paladin/protection/modules/features/SpellUsable.js
- src/parser/paladin/protection/modules/spells/Judgment.js
- src/parser/paladin/protection/modules/talents/RighteousProtector.js
also changed the label of the Righteous Protector cooldown reduction stat to differentiate it.
also also trying something with the changelog. apparently padding (aka blank lines) in json lists can help prevent merge conflicts. merge #2523 first to test this.
> [Prot] Shield of the Righteous CDR stat

- src/parser/shaman/restoration/modules/talents/UnleashLife.js
Reworks Unleash Life a bit. Motivation comes from needing to find out the healing distribution between the spells for a future module, and also to improve accuracy, as that wasn't quite there (riptide mostly).
The player_heal function is definitely a bit overloaded, but with how UnL works it does make other solutions hard (unless I'm missing something).
Casts & Heals essentially go through the same logic, as the combat log order for that is unreliable. Either standalone work fine.
I ran into issues using applybuff events for Riptide, with situations like this where Riptide isn't affected by Unleash Life (already consumed by Surge), but the `hasBuff(UnleashLife)` function will always return true here: 
Added a tooltip for more detail on the breakdown: …
> [Restoration Shaman] Unleash Life

- src/parser/shared/modules/features/TimelineTab/TabComponent/index.js
Clicking on the link leads to a "Create new page" if logged into github (or contributing if not), probably because the wikipage was renamed.
example from discord: https://wowanalyzer.com/report/hzw9FHMqGYP7Z3fd/1-Heroic+Taloc+-+Kill+(4:07)/16-Anikka/timeline
> fix wikilink

- src/parser/hunter/beastmastery/CHANGELOG.js
- src/parser/hunter/beastmastery/CombatLogParser.js
- src/parser/hunter/beastmastery/modules/features/TraitsAndTalents.js
- src/parser/hunter/beastmastery/modules/talents/KillerInstinct.js
Implement a module for the Level 15 Beast Mastery talent _Killer Instinct_, as requested by #2529 
It currently only adds a statistic in the Talents section, mentioning how many casts have been done when the enemy had less than 35% of it's health left, and another substatistic in the _Spells, Traits and Talents_ section showing how much damage has been contributed by this talent.
> [Beast Mastery] Implement a Killer Instinct module

- src/parser/mage/frost/modules/features/Abilities.js
The diff gets really messed up when you edit values like these, sorry! Sorted by estimated cast count / cooldown length, rather than the default sorting
Before:
After:
> [Frost Mage] Sort spells on timeline

- src/parser/shared/modules/features/SelfHealTimingGraph.js
Now plots the graph in 500ms precision instead of 1s. 
This is primarily an issue when taking burst-damage while timing DS really close to that event (or LotP for prot).
**Before**
**After**
> [Blood Deathknight][Protection Paladin] increase SelfhealTimingGraph precision

- src/parser/hunter/beastmastery/modules/talents/Stampede.js
In regards to #2529, this adds more statistics and suggestions for the _Stampede_ level 90 talent.
First it adds an extra expandable statistics sheet in the _Talents_ section:
Second, it adds a suggestion regarding inefficient Stampede usage, where not all potential stampede hits actually hit the target:
The already existing damage contribution is untouched.
> [Beast Mastery] Implement talent statistics and suggestions for the Stampede module

- src/parser/warlock/destruction/CHANGELOG.js
- src/parser/warlock/destruction/CombatLogParser.js
- src/parser/warlock/destruction/modules/talents/FireAndBrimstone.js
- src/parser/warlock/destruction/modules/talents/index.js
Fire and Brimstone talent was disabled a little while ago because of it was wired to a system that got removed. This fixes it to work correctly again.
Example log - /report/M7rwPTjc2QK34JDa/25-LFR+Zul+-+Kill+(4:37)/19-Alucar/
> [Destruction] Fixed Fire and Brimstone talent

- src/parser/warlock/affliction/CONFIG.js
- src/parser/warlock/demonology/CONFIG.js
- src/parser/warlock/destruction/CHANGELOG.js
- src/parser/warlock/destruction/CONFIG.js
- src/parser/warlock/destruction/CombatLogParser.js
- src/parser/warlock/destruction/modules/features/Checklist/Component.js
- src/parser/warlock/destruction/modules/features/Checklist/Module.js
Destro isn't a very complicated spec so this is pretty simple like "use your stuff, don't cap resources" etc. I also updated configs for both Destro and Affli and removed the Warning from Destro as I'm actively working on it right now. I still got some things to add but it's mostly talent related "statistic" stuff, `how much damage did talent X do` etc., so I don't think it's blocking players from using this.
Example log (from which the screen is): /report/7aKQwdf4M86BcGgx/46-Mythic+Zul+-+Kill+(3:23)/83-Strungol/
PS. Not a clue why the warning is shown on the timeline, all haste buffs should be implemented by now (Overwhelming Power, elemental Whirl, Reverse Entropy). Maybe only Reorigination Array and Backdraft but that's affecting cast time, not haste.
> [Destruction] Checklist implementation

- src/common/SPELLS/rogue.js
- src/parser/core/CASTS_THAT_ARENT_CASTS.js
- src/parser/rogue/assassination/CHANGELOG.js
- src/parser/rogue/assassination/CONFIG.js
- src/parser/rogue/assassination/CombatLogParser.js
- src/parser/rogue/assassination/modules/Abilities.js
- src/parser/rogue/assassination/modules/features/CooldownThroughputTracker.js
- src/parser/rogue/assassination/modules/spells/GarroteUptime.js
- src/parser/rogue/assassination/modules/spells/RuptureUptime.js
- src/parser/shared/modules/CooldownThroughputTracker.js
- src/parser/shared/modules/GlobalCooldown.js
Depends on #2588
Also changed CooldownThroughputTracker to support debuffs (Vendetta).
> [Assassination] Cooldown tab & dot uptime suggestions

- src/parser/hunter/beastmastery/modules/Abilities.js
- src/parser/hunter/marksmanship/modules/Abilities.js
- src/parser/hunter/shared/modules/talents/AMurderOfCrows.js
- src/parser/hunter/survival/modules/Abilities.js
Old (without associated bugfix in this PR which would push it to 26): 
New: 
Log: https://wowanalyzer.com/report/GrzhBC6MPVZ8cbQp/28-Mythic+Fetid+Devourer+-+Kill+(4:41)/19-Raicha/abilities
Fixes a bug where a player wouldn't be doing any damage in the timespan where crows could reset, so it was never registered as a reset.
Moves Crows into its own module and ensure the maxCasts prop is accurate.
> [Hunter] A Murder of Crows fixing

- src/parser/priest/holy/CHANGELOG.js
- src/parser/priest/holy/modules/spells/Renew.js
Renew is a pretty bad spell for priests. One of the most common improvements you can make as a player is to limit the number of renews that you cast. Renew should only be cast when moving, and when you have no other instant cast spells. This update tries to validate if you are casting renew well. This is a bit hard to do as it's hard to tell if a player is moving.
> [Hpriest] Adding renew cast suggestion

- src/parser/deathknight/blood/CHANGELOG.js
- src/parser/deathknight/blood/modules/core/DeathsCaress.js
- src/parser/deathknight/blood/modules/features/Checklist.js
- src/parser/shared/modules/MitigationCheck.js
**Blood Death Knight**
Updates the Death's Caress-module to account for distance between the player and the target and checks if other ranged spells where available (DnD or BD, since those to more than DC).
The 12 yrd limit right now is kind of arbitrary. I had some distances that were bigger than 30yrds (up to 37yrd), which should be due to travel-time of the spell and the target's hitbox. But I think 12yrd should be a good place to start since it's still in the 8yrd range (+- boss hitbox) for BB.
Will adjust that number according to feedback. But it's for sure more accurate than the current implementation that just flags every single cast as bad.
**Soft Mitigation Check**
Now flags checks that were parried, dodged, missed or immuned as passed.
> [Blood Death Knight][All tanks] Deaths Caress update + softmit-check

- src/parser/mage/arcane/modules/features/Channeling.js
> [Mage] Fix evocation channeling

- src/parser/priest/shadow/modules/checklist/Component.js
Currently, if you end a fight in voidform, you can be penalized in the checklist for the number of stacks you have. The stack average ignores ending voidforms, but the checklist still shows the last one as red. This fix makes it so the checklist will always show a fight ending voidform as green.
Before
After:
> [Spriest] Making last voidform green on the checklist if you ended the fight in it.

- src/parser/core/CombatLogParser.js
https://cdn.discordapp.com/attachments/392514374532726795/510315859969835008/unknown.png
[9:15 PM] niseko: found the cause, on_finished never gets called
[9:30 PM] Dambroda: found another bug, or tell me if its just my end
[9:30 PM] Dambroda: if i go to the events tab and scroll all the way to the bottom, it crashes
[9:30 PM] Dambroda: only if i have fabricated turned on
[9:31 PM] niseko: that is one impressive error message
> [Core] Fix bug with fabricate event filter property

- src/CHANGELOG.js
- src/common/SPELLS/bfa/dungeons/items.js
- src/parser/core/CombatLogParser.js
- src/parser/shared/modules/items/bfa/dungeons/RotcrustedVoodooDoll.js
Adds tracking of Rotcrusted Voodoo Doll to timeline, abilities tab & statistics icon
fixes #1696
> [Trinket] Added 'Rotcrusted Voodoo Doll' Trinket

- server/helpers/fetchFromWarcraftLogsApi.js
- src/common/SPELLS/bfa/azeritetraits/__UNUSED.js
- src/common/SPELLS/bfa/azeritetraits/rogue.js
- src/parser/rogue/assassination/CHANGELOG.js
- src/parser/rogue/assassination/CombatLogParser.js
- src/parser/rogue/shared/azeritetraits/SharpenedBlades.js
- src/parser/rogue/subtlety/CHANGELOG.js
- src/parser/rogue/subtlety/CombatLogParser.js
Implements a suggestion to avoid wasting Sharpened Blade stacks on a per minute threshold.
> [Assassination/Subtlety Rogue] Implement suggestion for Sharpened Blades stack wastage

- src/interface/others/ItemStatisticBox.js
- src/interface/others/TalentStatisticBox.js
- src/interface/others/TraitStatisticBox.js
This commit https://github.com/WoWAnalyzer/WoWAnalyzer/commit/770c2209a0dbf5bd23acd5cdb1d735c622fca782 changed a bit of CSS but didn't fix all of the affected statistic boxes.
Before
After
> [Core] Fix StatisticBox icon size

- server/helpers/fetchFromWarcraftLogsApi.js
- src/CHANGELOG.js
- src/common/ITEMS/bfa/dungeons/index.js
- src/common/SPELLS/bfa/dungeons/items.js
- src/parser/core/CombatLogParser.js
- src/parser/shared/modules/items/bfa/dungeons/MydasTalisman.js
Added My'Das Talisman stat block and added the spell to abilities for tracking. I also flagged it for cast efficiency suggestions, but I couldn't test if it works because all the logs I could find used it on cooldown.
> [Core] Add My'das Talisman stat block and event tracking

- src/parser/priest/shadow/modules/core/Channeling.js
Fixing issue that caused MindFlay to trigger the end channel event twice in a row under certain circumstances. Would cause the spell timeline to display a long mind flay channel time and would cause the downtime card to be funky:
Example broken log: https://wowanalyzer.com/report/qtLF1aNfZr92kcdG/9-Mythic+Zek'voz+-+Kill+(7:44)/21-Yath
> [Spriest] Fixing double firing of endChannel event

- src/game/ZONES.js
Because Warcraftlogs doesn't include these 3 bosses titles, our raid filter can't find them. 
Example:
Fix:
> [Core] adjust Zul, Mythrax and Zek'vos names

- src/parser/warlock/affliction/CHANGELOG.js
- src/parser/warlock/affliction/modules/features/Abilities.js
- src/parser/warlock/demonology/CHANGELOG.js
- src/parser/warlock/demonology/modules/features/Abilities.js
- src/parser/warlock/destruction/CHANGELOG.js
- src/parser/warlock/destruction/modules/features/Abilities.js
Demonology's Nether Portal is missing, but to avoid merge conflicts (it's missing the spell in SPELLS in this branch), I'll add it in #2644
> [Warlock] Added buffSpellIds to Abilities

- src/parser/monk/mistweaver/modules/spells/ThunderFocusTea.js
Quick bug fix for some mislabeled variables.
Was causing some `undefined` errors on the display.
> [MW] TFT Bug Fix

- src/parser/paladin/protection/modules/spells/LightOfTheProtector.js
This bug is triggered by casting SotR before being hit the first time in an encounter, something that apparently didn't happen in my test logs.
> fixed a crashing bug in the light of the protector module

- src/parser/mage/shared/modules/features/RuneOfPower.js
According to sims and mage TCS, there are really no situations where Incanter's Flow or Mirror Image are good options. On average, looking at WCL, a well played RoP increases throughput by about 10% on average. Because it's a playstyle choice, I think it's better to not make it part of the checklist and to keep it as an _Average_ suggestion. I also added an easy way (the constant at the top of the module) to enable/disable the suggestion as talents are rebalanced.
Also, changed module to new eventlistener 😉
> [Mage] Add a suggestion to talent into Rune of Power when playing Arcane or Fire

- src/parser/core/modules/EventEmitter.js
Not sure if it was intentionally left out. Also was considering adding a way to send either numbers/numbers array instead of only spell objects, but I don't want to mess with the design too much.
> [Core] Allow array in new event spell filter

- src/parser/shaman/restoration/CHANGELOG.js
- src/parser/shaman/restoration/modules/talents/EarthenWallTotem.js
Enables the module to show efficiency on a cast-by-cast basis.
Before:
After:
Update: Changed it to use absorbed damage instead of damage taken as effective healing, as they can differ. The totem processes damage events in batches, so you can actually get more healing out of it than what should be possible. Earthen Wall applies shields to everyone around it, that are replenished / reapplied instantaneously - every time a shield absorbs any damage, the totem damages itself for the same amount. The combination of raid-wide damage, the raid being stacked near the totem and the totem batching events together, you can get what's shown below:
(it dies midway through processing the damage events, following are just a bunch of buff removals until the next cast)
> [Restoration Shaman] Earthen Wall Totem cast details

- src/parser/mage/fire/CHANGELOG.js
- src/parser/mage/fire/CombatLogParser.js
- src/parser/mage/fire/modules/Checklist/Module.js
- src/parser/mage/fire/modules/features/HeatingUp.js
- src/parser/mage/fire/modules/features/HotStreak.js
- src/parser/mage/fire/modules/features/HotStreakPreCasts.js
- src/parser/mage/fire/modules/features/HotStreakWastedCrits.js
I redid Hot Streak to be easier to work with, updated it to the new event listeners, and fixed some bugs.
- Split Hot Streak into 3 separate modules (HotStreak, HotStreakWastedCrits, and HotStreakPreCasts)
- Split the double Stat Box into two separate boxes (which should be easier to understand)
- Rewrote the PreCasts suggestion to not include precasting Scorch cause that leads to munched procs.
- Changed the analysis on PreCasts to ignore anything during Combustion, the Firestarter execute, or the Searing Touch execute
- removed some variables that werent used
- Updated the Checklist to look at the new files
- Added comments throughout the code
- Added a position to Heating Up's stat box (Cause it was ordered weird)
- Added timeline highlights for wasted crits
- Changelog stuff
Stat …
> [Fire Mage] Hot Streak Redo

- src/common/SPELLS/demonhunter.js
- src/parser/demonhunter/vengeance/CHANGELOG.js
- src/parser/demonhunter/vengeance/modules/Abilities.js
- src/parser/demonhunter/vengeance/modules/features/SoulFragmentsTracker.js
- src/parser/demonhunter/vengeance/modules/statistics/SoulFragmentsConsume.js
- src/parser/demonhunter/vengeance/modules/talents/FeedTheDemon.js
Improved Feed The Demon soul talent tracking. There is a delay in changing of buff stacks and actually consuming a soul. When consuming a soul thats when the actual reduction for the talent happens. Changed the code to track that so its more accurate. 
Now that i track that and reduce the CD of demon spikes i also updated it int he abilities file.
Also updated some code and values in the soul tracking to make it more clear what its doing.
> {VDH} Fixed FTD talent tracking and cleaned up soul code

- src/parser/shared/modules/items/bfa/pvp/DreadGladiatorsMedallion.js
Noticed that it is missing from the module
https://www.warcraftlogs.com/reports/RH8mJB7NgwDzth2k#fight=46&type=summary&source=3
> [Trinket] Add missing Dread Gladiator's Medallion on use ability

- src/parser/shaman/restoration/modules/talents/EarthenWallTotem.js
Casting a EWT pre-pull was causing it to crash, since I didn't account for it starting with absorb events, not damage taken events (absorb events don't have max-health information). This fix creates an array if there is none, until the damage taken events come in and fully initializes it.
Failing log: https://wowanalyzer.com/report/RXWCm7BZMjPb4K6c/7-Mythic+G'huun+-+Kill+(8:48)/3-Maeveycakes
> [Restoration Shaman] EWT crash fix

- src/common/SPELLS/mage.js
- src/parser/mage/fire/CHANGELOG.js
- src/parser/mage/fire/CombatLogParser.js
- src/parser/mage/fire/modules/traits/BlasterMaster.js
Added support for the Blaster Master Trait. Keeps track of the max number of stacks you got to during Combustion.
Suggestion
Timeline
Stat Box
> [Fire Mage] Blaster Master Trait

- src/parser/core/modules/EventEmitter.js
- src/parser/core/modules/EventEmitter.test.js
Old situation:
```
1. cast event handled 
1.1 some module called early: ohh nice cast event! let me fabricate something
-> fabricated event handled completely
1.2 cast event called on the rest of the listeners
2. next event
```
New situation:
```
1. cast event handled 
1.1 some module called early: ohh nice cast event! let me fabricate something
-> fabricated event queued
1.2 cast event called on the rest of the listeners
2. fabricated event
3. next event
```
It's beautiful in its own way.
> Fix issue where fabricated events had wonky event order

- src/common/SPELLS/warlock.js
- src/parser/warlock/demonology/CHANGELOG.js
- src/parser/warlock/demonology/CombatLogParser.js
- src/parser/warlock/demonology/modules/features/Abilities.js
- src/parser/warlock/demonology/modules/features/Checklist/Component.js
- src/parser/warlock/demonology/modules/features/Felstorm.js
- src/parser/warlock/demonology/modules/talents/BilescourgeBombers.js
- src/parser/warlock/demonology/modules/talents/DemonicCalling.js
- src/parser/warlock/demonology/modules/talents/DemonicStrength.js
- src/parser/warlock/demonology/modules/talents/Dreadlash.js
- src/parser/warlock/demonology/modules/talents/GrimoireFelguard.js
- src/parser/warlock/demonology/modules/talents/index.js
Overall simple changes:
- added cast efficiency for Bilescourge Bombers talent
- tweaked Checklist a little
- moved shorter CD abilities to core spells instead of cooldowns
- added few more CDs
- added description to the first rule
- fixed the description in ABC rule (was copied from Affli)
- cleaned up and fixed Felstorm module (was picking up casts from Demonic Strength as well)
- fixed Demonic Calling module (was counting proc refreshes while the ability was on CD as wasted)
- updated Demonic Calling and Felstorm to the new event listening method
- added T15 talent modules
> [Demonology] Few fixes + Tier 15 talents

- src/parser/mage/fire/CHANGELOG.js
- src/parser/mage/fire/modules/features/HeatingUp.js
Rewrote Heating Up with the new event listeners.
Also fixed an issue that was causing the module to not properly register that the player was in the Searing Touch execute window if they had the talent.
- Updated to new event listeners
- Fixed Searing Touch execute window
- Increased the thresholds now that the values are accurate
- Changelog
> [Fire Mage] Heating Up Redo

- src/parser/priest/shadow/CHANGELOG.js
- src/parser/priest/shadow/CombatLogParser.js
- src/parser/priest/shadow/modules/spells/VampiricEmbrace.js
Vamp Embrace is optional for Shadowpriests, but represents a handy healing cooldown for the overall raid. It shouldn't be recommended, but it should be represented.
> Shadow priest/vamp embrace

- src/common/SPELLS/mage.js
- src/parser/mage/fire/modules/Checklist/Component.js
- src/parser/mage/fire/modules/features/Pyroclasm.js
- src/parser/mage/frost/modules/checklist/Component.js
- src/parser/mage/frost/modules/checklist/Module.js
- src/parser/mage/frost/modules/features/BoneChilling.js
- src/parser/mage/shared/modules/GetDamageBonus.js
Currently, there is a checklist rule (Maintain Your Buffs) for all three mage specs that checks for Arcane Intellect uptime. In most cases, it is the only item in that section. The exceptions are Frost (if talented into Bone Chilling) and Arcane (if talented into Arcane Familiar). Because Bone Chilling is a completely passive talent that requires no interaction from the player, it doesn't seem right to make it a checklist item; its uptime basically mirrors the player's uptime. So, removing that item, now there is only the Arcane Familiar uptime (a rarely taken talent) that would ever make this checklist rule contain more than one item. 
Taking that into account, I thought it might be better to put Arcane Intellect into the Be Prepared section, as it's a pre-combat buff and the idea of a …
> [(Frost) Mage] Moved Arcane Intellect rules & change how Bone Chilling is analyzed

- src/parser/core/Entity.js
Because there is no buff remove event at the end of the fight, getStackWeightedBuffUptime doesn't work properly because the last stack change event (the one that sets it to 0 when buffremove is called) is never actually added to the buffhistory. 
Another solution would be to fabricate the buffremove event at the end of the fight. This one seems simpler and less likely to cause bugs.
I discovered this while working on Bone Chilling, where frost mages would get the 10 stacks of the buff in the first 15 seconds of the fight and never lose them. Weighted uptime showed ~1% when it should have been close to 1000%, even though regular getBuffUptime was correct.
> [Core] Fix weighted buff uptime calculation when buff doesn't expire

- src/parser/paladin/retribution/modules/core/GlobalCooldown.js
> [7:17 PM] Skeletor: https://wowanalyzer.com/report/yTY6Gp3nWKmZLPz9/21-Mythic+Taloc+-+Kill+(5:13)/7-Alfajhor
> happening to me on multiple logs for ret
> "A connection error occured.
> Something went wrong talking to our servers, please try again.
> t.module is undefined"
I have no idea what happened that caused this to break all of a sudden, it was fine up until a few hours ago. It looks like it should have been broken before, but maybe it's just specific logs. 
Anyway, this module didn't need to override deps so I just removed that.
> [Ret Pally] Fix another case of deps not being properly expanded

- src/interface/others/DevelopmentTab.js
`parser._modules` was returning already the instances of the classes (`typeof === object`), whereas `getModule()` wants the class (`typeof === function`) causing it to crash in dev.
> [Core] Fix for Development Tab

- src/parser/hunter/marksmanship/CHANGELOG.js
- src/parser/hunter/marksmanship/CombatLogParser.js
- src/parser/hunter/marksmanship/modules/features/SpellsAndTalents.js
- src/parser/hunter/marksmanship/modules/spells/LoneWolf.js
- src/parser/hunter/marksmanship/modules/spells/PreciseShots.js
Creates a simple Precise Shots module and updates Lone Wolf module to be active despite WCL not showing LW buff uptime if it was at 100% throughout the fight. 
Renames the Spell and Talents list in preparation for talents to be potentially being moved out of it and traits 100% not being apart of it.
> [Marksmanship] Precise Shots & Lone Wolf update

- src/parser/shared/normalizers/PrePullCooldowns.js
I was just setting 1500ms for everything. While it's true I cant use the standard gcd resolutions (normalizer: I can't call the functions because haste, etc, will be wrong), I can check for regular numbers and use those instead of the worst-case 1500 _if_ they are set.
> [Core] Try to better guess GCD's for prepull cast events

- src/parser/warlock/destruction/modules/features/RainOfFire.js
I have no clue how this could happen. Fixes (ignores) damage events when there should be no Rain of Fires active. 
Log that caused this: `/report/48F3art1K9qCfXc6/1-Heroic+Taloc+-+Kill+(5:36)/9-Sharwem` - 2 damage events without any cast event before it (also how could there be just 2 of them and not more??)
> [Destruction] Rain of Fire bugfix

- src/common/SPELLS/bfa/azeritetraits/warlock.js
- src/parser/core/calculateBonusAzeriteDamage.js
- src/parser/druid/feral/modules/azeritetraits/WildFleshrending.js
- src/parser/hunter/beastmastery/modules/spells/azeritetraits/FeedingFrenzy.js
- src/parser/warlock/affliction/CombatLogParser.js
- src/parser/warlock/affliction/modules/azerite/DreadfulCalling.js
- src/parser/warlock/shared/helpers.js
Part of #2724. Added a helper function that should *estimate* the bonus part of Azerite traits that affect damage of spells (related issue: #2088). 
Assuming following:
- Azerite traits of this type affect *base* damage of spells
- For casters, this damage is determined by Intellect (and thus Spell Power) and the spell's SP coefficient
- so if `damage = (base + trait bonus) * coefficients`, that means both base and the trait bonus is scaled by same coefficients (like mastery, versatility etc.)
- and even if both damage parts gets scaled by the coefficients, their ratio stays the same regardless of it
We should be able to at least estimate the damage bonus with the following:
```
trait bonus = value that affects the damage
base damage = SP coefficient * current intellect
portion = trait …
```
> [Affliction] Dreadful Calling trait

- src/parser/warlock/demonology/CHANGELOG.js
- src/parser/warlock/demonology/modules/features/Abilities.js
Not sure how I've missed this, Grimoire: Felguard nowadays has 2 minutes instead of 1,5 minute CD.
> [Demonology] [Bug] Fixed Grimoire: Felguard cooldown

- src/interface/others/RestorationShamanSpreadsheet.js
- src/parser/shaman/restoration/modules/azerite/BaseHealerAzerite.js
- src/parser/shaman/restoration/modules/azerite/EbbAndFlow.js
- src/parser/shaman/restoration/modules/azerite/OverflowingShores.js
- src/parser/shaman/restoration/modules/azerite/SoothingWaters.js
- src/parser/shaman/restoration/modules/azerite/SpoutingSpirits.js
- src/parser/shaman/restoration/modules/azerite/SurgingTides.js
- src/parser/shaman/restoration/modules/azerite/SwellingStream.js
So I don't have to do that in 8.1 when i add the new traits.
Also adds the possibility to add mouseover details of the trait
> [Restoration Shaman] Update azerite to use event listeners

- src/common/SPELLS/bfa/azeritetraits/warlock.js
- src/parser/shared/modules/StatTracker.js
- src/parser/warlock/demonology/CombatLogParser.js
- src/parser/warlock/demonology/modules/azerite/DemonicMeteor.js
Part of #2724. Although Hand of Gul'dan damage scales with shards used, it's also as a multiplicative bonus, same as versatility for example, so it's not included.
> [Demonology] Demonic Meteor trait

- src/parser/paladin/protection/modules/spells/LightOfTheProtector.js
`this._lastHit` is initially null, so trying to get the timestamp of the _lastHit is erroing.
This fixes the error, but not sure how much it screws with the displayed data.
@emallson should have a look at it when he has some time.
> [Bug] [Protection Paladin] LotP fix

- src/common/SPELLS/bfa/azeritetraits/warlock.js
- src/parser/shared/modules/StatTracker.js
- src/parser/warlock/destruction/CombatLogParser.js
- src/parser/warlock/destruction/modules/azerite/BurstingFlare.js
Part of #2724. As for the event listeners - I know and you can read my rants about it on Discord - basically if I tried to do this properly, I got stuck somewhere in circular dependencies or circular imports, which would cause `characterTab` and `statTracker` to go `undefined` in `CombatLogParser` for no apparent reason => crashing the app. A solution proposed on Discord would be to have the event handlers in Events together with all other handlers. If that would be ok, I'll update the PR.
> [Destruction] Added Bursting Flare trait

- src/common/SPELLS/bfa/azeritetraits/__UNUSED.js
- src/common/SPELLS/bfa/azeritetraits/warlock.js
- src/parser/core/calculateBonusAzeriteDamage.js
- src/parser/druid/feral/modules/azeritetraits/WildFleshrending.js
- src/parser/hunter/beastmastery/modules/spells/azeritetraits/FeedingFrenzy.js
- src/parser/warlock/affliction/modules/azerite/DreadfulCalling.js
- src/parser/warlock/affliction/modules/azerite/InevitableDemise.js
- src/parser/warlock/affliction/modules/azerite/SuddenOnset.js
- src/parser/warlock/demonology/CombatLogParser.js
- src/parser/warlock/demonology/modules/azerite/DemonicMeteor.js
- src/parser/warlock/demonology/modules/azerite/ForbiddenKnowledge.js
- src/parser/warlock/demonology/modules/azerite/ShadowsBite.js
- src/parser/warlock/demonology/modules/azerite/ShadowsBiteForbiddenKnowledgeCore.js
Part of #2724. This one was a little complicated, because both of these traits can affect Demonbolt at the same time (there's a very small window, around 3 seconds where this can happen, but I've tested it and it works) + they snapshot the effects on cast, so spell queue was also necessary. 
Because of this, I also had to change the signature of `calculateBonusAzeriteDamage` (and change all existing occurences):
- `coefficients` has to be an explicitly stated array
- there's an optional array parameter `knownOtherEffects` that contains ADDITIVE other trait bonuses
- resulting base damage is then multiplication of all coefficients (like Spell Power, SP coefficients etc.) + sum of all known effects
I'm aware that some of my other opened PRs use the old signature - I'll change them as soon …
> [Demonology] Shadow's Bite and Forbidden Knowledge traits

- src/interface/others/StatisticBox.js
- src/interface/others/TalentStatisticBox.js
- src/interface/others/TraitStatisticBox.js
Simplified the core code for TraitStatisticBox (like I did for talents in #2735). As discussed, this lead to potential issues with font sizes being too large, so I added a prop into core statistic box that allows us to add the font smallifying css class (name is pretty bad, I just have it match the css class name but its very misleading I think).
Mainly creating this PR to hopefully actually get a discussion going on how to determine font size for statistic boxes.
> [Core] Simplify code for TraitStatisticBox and fix font size for talent boxes

- src/parser/druid/guardian/modules/Abilities.js
Pretty straightforward. This should prevent the analyzer from complaining about downtime when Catweaving
> [Guardian Druid] Add cat form abilities to spellbook

- src/parser/mage/frost/CHANGELOG.js
- src/parser/mage/frost/modules/checklist/Component.js
- src/parser/mage/frost/modules/checklist/Module.js
- src/parser/mage/frost/modules/features/ThermalVoid.js
Thermal Void is currently in the checklist using flat extension values to determine if the player used it properly. As it is entirely RNG and fight-dependent how long you can extend TV, I think it's better to not have a checklist/suggestion item and instead only include a statistic. Suggestions would probably be tied into FoF/brain freeze efficiency upgrades instead.
(worth noting that in the sample provided, frozen orb was cast twice during Icy Veins; just goes to show that we really cannot use extension time as suggestion threshholds here)
**_No suggestion/checklist items_**
> [Frost Mage] Thermal Void rewrite

- src/parser/warlock/demonology/CombatLogParser.js
- src/parser/warlock/demonology/modules/pets/CONSTANTS.js
- src/parser/warlock/demonology/modules/pets/DemoPets/DemonicTyrantHandler.js
- src/parser/warlock/demonology/modules/pets/DemoPets/ImplosionHandler.js
- src/parser/warlock/demonology/modules/pets/DemoPets/PetDamageHandler.js
- src/parser/warlock/demonology/modules/pets/DemoPets/PetSummonHandler.js
- src/parser/warlock/demonology/modules/pets/DemoPets/PowerSiphonHandler.js
- src/parser/warlock/demonology/modules/pets/DemoPets/WildImpEnergyHandler.js
- src/parser/warlock/demonology/modules/pets/DemoPets/index.js
- src/parser/warlock/demonology/modules/pets/PETS.js
- src/parser/warlock/demonology/modules/pets/PetTimelineTab/TabComponent/PetTimeline.js
- src/parser/warlock/demonology/modules/pets/helpers.js
- src/parser/warlock/demonology/modules/pets/normalizers/PrepullPetNormalizer.js
- src/parser/warlock/demonology/modules/talents/DemonicConsumption.js
- src/parser/warlock/demonology/modules/talents/InnerDemons.js
- src/parser/warlock/demonology/modules/talents/normalizers/PowerSiphonNormalizer.js
The diff on this is ugly but the point is here:
- DemoPets.js was an unmaintainable mess, 440+ lines of glued up spaghetti code that somehow worked
- I broke it down into 6 smaller pieces, each of which takes care of **single** thing - Pet summoning, Wild Imp despawns due to energy, Demonic Tyrant extensions etc.
- these modules have been also updated to the new event listening system (apart from PetSummonHandler, which wasn't updated due to it listening to "spendresource" event)
- old `/pets/DemoPets.js` was moved to `/pets/DemoPets/index.js` so the imports are same
- new DemoPets.js now contains only `PetDamage` and `PetTimeline` objects, API methods and some common helper methods that I didn't want to duplicate across modules
- I also removed some helper arrays in `/pets/CONSTANTS.js`, …
> [Demonology] Pet tracking refactor and cleanup

- src/parser/priest/discipline/modules/Abilities.js
We might want to consider adding a check in the AbilityRequirement to make sure the efficiency is enabled. 
Before:
After:
> [DiscPriest] Fixing Shadow Covenant on checklist

- src/CHANGELOG.js
- src/parser/shared/modules/StatTracker.js
Example log: `/report/8Cy3KTwHzD4PgRtN/52-LFR+Zul+-+Kill+(5:27)/1210-Ishbale` - both the ele shaman Ishbale and arcane mage Andrømedâ share at least Archive of the Titans which is added with the `add()` method. Doesn't crash now.
> [Core] [Bug] StatTracker fix

- src/parser/core/modules/Ability.js
- src/parser/hunter/survival/modules/Abilities.js
- src/parser/shared/modules/features/TimelineTab/TabComponent/SpellTimeline.js
This allows you to set which spell you want linked in the timeline on the left, if nothing is defined as shownSpell, it'll just default to what it used to. 
Also deleted the redundant 
```JS
{abilities.getAbility(spellId).name}
```
but if it was used somewhere let me know, I just couldn't find anywhere that would do anything different than regular spelllink. 
With the prepot update (I think), my prior hack to this broke - this fixes it permanently.
> [Core] Update Timeline to allow specifying which spell you want shown

- src/parser/mage/arcane/CHANGELOG.js
- src/parser/mage/arcane/CONFIG.js
- src/parser/mage/fire/CHANGELOG.js
- src/parser/mage/fire/CONFIG.js
- src/parser/mage/fire/modules/traits/BlasterMaster.js
- src/parser/mage/frost/CHANGELOG.js
- src/parser/mage/frost/CONFIG.js
- src/parser/mage/frost/modules/traits/Whiteout.js
Update all Mage specs to 8.1. Mage didnt get very many changes overall, so this is pretty short.
- No changes for Arcane
- Blaster Master caps at 3 stacks now
- Frost's damage aura was updated
> [Mage] Update all specs to 8.1

- src/parser/druid/feral/modules/Abilities.js
- src/parser/druid/feral/modules/features/checklist/Component.js
- src/parser/druid/feral/modules/features/checklist/Module.js
- src/parser/druid/feral/modules/talents/BrutalSlashHitCount.js
Brutal Slash itself didn't change much (just increased coefficient, which is used for calculating Azerite trait damage.) But the talent tree was rearranged so it's now the best choice in its row for single target damage rather than the worst. This removes a suggestion and checklist item around that fact.
> [Feral Druid] Update Brutal Slash for 8.1

- src/parser/shaman/elemental/modules/features/StormFireElemental.js
Got a report that the cooldown percentages were wrong if the Elemental was not being used pre-pull, because I was comparing the summon events with the cast spellids.
Changed it to actually check on cast now instead of on summon.
http://localhost:3000/report/6M3Z8pQvxC4Ttc7n/3-Mythic+MOTHER+-+Kill+(4:10)/9-Nellor/events
> Checking on cast instead of on summon so the ability guids match

- src/parser/paladin/retribution/modules/talents/Crusade.js
The module previously gave players a 500 ms lenience to use a spender after casting Crusade. The module now calculates the Crusade GCD on cast and adds that to the lenience.
>  [Ret] Updating Crusade module to account for it being on the GCD

- src/parser/druid/feral/CHANGELOG.js
- src/parser/druid/feral/CONFIG.js
- src/parser/druid/feral/constants.js
- src/parser/druid/feral/modules/bleeds/RakeSnapshot.js
- src/parser/druid/feral/modules/bleeds/RipSnapshot.js
- src/parser/druid/feral/modules/bleeds/RipUptime.js
- src/parser/druid/feral/modules/core/Snapshot.js
- src/parser/druid/feral/modules/features/SpellUsable.js
- src/parser/druid/feral/modules/features/checklist/Component.js
- src/parser/druid/feral/modules/features/checklist/Module.js
- src/parser/druid/feral/modules/talents/MoonfireSnapshot.js
The mechanics of Rip were changed in 8.1, which is now reflected in the logic of RipSnapshot. Previously Rip had a set duration like the other Feral DoTs but now it depends on the combo points used. In addition the Sabertooth talent works differently, extending the duration by a set amount rather than resetting it.
Reworked `RipSnapshot` to work with the new mechanics of Rip.
Removed reference to the removed Jagged Wounds talent.
Removed anything to do with the removed mechanic of Ferocious Bite refreshing Rip when target is in execute range.
Improved `RipUptime`'s suggestion to only advise against using Bite if the player doesn't have Sabertooth.
Moved some constants from `Snapshot` out to `constants`
Prevented false information coming from the Predator analysis in `SpellUsable` 
Added …
> [Feral Druid] Update RipSnapshot for 8.1

- src/parser/paladin/protection/modules/features/ShieldOfTheRighteous.js
[Crashing log](https://www.wowanalyzer.com/report/JMZXyh6qjgKWtV7w/1-+Atal'Dazar+-+Kill+(37:38)/4-Aurovin)
`this.owner` does not have a `boss` prop in M+ logs.
> [Prot Paladin] fixed m+ crash with SotR module

- src/common/SPELLS/warrior.js
- src/parser/warrior/fury/modules/Abilities.js
- src/parser/warrior/fury/modules/features/SpellUsable.js
- src/parser/warrior/fury/modules/talents/SuddenDeath.js
When talented into Massacre, Execute has a different spell id and this was missing in a few places
> [Fury Warrior] Missing Spell ID for Execute

- src/parser/warrior/fury/CombatLogParser.js
- src/parser/warrior/fury/modules/normalizers/Enrage.js
When Bloodthirst triggered Enrage, the enrage event appeared after the cast and so the haste didn't effect it's GCD.
> [Fury Warrior] Fixed SpellUseable issue for Fury

- src/parser/core/CASTS_THAT_ARENT_CASTS.js
Charge has a cast event for the damage event when you reach your target but was not classed as an ability. It's now been added to the Casts that aren't casts list
> [Warrior] Missing Charge ability

- src/parser/mage/fire/modules/features/HeatingUp.js
If the player casts Phoenix Flames before the pull then it crashed the module since there was no cast event in the log.
> [Fire Mage] Fix Crash in Heating Up

- src/common/SPELLS/priest.js
- src/parser/priest/discipline/CombatLogParser.js
- src/parser/priest/shadow/CONFIG.js
- src/parser/priest/shadow/CombatLogParser.js
- src/parser/priest/shadow/modules/Abilities.js
- src/parser/priest/shadow/modules/spells/VampiricEmbrace.js
- src/parser/priest/shared/normalizers/ShadowfiendNormalizer.js
Bumping Shadow Priest version as there were no large changes in 8.1.
Bug Fixes:
Glyphed Shadow Fiends don't currently work correctly in Shadow. I've moved the Disc shadowfiend normalizer into a shared directory and added an additional check to fix this.
Example log: /report/cajpvgQdbX2BRCWk/9-Heroic+Taloc+-+Kill+(4:19)/135-Ellipsìs
Fixed problem with Vamp Embrace
> [SPriest] 8.1 & Adding Shadowfiend normalizer to shadow

- src/parser/warlock/affliction/modules/talents/SoulConduit.js
- src/parser/warlock/demonology/modules/azerite/DemonicMeteor.js
- src/parser/warlock/demonology/modules/talents/SoulConduit.js
- src/parser/warlock/destruction/modules/talents/SoulConduit.js
- src/parser/warlock/shared/probability.js
I got inspired by emallson and Putro and tried to make usage of some probability distributions in my Warlocks. Specifically, I looked at classic [binomial distribution](https://en.wikipedia.org/wiki/Binomial_distribution) and its generalized neighbor, [Poisson binomial distribution](https://en.wikipedia.org/wiki/Poisson_binomial_distribution) (the difference is merely in the fact that binomial has fixed probability chance for all events whereas Poisson can have different probabilities for each event).
Originally I wanted to implement it in more places but I'd rather not inflate this PR any more than needed. Added both distributions, their [PMF](https://en.wikipedia.org/wiki/Probability_mass_function) and [CDF](https://en.wikipedia.org/wiki/Cumulative_distribution_function) functions and …
> [Warlock] Probability playground

- src/common/SPELLS/paladin.js
- src/parser/paladin/protection/modules/Abilities.js
Glyph of the Queen (https://www.wowhead.com/spell=212642/glyph-of-the-queen) changes the spell id of GoAK, similarly to the 200 different polymorph spells. This fixes the detection of the alternate spell.
> [Prot Pal] Fix GoAK + Glyph of the Queen

- src/parser/deathknight/blood/__snapshots__/CombatLogParser.test.js.snap
- src/parser/deathknight/blood/modules/features/DancingRuneWeapon.js
Whitelist DRW for DRW since the cast is since BfA on the GCD. The DRW cast event happens right after the buff apply and fails the check.
> [Blood Death Knight][Bug] allow DRW cast event during DRW

- src/common/SPELLS/bfa/raids/battleofdazaralor/index.js
- src/common/SPELLS/bfa/raids/battleofdazaralor/items.js
- src/common/SPELLS/bfa/raids/battleofdazaralor/mechanics.js
- src/common/SPELLS/bfa/raids/index.js
Adds spell info for Battle of Dazar'alor items, a prerequisite for making analyzers for the raid's trinkets.
> Add Battle of Dazar'alor item spells

- src/common/SPELLS/bfa/azeritetraits/druid.js
- src/parser/druid/restoration/CHANGELOG.js
- src/parser/druid/restoration/CONFIG.js
- src/parser/druid/restoration/modules/items/azeritetraits/AutumnLeaves.js
- src/parser/druid/restoration/modules/items/azeritetraits/LivelySpirit.js
Autumn Leave changes are basically a copy paste of an old legion trait which did the same:
https://github.com/WoWAnalyzer/WoWAnalyzer/blob/d47e2a9d5e6d1cc451b6827f21e956d8cf8cbd91/src/Parser/Druid/Restoration/Modules/Traits/Persistence.js
> Resto druid 8.1 changes

- src/parser/warlock/affliction/modules/azerite/PandemicInvocation.js
- src/parser/warlock/affliction/modules/talents/SoulConduit.js
- src/parser/warlock/demonology/modules/azerite/DemonicMeteor.js
- src/parser/warlock/demonology/modules/talents/SoulConduit.js
- src/parser/warlock/destruction/modules/azerite/ChaosShards.js
- src/parser/warlock/destruction/modules/soulshards/SoulShardTracker.js
- src/parser/warlock/destruction/modules/talents/SoulConduit.js
- src/parser/warlock/shared/probability.js
Cleaned up the `findMax` function, now it doesn't depend on the function shape (and instead iterates through all possibilities, which is more computationally heavy but in our cases (relatively small N), it shouldn't be a problem), and the `pmf` has been changed to not provide the probabilities.
This allows for more generalized syntax that you can see in Demonic Meteor or Soul Conduit for example.
Implemented this probability things in Pandemic Invocation and Chaos Shards traits:
- for Pandemic Invocation, the additional code is tracking dots and handling Pandemic effect
- for Chaos Shards I modified Destro SoulShardTracker to emit `fullshardgained` event when .. generating a full Shard 😄 
Also rewrote texts a little so that it doesn't break when player was most likely to get *no* Shards …
> [Warlock] More probability things

- src/parser/rogue/subtlety/CHANGELOG.js
- src/parser/rogue/subtlety/CONFIG.js
- src/parser/rogue/subtlety/CombatLogParser.js
- src/parser/rogue/subtlety/normalizers/ShurikenStormNormalizer.js
Fixes #2696
Normalizer to remove crazy CP waste when using Shuriken Storm in a situation with more then 6 targets.
> [Sub Rogue] Shuriken Storm limit CP waste

- src/interface/report/Results/EncounterStats.js
Healers currently show "dps done" in the similar fights pane. This fixes that.
I felt that the wording for the similar kill times was a bit off.
`These are the 9 top 9 logs that are closest to your kill-time within 20% variance.`
will now be
`These are 9 of the top 9 logs that are closest to your kill-time within 20% variance.`
This is an examples of a *healers* log:
Before: ![screen shot 2019-01-31 at 8 05 26 am](https://user-images.githubusercontent.com/716498/52063071-10f9ae80-252f-11e9-91d8-6c90678b4d5b.png)
After: ![screen shot 2019-01-31 at 8 05 46 am](https://user-images.githubusercontent.com/716498/52063081-13f49f00-252f-11e9-9c01-1651cc6bf131.png)
> [General] Updating the wording on the EncounterStats

- src/CONTRIBUTORS.js
- src/parser/warrior/arms/CHANGELOG.js
- src/parser/warrior/arms/CombatLogParser.js
- src/parser/warrior/arms/modules/core/Execute/MortalStrike.js
- src/parser/warrior/arms/modules/core/Overpower.js
- src/parser/warrior/arms/modules/core/Slam.js
- src/parser/warrior/arms/modules/spells/azeritetraits/CrushingAssault.js
- src/parser/warrior/arms/modules/spells/azeritetraits/LordOfWar.js
- src/parser/warrior/arms/modules/spells/azeritetraits/StrikingTheAnvil.js
Slam with crushing assault is not a bad cast over mortal strike during execution phase.
Added Lord of War tracking.
Added more info to the tooltip on Crushing assault.
Added more information to overusing Mortal Strike/Slam.
Excluded Striking the Anvil "waste" when in execute range.
> Arms warrior improvements

- src/parser/demonhunter/havoc/CHANGELOG.js
- src/parser/demonhunter/havoc/CONFIG.js
- src/parser/demonhunter/havoc/CombatLogParser.js
- src/parser/demonhunter/havoc/modules/talents/DemonBlades.js
- src/parser/demonhunter/havoc/modules/talents/ImmolationAura.js
Created a log with the 3rd talent, but unfortunately due to its nature i have no way of calculating its fury generation.  
Talent in question:
**Insatiable Hunger:**  Demon's Bite generates up to 10 additional Fury.
As for **Demons Bite:** Quickly attack for (45.279% of Attack power) Physical damage. Generates 20 to 30 Fury.
Since they both generate variable amount of fury, and logs dont show the extra fury Insatiable hunger provides, i have no way of separating the 2 and calculating the extra it provides. A log if anyone wants to look into it:
https://www.warcraftlogs.com/reports/AZMDnzrG48KJLgP6/#fight=last&type=resources&view=events&spell=117
> [Havoc DH] Level 100 talents

- src/parser/monk/mistweaver/CHANGELOG.js
- src/parser/monk/mistweaver/CONFIG.js
- src/parser/monk/mistweaver/CombatLogParser.js
- src/parser/monk/mistweaver/modules/features/Checklist/Component.js
- src/parser/monk/mistweaver/modules/features/Checklist/Module.js
- src/parser/monk/mistweaver/modules/features/MistweaverHealingEfficiencyDetails.js
- src/parser/monk/mistweaver/modules/features/StatValuesSpellInfo.js
- src/parser/monk/mistweaver/modules/spells/Vivify.js
- src/parser/monk/mistweaver/modules/talents/RenewingMistDuringManaTea.js
Added a new statistic and checklist item to track the number of Renewing Mists active during Mana Tea.
> [MW] REM During MT Updates

- src/common/SPELLS/bfa/azeritetraits/druid.js
- src/parser/druid/feral/CHANGELOG.js
- src/parser/druid/feral/CombatLogParser.js
- src/parser/druid/feral/modules/Abilities.js
- src/parser/druid/feral/modules/azeritetraits/UntamedFerocity.js
- src/parser/druid/feral/modules/azeritetraits/WildFleshrending.js
Untamed Ferocity increases the direct damage of all combo generating abilities by X, and reduces the remaining cooldown of Berserk/Incarnation whenever they're used. This adds a tracker for how much damage that provides and how much the cooldown is reduced.
Because Wild Fleshrending also increases direct damage of some combo generating abilities that module was updated to take the Untamed Ferocity damage into account. I've tried to keep the logic for each trait in their own file, exporting and importing as needed between the two.
I also removed a chunk of dead code from the Wild Fleshrending module. It was debug-only code that used an alternative method to calculate damage contribution and is no longer needed.
**Example logs:**
Using only Untamed Ferocity …
> [Feral] Add Untamed Ferocity azerite trait

- src/parser/deathknight/blood/CHANGELOG.js
- src/parser/deathknight/blood/__snapshots__/CombatLogParser.test.js.snap
- src/parser/deathknight/blood/modules/features/MarrowrendUsage.js
- src/parser/deathknight/blood/modules/spells/azeritetraits/BonesOfTheDamned.js
- src/parser/deathknight/blood/modules/spells/azeritetraits/EternalRuneWeapon.js
- src/parser/deathknight/blood/modules/talents/Bonestorm.js
Updates the calculation for bad Marrowrends by counting the wasted charges.
The module is currently punishing all types of bad Marrowrends equally, but there is a difference between wasting a potential BotD-proc and capping 3 stacks.
I've made an extra suggestion for possible BotD-procs to keep the number for the core-suggestion accurate.
Also fixed two issues with Bonestorm and ERW that caused errors when used prepull.
> [Blood Death Knight] Marrowrend-usage update

- src/parser/paladin/protection/CHANGELOG.js
- src/parser/paladin/protection/modules/features/Checklist/Component.js
- src/parser/paladin/protection/modules/spells/LightOfTheProtector.js
Pretty self-explanatory. Don't want to track delay since last time the Paladin was hit when they HotP another target.
> [Prot Pal] HotP delay now only looks at self-targeted casts

- src/parser/shared/modules/Entities.js
This is still not a nice fix but it at least fixes the changebuffstack events.
I would like to completely get rid of the one rogue buff event in the buff history but for that I need more time to understand why it even exists.
Live:
Fixed:
Report:
http://localhost:3000/report/naqbT14ywgHpWh7D/25-Mythic+Conclave+of+the+Chosen+-+Wipe+11+(4:51)/94-Syqu/events
> Fixing Lifebloom Fix?

- server/constants/index.js
- server/controllers/api/character.js
- src/CONTRIBUTORS.js
- src/interface/report/PlayerSelection/PlayerTile.js
Resolves #2963 
The result looks like this:
Please note that this is my first contribution to this project, and so please forgive me if I have done something in the wrong place. If so - I'll happily fix it!
> #2963 Fetch Heart of Azeroth item level from Blizzard API and display the value on Raid Composition page

- src/parser/core/Combatant.js
- src/raids/battleofdazaralor/ConclaveOfTheChosen.js
- src/raids/battleofdazaralor/HighTinkerMekkatorque.js
- src/raids/battleofdazaralor/JainaProudmoore.js
- src/raids/battleofdazaralor/KingRastakhan.js
- src/raids/battleofdazaralor/OpulenceTreasureGuardian.js
- src/raids/battleofdazaralor/RaceTranslation.js
- src/raids/battleofdazaralor/StormwallBlockade.js
Resolves #3014
As the comment indicates, there are better ways to compare the players class, but our way of handling it is pretty poor at the moment and it's either this or doing something like
`return spec.ranking.id === SPECS.GuardianDruid.ranking.id ? RACES.NightElf : RACES.Draenei;`
Which seems pretty arbitrary and confusing
> [Core] Added race translation tables for BoD faction swaps

- src/common/SPELLS/bfa/azeritetraits/druid.js
- src/parser/druid/feral/CHANGELOG.js
- src/parser/druid/feral/CombatLogParser.js
- src/parser/druid/feral/modules/azeritetraits/JungleFury.js
Adds simple analysis of the [Jungle Fury](https://www.wowhead.com/spell=274424/jungle-fury) azerite trait. Provides a statistic showing what critical strike rating it gave over the fight and how much extra duration on the Tiger's Fury buff was added by the trait.
Example log: report/tQRnCGHaTgKrA2JV/9-Heroic+Grong+the+Revenant+-+Kill+(3:18)/555-Hoofhartd
> [Feral] Jungle Fury azerite trait

- src/parser/core/Combatant.js
CLP.boss can be undefined, turns out
> [Core][Bugfix] Fix attempting to get race swap info for undefined boss info

- server/migrations/20190223014101-character.js
- server/models/Character.js
This resolves the issue where the updated Character data fetched the Blizzard API is not defined in the Character model, and thus does not display when the character is fetched from the cache.
Definition:
https://github.com/WoWAnalyzer/WoWAnalyzer/blob/next/server/controllers/api/character.js#L77
Resolves #2963
> Character cache storage - persist heartOfAzeroth field in Sequelize cache

- src/common/SPELLS/rogue.js
Recent Rogue PR introduced a duplicate SPELL object with Rogue Azerite trait Ace Up Your Sleeve which I didn't thought to check while reviewing and which is failing the site in development. This removes it (and leaves it in `azeritetraits/rogue.js` where it's supposed to be)
> [BUG] Fix for duplicate Rogue trait

- src/common/SPELLS/bfa/azeritetraits/__UNUSED.js
- src/common/SPELLS/bfa/azeritetraits/druid.js
- src/common/SPELLS/druid.js
- src/parser/druid/feral/CHANGELOG.js
- src/parser/druid/feral/CombatLogParser.js
- src/parser/druid/feral/modules/Abilities.js
- src/parser/druid/feral/modules/azeritetraits/IronJaws.js
Adds support for the [Iron Jaws](https://www.wowhead.com/spell=276021/iron-jaws) azerite trait.
Using Iron Jaws requires a change in the player's ability priorities, so there's suggestions generated if they don't make the required changes.
Unusually the Iron Jaws trait is extremely weak if just one trait is active. It requires a change in rotation which is a damage loss without the trait, and having one trait barely makes up for that loss. So a suggestion is also generated if just one trait is detected.
Example log that uses Iron Jaws successfully:
`report/vWqBGXyhCr7LT931/13-Heroic+Grong+-+Kill+(3:17)/1-Berendain`
Example log that needs improvement with Iron Jaws:
`report/ZHwzYdhp6J1m9vWC/13-Normal+Grong+-+Kill+(4:02)/33-Lunardin`
> [Feral] Iron Jaws azerite trait

- src/parser/warlock/demonology/CombatLogParser.js
- src/parser/warlock/demonology/__snapshots__/CombatLogParser.test.js.snap
- src/parser/warlock/demonology/modules/features/LegionStrike.js
It was brought upon my attention that some players have Felguard's Legion Strike auto-cast turned off, smh. This module warns them if the Felguard didn't cast any Legion Strike and also shows the damage done by it (only by the permanent pet, since you have control over that one, Grimoire: Felguard (from talent) casts it too, but it does it automatically and it's already counted as total damage done by the talent elsewhere).
> [Demonology] Legion Strike module

- src/parser/shared/modules/throughput/DamageTaken.js
`DamageTaken._subtractDamage` wasn't respecting the new `ability` parameter. This was causing damage to be double-counted as both staggered and taken. AFAIK BrM is the only spec to use this functionality
> fixed DamageTaken's interaction with stagger

- src/CHANGELOG.js
- src/parser/shared/modules/features/Checklist/Rule.js
The old checklist would hide a rule if all of the requirements underneath it were hidden, but it doesnt look like the new checklist does that. This should fix that.
Before (Use GS and Use talents are empty)
After
> [Core] Hide empty rules in the checklist

- src/parser/mage/arcane/modules/features/ArcaneOrb.js
Fix a bug that was always counting the first arcane orb as not hitting anything. Also remove the reference to the Legion Legendary.
> [Arcane Mage] Fix Arcane Orb bug

- src/common/SPELLS/bfa/azeritetraits/druid.js
- src/parser/core/CASTS_THAT_ARENT_CASTS.js
- src/parser/druid/feral/CHANGELOG.js
- src/parser/druid/feral/CombatLogParser.js
- src/parser/druid/feral/modules/Abilities.js
- src/parser/druid/feral/modules/azeritetraits/GushingLacerations.js
Adds tracking for the [Gushing Lacerations](https://www.wowhead.com/spell=278509/gushing-lacerations) azerite trait. Provides a simple statistic with damage increase and combo points generated (and wasted) from the trait.
> [Feral] Gushing Lacerations azerite trait

- src/parser/paladin/retribution/CombatLogParser.js
- src/parser/paladin/retribution/modules/core/azeritetraits/IndomitableJustice.js
Indomitable Justice works based on comparing your health to the health of your target. This module just displays the effective benefit for a fight. Thanks Hawk for the help!
> [Retribution Paladin] Indomitable Justice Module

- src/common/SPELLS/bfa/azeritetraits/paladin.js
Changed from "ïcon" to "icon". Now properly shows on Indomitable Justice module and Character page.
> [Retribution Paladin] Indomitable Justice Icon Fix

- src/parser/paladin/retribution/CHANGELOG.js
- src/parser/paladin/retribution/CONFIG.js
- src/parser/paladin/retribution/modules/talents/DivinePurpose.js
- Adds breakdown of what spells were used to consume the divine purpose proc similar to tooltip of judgment module.
- Adds a line in the tooltip displaying the largest chain of procs, if there were any
Kinda resolves #1508, though i think Zero intended it to be for Holy's Divine Purpose
> [Retribution] Updating Divine Purpose module

- src/parser/mage/arcane/CHANGELOG.js
- src/parser/mage/arcane/CONFIG.js
- src/parser/mage/fire/CHANGELOG.js
- src/parser/mage/fire/CONFIG.js
- src/parser/mage/frost/CHANGELOG.js
- src/parser/mage/frost/CONFIG.js
There were no changes to anything for mages in 8.1.5, so updating compat to 8.1.5
> [Mage] Updated Spec Compat to 8.1.5

- src/common/SPELLS/monk.js
- src/parser/monk/mistweaver/CHANGELOG.js
- src/parser/monk/mistweaver/modules/features/Abilities.js
- src/parser/monk/mistweaver/modules/features/Buffs.js
- src/parser/monk/mistweaver/modules/features/CooldownThroughputTracker.js
- src/parser/monk/mistweaver/modules/features/EvmVivCastRatio.js
- src/parser/monk/mistweaver/modules/features/StatValuesSpellInfo.js
- src/parser/monk/mistweaver/modules/spells/RenewingMist.js
- src/parser/monk/mistweaver/modules/spells/SoothingMist.js
This was to look over all the mw related constants/code to find and **destroy** any legion cobwebs which more or less happened but I also added SI to the buff timeline. It adds an event every ~30 seconds for people with SI but seeing what you cast in it is completely worth it imo (i double checked with voulk and a few others on this and the general idea was that it was fine). This clean up has also uncovered a big bug with how we track gusts of mist as we are on counting too much (i have seen as high as 200k healing more) which I have an idea but thought it would be idea to pus this clean up up first. Change log only denotes the SI change due to those being the only ones that effect end user; I can updated that to include cleaning out cobwebs if you wish.
> [MW] Clean up

- src/parser/monk/mistweaver/modules/features/Checklist/Component.js
- src/parser/monk/mistweaver/modules/spells/EnvelopingMists.js
- src/parser/monk/mistweaver/modules/spells/RenewingMist.js
- src/parser/monk/mistweaver/modules/spells/SoothingMist.js
- src/parser/monk/mistweaver/modules/spells/Vivify.js
- src/parser/monk/mistweaver/modules/talents/JadeSerpentStatue.js
- src/parser/monk/mistweaver/modules/talents/ManaTea.js
Should have broken up this into more pull requests most likely but shrug. Fixed mastery within 2ish% some fights its lower some its higher. Its a dirty fix but it works. The issue is that we can miss some casts and count some twice but we are always count the right number now. aka no more 2 env -> 8 gusts hit from env. It will always be 2 env -> 2-4 gusts procs depending on ef buff. This is a quick fix that works and could be slightly improved if you have a big brain idea. 
Most of the other things in here are removing old dead code/icon changes/tooltip changes
Didn't put anything in the change log as imo we don't want people to see we had issues before
> [MW] Mastery correction, small bugs

- src/parser/warrior/protection/CombatLogParser.js
- src/parser/warrior/protection/modules/talents/Bolster.js
Bolster and Shield Block both provide 100% block coverage, this tells you the number of times that you cast one of them while the other was active, and gives you the total time wasted with overlaps.
> [warrior][prot] Add tracker for Shield Blocka and Last Stand overlap while using Bolster

- src/parser/monk/mistweaver/CHANGELOG.js
- src/parser/monk/mistweaver/CONFIG.js
- src/parser/monk/mistweaver/modules/features/EssenceFontMastery.js
- src/parser/monk/mistweaver/modules/features/MasteryStats.js
- src/parser/monk/mistweaver/modules/spells/EnvelopingMists.js
- src/parser/monk/mistweaver/modules/spells/RenewingMist.js
- src/parser/monk/mistweaver/modules/spells/Vivify.js
Updated the other files to track their ef double splash healing and modified the donut chart to count it. From the logs I have tested we are nearly perfect. 
There appears to be some bad logic in EssenceFontMastery as it is counting the first and second gusts that procs off of it as its own healing. As well it seems we have set the suggestion thresh holds a bit too low depending if they take upwelling or not since upwelling doubles the amount of time they have and getting 2 casts off in 8 seconds seems like a given.
> [MW] Doughnut Update

- src/parser/shared/modules/items/bfa/FirstMatesSpyglass.js
- src/parser/shared/modules/items/bfa/GildedLoaFigurine.js
- src/parser/shared/modules/items/bfa/crafted/DarkmoonDeckBlockades.js
- src/parser/shared/modules/items/bfa/crafted/DarkmoonDeckTides.js
- src/parser/shared/modules/items/bfa/dungeons/AzerokksResonatingHeart.js
- src/parser/shared/modules/items/bfa/dungeons/MydasTalisman.js
- src/parser/shared/modules/items/bfa/dungeons/RevitalizingVoodooTotem.js
- src/parser/shared/modules/items/bfa/dungeons/RezansGleamingEye.js
- src/parser/shared/modules/items/bfa/dungeons/RotcrustedVoodooDoll.js
- src/parser/shared/modules/items/bfa/dungeons/Seabreeze.js
- src/parser/shared/modules/items/bfa/dungeons/VesselOfSkitteringShadows.js
- src/parser/shared/modules/items/bfa/enchants/CoastalSurge.js
- src/parser/shared/modules/items/bfa/enchants/Navigation.js
- src/parser/shared/modules/items/bfa/pvp/DreadGladiatorsBadge.js
- src/parser/shared/modules/items/bfa/pvp/DreadGladiatorsInsignia.js
Ran into a little bit of an issue with DMD Blockades and Navigation as I couldnt really figure out how to make the dropdown in the new <Statistic> stuff. But changing item to statistic without changing the StatisticBox worked and everything still works fine, so i think its still ok to use StatisticBox??
Towards #2939
There is about 12-13 left after this
> [Core] Replace item() with statistic() (Part 2)

- src/parser/hunter/marksmanship/CombatLogParser.js
- src/parser/hunter/marksmanship/modules/spells/Trueshot.js
- src/parser/hunter/marksmanship/modules/spells/azeritetraits/InTheRhythm.js
- src/parser/hunter/marksmanship/modules/spells/azeritetraits/UnerringVision.js
Removes some old information from Trueshot and adds a continous TODO to it until Blizzard a) updates tooltip or b) fixes the buggy Trueshot cooldown reduction. 
Adds the Unerring Vision Azerite Trait: 
Log: https://www.warcraftlogs.com/reports/47LJvZ9BgdhR8TXf#fight=43&type=summary&source=16
> [Hunter] Unerring Vision

- src/common/SPELLS/bfa/azeritetraits/hunter.js
- src/parser/hunter/marksmanship/CHANGELOG.js
- src/parser/hunter/marksmanship/CombatLogParser.js
- src/parser/hunter/marksmanship/modules/core/SpellUsable.js
- src/parser/hunter/marksmanship/modules/spells/azeritetraits/SurgingShots.js
Relies on #3087 because of moving Spell IDs around. 
Log: https://www.warcraftlogs.com/reports/y4HQqGk37WF1M2Dc#fight=18&type=summary&source=24
Source on the bugginess of this trait: https://github.com/simulationcraft/simc/blob/bfa-dev/engine/class_modules/sc_hunter.cpp#L2724
> [Hunter] Add Surging Shots Azerite Trait

- src/common/SPELLS/warlock.js
- src/parser/warlock/demonology/CombatLogParser.js
- src/parser/warlock/demonology/modules/pets/normalizers/PrepullPetNormalizer.js
- src/parser/warlock/demonology/modules/pets/normalizers/SummonOrderNormalizer.js
Some pet summons instantly trigger a cast(demonic consumption for example), these events are pushed before the actual summon, so the normalizer created fabricated summons, as they were already present when the boss was pulled.
My change will remove that extra summons.
Here is how it looks currently: https://www.wowanalyzer.com/report/XnMK8R3wq1NTQd7Y/22-Heroic+Mekkatorque+-+Kill+(5:23)/Gwelican/pet-timeline
> Fix prepull normalizer for demonology warlock

- src/parser/shared/modules/StatTracker.js
The seraphim buff was still set to 110 values for the stats. This fixes a fair few CD errors since Seraphim is a widely used talent.
> [Prot Pal] fixed seraphim stats

- src/parser/monk/brewmaster/CHANGELOG.js
- src/parser/monk/brewmaster/modules/features/MitigationSheet.js
I forgot to subtract off the value of the base 8% mastery provided by the passive itself. Since the value of mastery is not linear (it has slight DR since more mastery -> you get fewer stacks), this has a relatively large impact on the valuation.
Still better than everything else, but not quite as insane.
**Before**
**After**
> [BrM] fixed mastery's value in the mit sheet

- src/CHANGELOG.js
- src/parser/core/CASTABLE_WHILE_CASTING_SPELLS.js
- src/parser/shared/normalizers/CancelledCasts.js
There was a bug with the timeline where it would show a spell as cancelled if the player cast an ability that is castable while casting (Such as Shimmer, Fire Blast, Ice Floes, or Combustion). These spells do not interrupt spell casting and should not trigger marking an ability as cancelled.
Maybe there is a better way to resolve this, but i saw the CASTS_THAT_ARE_NOT_CASTS thing and just decided to replicate that since it was the easiest way to fix it.
> [Core] Fix for Cancelled Casts in Timeline

- src/CONTRIBUTORS.js
- src/common/SPELLS/bfa/azeritetraits/rogue.js
- src/common/SPELLS/rogue.js
- src/parser/rogue/outlaw/CONFIG.js
- src/parser/rogue/outlaw/CombatLogParser.js
- src/parser/rogue/outlaw/modules/Abilities.js
- src/parser/rogue/outlaw/modules/Buffs.js
- src/parser/rogue/outlaw/modules/core/ComboPoints.js
This is a few general changes to the spec. I added a couple of missing spells that were causing the Combo Point Usage and Energy Usage tabs to error. Did a pass on the abilities module to tweak/add some basic recommendations, and added a buffs module, basing it on other specs. Added a contributors entry for myself.
(Split 1 of 5 from my original: https://github.com/WoWAnalyzer/WoWAnalyzer/pull/3113)
> [Outlaw] Abilities, Buffs, and Spells updates

- src/parser/druid/balance/modules/features/EarlyDotRefreshes.js
- src/parser/druid/balance/modules/features/EarlyDotRefreshesInstants.js
- src/parser/rogue/assassination/CHANGELOG.js
- src/parser/rogue/assassination/CombatLogParser.js
- src/parser/rogue/assassination/modules/features/Checklist/Component.js
- src/parser/rogue/assassination/modules/features/Checklist/Module.js
- src/parser/rogue/assassination/modules/spells/EarlyDotRefresh.js
- src/parser/rogue/subtlety/modules/core/NightbladeEarlyRefresh.js
- src/parser/rogue/subtlety/modules/features/checklist/Component.js
- src/parser/shared/modules/earlydotrefreshes/EarlyDotRefreshes.js
- src/parser/shared/modules/earlydotrefreshes/EarlyDotRefreshesInstants.js
- src/parser/shared/modules/earlydotrefreshes/EarlyDotRefreshesInstantsSuggestion.js
- src/parser/shared/modules/earlydotrefreshes/EarlyDotRefreshesSuggestion.js
- src/parser/shared/modules/earlydotrefreshes/EarlyDotRefreshesSuggestionByCount.js
Adds early refresh logic for assassination, and fixes a bug in balance druid dots. 
Did not update Balance druid all the way to use effective refresh calculation, because I don't really know if calculating by effective duration instead of share of bad casts would be correct.
I think it is applicable in full to Stellar Flare, but maybe not to the instant casts. At least they might need a more advanced logic to calculate the effective duration.
Timeline (only for the default message):
Assa checklist:
Assa suggestion:
> [Assa Rogue] Check for early refresh of dots.

- src/parser/priest/holy/modules/spells/GuardianSpirit.js
- src/parser/priest/holy/modules/spells/HymnBuffBenefit.js
Currently the Divine Hymn and Guardian Spirit components count every Divine Hymn and Guardian Spirit cast from every priest as part of the calculations. This fix makes it to it only counts the selected priests casts.
> [Hpriest] Bug: Fixing Hymn and GS filters

- src/parser/monk/brewmaster/modules/constants/AbilityBlacklist.js
Includes spells for BoD and CoS. In case anyone's forgotten: this is mostly used to blacklist dots that can't be effectively mitigated with Ironskin Brew but also produce a LOT of hits that skew hit tracking. The worst offender this tier is Jaina, with Chilling Touch frequently being 3-5x as many hits as Ice Shard.
> [BrM] (finally) updated mitigation blacklist for ISB hit tracking

- src/CHANGELOG.js
- src/parser/mage/fire/__snapshots__/CombatLogParser.test.js.snap
- src/parser/shared/modules/CancelledCasts.js
- src/parser/shared/normalizers/CancelledCasts.js
One of the contributors in the Mage Discord brought up an issue for Fire Mages where the Cancelled Casts stat box and the timeline would incorrectly mark a spell as cancelled.
Some background, Fire Mage has a proc called Hot Streak that makes your next Pyroblast instant cast. You get Hot Streak by getting two critical strikes in a row with a direct damage ability (Like Fireball, Fire Blast, Scorch, Pyroblast, etc). Additionally, abilities like Fire Blast and Phoenix Flames are guaranteed to crit, and with a talent Scorch is guaranteed to crit under 30% health. So you can predict when you will gain Hot Streak because you know that the Fire Blast will give you your second crit and give you Hot Streak.
So it is common for Fire Mages to be casting a spell, hit Fire Blast mid cast to get their …
> [Core] Fix for Cancelled Casts (Statistic and Timeline)

- src/parser/core/Entity.js
- src/parser/shared/modules/items/bfa/enchants/Navigation.js
- src/parser/shared/modules/items/bfa/raids/crucibleofstorms/TridentOfDeepOcean.js
#3123 
Separated weighted stacked buff uptimes, which already existed on the Entity, into two functions: one that fulfills the same function as before, one that just returns the uptimes of each stack amount in order to centralize tracking for both weighted stacks as well as uptimes.
new functions:
Entity.getStackBuffUptimes(spellId, sourceID = null): returns an objects containing the amount of time the specified spell was active per stack across the entire fight.
Example log for outputs / to compare old version with rework: https://www.warcraftlogs.com/reports/6xHLtAFW4yC73mRD/#fight=28&source=2
Updated both the Navigation Enchants as well as the Trident of Deep Ocean to utilize this new function instead of their copy-pasted code. I couldn't find any other places in the code that used …
> Stack uptime calculation moved to central location (entity)

- src/common/ITEMS/bfa/raids/crucibleofstorms/index.js
- src/common/SPELLS/bfa/raids/crucibleofstorms/items.js
- src/parser/core/CombatLogParser.js
- src/parser/shared/modules/items/bfa/raids/crucibleofstorms/StormglideSteps.js
Requires https://github.com/WoWAnalyzer/WoWAnalyzer/pull/3137 to be merged first as it utilizes its new stack uptime calculation, do not merge beforehand. I just created this PR already so its functionality can be reviewed.
Adds the leather boots "Stormglide Steps" from crucible of storms.
Example log: https://www.warcraftlogs.com/reports/RDHTGY68yPQ3WJ9r#fight=28source=14
Box:
Tooltip:
> Stormglide steps [don't merge yet]

- src/parser/paladin/protection/CHANGELOG.js
- src/parser/paladin/protection/modules/features/SpellUsable.js
Crusader's Judgment gives the Judgment ability a 2nd charge and causes it to be reset by Grand Crusader procs. When implementing support for this, I copied from the implementation for Avenger's Shield, which used `this.isOnCooldown` to check for when the cooldown should get reset (the proc doesn't normally appear in logs).
However, `this.isOnCooldown` returns `true` if only 1 of 2 charges is on cooldown. This PR changes it to use `this.isAvailable` instead, which only returns `false` if both charges are on CD. The result is a pretty substantial drop in missed judgment casts across all logs using CJ (which is by far the most common talent to use on every fight).
> [Prot Pal] Fixed Judgment being reset too often with the CJ talent

- src/common/ITEMS/bfa/raids/crucibleofstorms/index.js
- src/common/SPELLS/bfa/raids/crucibleofstorms/index.js
- src/common/SPELLS/bfa/raids/crucibleofstorms/items.js
- src/common/SPELLS/bfa/raids/crucibleofstorms/mechanics.js
Added the IDs for the on use / equip items from crucible of storms as well as all the spell IDs I could find with the use of public logs. I haven't found logs for every single item so those spell IDs might be incorrect, it is noted where appropriate. This pull request is meant as a baseline for adding statistics boxes for these items in future PRs, which I've been slowly working on one item at a time
Example logs the IDs are extracted from (where I could find logs), I'll update these (as well as relevant spell IDs) as I find more logs:
Abyssal Speaker's Gauntlets: https://www.warcraftlogs.com/reports/7bfnQGY8cKpT94RA#fight=11&source=18&translate=true
Fathom Dredgers: https://www.warcraftlogs.com/reports/vZQfwra1xVK76M4L/#fight=13&source=6
Fathuuls Floodguards: …
> added item and spell IDs for most crucible items

- src/parser/monk/brewmaster/modules/constants/AbilityBlacklist.js
Frozen Solid ticks (from being stuck in an ice block) skew otherwise useful info if the brewmaster gets frozen for long enough for mitigation to drop.
> Add Jaina's Frozen Solid to mitigation blacklist

- src/parser/core/Entity.js
#3123 
Fixed an issue with the buff uptime returning "NaN" for a stack the the fight "ends on" if that stack has never been seen before
> Buff Uptime Bugfix

- src/interface/report/PlayerLoader.js
specifically: if a player combatant is in the log, but not in the
report.friendlies list, the player selection screen would crash. this
fixes it
see log warcraftlogs.com/reports/HF93kqPQMDhx6Bbg#fight=1 for an example of the issue
> fix crash in player loader when a friendly is missing

- src/common/SPELLS/bfa/raids/crucibleofstorms/items.js
- src/parser/core/CombatLogParser.js
- src/parser/shared/modules/items/bfa/raids/crucibleofstorms/LurkersInsidiousGift.js
Adds the Agi DPS trinket "Lurker's Insidious Gift" from Crucible of Storms, including a wasted stack suggestion.
Example logs: 
https://www.warcraftlogs.com/reports/vZQfwra1xVK76M4L/#fight=13&source=17
https://www.warcraftlogs.com/reports/vZQfwra1xVK76M4L/#fight=13&source=1
Suggestion:
> added lurker's insidious gift

- src/parser/druid/restoration/CHANGELOG.js
- src/parser/druid/restoration/modules/items/azeritetraits/LivelySpirit.js
Fixed a bug where Lively Spirit increased int gain on tab switch.
> Lively spirit tab switch fix

- src/parser/monk/brewmaster/modules/spells/PurifyingBrew.js
Now looks like this
Previously had the HTML tags printed in the tooltip
> [BrM] fixed purify timeline inefficient cast tooltip

- src/parser/druid/restoration/CHANGELOG.js
- src/parser/druid/restoration/modules/features/StatWeights.js
- src/parser/paladin/holy/CHANGELOG.js
- src/parser/paladin/holy/modules/StatValues.js
- src/parser/shared/modules/features/BaseHealerStatValues.js
As of Voulk's request I have enabled the QElive auto import stat Value link for resto druid and holy pally. He is planning to enable it for the last 3 healers (holy priest, resto shamie, and disc priest) but as of right now they are not 100% ready.
> QELive button

- src/parser/core/CombatLogParser.js
- src/parser/shared/modules/items/bfa/raids/crucibleofstorms/LegplatesOfUnboundAnguish.js
Adds the plate legs "legplates of unbound anguish"
Example log: https://www.warcraftlogs.com/reports/dFc9GAjyvK2MCxJ1#fight=10&source=6
> Added legplates of unbound anguish

- src/parser/core/CombatLogParser.js
- src/parser/shared/modules/items/bfa/raids/crucibleofstorms/GripsOfForsakenSanity.js
Adds the mail hands "grips of forsaken sanity" from crucible of storms
Example log: https://www.warcraftlogs.com/reports/K8ZDQLNhJGwBqWjC#fight=17&source=10
> Grips of forsaken sanity

- src/common/SPELLS/bfa/raids/crucibleofstorms/items.js
- src/parser/core/CombatLogParser.js
- src/parser/shared/modules/items/bfa/raids/crucibleofstorms/IdolOfIndiscriminateConsumption.js
Added the tank trinket "idol of indiscriminate consumption" from crucible of storms
Example log: https://www.warcraftlogs.com/reports/D4LF8KhaAmBJ6T7x#fight=13&source=5
> Added Idol of Indiscriminate Consumption

- src/parser/core/CombatLogParser.js
- src/parser/shared/modules/items/bfa/raids/crucibleofstorms/FathuulsFloodguards.js
Adds mail legs Fa'thuul's Floodguards from crucible of storms
Example log: https://www.warcraftlogs.com/reports/Px9pcQwt3rFXjDn7#fight=24&source=186
> Fa'thuul's floodguards

- src/CHANGELOG.js
- src/parser/core/CombatLogParser.js
- src/parser/shared/modules/items/bfa/dungeons/IgnitionMagesFuse.js
- src/parser/shared/normalizers/MissingCasts.js
Some items that provide buffs do not produce associated cast events for using the item (see Ignition Mage's Fuse for example), leading to them having to manually track uses for e.g. the usage statistic.
This PR adds a normalizer that fabricates cast events when the buffs given are applied.
Currently only contains the Ignition Mage's fuse (as this is where the cast being missing was noticed), but obviously provides an easy way to add further items to it.
> Add normalizer for buffs that are missing cast events

- src/parser/shared/modules/items/bfa/raids/bod/CrestOfPaku.js
Crest of paku was displaying haste for both haste and speed, fixed the speed display to actually display speed.
> Fixed crest of paku display

- src/parser/core/CombatLogParser.js
- src/parser/shared/modules/items/bfa/raids/crucibleofstorms/MalformedHeraldsLegwraps.js
Adds the cloth legs "Malformed Herald's Legwraps" from crucible of storms
Includes suggestions for lack of usage as well as dropping the buff early
Example log: https://www.warcraftlogs.com/reports/GD6xT8JwbzHqYF3j#fight=22&source=33
> added malformed herald's legwraps

- src/parser/monk/brewmaster/modules/spells/GiftOfTheOx.js
- src/parser/shared/modules/throughput/HealingDone.js
Fixed 2 slight formatting issues I happened to notice while analyzing a log last night.
First issue: "$" being displayed here
Second issue: no space or newline after first sentence
> fixed 2 minor formatting issues

- src/parser/druid/feral/CHANGELOG.js
- src/parser/druid/feral/CombatLogParser.js
- src/parser/druid/feral/modules/Abilities.js
- src/parser/druid/feral/modules/Buffs.js
Replaces the old `buffSpellId` properties within `Abilities.js`, instead creating a `Buffs.js` for the Feral spec. This also makes the timeline view for Feral show information that's more consequential to the spec.
Timeline before:
Timeline after:
> [Feral] Separate out buffs

- src/common/SPELLS/druid.js
The SpellId used to report energy gains from Feral's talent Soul of the Forest was missing from druid's `SPELLS`.
Before:
After:
> [Feral] [Minor] Add SotF energy generator

- src/parser/rogue/outlaw/modules/spells/RollTheBonesEfficiency.js
Previous way was counting all casts made instead of rerolling, when it should have been counting how many of the rolls were delayed. The fix is to mark the cast objects with a flag that can be counted, instead of a separate counter variable.
> [Outlaw] Fixing a bug with the low value RTB suggestion

- src/parser/druid/feral/CHANGELOG.js
- src/parser/druid/feral/CombatLogParser.js
- src/parser/druid/feral/modules/bleeds/RakeSnapshot.js
- src/parser/druid/feral/modules/bleeds/RipSnapshot.js
- src/parser/druid/feral/modules/combopoints/ComboPointDetails.js
- src/parser/druid/feral/modules/combopoints/FinisherUse.js
- src/parser/druid/feral/modules/core/Snapshot.js
- src/parser/druid/feral/modules/features/checklist/Component.js
- src/parser/druid/feral/modules/features/checklist/Module.js
- src/parser/druid/feral/modules/spells/TigersFuryEnergy.js
- src/parser/druid/feral/modules/talents/MoonfireSnapshot.js
- src/parser/druid/feral/normalizers/BleedDebuffEvents.js
- src/parser/druid/feral/normalizers/BleedDebuffEvents.test.js
- src/parser/druid/feral/normalizers/RakeBleed.js
Previously combo use was analysed by just counting how many casts were at full and not-full combo points. That would incorrectly consider the standard (and highest DPS) opener as including a mistake when the player uses Rip without full combo points.
Now each time a finisher is used the `FinisherUse` module will determine if it was a good use or not. Most finishers should still always be used at full combo points but the exceptions for Rip are handled. If Rip is applied to a target that doesn't yet have the debuff, that's correct play even with very low combo points. Just getting the DoT ticking is a damage increase over waiting for full combo points. Similarly upgrading the snapshot damage of an existing Rip depends only on the buffs active and not on combo points, so a low combo point …
> [Feral] Improve tracking of finisher combo use

- src/parser/druid/feral/modules/bleeds/RipSnapshot.js
- src/parser/druid/feral/modules/combopoints/FinisherUse.js
- src/parser/druid/feral/modules/core/getComboPointsFromEvent.js
Example log that would cause the error:
`/report/68ntwpRPLYCqfzyQ/17-Heroic+Opulence+-+Kill+(8:07)/Morghan/events`
The cast event for an ability that uses combo points will not report that it uses combo points if the ability was parried or otherwise failed to hit, which was leading to a null object reference. Fixing the bug revealed a repeated function so corrected the function and have the two modules import it instead of duplicating it.
> [Feral] Fix null reference error

- src/parser/druid/feral/modules/combopoints/FinisherUse.js
- src/parser/druid/feral/modules/core/Snapshot.js
- src/parser/druid/feral/normalizers/BleedDebuffEvents.js
Small fix for a possible null reference. As well as checking for the null reference also fixes the cause of the null object. It was due to a greater than 100ms timestamp difference between an ability's cast and debuff events.
Log which caused an error:
`report/1wWP8749VFN6Z2xA/3-Heroic+Conclave+of+the+Chosen+-+Kill+(6:10)/Cajotan`
> [Feral] FinisherUse null reference fix

- src/parser/shared/modules/items/bfa/raids/crucibleofstorms/VoidStone.js
fixes https://wowanalyzer.com/report/7c8zdHXYtRrDVvpA/3-Mythic+Conclave+of+the+Chosen+-+Kill+(5:39)/Gospi
crash caused by player casting void stone on a totem instead of a player
> fix crash if no player targetted with void stone

- src/parser/monk/mistweaver/modules/spells/ThunderFocusTea.js
If you tft rsk in wotc its not counted against you (as it shouldn't)
> [MW] TFT updates for wotc

- src/common/SPELLS/monk.js
- src/parser/monk/brewmaster/CHANGELOG.js
- src/parser/monk/brewmaster/CombatLogParser.js
- src/parser/monk/brewmaster/__snapshots__/CombatLogParser.test.js.snap
- src/parser/monk/brewmaster/modules/features/AgilityValue.js
- src/parser/monk/brewmaster/modules/features/HotTrubTimeMachine.js
- src/parser/monk/brewmaster/modules/features/HotTrubValue.js
Shows an estimate of the damage the Hot Trub PvP talent would do if you'd used the Conflict & Strife essence. Hot Trub deals damage equal to 20% of purified damage, up to a maximum of 20% of your max HP per cast.
Hot Trub is not usable in PvE content *yet* so this lets us get an idea for how much damage it does in current content.
(screenshot looks mega large for some reason, not sure why)
> [BrM] Hot Trub Damage Estimator

- src/parser/monk/brewmaster/CombatLogParser.js
- src/parser/monk/brewmaster/__snapshots__/CombatLogParser.test.js.snap
- src/parser/monk/brewmaster/modules/features/CritValue.js
- src/parser/monk/brewmaster/modules/features/MitigationSheet.js
- src/parser/monk/brewmaster/modules/features/VersatilityValue.js
- src/parser/monk/brewmaster/modules/spells/CelestialFortune.js
Follow-up from #3121, covering Versatility and Critical Strike.
Currently some minor code-smell with Armor's mitigation being added to events as the field `_mitigated`. Since mitigation is multiplicative, you have to track mitigation across sources, which means either doing it all in one place or tracking what has already been mitigated.
> More BrM Sheet cleanup

- src/parser/monk/mistweaver/CHANGELOG.js
- src/parser/monk/mistweaver/modules/talents/ManaTea.js
If you didn't have mana tea as a talent this map would never get made so while going through suggestion threshholds it would go into "RenewingMistDurationManaTea" which depends on mana tea's cast variable to not be null
This is strange because both modules are disabled but w/e I fixed it
> SUPER IMPORT Bug Fix

- src/parser/priest/discipline/CHANGELOG.js
- src/parser/priest/discipline/normalizers/PowerWordRadianceNormalizer.js
There used to be a problem where if you cast evangelism immediately after PW:R, the evangelism module wouldn't pick up on those last 5 atonements that PW:R applied, so the atonement count & healing contribution would be way off. It was fixed at one point back during legion, but seems to be broken again. This PR reorders the events correctly and resolves the issue.
Before:
After:
Example Log: https://wowanalyzer.com/report/W1THLf49pP2m3jtx/3-Mythic+Abyssal+Commander+Sivara+-+Kill+(5:32)/Xaph/statistics
> [DPriest] Bug: Fixing PW:Radiance Evangelism overlap

- src/CHANGELOG.js
- src/parser/shared/modules/spells/bfa/essences/TheEverRisingTide.js
Fixed ERT haste calculation, error was that I expected `array.findIndex` to return `null` if it doesn't find an Index while its actually returning `-1`.
https://www.warcraftlogs.com/reports/vNQyRq6Zbpmgjh4A/#fight=14&source=7
> Ever Rising Tide haste

- src/parser/monk/mistweaver/CHANGELOG.js
- src/parser/monk/mistweaver/modules/spells/azeritetraits/FontOfLife.js
- src/parser/monk/mistweaver/modules/spells/azeritetraits/UpliftedSpirits.js
- src/parser/shared/modules/helpers/CalculateTraitHealing.js
Fights with healing increases or decreases break the mistweaver azerite calculations, as those effects are not accounted for. Since its not realistic to account for all those effects, I changed the calculation around based on my [Resto Shaman azerite](https://github.com/WoWAnalyzer/WoWAnalyzer/blob/master/src/parser/shaman/restoration/modules/azerite/BaseHealerAzerite.js#L63) approach which is unaffected by any outside factors.
Example of a log with lots of healing decreases: https://www.warcraftlogs.com/reports/yFpzQTVCZ9Ht27ba#fight=1&type=healing
fixed
> [Mistweaver] Trait calculation fix

- src/CHANGELOG.js
- src/interface/report/Results/DegradedExperience.js
- src/interface/report/Results/index.js
- src/parser/core/CombatLogParser.js
- src/parser/core/MODULE_ERROR.js
- src/parser/core/modules/EventEmitter.js
#2174 
Adds a warning about a degraded experience if a module is disabled during loading. Also disables any modules depending on this module. Catches errors during initialization of modules (during constructor), event handling, as well as result generation (and new types can be added easily). Outside of production these errors don't get suppressed / modules stay enabled and throw their errors to allow debugging during development.
> Degraded experience toaster

- src/CHANGELOG.js
- src/interface/report/Results/DegradedExperience.js
- src/parser/core/CombatLogParser.js
- src/parser/core/modules/EventEmitter.js
Keeps track of each module's "desired name" so in minified production code, error messages still appear correct.
> Keep track of module names for errors in production

- src/parser/druid/feral/CHANGELOG.js
- src/parser/druid/feral/modules/Buffs.js
Feral's `Buffs` was missing the `triggeredBySpellId` properties needed by the `PrePullCooldowns` normalizer, so cast efficiency wasn't accounting for pre-pull uses of Berserk and Tiger's Fury.
Example log with pre-pull cooldown use:
`report/T4LvfdbKAFPkVQ7Z/1-Mythic+Abyssal+Commander+Sivara+-+Kill+(4:14)/Sxqkitty/`
> [Feral] Fix prepull cooldowns

- src/CHANGELOG.js
- src/common/fabricateBossPhaseEvents.js
the extraAbility check used in interrupts crashes the filter if no extraAbility exists, meaning if 2 different phases use regular cast events, this crashes. Fix checks for extraAbility to be present before comparing guid
> Fix for phase filter crashing if multiple casts get listed

- src/CONTRIBUTORS.js
- src/parser/shaman/elemental/CHANGELOG.js
- src/parser/shaman/elemental/modules/core/FlameShock.js
8.1 introduced an undocumented change so that lava burst checks if the target has flame shock on damage instead of cast to guarantee the crit.
@HawkCorrigan
> lava burst check's for flame shock on damage instead of on cast

- src/common/SPELLS/bfa/azeritetraits/druid.js
- src/parser/druid/balance/CHANGELOG.js
- src/parser/druid/balance/modules/talents/azeritetraits/StreakingStars.js
Damage calculations were naively done by multiplying occurences by amount of
damage the trait gives. This does not take into consideration absorb
shields, crits, damage boosts, ... etc. Now using the ability tracker to
get the correct values (which now also perfectly match the WCL logs
unlike before)
@Gebuz
> Fix damage calculation for Streaking Stars.

- src/parser/mage/fire/CHANGELOG.js
- src/parser/mage/fire/modules/Checklist/Component.js
- src/parser/mage/fire/modules/features/CombustionFirestarter.js
Fixed a couple bugs
1. The Pyroclasm checklist item was showing up without Pyroclasm talented
2. Combustion during Firestarter was checking every cast during Combustion instead of just the first one, which meant if the target switched targets during Combustion, it would mark them as casting Combustion during Firestarter
> [Fire Mage] Bug Fixes

- src/common/SPELLS/bfa/azeritetraits/priest.js
- src/parser/priest/shadow/CHANGELOG.js
- src/parser/priest/shadow/CombatLogParser.js
- src/parser/priest/shadow/modules/spells/azeritetraits/WhispersOfTheDamned.js
- Tracks additional damage gained
- Tracks additional insanity generated from critical strikes
On the checklist of #2612
> [Shadow Priest] Add Whispers of the Damned azerite trait

- src/parser/druid/restoration/CHANGELOG.js
- src/parser/druid/restoration/modules/Abilities.js
A few abilities associated with a druid's animal forms had their GCD incorrectly set. The main correction is that the cat abilities always have a 1.00 second GCD regardless of haste (just like Feral or Rogue abilities.) Dash/Tiger Dash also have an unusual effect where they only trigger the GCD (which for some reason also isn't affected by haste) if used when outside of cat form.
Top line is before, bottom is after these changes.
> [Resto Druid] Correct catweaving GCDs

- src/CHANGELOG.js
- src/interface/others/DeathRecap.js
- src/interface/others/DeathRecapTracker.js
- src/interface/report/EventParser.js
- src/interface/report/index.js
- src/parser/core/CombatLogParser.js
idea by @abelito75 
Adds a button to the death recap that lets you filter the events to only include events prior to the death  to make suggestions / analysis more accurate using the existing time filtering functionality. In the case of multiple deaths it filters events to the time between the deaths.
Also attaches the filtering functionality (both time and phase based) to the combatlogparser object so other modules can make use of this functionality
Examples:
> Add timefilter shortcut to Death Recap

- src/parser/mage/fire/CHANGELOG.js
- src/parser/mage/fire/modules/features/CombustionFirestarter.js
- src/parser/mage/fire/modules/features/HeatingUp.js
- src/parser/mage/fire/modules/features/HotStreakPreCasts.js
- src/parser/mage/fire/modules/features/SearingTouch.js
Fixes a bug for Lady Ashvane where the boss health was not being calculated correctly because the hitPoints and maxHitPoints values were missing on damage events when Ashvane has the Carapace up.
> [Fire Mage] Health Calculation Fixes

- src/common/SPELLS/bfa/azeritetraits/priest.js
- src/parser/priest/shadow/CHANGELOG.js
- src/parser/priest/shadow/CombatLogParser.js
- src/parser/priest/shadow/modules/spells/azeritetraits/SpitefulApparitions.js
- Tracks additional damage from Spiteful Apparitions done by Shadowy Apparitions to targets with Vampiric Touch
Completes part of #2612
> [Shadow Priest] Add Spiteful Apparitions azerite trait

- src/CHANGELOG.js
- src/common/SPELLS/bfa/essences/essences.js
- src/parser/mage/fire/CHANGELOG.js
- src/parser/mage/fire/CombatLogParser.js
- src/parser/mage/fire/__snapshots__/CombatLogParser.test.js.snap
- src/parser/mage/fire/modules/features/Abilities.js
- src/parser/mage/fire/modules/items/HyperthreadWristwraps.js
- src/parser/mage/fire/modules/items/LucidDreams.js
- src/parser/shared/modules/Haste.js
Adds Fire Mage support for Lucid Dreams Major and Minor
Adds Spell IDs for Condensed Life Force
Adds the stacking Haste buff from Condensed Life Force
Adjusted Hyperthread Wristwraps to give double the reduction during Lucid Dreams to compensate for the doubled cool down regen from Lucid.
> [Fire Mage] Lucid Dreams Support & CLF Haste Buff

- src/common/SPELLS/bfa/essences/essences.js
- src/parser/warrior/protection/CHANGELOG.js
- src/parser/warrior/protection/CombatLogParser.js
- src/parser/warrior/protection/modules/Abilities.js
- src/parser/warrior/protection/modules/features/Checklist/Component.js
- src/parser/warrior/protection/modules/features/Checklist/Module.js
- src/parser/warrior/protection/modules/talents/AngerCD.js
Added custom cd calculators so angermanagement doesn't show crazy things like 150% cast rate of avatar
Checklist clean up is for anger management and deleting the generic cast efficient suggestions so we don't double post.
Visions minor for rage shows up and Unknown spell. now it doesn't
example log
https://wowanalyzer.com/report/YTkJCPQ9cVKHMvaq/24-Normal+Orgozoa+-+Kill+(6:30)/Istenn/rage-usage
> [Prot warrior] AngerManagement + checklist clean up + visions minor for rage

- src/CHANGELOG.js
- src/interface/others/Cooldown.js
> Absorbed damage now included in damage calculations for cooldown tabs

- src/CONTRIBUTORS.js
- src/common/SPELLS/shaman.js
- src/parser/shaman/elemental/CHANGELOG.js
- src/parser/shaman/elemental/CombatLogParser.js
- src/parser/shaman/elemental/modules/Buffs.js
- src/parser/shaman/elemental/modules/talents/SurgeOfPower.js
This is kind of a rough implementation but it works locally with my character. There might be nicer ways of doing what I did. I used the Master of the Elements implementation as a guide.
This PR adds a Statistic object that shows the amount of cooldown reduction for fire ele by default. There is also a dropdown with a table that shows a breakdown of all SoP empowered casts.
https://i.imgur.com/xb6gC2N.png
It also adds an object to the Suggestions view that tracks the amount of SoP empowered stormkeepers.
https://i.imgur.com/chNK4kt.png
> Initial Surge of Power talent support for Elemental Shamans

- src/CHANGELOG.js
- src/common/SPELLS/monk.js
- src/parser/shared/modules/DispelTracker.js
Added a blacklist to Dispel Tracker so we can easily add spells we don't want listed
This currently only has Windwalking which is a friendly aura that ww give off no matter what. 
It can be `Dispelled` by warrior but instantly given it again. This is pointless and should be caught as it provides 0 useful data
> [Core] Dispel Tracker BlackList added

- src/CHANGELOG.js
- src/parser/shared/modules/CastEfficiency.js
fix #3309 
Issue was caused by https://github.com/WoWAnalyzer/WoWAnalyzer/commit/6d2863ff363cbc9ec8e94c896c571d2ae326c5d5#diff-fee0b230fde9d0291b998680603642deR98 doubling the time calculation for every spell that has actual cast events. I looked at the Mistweaver module to make sure that this commit didn't break it again, but without knowing what spell this was implemented for its hard to fully verify.
Before the change
After (increased are spells that have cast events, as the time spent casting is now correct)
> [Core] Time spent casting fix for Mana Efficiency module

- src/CHANGELOG.js
- src/parser/shared/modules/items/bfa/enchants/ForceMultiplier.js
It was crashing because the STAT module uses `criticalstrike` while the `StatTracker` module uses `crit`. :skull:
> fixed bug with Force Mult and crit

- src/parser/mage/fire/CHANGELOG.js
- src/parser/mage/fire/__snapshots__/CombatLogParser.test.js.snap
- src/parser/mage/fire/modules/features/Meteor.js
Meteor was using the wrong Spell ID when looking for the Rune of Power Buff so it was always saying that they cast Meteor during Rune of Power when they really didnt.
> [Fire Mage] Bug Fix for Meteor

- src/parser/warrior/protection/CHANGELOG.js
- src/parser/warrior/protection/modules/features/BlockCheck.js
- src/parser/warrior/protection/modules/spells/ShieldBlock.js
Now only checks blockable hits (retroactive)
Before:
After:
This will drop the stat a little bit but make it more accurate because before it only checked if it was physical and you had a block spell up so things that were aoe that were not blockable but happened while you had Shield block up counted as a good thing even thought it didn't matter
> [Prot Warrior] Block Checker Update

- src/parser/mage/arcane/CHANGELOG.js
- src/parser/mage/arcane/CONFIG.js
- src/parser/mage/fire/CHANGELOG.js
- src/parser/mage/fire/CONFIG.js
- src/parser/mage/frost/CHANGELOG.js
- src/parser/mage/frost/CONFIG.js
No changes for mages in 8.2.5, updating compatability to 8.2.5
> [Mage] Update Spec Combatability to 8.2.5

- src/parser/monk/windwalker/CHANGELOG.js
- src/parser/monk/windwalker/modules/features/AlwaysBeCasting.js
- src/parser/monk/windwalker/modules/spells/FistsofFury.js
Always Be Casting is mostly the same, just updated to use suggestions the new way.
Fists of Fury now has lower suggestion thresholds when using Cyclotronic since it's common to cancel Fists of Fury for bigger burst when using it.
> [Windwalker] Update Fists of Fury and ABC

- src/parser/monk/mistweaver/CHANGELOG.js
- src/parser/monk/mistweaver/modules/talents/Lifecycles.js
Small bug fix to remove excess mana saved from the calculation when a TFT empowered Vivify is cast with the Lifecycles buff.
> [MW] Lifecycles Bug Fix - Vivify

- src/parser/mage/arcane/CHANGELOG.js
- src/parser/mage/arcane/__snapshots__/CombatLogParser.test.js.snap
- src/parser/mage/arcane/modules/Checklist/Component.js
- src/parser/mage/arcane/modules/Checklist/Module.js
- src/parser/mage/arcane/modules/features/ArcanePower.js
SpellUsable is reporting that Arcane Power is off CD and available to be cast at the end of the fight when it 100% is not. Removing the check until i figure out why it thinks it is off CD.
> [Arcane Mage] Remove AP Check on Fight End

- src/CHANGELOG.js
- src/parser/deathknight/blood/__snapshots__/CombatLogParser.test.js.snap
- src/parser/mage/arcane/__snapshots__/CombatLogParser.test.js.snap
- src/parser/mage/fire/__snapshots__/CombatLogParser.test.js.snap
- src/parser/mage/frost/__snapshots__/CombatLogParser.test.js.snap
- src/parser/monk/brewmaster/__snapshots__/CombatLogParser.test.js.snap
- src/parser/paladin/holy/__snapshots__/CombatLogParser.test.js.snap
- src/parser/paladin/protection/__snapshots__/CombatLogParser.test.js.snap
- src/parser/shared/modules/CastEfficiency.js
Cast Efficiency was showing > 100% for the Time on Cooldown for a lot of spells.
This was because when calculating the Time on CD, it was essentially doing (SpellCooldown * SpellCasts / FightDuration).
So the remaining cooldown of the spell beyond the end of the fight was counting towards the time on cooldown.
In the above example, Combustion was cast 3 times (120 second cooldown each) and the fight was 299 seconds long. 
So it was doing 360/299= 120%
Instead it should have been 2 casts for 120s each and a third for 33s to total 273/299
I am not sure if this is the best way to fix it or not, but its the only way i could make it work.
> [Core] Cast Efficiency Fix

- src/CONTRIBUTORS.js
- src/parser/druid/restoration/CHANGELOG.js
- src/parser/druid/restoration/CONFIG.js
No spec changes have occurred, the restoration druid module is compatible with patch 8.2.5.
> [RDruid] patch update

- src/parser/monk/mistweaver/CHANGELOG.js
- src/parser/monk/mistweaver/modules/spells/SpinningCraneKick.js
The enemiesHitSCK array needs to be initialized to avoid checking if an enemy exists on an undefined variable when it expects an array. 
`TypeError: Cannot read property 'includes' of undefined`
An example of this error can be seen in this log: https://wowanalyzer.com/report/dtPChJZjHQwpYxrn/35-Mythic+Za%27qul+-+Wipe+6+(7:01)/15-Monclear
> [MW] Bugfix SCK

- src/CHANGELOG.js
- src/parser/deathknight/blood/__snapshots__/CombatLogParser.test.js.snap
- src/parser/mage/arcane/__snapshots__/CombatLogParser.test.js.snap
- src/parser/mage/fire/__snapshots__/CombatLogParser.test.js.snap
- src/parser/mage/frost/__snapshots__/CombatLogParser.test.js.snap
- src/parser/monk/brewmaster/__snapshots__/CombatLogParser.test.js.snap
- src/parser/paladin/holy/__snapshots__/CombatLogParser.test.js.snap
- src/parser/paladin/protection/__snapshots__/CombatLogParser.test.js.snap
- src/parser/shared/modules/CastEfficiency.js
Cast Efficiency was showing > 100% for the Time on Cooldown for a lot of spells.
This was because when calculating the Time on CD, it was essentially doing (SpellCooldown * SpellCasts / FightDuration).
So the remaining cooldown of the spell beyond the end of the fight was counting towards the time on cooldown.
In the above example, Combustion was cast 3 times (120 second cooldown each) and the fight was 299 seconds long. 
So it was doing 360/299= 120%
Instead it should have been 2 casts for 120s each and a third for 33s to total 273/299
I am not sure if this is the best way to fix it or not, but its the only way i could make it work.
> [Core] Cast Efficiency Fix (Attempt 2)

- src/parser/monk/mistweaver/CHANGELOG.js
- src/parser/monk/mistweaver/modules/talents/Tier45Comparison.js
Slightly logical error where it would effect ALL casts not the correct casts and this leads to incorrect results leading to wowA suggesting bad talents.
> [MW] Tier45 fixes

- src/CHANGELOG.js
- src/interface/report/Results/Character/PlayerInfo/Essence.js
Fixes #3366
There was a problem with the character tab logs pre 8.2. Low priority fix.
> fix character tab for old logs without essences

- src/parser/shaman/elemental/CHANGELOG.js
- src/parser/shaman/elemental/CombatLogParser.js
- src/parser/shaman/elemental/modules/checklist/Component.js
- src/parser/shaman/elemental/modules/checklist/Module.js
- src/parser/shaman/elemental/modules/talents/Icefury.js
Icefury is currently one of the most popular ele shaman talents at the moment and a lot of players will struggle to actually fully utilize it by using all of the charges before it expires because of how tight it can be to use them all especially when it sync with Stormkeeper (which is often). Many players will try to over optimize with Master of the Elements and ultimately cost themselves DPS.
> Add Icefury Efficiency checklist item and suggestion

- src/parser/shaman/elemental/CHANGELOG.js
- src/parser/shaman/elemental/modules/Buffs.js
- src/parser/shaman/elemental/modules/talents/Stormkeeper.js
Currently, the Stormkeeper cast ~5 seconds before pull is not included in the cast efficiency calculation. This results in suggestions that say you missed a cast of Stormkeeper when you really did not.
Here is an example WA report that demonstrates the issue: 
https://wowanalyzer.com/report/rJXM1TmkpKPgN2n7/4-Mythic+Abyssal+Commander+Sivara+-+Kill+(2:50)/Thejigglr/overview
The report says that I only used 2/3 possible Stormkeeper casts.
If you check the actual log (https://www.warcraftlogs.com/reports/rJXM1TmkpKPgN2n7/#fight=4&source=7&type=auras&ability=191634), you can see that I had the Stormkeeper buff 3 times during the fight, so a cast was not recorded.
This change manually tracks Stormkeeper casts, which results in the correct total number of casts being recorded.
> Include precast Stormkeeper in total number of Stormkeeper casts.

- src/parser/shaman/elemental/CHANGELOG.js
- src/parser/shaman/elemental/modules/checklist/Component.js
- src/parser/shaman/elemental/modules/checklist/Module.js
- src/parser/shaman/elemental/modules/core/FlameShock.js
- src/parser/shaman/elemental/modules/talents/TotemMastery.js
Pretty basic but important item. This is is more or less the last distinct thing I plan to add to the checklist, maybe something for storm elemental in the future.
> Add Totem Mastery Uptime Checklist item when talent is selected

- src/parser/paladin/holy/CHANGELOG.js
- src/parser/paladin/holy/modules/talents/CrusadersMight.js
Most Holy Paladin builds for raiding and M+ are taking the Crusader's Might talent in the first tier.  
The goal of these builds is to reduce the cooldown of Holy Shock to cast as many as possible.  Holy Shock will always do more damage or healing (depending on who it is cast on) than Crusader Strike.  Therefore Holy Shock should always be cast before Crusader Strike.  There are situations where it will not be beneficial to cast Light of Dawn, so I did not push those events to the timeline.
The previous trait statistic was showing the total cooldown reduction for HS and LoD.  I added a tooltip that shows how much cooldown reduction was left "on the table" for each spell and how many extra casts it equates to.
I also converted the module to use an event instead of an onCast method.
> Crusaders Might Additional Info

- src/parser/monk/mistweaver/CHANGELOG.js
- src/parser/monk/mistweaver/modules/talents/Tier45Comparison.js
If someone played poorly where they wouldn't save or have any mana returned from a tier 45 talent the best variable would be null.
> MW tier45 fixes

- src/parser/shaman/restoration/CHANGELOG.js
- src/parser/shaman/restoration/modules/features/TidalWaves.js
- src/parser/shaman/restoration/modules/features/checklist/Component.js
- src/parser/shaman/restoration/modules/features/checklist/Module.js
Tidal Waves aren't what they used to be, and this makes this checklist item more misleading for people trying to learn, than anything else. I'll see if I can figure out a new format for it in the future. Alternatively if TW get to be an important part of the gameplay again in the future I'll add it again.
> [Restoration Shaman] Removal of Tidal Wave checklist rule

- src/parser/monk/mistweaver/CHANGELOG.js
- src/parser/monk/mistweaver/modules/core/HotTracker.js
- src/parser/monk/mistweaver/modules/talents/RisingMist.js
Updated RM to include the healing from extra vivify cleave, extra evn hits, and extra ef mastery procs. Also made it so hot tracker can actually track rem bounces.
**### BIG NOTE HERE** These changes will show very little this patch but next patch it will be more useful. They are adding these features in its just they are extending the duration you extend hots so this is just getting work done ahead of time
> [MW] RM updates + hot tracking

- src/common/SPELLS/bfa/azeritetraits/shaman.js
- src/parser/shaman/elemental/CHANGELOG.js
- src/parser/shaman/elemental/CombatLogParser.js
- src/parser/shaman/enhancement/CHANGELOG.js
- src/parser/shaman/enhancement/CombatLogParser.js
- src/parser/shaman/shared/azerite/NaturalHarmony.js
Hovering avg stat gained lines gives uptime for each buff.
The tooltip on the stat reads:
```
Grants x critical strike via Natural Harmony: Fire for 12 seconds after casting a fire spell.
Grants x haste via Natural Harmony: Nature for 12 seconds after casting a nature spell.
Grants x mastery via Natural Harmony: Frost for 12 seconds after casting a frost spell.
```
> Add Natural Harmony statistic for elemental/enhancement shaman

- src/CHANGELOG.js
- src/interface/Hotkeys.js
Make it less likely that if someone accidentally starts typing in wowA they won't go to localhost
new combo is ctrl + l 
(this is a lower case L not a capital I)
> ctrl on modifier to go to local host

- src/parser/deathknight/blood/CHANGELOG.js
- src/parser/deathknight/blood/CONFIG.js
- src/parser/deathknight/blood/modules/features/MarrowrendUsage.js
- Bumped version from 8.1 to 8.2.5 (had no gameplay impacting changes)
- Removed the `<br>` from the tooltip as it's not working anymore
- Fixed an issue where the BS-tracker wouldn't count the stacks gained/lost properly, resulting in wrong metrics for bad marrowrend usage, wasted BS stacks and BotD procs.
The change does not impact other logs. The module now essentially just copies the correct amount of stacks from the last event, making it somewhat self-correcting instead of continuing with wrong numbers.
**bugged example**
report/btLn3zCJWP1ARNVY/10-Mythic+Queen+Azshara+-+Kill+(10:32)/Scorned/standard/timeline
live
updated
> [Blood][Bug] fixed MR stack counting & blood version bump

- src/CHANGELOG.js
- src/parser/core/tests/integrationTest.js
- src/parser/core/tests/log-tools.js
- src/parser/mage/frost/CombatLogParser.test.js
The Frost Mage integration test was using `NO_IL`, so those tests again pass.
> fixed parseLog parameters & integrationTest can test spec builds

- src/parser/monk/brewmaster/CHANGELOG.js
- src/parser/monk/brewmaster/__snapshots__/CombatLogParser.test.js.snap
- src/parser/monk/brewmaster/modules/features/checklist/Component.js
- src/parser/monk/brewmaster/modules/spells/PurifyingBrew.js
**tl;dr** - The old threshold was set in Legion. Half the fights this tier didn't consistently put you in heavy stagger (i have 0.96% time in Heavy Stagger on radiance), which made the threshold wrong. This changes it to adjust based on actual time in Heavy Stagger.
The new function is `threshold(x) = max(1 - 2 x, 0) + 0.1` (y = threshold, x = fraction of time in heavy stagger):
If you spend at least 50% of the fight in heavy stagger, the threshold is unchanged. Otherwise, it is increased. The only fight that will likely be unchanged this tier is Za'qul, where 40-60% heavy stagger is pretty common. This will still ding people for purifying too often during medium/light stagger, but not on fights where you don't have other options. At some point, I should *probably* make all light stagger …
> [BrM] Purifying Brew / Heavy Stagger threshold calculation change

- src/CHANGELOG.js
- src/interface/ReportRaidBuffList/ReportRaidBuffList.tsx
https://discordapp.com/channels/316864121536512000/360770373454659585/676947886126268437
Warcraftlogs gave us incomplete information on one of the players and caused the player selection to break through the raid buffs module.
https://wowanalyzer.com/report/G32tBkRD4x8PVQCJ/7-Normal+N%27Zoth+the+Corruptor+-+Kill+(11:20)
The player causing that issue still won't be select able, as there is a lot of information missing, but the rest works fine.
> Fix #support Player Selection breaking

- src/CHANGELOG.js
- src/parser/shared/modules/items/bfa/raids/nyalothathewakingcity/VitaChargedTitanshard.js
- src/parser/shared/modules/items/bfa/raids/nyalothathewakingcity/VoidTwistedTitanshard.js
~~SimulationCraft seems to be 30 critrating off when calculating the voidshroud buff, going with in-game numbers (30 crit rating at ilvl460)~~ Scamaz'd by human race
> Update raden trinket values to match in-game behaviour

- src/CHANGELOG.js
- src/common/ITEMS/bfa/raids/nyalothathewakingcity/index.js
- src/interface/report/Results/ItemWarning.js
- src/interface/report/Results/index.js
- src/parser/hunter/beastmastery/modules/core/BeastMasteryFocusCapTracker.tsx
- src/parser/hunter/shared/modules/resources/FocusCapTracker.js
With bad item: 
Without:
It has the possibility to add more items if a player is so unlucky to be using multiple items that causes errors - did that for futureproofing purposes.
> Add item warnings to Core and update focuscaptracker for Hunter

- src/parser/hunter/beastmastery/CHANGELOG.tsx
- src/parser/hunter/beastmastery/modules/Abilities.tsx
The spell is so short CD with all the reductions in 8.3 that it isn't uncommon for WoWA to tell you that you've used it too few times even if only a GCD is in between it coming off CD and it being cast. This tries to account for that by simply lowering the cast efficiency. It will still trigger if people aren't casting it enough, but won't trigger if there are simply a GCD between it coming off CD and it being cast.
> Tweak BW cooldown efficiency

- src/CONTRIBUTORS.js
- src/parser/monk/mistweaver/CHANGELOG.js
- src/parser/monk/mistweaver/modules/features/Abilities.js
Bugfix to only show Rising Sun Kick cast efficiency suggestion when Rising Mist is talented.
> [MW] RSK Cast Effciency

- src/parser/monk/brewmaster/CHANGELOG.js
- src/parser/monk/brewmaster/CONFIG.js
- src/parser/monk/brewmaster/modules/constants/AbilityBlacklist.js
Just blacklisted a bunch of dots / raid dmg effects that skew hit counts. Removed Legion blacklist.
Also bumped patch compatibility.
> [BrM] Updated ISB Hit Tracking for 8.3

- src/parser/monk/mistweaver/CHANGELOG.js
- src/parser/monk/mistweaver/modules/core/HotTracker.js
- src/parser/monk/mistweaver/modules/talents/RisingMist.js
There was an issue with rm hot extension tracking actually only tracking some healing not all of it. I just wrote it into the core hot tracker for mw as that is an important cool thing
> [MW] RM Fixes

- src/parser/druid/feral/CHANGELOG.js
- src/parser/druid/feral/CONFIG.js
- src/parser/druid/feral/modules/features/EnergyCapTracker.js
Wasted energy thresholds were valid pre-essences and the crazy stats we have now but now its impossible to not cap on energy during berserk without wasting combo points. Switched to %
> [Feral] Changed wasted energy threshold

- src/CHANGELOG.js
- src/parser/shared/modules/items/bfa/raids/azsharaseternalpalace/AzsharasFontofPower.js
Fixes Font of Power so the channel no longer shows up as downtime in the timeline and in the Downtime % stat.
Also added the Latent Arcana Buff to the timeline buffs.
> [Core] Font of Power fix

- src/parser/deathknight/frost/CHANGELOG.js
- src/parser/deathknight/frost/modules/features/SpellUsable.js
Previously didn't count the internal cooldown for icecap properly.  Corruption is allowing people to reach sufficient levels of haste and crit that my error was noticed.
> [Frost Death Knight] Icecap fix

- src/CHANGELOG.js
- src/common/PATCHES.js
The patches were behind, preventing warnings from appearing when viewing classes in which wowanalyzer is not up-to-date for.
In my opinion, this should trigger both maintainers and people from the community that use wowanalyzer to update the modules for the respective class/spec.
> Updated patch list

- src/parser/rogue/assassination/CHANGELOG.js
- src/parser/rogue/assassination/normalizers/GarroteNormalizer.js
Seems the convertion in #3580 was wrong for the GarroteNormalizer. I'll take the time to look through all the changes tomorrow afternoon (EU) in that PR again to make sure no other modules suffer from this.
> Fixed garrote early refresh tracking.

- src/parser/mage/frost/CHANGELOG.tsx
- src/parser/mage/frost/integrationTests/example.test.ts.snap
- src/parser/mage/frost/modules/features/SplittingIce.tsx
- src/parser/mage/frost/modules/features/ThermalVoid.tsx
> [Frost Mage] Fix typos and incorrect SpellLink in Splitting Ice / Thermal Void modules

- src/CHANGELOG.js
- src/common/DEFENSIVE_BUFFS.js
This caused a massive amount of errors (local development) to be generated when viewing death recaps (where guardian spirit was active on the player that died).
Aditionally, Guardian Spirit was shown as twice on the character that died eventhough that is not the case.
Before PR:
After PR:
[See Report](https://wowanalyzer.com/report/dfcJYaAg8Z7Q6KvW/8-Mythic+Maut+-+Kill+(5:26)/Part%C3%ADcle/standard/death-recap)
> Removed duplicate entry of Guardian Spirit in defensive buffs.

- src/parser/hunter/beastmastery/CHANGELOG.tsx
- src/parser/hunter/beastmastery/CombatLogParser.tsx
- src/parser/hunter/beastmastery/modules/spells/BarbedShot.tsx
- src/parser/hunter/marksmanship/CHANGELOG.tsx
- src/parser/hunter/marksmanship/CombatLogParser.tsx
- src/parser/hunter/shared/modules/core/DeathTracker.tsx
- src/parser/hunter/survival/CHANGELOG.tsx
- src/parser/hunter/survival/CombatLogParser.tsx
- src/parser/hunter/survival/modules/talents/MongooseBite.tsx
- src/parser/shared/modules/DeathTracker.tsx
Blocked by #3611 
Fixes #2670 
Due to combatlog restrictions, Feign Death is not shown as a cast event to other players (to make it more believable, otherwise it is cheesable with WA/AddOns easier than already). 
This change ignores extremely short deaths for hunters. 
Log: 
Before: 
After:
No suggestion
Log: 
Before:
After:
> [Hunter] Extend DeathTracker to ignore Feign Death casts as deaths

- .idea/codeStyles/Project.xml
- src/CHANGELOG.js
Jetbrains IDEs were configured to remove all blank lines between methods. Which is inconsistent with codestyles mentioned in [airbnb/javascript](https://github.com/airbnb/javascript#whitespace--after-blocks). 
Currently it would format the code as following
I believe this is what we wish to see
> Jetbrains codestyle update

- src/parser/mage/arcane/CHANGELOG.tsx
- src/parser/mage/arcane/modules/features/CooldownThroughputTracker.js
Same as the change for Fire, adds the 4 seconds of spells before Arcane Power to the Cooldowns page.
Before
After
> [Arcane Mage] Cooldown Pre Spells

- package.json
- src/CHANGELOG.js
- src/interface/report/Results/DegradedExperience.js
- src/parser/core/Analyzer.ts
- src/parser/core/CombatLogParser.js
- src/parser/core/EventFilter.ts
- src/parser/core/EventSubscriber.ts
- src/parser/core/MODULE_ERROR.js
- src/parser/core/Module.ts
- src/parser/core/ModuleError.ts
- src/parser/core/modules/EventEmitter.ts
- src/parser/mage/arcane/modules/features/CooldownThroughputTracker.js
- src/parser/mage/fire/modules/features/CooldownThroughputTracker.js
- src/parser/shared/modules/CooldownThroughputTracker.tsx
- src/parser/shared/modules/EventHistory.ts
- types/sentry.d.ts
- yarn.lock
What's in here?
**TS Conversion**
- Converted EventEmitter to TS
- Converted MODULE_ERROR to TS enum
- Converted CooldownThroughputTracker to TS
- Stictified some existing TS
**New functionality**
- New module EventHistory that can be imported as a dependency
- Adds EventHistory.last(count, maxTime, filterDef)
```
/**
* @param count the maximum number of events to return, or null for no limit
* @param maxTime the maximum number of milliseconds to look back, or null for no limit
* @param filterDef an optional EventFilter to apply to all events
* @returns the last `count` events that match the given filters, with the oldest events first
*/
- CooldownThroughputTracker (and children) cooldownSpells have new options (thanks Sharrq):
- `startBufferMS`: If provided, the cooldown tracker will add …
```
> [Core] Event History utility function and some TS conversions

- src/parser/priest/discipline/CHANGELOG.js
- src/parser/priest/discipline/modules/features/AtonementApplicatorBreakdown.js
Fixes this problem: https://discordapp.com/channels/316864121536512000/360770373454659585/734730843112734732
The atonement argument in the foreach of the `handleEvangelismCasts` method is sometimes null, I simply forgot to initially add the same null check done inside `handleAtonementsHits`
> Atonement Applicator Breakdown bugfix

- .github/workflows/changelog-entry.yml
- src/CHANGELOG.js
- src/parser/deathknight/blood/modules/features/BoneShieldTimesByStacks.js
- src/parser/druid/balance/modules/talents/Starlord.js
- src/parser/hunter/shared/modules/spells/KillShot.tsx
- src/parser/hunter/shared/modules/spells/covenants/venthyr/FlayedShot.tsx
- src/parser/mage/arcane/integrationTests/example.test.ts.snap
- src/parser/mage/arcane/modules/Checklist/Component.tsx
- src/parser/mage/fire/integrationTests/example.test.ts.snap
- src/parser/mage/frost/integrationTests/example.test.ts.snap
- src/parser/mage/shared/modules/features/RuneOfPower.tsx
- src/parser/monk/brewmaster/modules/Abilities.js
- src/parser/paladin/retribution/modules/core/azeritetraits/RelentlessInquisitorStackHandler.js
- src/parser/shaman/elemental/modules/talents/UnlimitedPowerTimesByStacks.js
- src/parser/shaman/shared/azerite/SynapseShock.js
- src/parser/warrior/protection/modules/talents/IntoTheFray.js
Should have no influence over any results - simply using a cleaner and more standardized approach to handling buffs. 
This PR does not adjust traits and essences using handleStacks as we'll be removing those come SL.
> [Shadowlands] Change remaining handleStacks usage to use currentStacks helper

- src/CHANGELOG.js
- src/interface/report/Results/index.js
Added a warning message to notify users that we will be removing support for Azerite, Essences, Corruption, and all BFA items with the launch of Prepatch.
> [Core] Warning Message for Shadowlands Prepatch

- src/common/SPELLS/mage.js
- src/parser/mage/arcane/CHANGELOG.tsx
- src/parser/mage/fire/CHANGELOG.tsx
- src/parser/mage/frost/CHANGELOG.tsx
- src/parser/mage/frost/CombatLogParser.ts
- src/parser/mage/frost/modules/talents/FocusMagic.tsx
- src/parser/mage/shared/modules/features/FocusMagic.tsx
Added a module to track the Focus Magic buff for all mage specs
- Tracks the Int and Crit buffs for Focus Magic (Had to manually count the int one because it is a hidden buff)
- Added statistic for the crit buff uptime and the uptime at 8 stacks of the Intellect buff
- Suggestion is based on the crit uptime, as if they raise that, the int one will raise alongside it (in theory)
Towards #3657
> [Shadowlands][Mage] Focus Magic Module

- src/CHANGELOG.js
- src/interface/common/makeAnalyzerUrl.js
> [Core] Fix armory link for realms with spaces or apostrophes

- .gitignore
- src/CONTRIBUTORS.ts
- src/parser/shaman/enhancement/CHANGELOG.tsx
- src/parser/shaman/enhancement/modules/Abilities.tsx
Based on comments from Enhancement Shaman discord, Earth Elemental is no longer a valid offensive GCD.
> [Shadowlands][Enhancement] Removed Earth Elemental suggestion

- src/CONTRIBUTORS.ts
- src/parser/monk/mistweaver/CHANGELOG.js
- src/parser/monk/mistweaver/modules/shadowlands/conduits/NourishingChi.js
Was only tracking selected players hots when it should be all hots
> [MW] Nourishing chi now tracks all hots

- src/CHANGELOG.tsx
- src/CONTRIBUTORS.ts
- src/interface/NameSearch/NameSearch.tsx
When trying to use character or guild search it fails to submit.
We can see that the realm is undefined even though it has been selected.
This is because the onChange handler argument is a string of realm not an object.
> [Core] fix character and guild search submit action

- src/interface/report/ReportDurationWarning.tsx
fixes #3800 
Converted a smaller component (no state/hooks). Converted getter to generic function. Nothing else altered.
Let me know if this needs any further modifications!
> Convert ReportDurationWarning from React class component to functional component
